### ISSUE TITLE
Please help to fill in the Readme.md with the info discussed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1]

**Comment by championswimmer** [comment]
I have updated the README.md, please check, if I need to add further info.

**Comment by championswimmer** [comment]
@mariobehling Will the scope of the webapp also include complete replacement of the functionality of the main website ?

**Comment by mariobehling** [comment]
Which main website are you referring to? The best would be an app that works on desktop and mobile. We only have the orga server. This server is not intended to work for event participants. The idea is to get a JSON from the orga server and generate a web app. Does this make sense to you?
