### ISSUE TITLE
UI : Increase spacing between the buttons on the app screen

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1000]
The buttons on the app screen do not have proper spacing.
![screen shot 2017-01-14 at 11 20 22 pm](https://cloud.githubusercontent.com/assets/12807846/22191529/8e58a90e-e151-11e6-87a0-f14ed9a16aa9.png)

**Comment by Princu7** [comment]
@geekyd It looks decent enough at the moment. Could you please share a mockup of the proposed UI? Thanks!!

**Comment by aayusharora** [comment]
No need for this at the moment. Closing this.

**Comment by geekyd** [comment]
Okay sir.

I saw the android app generator and it looks like this.
![screen shot 2017-01-28 at 9 13 31 am](https://cloud.githubusercontent.com/assets/12807846/22394006/4ee9a1a0-e53a-11e6-9514-5e25a3085ed0.png)

I thought the web app generator could also use the design . :)
