### ISSUE TITLE
Multilingual support : Adding language support to generated Webapp

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1002]
After generating app, participant can change the language of the pages with a selectbox.
Things to Consider
1. The webapp generated are static pages that work offline.

@Princu7 @mariobehling What are your views ?

**Comment by Princu7** [comment]
Good idea. Maybe i18next can help in this.

**Comment by geekyd** [comment]
Its a great idea.
@Princu7 `i18next` is a good option.

**Comment by aayusharora** [comment]
Awesome @Princu7 @geekyd `i18next` is nice. Let me know how you are going to proceed with this ?

**Comment by Princu7** [comment]
@aayusharora I can currently working on some of the issues of the web app as well as the server. As soon as I finished with them, I will start working on this issue. In the meantime, I will research more about the `i18next` and the way to integrate it within the app. Thanks!!

**Comment by utkarshnath** [comment]
@aayusharora can I work on this?

**Comment by aayusharora** [comment]
Yeah @princu seems already busy in other tasks. You can go ahead @utkarshnath

**Comment by utkarshnath** [comment]
@aayusharora, @Princu7 

- do you want me to change only the static content of the pg or the whole content of the pg

- should we parse the language from json, or should the user be able to choose

**Comment by aayusharora** [comment]
`do you want me to change only the static content of the pg or the whole content of the pg`
@utkarshnath All the pages generated by the generator are static, and we have to translate them.
`should we parse the language from json, or should the user be able to choose`
As mentioned, after app generation we should be able to choose this.

**Comment by utkarshnath** [comment]
@aayusharora I was talking of the contents , Like the speakers would be different for different events. i18next is not exactly a translating engine. It has a fallback language and key value pairs for all the other languages so here we have to define the key(words to be converted) beforehand

**Comment by aayusharora** [comment]
@utkarshnath Can you try jquery-translate. Its a layer on Google Translate API. We need to change each and everything on the page, hence can not give key-value beforehand. 
Please also go through Google Translate API.

**Comment by utkarshnath** [comment]
@aayusharora I tried Google Translate API


![ezgif-1-71cf920076](https://cloud.githubusercontent.com/assets/12716067/23118467/454bff88-f77a-11e6-8a7d-077b663878d3.gif)

**Comment by aayusharora** [comment]
Awesome @utkarshnath :)  I am excited to add this. Please generate a PR.

**Comment by geekyd** [comment]
@utkarshnath Great work looks nice!

**Comment by aayusharora** [comment]
@utkarshnath Also join the discussions here https://gitter.im/fossasia/open-event-webapp

**Comment by utkarshnath** [comment]
@aayusharora do you think the placement of select box is fine and I will check for internet connection
@geekyd thanks :)

**Comment by Princu7** [comment]
@utkarshnath Looks Nice. Good work :)

**Comment by aayusharora** [comment]
@utkarshnath it will be nice if we can find out any space on the navbar left side.

**Comment by mariobehling** [comment]
Sorry, but this feature should not be in the middle of the page. It is also unclear if we autotranslation should be used as this is buggy. E.g. why would I need Amenian for an event in Singapore. We need to reconsider this feature in detail.

**Comment by mariobehling** [comment]
Surely, everyone can follow his/her interest and develop what you like, but what this apps needs at the moment: To get rid of the bugs instead of adding more features, that do not immediately benefit attendees. And it is unclear if this is a suitable approach. E.g. if an event is in English, the participants need to speak in English. If it has two languages, the program needs to be in two languages. Auto-translation is not the right approach for this, but we can follow up, if you have arguments. Maybe in the meantime help with some pressing bug issues? https://github.com/fossasia/open-event-webapp/labels/bug

**Comment by mariobehling** [comment]
This should follow the development of the main app. Closing this for now. We will come back to this later.
