### ISSUE TITLE
Hide download and preview button if X is clicked

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1005]
@aayusharora @mariobehling  @Princu7 

After generating the web app if the user clicks X button, the download and preview button remain active.

Please check this link to see the demo of the situation.

https://www.useloom.com/share/68907210e57511e68456953b30d4311d

**Steps to reproduce**
1.  Generate a web app
2.  After the generation of the application is completed hit X. 

**Proposal**
We should hide the download and the preview and also disable the generate web-app button as soon as the user hits X.

**Comment by aayusharora** [comment]
@geekyd What if the user wants to generate app for more than one event.

**Comment by geekyd** [comment]
@aayusharora 
The buttons will get appear when an event is generated like it is getting generated. If the user presses X we will hide the download and preview buttons, If the user upload more zips the buttons will get generated in the usual manner, after the app is generated.

Please check the proposed idea at
https://open-event-web-appp.herokuapp.com/

**Steps** 
1. Generate the webapp 
2. Hit the X button
3. upload zip and hit generate webapp button.

**Comment by geekyd** [comment]
@aayusharora Please check the proposed UX @ 
https://open-event-web-appp.herokuapp.com/

**Comment by geekyd** [comment]
@Princu7 @aayusharora 
Currently when X is clicked by the user after the webapp is generated, the download and preview buttons are shown even after clicking X.
Also the user is able to access the download and preview buttons while generating second webapp.

**After clicking X button preview and download buttons are accessible**


![screen shot 2017-02-12 at 12 32 17 pm](https://cloud.githubusercontent.com/assets/12807846/22860287/4bfe5116-f11f-11e6-85b0-6e15e856b4c4.png)


**While generating the second webapp**


![screen shot 2017-02-12 at 12 30 21 pm](https://cloud.githubusercontent.com/assets/12807846/22860285/288fe9c4-f11f-11e6-83da-63864a23a09b.png)

**Comment by Princu7** [comment]
@geekyd Yeah, it should be like that the first site is being generated. Go ahead!!

**Comment by geekyd** [comment]
@Princu7 Thanks I will do that asap.

**Comment by shashanktatti** [comment]
Hello @geekyd , can i go ahead and try to solve this issue?

**Comment by geekyd** [comment]
@shashanktatti I'm almost done with this issue. You can go ahead with some other issue 😄
