### ISSUE TITLE
Remove additional scroll bar in the sessions column

### ISSUE THREAD

**Issue by shiftsayan** [fossasia/open-event-webapp#101]
<img width="969" alt="screen shot 2016-01-04 at 4 09 52 pm" src="https://cloud.githubusercontent.com/assets/8451336/12088011/a9ab0298-b2fd-11e5-9deb-0e72d87877e6.png">

There are 2 scroll bars in the sessions column. One of them only scroll down to hide the search bar, and not navigate through the entire schedule. Navigating through them can be difficult, especially on touch screen devices. It could be better to have a static search bar.

**Comment by shiftsayan** [comment]
Could leave you in this condition:
<img width="1280" alt="screen shot 2016-01-04 at 4 19 55 pm" src="https://cloud.githubusercontent.com/assets/8451336/12088195/1005b730-b2ff-11e5-96d6-5c708c4f25a5.png">

**Comment by abhibansal530** [comment]
Do we have to remove external scroll bar?

**Comment by shiftsayan** [comment]
I guess, so that we have a scroll bar for the posts and as static search bar.

**Comment by abhibansal530** [comment]
But there's no issue if we use chrome.

**Comment by shiftsayan** [comment]
I was using Chrome for OS X

**Comment by abhibansal530** [comment]
But as u can see in image it works fine on my system(Ubuntu).

**Comment by shiftsayan** [comment]
I am assuming that is due to the screen size. You must be having a larger display than I do.

**Comment by abhibansal530** [comment]
So what to do for this issue?

**Comment by shiftsayan** [comment]
I guess we could improve on the viewport mechanics.

**Comment by abhibansal530** [comment]
Sorry,but i did not get you?What do you mean by viewport mechanics?

**Comment by shiftsayan** [comment]
Since the problem is occuring on smaller screens, this would be due to the mobile optimisation, which can be improved.

**Comment by abhibansal530** [comment]
Are you on irc?I would like to talk to u there.

**Comment by shiftsayan** [comment]
Hey @abhibansal530 
Sorry for the late response. I am on IRC. What is your name?

**Comment by abhibansal530** [comment]
@shiftsayan my nickname is abhibansal53

**Comment by tarun14110** [comment]
@shiftsayan  Are you still working on this issue ? I would like to work on this.
.

**Comment by SilentFlame** [comment]
@championswimmer @mariobehling  this can be closed once we merge PR #131.
as it handles all mentioned in this issue.
