### ISSUE TITLE
Feature : The generated web app should have share button

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1010]
The webapp generated should have buttons to share the website links to social networking websites.

@mariobehling @Princu7 @aayusharora What are your thoughts on this?

**Comment by aayusharora** [comment]
@geekyd Yeah it's great idea. Will you like to work for this ?

**Comment by geekyd** [comment]
Yes i would love to work on this 😄 

What should we go with in your opinion ?
Should we add share links for all the sessions or a share button to share only event website link ?
I think we should add share button to all the sessions.

@aayusharora @Princu7 @mariobehling 
What do you think?

**Comment by Princu7** [comment]
@geekyd Great idea. I think sharing link for the whole event rather than a particular session would be more better. Other event management systems also provide this option.

**Comment by geekyd** [comment]
@Princu7 thanks for the feedback
@aayusharora What do you think?

**Comment by aayusharora** [comment]
Exactly !!  sharing event sounds good :)

**Comment by aayusharora** [comment]
@geekyd Can you update me on this :)

**Comment by geekyd** [comment]
@aayusharora sorry about the delay, I had examination.
I will start working on this asap.

**Comment by geekyd** [comment]
@aayusharora I have successfully added the share button for facebook and twitter. 
Check out 
https://open-event-web-appp.herokuapp.com/

I need your suggestion about where to place the social links.
One option is to provide the links on all the pages with a small slider present on every page for the social media websites.
something like this. 

![screen shot 2017-02-11 at 11 48 14 pm](https://cloud.githubusercontent.com/assets/12807846/22856303/a810f7f8-f0b4-11e6-8ad0-f7edf1b03711.png)

**Comment by Princu7** [comment]
@geekyd Nice. Yeah. That is the standard norm.

**Comment by aayusharora** [comment]
@geekyd We have a lot of space above search bar on right side. Can you try this mockup.
![12](https://cloud.githubusercontent.com/assets/12194719/23009388/bb959a4c-f43b-11e6-9ff7-4929d4473c1c.png)

**Comment by geekyd** [comment]
@aayusharora Sure we can try that. 
I will create two mock-up designs and we can choose the better one, before PR.

**Comment by aayusharora** [comment]
Will be awesome @geekyd !! Looking forward :)

**Comment by geekyd** [comment]
@aayusharora 
Here are the two designs
**I think we should implement a side hover bar. What do you think?**

**Buttons**
![screen shot 2017-02-16 at 11 07 17 pm](https://cloud.githubusercontent.com/assets/12807846/23033101/e6bd9e02-f49c-11e6-984e-40e39c452874.png)


**Side hover bar**
![screen shot 2017-02-16 at 10 29 55 pm](https://cloud.githubusercontent.com/assets/12807846/23033144/ffc86b02-f49c-11e6-995e-47a008c7d6fc.png)

**Comment by aayusharora** [comment]
@geekyd  The seconds sounds good on desktop view but the first is better on mobile UX as we can allocate space from left and right sides on mobile.
1. Implement the second view on Desktop.
2. Implement the first one on Mobile Screen.
3. Make sure the search bar must remain inline along with date nav bar.

Thanks

**Comment by geekyd** [comment]
@aayusharora please check http://open-event-web-appp.herokuapp.com/

**Comment by geekyd** [comment]
This issue has been solved.

**Comment by mariobehling** [comment]
Please have a look at the follow up issue here: https://github.com/fossasia/open-event-webapp/issues/1055
