### ISSUE TITLE
Website not being generated for the EHealth Africa Sample

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1014]
It seems that the app is currently hanging while generating the website of the Ehealth Africa Sample. 
![screenshot from 2017-02-07 18-49-35](https://cloud.githubusercontent.com/assets/8847265/22692715/3c2c3f58-ed66-11e6-8f97-42a591cee535.png)

I am working on fixing it :)

**Comment by aayusharora** [comment]
Thanks for pointing this out and fixing this :)
