### ISSUE TITLE
inaccessible events on schedules page via tab browsing.

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-webapp#1019]
for tabbed browsing user events that are on schedule page are inaccessible.

 I would like to work on it if it is important.

**Comment by aayusharora** [comment]
@anu-007 Can you please elaborate this issue.

**Comment by anu-007** [comment]
On schedule page, if you browse it using tab key you will not able to focus on events and hence it is inaccessible.

**Comment by aayusharora** [comment]
Ok @anu-007 Go ahead !!

**Comment by aayusharora** [comment]
Closing this :)
