### ISSUE TITLE
UX : Disabling generate button if the web app is generated

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1023]
@aayusharora @mariobehling @Princu7 
Currently the user is able to click generate app button even after the webapp is generated.
The generate button should be disabled after the web-app is generated. In case of multiple generation of web app the generate button should be enabled for every new json uploaded.

**Comment by Princu7** [comment]
@geekyd Valid point. Go ahead. :+1:

**Comment by geekyd** [comment]
@Princu7 I have made the changes
Please check this link for the demo
https://open-event-web-appp.herokuapp.com

**Comment by geekyd** [comment]
Closing the issue
This issue is solved 😄
