### ISSUE TITLE
Add other links defined in the JSON files to the top bar, e.g. blog

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1025]
Currently not all links are added to the UI. Please also add other links except social media, e.g. blog links.

**Comment by geekyd** [comment]
@mariobehling Sir do you mean adding links present in event json file to the header along with the other social links?

**Comment by ParthS007** [comment]
@geekyd @mariobehling  @aayusharora Is this issue still there and I have doubt that social links which are already there are of Event(For e.g. If twitter link is there for FOSSASIA 2014, It goes to FOSSASIA twitter handle) so can I have to add a link to blog of FOSSASIA and same for the other generated web apps respectively? 
Please tell If I am understanding it wrong .Thanks
