### ISSUE TITLE
Navbar Improvements on screen

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1027]
The Nav bar shows a scroll in Mobile view which leads to bad UX.
Propose an effective solution and implement it.

- [x] Remove the scroll 
- [x] Implement a solution that works on all screen sizes.
![badui1](https://cloud.githubusercontent.com/assets/12194719/22972934/d8e08304-f3a1-11e6-9011-5b297eaeb9a5.png)

**Comment by utkarshnath** [comment]
@aayusharora are you talking about the date panel ? if yes we can implement a carousel for this.

**Comment by aayusharora** [comment]
Yes @utkarshnath

**Comment by anu-007** [comment]
@aayusharora I think we should use drop-down tabs or we should use tabs vertically instead of horizontally and show the content of each tab in form of list.

**Comment by aayusharora** [comment]
@anu-007 That can be one of the solutions but it should be with toggle, so that we can save vertical space in mobile

**Comment by geekyd** [comment]
@aayusharora We can have the days as a bar and make the detailed view invisible, we can toggle the visibility whenever the user clicks any tab.

That would save us the space required and also provide a better UX.

**Comment by aayusharora** [comment]
@geekyd That will be fine but make sure we should have no scroll bars anywhere.

**Comment by geekyd** [comment]
@aayusharora Here is the mock-up design of the navbar

<h3>Desktop View</h3>
**When the page loads for the first time**

![screen shot 2017-02-16 at 9 54 58 pm](https://cloud.githubusercontent.com/assets/12807846/23030104/c25e8940-f492-11e6-92e6-168acff6d8ef.png)

**When user clicks a navbar link**

![screen shot 2017-02-16 at 9 55 13 pm](https://cloud.githubusercontent.com/assets/12807846/23030123/cee56954-f492-11e6-83b6-8c51b0970120.png)

<h3>Mobile View</h3>
**When the page loads for the first time**

![screen shot 2017-02-16 at 9 55 28 pm](https://cloud.githubusercontent.com/assets/12807846/23030190/0cd0db18-f493-11e6-8a13-514d2e8c9f8d.png)


**When user clicks a navbar link**

![screen shot 2017-02-16 at 9 55 40 pm](https://cloud.githubusercontent.com/assets/12807846/23030196/115b16c6-f493-11e6-9746-bc4d3bc35f83.png)

**Comment by aayusharora** [comment]
Hey @geekyd Thanks !! Please send the PR. Assigning this to you than :)

**Comment by Princu7** [comment]
Looks Nice :)
