### ISSUE TITLE
inactive generate-webapp button after correcting the wrong email address.

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-webapp#1029]
Steps to regenerate issue-
1. insert a wrong email address
2. click on Upload your own JSON files checkbox
3. upload the JSON file 
4. click generate web app

a warning shows up and tells us to enter the correct email address so after inserting correct email address the generate-web app button is still inactive.

desired result-
the generate-web app button should be active after correcting the email address.

I would like to work on this.

**Comment by aayusharora** [comment]
Go ahead @anu-007

**Comment by aayusharora** [comment]
@anu-007 Any progress with this ?

**Comment by anu-007** [comment]
@aayusharora working on it ,i will send a PR soon.

**Comment by Princu7** [comment]
Solved. Thanks!!
