### ISSUE TITLE
Progress bar should be removed after the zip is uploaded successfully

### ISSUE THREAD

**Issue by utkarshnath** [fossasia/open-event-webapp#1030]
Zip upload progress bar should be removed after the zip is uploaded successfully

**Comment by Princu7** [comment]
I think it's good the way it is now. We actually already had a discussion about it earlier when the issue was opened previously. :)

**Comment by aayusharora** [comment]
Thanks @utkarshnath For now I guess, we have discussion regarding this in other issues. Closing this.
