### ISSUE TITLE
Changing the data source is not disabling the Generate WebApp Button and is not hiding preview and download button

### ISSUE THREAD

**Issue by shashanktatti** [fossasia/open-event-webapp#1036]
@aayusharora 
Suppose we have ,
![upload](https://cloud.githubusercontent.com/assets/18312854/23091356/19122272-f5da-11e6-8ece-579b7e1b106d.png)

Now everything works fine until here..
next if you change your data source ,
![endpoint](https://cloud.githubusercontent.com/assets/18312854/23091380/b42bcda8-f5da-11e6-87ad-eed2028ad83e.png)
Here even if the endpoint is not given , 
1. the generate webapp button is not disabled
2. both the preview and download buttons are not hidden.
if you click on preview it loads the data from the JSON zip file that was uploaded and generates the site , which actually should not happen since your current data source is api endpoint!

I would like to work on this issue!

**Comment by aayusharora** [comment]
exactly thanks @shashanktatti go ahead !

**Comment by geekyd** [comment]
@shashanktatti Great find, I have noticed that the user can toggle between zip upload and api endpoint while the app is generating , it would be great if we can handle that also.

@aayusharora what do you think?

**Comment by aayusharora** [comment]
@geekyd Do you mean to disable the button of api endpoint while app generation.

**Comment by geekyd** [comment]
@aayusharora Yes, we should disable the api button while generation

**Comment by aayusharora** [comment]
While app generation
1. We need only a progress bar with a ' X'  button with all other things disabled.

**Comment by geekyd** [comment]
@aayusharora Yes I think that would be good from the UX prospective.

**Comment by shashanktatti** [comment]
@aayusharora Yes that looks good! Will implement in that fashion.

**Comment by shashanktatti** [comment]
@aayusharora @geekyd why do we actually need the 'X' button in the progress bar. Before used method did not provide any sort of opportunity to the user for cancelling the progress. Then why do we actually need it here?

**Comment by aayusharora** [comment]
@shashanktatti We need it in the `file upload` bar to cancel the file upload in between and upload the new one.

**Comment by shashanktatti** [comment]
@aayusharora why wouldn't the upload progress bar work if a file is uploaded for the second time?
Everything else apart from this is working fine.

**Comment by shashanktatti** [comment]
@aayusharora please take a look at this and suggest changes if any
[https://www.useloom.com/share/dcde924665a444a08d6fcea5c8187214](url)

**Comment by sumedh123** [comment]
@aayusharora @Princu7 This issue now doesn't seem to be quite meaningful since now we are in a state where after generation of web app, both the buttons( for source selection ) are disabled. And if the user wants to generate the app again, he has to refresh the page. What are your opinions on this? Shall this be implemented or the current state is okay?
