### ISSUE TITLE
Webapp Improvements for Mobile

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1043]
The current UI on mobile is not user-friendly.
**Note : These UI changes must only be done for Small screens.**
 - [ ]  Make the space less around heading.
 - [ ] Make date capsules smaller and inline 
 - [ ] Save as much space as possible to show main content in the first window frame.
![bug](https://cloud.githubusercontent.com/assets/12194719/23118141/0b761e7a-f779-11e6-824a-a96b5df23337.png)

**Comment by aayusharora** [comment]
@geekyd Looks good :)

**Comment by geekyd** [comment]
@aayusharora 
Please check live demo
https://open-event-web-appp.herokuapp.com/

**Comment by aayusharora** [comment]
@geekyd Can you please make a PR and post the link of live demo in that. Thanks

**Comment by Abhi2424shek** [comment]
Is'nt this solved?

**Comment by geekyd** [comment]
@Abhi2424shek Yes its solved.
