### ISSUE TITLE
Frontend: Hover on Speaker not working

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1044]
Hovering on each speakers on Speaker Page is not working as of previous version.
`Bug is in preserve3d and hoverstate ` class
- On hovering the first speaker social icons are visible but for other speakers, there is nothing visible.
![123](https://cloud.githubusercontent.com/assets/12194719/23126331/2caf34f0-f79c-11e6-87b0-579d048341a4.png)

**Comment by aayusharora** [comment]
On hovering the first speaker `social icons are visible` but for other speakers, there is nothing visible.

**Comment by geekyd** [comment]
@aayusharora I can see the social icons for every speaker while hovering.

**Comment by aayusharora** [comment]
@geekyd Please make sure to check speakers page.

**Comment by geekyd** [comment]
@aayusharora Check this

![screen shot 2017-02-20 at 9 07 40 pm](https://cloud.githubusercontent.com/assets/12807846/23245916/21f68ef2-f9b6-11e6-8078-0fab485bed87.png)

**Comment by aayusharora** [comment]
The correct view on hover on each speaker should be 
![4](https://cloud.githubusercontent.com/assets/12194719/23330398/eff05f96-fb72-11e6-8689-e566a13a188b.png)
This is already been implemented but somehow not working @geekyd

**Comment by geekyd** [comment]
@aayusharora Okay got it, I check why it is misbehaving and report asap.

**Comment by sumedh123** [comment]
Is the fix for this done? @geekyd  or shall I work on this?

**Comment by geekyd** [comment]
@sumedh123 Please go ahead :)

**Comment by sumedh123** [comment]
I am not quite clear from the above discussion that what to implement. The hover is working. Right @geekyd ? Can you explain me this issue?

**Comment by geekyd** [comment]
@sumedh123 On hovering featured speakers on home page of the app there is an overlay that appears with the social links of the speaker.

Screenshot: 
![2c90a320-fb73-11e6-9d86-310fdd4f8aee](https://cloud.githubusercontent.com/assets/12807846/24082171/17dcd5a4-0ce7-11e7-818f-8a9ea4573a33.png)

This function is also present in speakers page but it is not working currently we need to find out why it is happening and make it work.

Please check the working implementation using the classes `preserve3d & hoverstate`
