### ISSUE TITLE
Adding Grid View to schedule

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1048]
- [ ] Adding a select box that can help the user to see and print the grid view format of schedule.

![123](https://cloud.githubusercontent.com/assets/12194719/23176801/a0875d50-f88a-11e6-8fcc-400a80095c89.png)

**Comment by mariobehling** [comment]
Please add buttons on the page a) grid view and b) list view.

**Comment by geekyd** [comment]
@aayusharora @mariobehling Can I work on this?

**Comment by aayusharora** [comment]
Sure @geekyd

**Comment by Princu7** [comment]
Already solved.
