### ISSUE TITLE
Session information unreadable - avoid shadows and gray colors.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1053]
The session information shows shadows and gray colors. Previously it was readable easily, but it was changed at some point.

Please change the font to be easily readable again:
* Take out shadows
* Use black font for all components
* No font color change on scroll over

![screenshot from 2017-02-22 13-27-48](https://cloud.githubusercontent.com/assets/1583873/23198857/52bd8bb4-f905-11e6-8f3a-60a1b6ae503b.png)

**Comment by aayusharora** [comment]
@mariobehling I will work on this.

**Comment by anu-007** [comment]
@aayusharora @mariobehling this happen after this PR ( https://github.com/fossasia/open-event-webapp/pull/1035 ) which solves this issue ( https://github.com/fossasia/open-event-webapp/issues/1019 ) but changing div's to buttons simply solves the issue and gives them some native controls without hindering the UI of the app.

**Comment by aayusharora** [comment]
@anu-007 Thanks for pointing out. `ul li ` under buttons does not seem to be suitable markup. @mariobehling Fixed via #1057
