### ISSUE TITLE
Change link share to become "Share" and implement sharing of link and social media

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1055]
Currently the share button below sessions has the functionality to share links. This feature can be enhanced to share more items and speaker can share their own session info here. 

Please have a look at youtube and click the "Share" button below videos. They show a number of options to share.

Implement the same functionality for the share button in the web app. Change the wording from "links" to "Share".

![screenshot from 2017-02-22 14-13-01](https://cloud.githubusercontent.com/assets/1583873/23199418/33777bd0-f909-11e6-8844-9a3d5b9b335f.png)

**Comment by geekyd** [comment]
@mariobehling Okay sir I will enhance the share feature. For sharing the info of speakers should we add a share button for each speaker?

**Comment by geekyd** [comment]
@mariobehling sir that would be good for the desktop app, I have made some changes please check the screenshots.

![screen shot 2017-02-23 at 3 52 26 pm](https://cloud.githubusercontent.com/assets/12807846/23255083/4a5a40da-f9e0-11e6-9961-eb48d63f6c79.png)

![screen shot 2017-02-23 at 3 52 56 pm](https://cloud.githubusercontent.com/assets/12807846/23255093/4e726526-f9e0-11e6-9296-6c4053c74e00.png)

I think we should go with something like this for the mobile view.

![ffc86b02-f49c-11e6-995e-47a008c7d6fc](https://cloud.githubusercontent.com/assets/12807846/23254712/fd3b8012-f9de-11e6-9cce-4d6abfc6f9e6.png)

Please guide. Thanks!

**Comment by geekyd** [comment]
@mariobehling Please check the screenshots, I have implemented the "share" feature like you proposed.

Screenshot:
![screen shot 2017-03-03 at 2 26 47 am](https://cloud.githubusercontent.com/assets/12807846/23526708/19143736-ffb9-11e6-9a6d-f26e03cc1ad8.png)

**Comment by mariobehling** [comment]
@geekyd Thank you, though where is the PR? Have a live test page? Could you make the design closer to how others e.g. Youtube does it?

**Comment by aayusharora** [comment]
@mariobehling @geekyd The UX seems confusing with same two separate rows containing the same Twitter icon.

**Comment by geekyd** [comment]
@mariobehling I will improve the design and send a PR. @aayusharora The sharing buttons only appear when the user clicks the link icon.

**Comment by geekyd** [comment]
@mariobehling @aayusharora @championswimmer This feature was added in #1116, Please close it. Thanks
