### ISSUE TITLE
Correct information in Email

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1060]
The mail that is received after app generation should be correct.

- [ ] Render the links
- [ ] UrlEncode the links to remove `%20`
- [ ] Add information for the period after which the link will expire.
![11](https://cloud.githubusercontent.com/assets/12194719/23257180/b05250f0-f9e8-11e6-9b32-43dc173a872e.png)

**Comment by geekyd** [comment]
@aayusharora Why are we trying to do URLencode we could simply do something like this.

<a href="#">Preview it live</a>
<a href="#">Download zip</a>

What do you suggest?

**Comment by utkarshnath** [comment]
@aayusharora can I work on this and whats the exact period after which the link expires here or where could I find that

**Comment by Princu7** [comment]
@geekyd Nice Idea.

@utkarshnath Go Ahead :) The preview link of the Heroku URL expires really quickly(somewhere under couple of hours). The Download Link of the zip file on the AWS has been setup to expire within 3 days from the time of upload. Please add these relevant details to the email send to the user. Also, try to implement @geekyd suggestion.
