### ISSUE TITLE
Session and speakers information not showing up on generated site from API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1061]
Session and speakers information should be showing on the site below the session main heading. Site was generated through the API from the 2017 FOSSASIA example.

![screenshot from 2017-02-23 20-05-31](https://cloud.githubusercontent.com/assets/1583873/23258499/80e766dc-fa03-11e6-9de7-8838dfb776ff.png)

**Comment by Princu7** [comment]
@mariobehling  The earlier event files used `long_abstract` property for their description. In the FOSSASIA 17 files, `short_abstract` is being used for the description and the `long_abstract is empty. That's why there is no session detail. Will correct and send a request soon.

**Comment by aayusharora** [comment]
@mariobehling @Princu7 Issue opened : https://github.com/fossasia/open-event-orga-server/issues/3237

**Comment by Princu7** [comment]
@aayusharora @mariobehling Based on the discussion in the above issue, we should implement it according to the latest changes in the server.

**Comment by mariobehling** [comment]
Ok, I think we can do like that: Implement a function: If long abstract is not available use short abstract. (Same with speakers info).

**Comment by geekyd** [comment]
@mariobehling yeah that will be good.

**Comment by Princu7** [comment]
Nice. On it :)

**Comment by aayusharora** [comment]
@Princu7 What's the status?

**Comment by Princu7** [comment]
@aayusharora It's almost done. Sorry for the delay. I have exams from Monday and haven't studied anything so :sweat_smile: I will send a PR soon. Thanks!!

**Comment by aayusharora** [comment]
Cool :) Best of luck.

**Comment by Princu7** [comment]
Closed via #1084
