### ISSUE TITLE
Start Page: Detailed Featured Speaker Info not showing up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1062]
The FOSSASIA Summit 2017 site that is generated from the API does not show the detailed speakers info on the start page.

![screenshot from 2017-02-23 20-10-24](https://cloud.githubusercontent.com/assets/1583873/23258674/3b2f5b44-fa04-11e6-9614-82a159ec62e7.png)

**Comment by AnaghHegde** [comment]
@mariobehling I am interestedd in this. Can i work on this ?

**Comment by aayusharora** [comment]
@AnaghHegde, yes go ahead !!.

**Comment by Princu7** [comment]
@aayusharora @AnaghHegde This issue got solved because of #1084. Closing this.
