### ISSUE TITLE
Copyright Info missing info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1063]
The copyright info of a page that is generated from the API file of FOSSASIA 2017 is missing a full stop and the word license.

![screenshot from 2017-02-23 20-12-35](https://cloud.githubusercontent.com/assets/1583873/23258762/a2b32b92-fa04-11e6-9650-c5b194bea665.png)

It should read "© 2017 FOSSASIA and Science Centre Singapore. The website and it's contents are licensed under the Creative Commons Attribution License."

If this issue is caused by the server output, please open an issue there.

**Comment by AnaghHegde** [comment]
@mariobehling I would like to work on this.

**Comment by Princu7** [comment]
@AnaghHegde Please proceed :)

**Comment by shubham-padia** [comment]
@Princu7 @aayusharora https://github.com/fossasia/open-event-orga-server/issues/3238 has been solved. A new field `licence_details` has been added to the api. Please have a look at http://open-event-dev.herokuapp.com/api/v1/#!/events/get_event for more info.
Cheers.

**Comment by geekyd** [comment]
@shubham-padia Thanks for the update. I will look into it. :)
