### ISSUE TITLE
Schedule and Rooms Page show wrong order of Days

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1064]
Menu tab show Sunday, Friday, Saturday on schedule and rooms page. Please ensure days are sorted by weekdays instead of other sortings like alphabetical.

![screenshot from 2017-02-23 20-17-16](https://cloud.githubusercontent.com/assets/1583873/23258875/3f33f3de-fa05-11e6-978e-42bc0b2d2d72.png)

**Comment by geekyd** [comment]
@mariobehling sir I would like to work on this.

**Comment by aayusharora** [comment]
@geekyd  Sure :)
