### ISSUE TITLE
Speakers Page shows speaker twice if they give talk a) alone and b) second one together with another speaker

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1065]
The Speakers Page shows speaker twice if they give talk a) alone and b) second one together with another speaker. Expected is, that the talk shows up across each speakers image.

This might be an issue in the format and server. Please open relevant issues in those projects.

![screenshot from 2017-02-23 20-21-10](https://cloud.githubusercontent.com/assets/1583873/23258985/cf57100e-fa05-11e6-8d48-398e2edc29e4.png)

**Comment by geekyd** [comment]
@mariobehling The issue lies in the api data as the speaker data for a talk containing two people is listed together as `speaker 1 and speaker 2` which lets the app generator treat them as one.

**Comment by geekyd** [comment]
@mariobehling @aayusharora I opened an issued in the orga-server please check this [issue](https://github.com/fossasia/open-event-orga-server/issues/3240) .

Seems like the organised entered two names in the speaker field which is causing the problem.
Please guide about how to handle the case.

**Comment by aayusharora** [comment]
@mariobehling Please suggest this. In that case this will belong to two separate sessions.  Thanks

**Comment by mariobehling** [comment]
@aayusharora Not sure, what is the question: The goal of the open event project was that we can have multiple relationships, e.g. several speaker for one session.

**Comment by geekyd** [comment]
@mariobehling We can have multiple speakers for a session but in the above case the organiser has entered names of two speakers in one data cell instead of adding them separately.

Please check https://github.com/fossasia/open-event-orga-server/issues/3240
