### ISSUE TITLE
Ticket link wrong on sample generated through API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1067]
The ticket link on a sample generated for the FOSSASIA Summit 2017 is https://eventyay.com/e/45da88b7/tickets/. It leads to a page that is not working. There is no ticket subpage. The link to the event itself works though: https://eventyay.com/e/45da88b7/

If this is an error in the server, please open issue there.

**Comment by aayusharora** [comment]
@Princu7 @mariobehling Issue https://github.com/fossasia/open-event-orga-server/issues/3238

**Comment by Princu7** [comment]
This issue has been fixed. Closing this :)
