### ISSUE TITLE
Display sponsors according to their level

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1068]
Sponsors on the open event server can get a number with the highest level number showing sponsors on the top. This is the case on the public event page on eventyay. Please ensure this is also the case on the web app: Show sponsors with the highest level number on the top.

![screenshot from 2017-02-23 20-37-03](https://cloud.githubusercontent.com/assets/1583873/23259441/10ca9ae0-fa08-11e6-9855-cc3ccec913b0.png)

**Comment by CosmicCoder96** [comment]
@mariobehling I would like to work on this.

**Comment by AnaghHegde** [comment]
@CosmicCoder96 I have already started working on this.

**Comment by aayusharora** [comment]
@CosmicCoder96 Sure !! Please check if the server is giving the exact details for sponsors as `Platinum` , `Gold` and `Silver`. This is already configured in webapp but as it is not reflecting here it seems an error in orga-server API data.

**Comment by aayusharora** [comment]
@CosmicCoder96 @Princu7 Here, we have to sort the sponsor levels and than have to arrange them according to their level. Please consider this https://github.com/fossasia/open-event-orga-server/issues/3245 for reference.

**Comment by Princu7** [comment]
@aayusharora I will try to solve this issue. It may take some time because of the exams :sweat: If anyone else want to take up this issue, feel free to do so. @CosmicCoder96 Are you solving this issue?

**Comment by geekyd** [comment]
@CosmicCoder96 have you started working on this issue?
We need to solve these issues as soon as possible.
Thanks.

**Comment by goelrohan6** [comment]
@aayusharora I'm willing to contribute to the issue, can you please help me get familiar with the codebase and where exactly are the changes need to be made.

**Comment by niharika88** [comment]
hi,
I can work on this asap

**Comment by aayusharora** [comment]
@goelrohan6 You will find sponsors level code in fold.js file. The data from the API send us the `levels ` keyword. We have to arrange speakers in a responsive UI from high value to low level value.
@niharika88  Please coordinate with @goelrohan6

**Comment by dinesh-sirvi** [comment]
Can I work on this?

**Comment by CosmicCoder96** [comment]
@geekyd @Princu7 @aayusharora 
Sorry it got delayed , because of the exams. Please go ahead.

**Comment by dinesh-sirvi** [comment]
@aayusharora plz check the result

[https://open-event-webapp1.herokuapp.com/](https://open-event-webapp1.herokuapp.com/)

**Comment by Princu7** [comment]
This has been fixed. Closing this :)
