### ISSUE TITLE
Day header is overlapping the slider

### ISSUE THREAD

**Issue by vjs3** [fossasia/open-event-webapp#107]
In the sessions tab of the web app header named Day 2 is overlapping the smaller slider.I have seen this issue in google chrome (in linux).
I am attaching screenshot for more clear understanding of the issue.
![openevent - google chrome_002](https://cloud.githubusercontent.com/assets/11405622/12818478/0e7d2452-cb7d-11e5-9f71-0834a678b9a6.png)

**Comment by tarun14110** [comment]
I think this is intentionally done. So that a user can scroll without caring to remember the day. At any point of time he can have a look over above and get an idea, where he is.

**Comment by vjs3** [comment]
Yes I know but my issue is different, it says that day header is
overlapping the scrollbar itself which should not happen.

**Comment by aayusharora** [comment]
@vjs3 ,I got your issue.Working on it.

**Comment by aayusharora** [comment]
fixed here ,#108

**Comment by rajansavaliya** [comment]
Please tell me how to open .js file. I am opening it in chrome and it is not displaying as you put photo. It is just displaying code
