### ISSUE TITLE
Logo in header not scaled properly for Fossasia Summit

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1074]
@mariobehling @aayusharora @Princu7 

I have noticed that the app generated using api, has improper scale for the logo in header

**Fossasia 2016**
![screen shot 2017-02-24 at 3 49 28 pm](https://cloud.githubusercontent.com/assets/12807846/23299864/2bf5fcbe-faa9-11e6-88c7-15a5c9460bda.png)

**Fossasia Summit**
![screen shot 2017-02-24 at 3 49 37 pm](https://cloud.githubusercontent.com/assets/12807846/23299865/2c017be8-faa9-11e6-84a1-0f40b8ad52c7.png)

**Mobile View**
![screen shot 2017-02-24 at 3 58 14 pm](https://cloud.githubusercontent.com/assets/12807846/23300104/1df3d8a6-faaa-11e6-899e-01456e0b0480.png)

**Comment by anu-007** [comment]
@geekyd I also noticed it, may I work on it.

**Comment by geekyd** [comment]
@anu-007 let @aayusharora review the issue first.
You can go ahead after that 👍

**Comment by aayusharora** [comment]
@anu-007  Cool, go ahead @geekyd we are not scaling the logo now if the app is generated with endpoint. But, We have to do this, thanks for opening :)

**Comment by geekyd** [comment]
@anu-007 Have you started working on the issue?
Please can you provide the status?

**Comment by kaushalvivek** [comment]
Hi, I am new to FOSS ASIA, and open source contribution in general, and I am looking for a place to start. May I take up this issue?

**Comment by Princu7** [comment]
@kaushalvivek Welcome :smiley: Sure. Also, check out the same issue #1277 related to a different event. It has been fixed for this event, I guess. And in the case of more questions, please do ask. Thanks!!

**Comment by aayusharora** [comment]
@Princu7 What does it mean by `it is fixed for this event` ?
Just to clear, We are not event driven. A code that works for one event should work for all events.
Thanks.

**Comment by Princu7** [comment]
@aayusharora Yes. I guess I phrased it incorrectly. What I wanted to say was that the logo of this event was changed so it doesn't cause any problem anymore. So, this issue won't be there when generating the app for this event. In the case of other events eg. OTS, where the logo is big and unscaled, we have to scale it and it would be good for testing purposes and the fix would naturally extend to all events. Thanks!!

**Comment by aayusharora** [comment]
Ok, make sense.

**Comment by geekyd** [comment]
@aayusharora @Princu7 We must scale the logo while generating the web-app, this will provide us more consistency across all the events, if we use `transform` CSS in frontend, the solution may work for few events, but not for all the events as the logo will be not be scaled and will have different sizes for different events.
One more advantage of this would be improved load speed as the logo size would be decreased significantly.

**Comment by Princu7** [comment]
@geekyd Agreed. Nice idea!! @aayusharora Please guide. Thanks!!

**Comment by Princu7** [comment]
Issue solved. Closing this :)
