### ISSUE TITLE
Improvements on Speakers page

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1078]
- [ ] Remove `( ) ` if there is no data 
 - [ ] change speaker social Icons color in popover to black on hover
 - [ ] On hover, Change the color of speaker session in popover to black with underline.

![67](https://cloud.githubusercontent.com/assets/12194719/23330488/ef9f9028-fb74-11e6-89fa-22ef5591b057.png)

**Comment by SparshBansal** [comment]
@aayusharora I can resolve this issue

**Comment by aayusharora** [comment]
@SparshBansal Go ahead :+1:

**Comment by Princu7** [comment]
Closing this :)
