### ISSUE TITLE
Date on sample page only shows beginning but not end date of event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1079]
The FOSSASIA sample page only shows the event start date on 17th March. It should also show the end date.

![screenshot from 2017-02-25 21-38-25](https://cloud.githubusercontent.com/assets/1583873/23331542/e866fc50-fba2-11e6-9bdd-1b7e88f90cb0.png)

**Comment by geekyd** [comment]
@mariobehling I will look into it.
