### ISSUE TITLE
Featured Speaker description is missing on new sample page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1080]
The featured speaker description is missing on the new sample page.

![screenshot from 2017-02-25 21-40-29](https://cloud.githubusercontent.com/assets/1583873/23331553/279ba5f6-fba3-11e6-9e14-a5063f4867c8.png)

**Comment by aayusharora** [comment]
@mariobehling  Seems a copy of the issue https://github.com/fossasia/open-event-webapp/issues/1062.
Closing this :)
