### ISSUE TITLE
Nav bar links are Grey instead of black

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1081]
@aayusharora @mariobehling @Princu7 

The colour of the nav bar links has changed
I think it got changed in #1070 

Screenshot
![screen shot 2017-02-26 at 12 14 33 am](https://cloud.githubusercontent.com/assets/12807846/23333852/40b08dfc-fbb9-11e6-997e-50456b9b222a.png)

**Comment by Princu7** [comment]
Go Ahead :)
