### ISSUE TITLE
Schedule page: text appending outside the div

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1085]
![dc41676a-fc12-11e6-9592-040cf87bfc76](https://cloud.githubusercontent.com/assets/12807846/23337827/0205a58a-fc20-11e6-864d-f5bb15d7d3e5.png)

@aayusharora @Princu7 @mariobehling 
I'm working on the fix for the issue.

**Comment by Princu7** [comment]
@geekyd I almost solved this issue while working on the previous PR. If you haven't started working on it or if you are busy in solving some other issues, then you can just ping me. I will quickly fix it. If you have already started, then no problem. Go ahead :smile:

**Comment by geekyd** [comment]
Sure go ahead 👍
