### ISSUE TITLE
Buggy scroll bar at Featured Speakers section

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1088]
- The scrollbar disappears instantly with just 2px away from it which result in a buggy situation where a user can not scroll down.

**Comment by geekyd** [comment]
@aayusharora could you please elaborate?

**Comment by aayusharora** [comment]
# Steps to Reproduce
-  Go to HOME page featured Speakers section.
-  Hover on any speaker and try to scroll it down
- The scroll bar disappears instantly.

**Comment by geekyd** [comment]
@aayusharora 
I works for me check this out.
Check this out 


![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/12807846/23342481/108f0734-fc81-11e6-9423-adbaff31db0d.gif)

**Comment by Princu7** [comment]
Yeah, Works for me too. Difficult to reproduce the error. Could you please provide a video or gif showing the problem :)

**Comment by aayusharora** [comment]
@geekyd It seems you are hovering on speakers page and try to scroll the down. Instead, hover on speakers description, you will get a scrollbar that will be visible for an instant only.

**Comment by geekyd** [comment]
@aayusharora Its about how the browser behaves, eg. chrome obeys the settings provided by the user in the system preferences. My preference was set to auto hide the scroll and use the track-pad, after changing the setting I was able to get this result. The scroll does not hide automatically after it. 

https://www.useloom.com/share/602a665716ca43da921a818ec951b48a

**Comment by aayusharora** [comment]
@geekyd Last year, I encountered with the same issue, What happens now 
- You add `overflow : overlay`.
- You are not giving the space to the user to scroll.
Please add padding-right, margins inside the speaker description content so that the scroll bar will get some space and will disappear when we are some px far away from the description.

**Comment by aayusharora** [comment]
@geekyd Can you also verify if it is working fine on Mozilla too.

**Comment by geekyd** [comment]
@aayusharora I will do that.

**Comment by geekyd** [comment]
@aayusharora The scroll is not functional in Morzilla. I'm working on it.
