### ISSUE TITLE
Schedule closes after clicking Link Icon

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1089]
# Steps to reproduce
- Go to Schedule page and click on any session.
- Click on link icon that appears in description.
### The `div` closes when the icon is clicked.

**Comment by geekyd** [comment]
@aayusharora Actually it closes on clicking the content inside the div.

**Comment by aayusharora** [comment]
Add an `if` condition in jQuery so that if the div containing the Link icon is clicked, the session does not closes.

**Comment by geekyd** [comment]
It is happening due to the `collapse class assigned to the div`

**Comment by geekyd** [comment]
@aayusharora 
Wouldn't it be better if we remove the `collapse` class?
What do you suggest?

**Comment by Princu7** [comment]
@geekyd @aayusharora Actually the div closes the clicking the contents of the div on rooms and speakers pages also. I think it has been there for quite some time. So if we decide to remove it, we should ensure that the behaviour is consistent across all the pages :)

**Comment by geekyd** [comment]
@Princu7 Absolutely 👍

**Comment by geekyd** [comment]
@aayusharora What do you suggest?

**Comment by geekyd** [comment]
@aayusharora Please check this 
https://www.useloom.com/share/123960c3b7d84d929fadff98a88f2b2f

**Comment by aayusharora** [comment]
@geekyd Please generate a PR for this.
