### ISSUE TITLE
Empty details of speaker

### ISSUE THREAD

**Issue by AmayAgrawal** [fossasia/open-event-webapp#109]
![screenshot from 2016-02-17 13 32 29](https://cloud.githubusercontent.com/assets/12967238/13103271/f9d861d0-d57a-11e5-88fe-40fb8f668132.png)

As can be seen in the above screenshot in most of the speaker details, Sessions and the social links field is still empty.

**Comment by SaptakS** [comment]
That is because the json data served from the server doesn't have any session or social link data associated with that specific speaker.

**Comment by AmayAgrawal** [comment]
So this is basically be done after open server one adds the json data to it.Am i right??

**Comment by SaptakS** [comment]
Yes.

**Comment by ashutoshsaboo** [comment]
@AmayAgrawal @SaptakS You can check out this PR - https://github.com/fossasia/open-event-webapp/pull/130 . It solves most of these issues. So, Can this be merged to close this issue and mark this issue as solved?

**Comment by AmayAgrawal** [comment]
Yes Sir definitely.I have also made some PR regarding  this in  Update speakers #111 .Can u please check this also.And I have also created some sharing sharing buttons also and PR'd  it also
