### ISSUE TITLE
Speaker Photo bug on rooms page

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1090]
Seems like the problem which was solved earlier on the tracks page still exists on the speakers page. The thumbnail image of the speaker is displayed below its intended position leading to bad UX. 
* Screenshots
![screenshot from 2017-02-27 01-19-55](https://cloud.githubusercontent.com/assets/8847265/23343060/33057b90-fc8b-11e6-90a9-a1d5d94ad301.png)
![screenshot from 2017-02-27 01-20-04](https://cloud.githubusercontent.com/assets/8847265/23343063/3cd52e4a-fc8b-11e6-90c5-3a74674d76e1.png)

**Comment by Princu7** [comment]
I am kind of busy right now due to exams so if anyone wants to take up this issue, feel free to do so :)

**Comment by geekyd** [comment]
@Princu7 I will take care of this :)
Best of luck for the exams 👍
