### ISSUE TITLE
Expansion of sessions not possible when scrolling over session title

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1097]
When the user tries to expand the session scrolling and clicking on the session title itself, it is not expanding. There is no expansion link. This can be observed on http://2017.fossasia.org/rooms.html

**Comment by Princu7** [comment]
I will have a look at it :)

**Comment by shashanktatti** [comment]
can i work on this?

**Comment by Princu7** [comment]
@shashanktatti I am working on it :)
