### ISSUE TITLE
Substitute spaces with underscore characters to avoid broken URLs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1099]
Substitute spaces with underscore characters to avoid broken URLs. 

Background: Direct links to tracks can contain spaces. Copying those URLs into other applications will result in broken URLs if the spaces are not counted as part of the URL, e.g. "http://2017.fossasia.org/tracks.html#2017-03-18-Hardware & Making".

**Comment by geekyd** [comment]
I will have a look at it.
