### ISSUE TITLE
Add a comma if several speakers are on same track

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1100]
The Artificial Intelligence panel has several speakers for example. Please add a comma after each person and its affiliation, if several speakers are in a session.

![screenshot from 2017-03-01 12-30-26](https://cloud.githubusercontent.com/assets/1583873/23446053/00dccaf0-fe7b-11e6-9e9a-5ec843ebc04b.png)

**Comment by Rishabhk07** [comment]
Hey, Can i work on this issue ?

**Comment by aayusharora** [comment]
Sure @Rishabhk07. Go ahead 👍

**Comment by Rishabhk07** [comment]
Thanks @aayusharora , can you please tell me api link/zip file of this generated website because this is not among sample zip files.

**Comment by geekyd** [comment]
@Rishabhk07 You can use https://eventyay.com/api/v1/events/6 for api endpoint.
For zip use this.
https://github.com/fossasia/open-event/tree/master/sample

**Comment by aayusharora** [comment]
Thanks @Rishabhk07

**Comment by geekyd** [comment]
@Rishabhk07 Great work, I think we can extend this to rooms page too.
@aayusharora what do you suggest?

**Comment by aayusharora** [comment]
Yes Exactly @geekyd

**Comment by Rishabhk07** [comment]
@aayusharora @geekyd  cool, i will work on that and send the PR soon

**Comment by Princu7** [comment]
Work Done. Thanks!!

**Comment by mariobehling** [comment]
The comma is not implemented according to US/GB English. There should not be a space before the comma.

![Uploading Screenshot from 2017-03-04 10-35-06.png…]()
