### ISSUE TITLE
Improving performance of Web app

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1105]
- Please see Google page insights and improve the performance of pages.
- [ ] Approaches we can adopt for RAIL model.
- [ ] Suggest and implement the ways to improve DOM and CSSOM construction, which is currently done at once.
- [ ] Remove render-blocking CSS
- [x] Add gulp to minify the JS, CSS code for production.
- [x] Compress images and scale them to 264px rather than 300px.
- [x] Add lazy loading for images

**Comment by anu-007** [comment]
@aayusharora checked google page insights, I think we need to do more work on web app for mobile devices as the scores are low i.e. (63/100) and the performance on desktop is also average i.e. (78/100),I like to work on it.

**Comment by Princu7** [comment]
I will read up on Gulp and try to integrate it. Will also compress the images using sharp module.

**Comment by geekyd** [comment]
@aayusharora We also need to use the browser cache to cache the resources used by the app.

**Comment by Princu7** [comment]
@geekyd Yeah, sure. Go ahead :+1:

**Comment by geekyd** [comment]
@aayusharora I'm working on minification of the scripts and css files using gulp, will be sending a PR for it.

**Comment by geekyd** [comment]
@aayusharora I have implemented the minification of all the css, js and html files using gulp.
Please check : https://open-event-web-appp.herokuapp.com
Also check the performance using https://developers.google.com/speed/pagespeed/insights/
The score has improved. Thanks

**Comment by aayusharora** [comment]
@geekyd Thanks. Minification is working but I guess,  still there are 7 JS files which are requested as resources and same goes for 3 CSS files. When we give the app to production, we can send only 1 minified JS and CSS from Node server, Please make sure there will be no conflicts in the code when doing this. You can use IIFE in JS to remove same name variable/function conflicts.

**Comment by geekyd** [comment]
@aayusharora So i should concat all the Js files and create a master script for web-app and same with Css??

**Comment by aayusharora** [comment]
Hmm, let's leave CSS for now, planning to use `critical-css` module to only load necessary CSS on first load. JS we can minify and do.

**Comment by geekyd** [comment]
@aayusharora Okay I'm on it. Thanks :)

**Comment by aayusharora** [comment]
@geekyd Updates ?

**Comment by geekyd** [comment]
@aayusharora I'm almost done with this, fixing the js files as they are causing problems after using iife and uglify. I will send a PR soon.

**Comment by mariobehling** [comment]
I am totally for speed up but lazy loading is distracting the user and makes this site look slower. It also means: Once I open the page, I do not download the whole page and can go offline, but it becomes more of an online app. The goal of this app is rather to have the browser storing the app and making the images smaller than lazy loading (where I need to be online).
We achieved to make the FOSSASIA 2016 Summit to 4.2 MB
For the FOSSASIA 2017 Summit just the background image is still 1.8MB.
So, can we rather optimize on that end than lazy loading?

**Comment by geekyd** [comment]
@mariobehling @aayusharora @Princu7 Lazy load can be customised to provide a better user experience, please check this link https://www.appelsiini.net/projects/lazyload , we can customise the **Threshold** , to load pictures before it reaches the viewport.

**Comment by Princu7** [comment]
@geekyd Yes. Increasing the threshold would be better indeed. But one more problem with the lazy loading as stated by @mariobehling is that the pages won't load fully unless we completely explore the page which means that they can't be saved and then viewed offline properly at conferences and events. We should have more detailed discussion regarding this but for the time being, let's go with the current configuration. Thanks!!

**Comment by geekyd** [comment]
@aayusharora I propose not to concat all the JS files of the project as not all the JS files are used in every page. If we concat all the js it leads to error in script for the page where it is not used.
eg. 
tabs.js gives error in the index.html page as it cannot resolve the classes used in the js.

We should minify all the js and use them separately.What is your opinion. Would love to know your opinion. :)

**Comment by aayusharora** [comment]
@mariobehling reverting this will load, say 1000 images at once on Network, lazy loading is always effective and efficient. Nobody wants to use a slow app.
@mariobehling @princu7 @geekyd I would suggest to resume this and make changes such that it works before the viewport.
@mariobehling The concept of lazy loading does not depend on internet, hence there is no problem for this in offline mode.

**Comment by aayusharora** [comment]
@geekyd please concatenate files using IIFE

**Comment by geekyd** [comment]
@aayusharora I used IIFE to concat all the files but as i mentioned the js which are not used in the html gives error in the script, which is not desired.

**Comment by aayusharora** [comment]
Can we insert it pagewise than ?

**Comment by geekyd** [comment]
Yes, we can make individual js for each page, that wont give any error and should work :)

**Comment by aayusharora** [comment]
@geekyd 
- Can you please change the threshold and generate a new PR, we don't want the user know, that something is happening.
- Can you check the performance improving after minification via gulp.

**Comment by geekyd** [comment]
@aayusharora I'm on it.

**Comment by aayusharora** [comment]
Cool !!

**Comment by geekyd** [comment]
@aayusharora Please re-open this issue. Thanks

**Comment by mariobehling** [comment]
Many improvements have been made. Follow up issues should go more into specifics.
