### ISSUE TITLE
Sessions in room page do not render properly

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1110]
This bug was introduced in while solving #1101.
Very sorry for the problem caused.

Screenshots :
![screen shot 2017-03-02 at 8 32 44 pm](https://cloud.githubusercontent.com/assets/12807846/23512693/79d2dcee-ff87-11e6-8007-77be75407138.png)

**Comment by Princu7** [comment]
Please fix it ASAP. Thanks!!

**Comment by geekyd** [comment]
@Princu7 Please check PR #1109
