### ISSUE TITLE
on cancelling upload of a zip file, chose file div should appear again

### ISSUE THREAD

**Issue by Rishabhk07** [fossasia/open-event-webapp#1115]
**Actual Behaviour**

on generator website,on cancelling while uploading a zip(JSON files), upload box disappears but chose a file does not reappear, you cannot chose another file to upload again unless you select "upload your own check JSON files" checkbox  again

**Expected Behaviour**

on cancelling while uploading a zip , chose a file box should appear again

**Steps to reproduce it**

Step1 : upload JSON file
Step2: cancel upload while uploading

**Screenshots of the issue**

<img width="952" alt="screen shot 2017-03-02 at 11 40 58 pm" src="https://cloud.githubusercontent.com/assets/8939938/23520639/e6f17f5a-ffa1-11e6-9789-262bea853991.png">

<img width="895" alt="screen shot 2017-03-02 at 11 41 07 pm" src="https://cloud.githubusercontent.com/assets/8939938/23520608/c3cd5634-ffa1-11e6-804c-7e55b43615b3.png">

**Would you like to work on the issue?**

Yes, will send the PR soon.

**Comment by Princu7** [comment]
@Rishabhk07 Thanks for the issue. Actually, this is a known bug and the work is already being done on it.
See the discussions in the issue #952. Please try other existing issues :)

**Comment by Rishabhk07** [comment]
i am sorry, to open an existing issue but couldn't help but notice that the issue is not quite the same as issue #952 and its discussion, after cancelling the upload of a file that is before clicking generate website,  i cannot upload another file because chose file box does not reappear. i have to select api endpoint check box and then again select upload your own JSON file checkbox so that  chose your file appears.
hence my issue was that chose your file box should re appear on cancelling the upload.

**Comment by Princu7** [comment]
@Rishabhk07 Yeah You are right that they are not exactly the same. This issue is a by-product of that issue. The problem is that the file continues to upload to the server after clicking the X button. That's why the choose file box option does not reappear because the file doesn't get cancelled correctly. So even if we show the checkbox for uploading the second file, the second file won't start uploading until the first one is finished. So the first priority is to fix this server bug. The UI issues will be fixed then easily

**Comment by Rishabhk07** [comment]
okay cool, really sorry for opening a redundant issue

**Comment by Princu7** [comment]
The first cancelled file continues to upload even after cancellation. Even if we select another file somehow,  it won't be uploaded until the first one is fully uploaded to the server or we refresh the page and abort the upload.
Video Demo:
https://www.useloom.com/share/ca84946367e94154a3ef5a9039f12b2a

If you want to correct the UI though, you can still go ahead

**Comment by Princu7** [comment]
@Rishabhk07 No problem at all. This wasn't really a duplicate. As soon as the server bug is fixed, you can work on the UI part of it. Thanks for the discussion.

**Comment by Rishabhk07** [comment]
@Princu7 ya, you are right even if the UI big is fixed, server will not be able to upload a new file until the previous file is uploaded, Thanks will fix it as soon as the server bug is fixed.
