### ISSUE TITLE
Do not show unscheduled sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1118]
The sessions in the exhibition track are unscheduled, but they still show up. This is related to the API showing data that is still unscheduled. So, this issue needs to be tackled together. There is a corresponding issue here: https://github.com/fossasia/open-event-orga-server/issues/3277

**Comment by geekyd** [comment]
@mariobehling I will look into it asap.Need clearance about what attribute of the API data will have the status?

**Comment by Princu7** [comment]
The work is still to be done in the API of the server.

**Comment by geekyd** [comment]
Okay if we change the API we also need to change the zip data format. That also needs to be done.

**Comment by Princu7** [comment]
@shubham-padia Has shed some light on this problem. He talks about it here:
https://github.com/fossasia/open-event-orga-server/pull/3450
If the microlocation field of the session is null, the session is unscheduled. There is no need for a redundant field in the API. We can implement the logic using it. I am looking into it. Thanks!!

**Comment by geekyd** [comment]
@Princu7 Go ahead.
