### ISSUE TITLE
Failed generation of web app at downloading speaker photo(Source = apiEndPoint)

### ISSUE THREAD

**Issue by dinesh-sirvi** [fossasia/open-event-webapp#1120]
While generating app using endPointApi http://eventyay.com/api/v1/events/6 , it failed on downloading speaker photo.

**Comment by Princu7** [comment]
Please give the full error log.  It seems to work on the official deployment.

**Comment by dinesh-sirvi** [comment]
`Downloading photo : https://storage.googleapis.com/eventyay.com/events/6/speakers/2167/photo/ZFd5OHBEam/1485777076.63.png to images/speakers/1485777076.63.png
/home/dinesh/Projects/open-event-webapp/src/backend/dist.js:462
      next(photoFilePath);
      ^

TypeError: next is not a function
    at /home/dinesh/Projects/open-event-webapp/src/backend/dist.js:462:7
    at Request.<anonymous> (/home/dinesh/Projects/open-event-webapp/src/backend/dist.js:34:9)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/home/dinesh/Projects/open-event-webapp/node_modules/request/request.js:986:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.pars`

**Comment by geekyd** [comment]
@dinesh-sirvi It seems to work, can you provide log. Thanks.

**Comment by dinesh-sirvi** [comment]
LOGS:- 
INFO:Copying Jsons

INFO:Fetching Jsons from the internet

INFO:Creating json folder insde the appPath directory

SUCCESS:All jsons have been successfully downloaded

SUCCESS:SASS file compiled successfully

SUCCESS:css file was written successfully

INFO:Extracting data from the uploaded jsons

It stopped here

**Comment by dinesh-sirvi** [comment]
fold.js

`
      if (speaker.photo !== null && speaker.photo != '') {
        if (speaker.photo.substring(0, 4) === 'http') {
          distHelper.downloadSpeakerPhoto(appFolder, speaker.photo), function(result){
            speakers[key].photo = encodeURI(result);
            callback();
          };
        }
        else  if (reqOpts.datasource === 'eventapi' ) {
          distHelper.downloadSpeakerPhoto(appFolder, urljoin(reqOpts.apiendpoint, speaker.photo), function(result){
            speakers[key].photo = encodeURI(result);
            callback();
          });
        } else {
          var reg = speaker.photo.split('');
          if(reg[0] =='/'){
            speakers[key].photo = encodeURI(speaker.photo.substring(1,speaker.photo.length));
            callback();
          }
        }
      } else {
        callback();
      }`

**Comment by dinesh-sirvi** [comment]
`
      if (speaker.photo !== null && speaker.photo != '') {
        if (speaker.photo.substring(0, 4) === 'http') {
          distHelper.downloadSpeakerPhoto(appFolder, speaker.photo), function(result){
            speakers[key].photo = encodeURI(result);
            callback();
          };
        }
        else  if (reqOpts.datasource === 'eventapi' ) {
          distHelper.downloadSpeakerPhoto(appFolder, urljoin(reqOpts.apiendpoint, speaker.photo), function(result){
            speakers[key].photo = encodeURI(result);
            callback();
          });
        } else {
          var reg = speaker.photo.split('');
          if(reg[0] =='/'){
            speakers[key].photo = encodeURI(speaker.photo.substring(1,speaker.photo.length));
            callback();
          }
        }
      } else {
        callback();
      }`

**Comment by dinesh-sirvi** [comment]
if (speaker.photo !== null && speaker.photo != '') {
        if (speaker.photo.substring(0, 4) === 'http') {
          distHelper.downloadSpeakerPhoto(appFolder, speaker.photo), function(result){
            speakers[key].photo = encodeURI(result);
            callback();
          };
        }
        else  if (reqOpts.datasource === 'eventapi' ) {
          distHelper.downloadSpeakerPhoto(appFolder, urljoin(reqOpts.apiendpoint, speaker.photo), function(result){
            speakers[key].photo = encodeURI(result);
            callback();
          });
        } else {
          var reg = speaker.photo.split('');
          if(reg[0] =='/'){
            speakers[key].photo = encodeURI(speaker.photo.substring(1,speaker.photo.length));
            callback();
          }
        }
      } else {
        callback();
      }

**Comment by Princu7** [comment]
Weird. It works on my localhost. Is your code updated? Plese check.

**Comment by geekyd** [comment]
@dinesh-sirvi @Princu7 It seems to work on server as well as local host.

**Comment by Princu7** [comment]
Yeah. There might be couple of reason

* The code is not updated. So the server might be crashing
* Because of the network issues(slow or behind a proxy)

**Comment by dinesh-sirvi** [comment]
was specific to my local repo, thanks...!! Closing this now
