### ISSUE TITLE
Featured Speakers: Unwanted line breaks and bold text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1121]
The featured speakers area shows line breaks where the should not be any and bold text.

Please see screenshot below:

![screenshot from 2017-03-05 16-13-50](https://cloud.githubusercontent.com/assets/1583873/23585666/ea7b6d60-01be-11e7-8831-8e7812657499.png)

**Comment by geekyd** [comment]
I will look into it :)
