### ISSUE TITLE
Speaker images saved as png and very large

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1123]
The speakers images are saved as png and they are very large. Jpg is probably better and they should be much smaller.

**Comment by Princu7** [comment]
I will look into it :)

**Comment by anu-007** [comment]
@Princu7 I would like to know if you had started to work on this issue ??

**Comment by Princu7** [comment]
@aayusharora @mariobehling I have done some work on this issue. Most of it is complete, just have to handle some of the edge cases. Here is the test server for testing purposes:
http://secure-meadow-20680.herokuapp.com/
The difference the conversion to jpeg makes to the size of the zip is astonishing. The size of the zip reduced from 32MB to just 12MB.

**Comment by geekyd** [comment]
@Princu7 Great work. The size has reduced significantly. 👍

**Comment by aayusharora** [comment]
Go to see this. This is because it's lossy compression.  Thanks @Princu7, please generate the PR.
