### ISSUE TITLE
Missing avatar for sessions.

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1129]
@mariobehling @aayusharora @Princu7 
The Avatar is missing for certain sessions where the speaker photo is missing. But after clicking the session the avatar appears.

We should add an avatar for the speakers with missing photographs for all such sessions.

Screenshot : 
**Sessions without Speaker photo** 
![screen shot 2017-03-06 at 12 42 24 am](https://cloud.githubusercontent.com/assets/12807846/23590449/236dca86-0206-11e7-9cb1-fb67b6ef6f70.png)

**On clicking the session**
![screen shot 2017-03-06 at 12 42 42 am](https://cloud.githubusercontent.com/assets/12807846/23590453/2e99cfc2-0206-11e7-93f9-5f42d84cbee4.png)

**Comment by Princu7** [comment]
Yeah. Just make a thumbnail for the avatar png image file which is displayed when the image of speaker is present. And then we can use its thumbnail here.

**Comment by aayusharora** [comment]
If the image is not present use the default image as used on speakers page @geekyd

**Comment by geekyd** [comment]
@Princu7 Thanks. @aayusharora I'm on it.

**Comment by geekyd** [comment]
This issue was solved closing it :)
