### ISSUE TITLE
the detail should be closed automatically if we click on different track or schedule or room

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-webapp#1130]
if we click on a different track or schedule or room the previously opened div should be closed, so as to reduce scrolling on the track, schedule and room page.

![alt text](https://github.com/anu-007/assets/blob/master/Screenshot%20from%202017-03-06%2004-10-32.png?raw=true "demo image")

if it is important I like to work on it.

**Comment by sumedh123** [comment]
I am on it.

**Comment by sumedh123** [comment]
I am on it.

**Comment by aayusharora** [comment]
This does not seem much important to me.
