### ISSUE TITLE
Preloading important scripts and resources without delaying page the page's onload event

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-webapp#1134]
@mariobehling @championswimmer @aayusharora 
I think we should implement <link rel="preload"> declarative fetch directive so that we can convey the browser about the resources (scripts, images, styles etc) that will be needed later to start loading now without blocking the browsers onload event.
By this, the rest of the pages that need the preloaded resources will load quickly and hence the performance of the web app increases.

**Comment by aayusharora** [comment]
@anu-007 Can you please mention the important scripts and files to load which are in your checklist. This is an important fix. Thanks :)

**Comment by anu-007** [comment]
@aayusharora scripts that are under src>backend>assets>js folder.

**Comment by aayusharora** [comment]
Thanks @anu-007 , the crucial step is to identify which functions on client side are taking the maximum time by analysing the `timeline` in chrome console. And than to group them and load them after DOM construction if they are not much important for initial page load.
This comes under RAIL model.

**Comment by anu-007** [comment]
@aayusharora but as mentioned using <link rel="preload"> does not affect the current on load event, but they are loaded parallelly.

**Comment by anu-007** [comment]
@aayusharora you can refer this link ( https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/ ) to understand what I am trying to say :)

**Comment by aayusharora** [comment]
Awesome find @anu-007. We can do this. Go ahead with this.
