### ISSUE TITLE
Apply Lazy load for images to all pages 

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1135]
The speakers page loads very fast on mobiles and desktop as of previous version.
- Apply lazy load to all pages as done on speakers page.
- compare the results and performance improvement, attach snapshots when submitting PR.

**Comment by geekyd** [comment]
@aayusharora I will add it in next PR and attach the screenshots along it :)
It would significantly improve the requests for resources.

**Comment by geekyd** [comment]
@aayusharora This issue was closed.

**Comment by Princu7** [comment]
@geekyd Terrific work. Closing this :)
