### ISSUE TITLE
Text overflow on Tweeter section of Homepage

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1136]
The dynamically appended tweets sometimes exceeds the width of container and results in a horizontal scrollbar on mobiles.

**Comment by geekyd** [comment]
Making the font size small for smaller screens would fix it.

**Comment by sumedh123** [comment]
@aayusharora @geekyd  The tweets are not loading on my heroku setup. Can you tell me what the problem would be with? There are no api configs I guess since we are using loklak.

**Comment by geekyd** [comment]
@sumedh123 The web-app uses loklak to retrieve the tweets from twitter. So heroku blocks the loklak as it uses http instead of https. You can check the tweets on gh-pages.

@aayusharora We need to acknowledge the issue of running loklak on https.
