### ISSUE TITLE
Suggestion : Split documentation in two parts.(i.e README.md and CONTRIBUTING.md)

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-webapp#1137]
I think we should split up the documentation in two parts. Currently it is only readme which also has contribution guidelines. Separating them into two would make the documentation clean.

**Comment by Princu7** [comment]
Thanks for opening the issue. Contribution guidelines don't seem to take up much of the README.md file. So, it would be kinda unnecessary to make a separate file for little content. But still, let's wait for more inputs from others. @aayusharora @mariobehling @geekyd What do you suggest about this issue. Would love to hear more opinions. Thanks!!
