### ISSUE TITLE
In schedule, search only works for Friday

### ISSUE THREAD

**Issue by rolandturner** [fossasia/open-event-webapp#1138]
If I go to http://2017.fossasia.org/tracks.html and type Roland into the Search box, I see the 4 events that I'm in.

![correct](https://cloud.githubusercontent.com/assets/646827/23704678/0906912c-0441-11e7-93b7-46a4cfe7acb4.png)

If I go to http://2017.fossasia.org/schedule.html and do the same, I only see the Friday listing. Clicking on the Friday/Saturday/Sunday buttons doesn't change this.

![incorrect](https://cloud.githubusercontent.com/assets/646827/23704679/090c8dd4-0441-11e7-978e-37e05ddead22.png)

**Comment by geekyd** [comment]
@rolandturner Great find. Would you like to work on this?

**Comment by Princu7** [comment]
@geekyd Roland Turner is speaker of few of the sessions which are to take place in the FOSSASIA Summit. I guess he just wanted to ensure that the sessions which he was delivering were being displayed on the site properly or not when he found this bug. It is now our responsibility to correct it. Would you be willing to work on it? Thanks!!

**Comment by geekyd** [comment]
@rolandturner @Princu7 Im sorry about the confusion. 😅  I will work be working on the fix :).

**Comment by aayusharora** [comment]
@rolandturner Thanks, we will fix this.
@Princu7 
 On schedule page, only the sessions name are visible, hence search box is designed to search according to session name. So, if you search your session name you will find it easily.
On tracks page both schedule name and speaker name both are visible, hence the search can be made either through schedule name or speaker name. Both will give filtered results.

**Comment by Princu7** [comment]
@aayusharora Ah. Ok. Got it. Thanks for explaining :)

**Comment by rolandturner** [comment]
@geekyd @Princu7 In addition to being a speaker, I'm part of the FOSSASIA organising team. Mario was showing off recent improvements and I noticed this oddity, so reported it.

I'd suggest that while it makes sense that searching for a speaker's name in a list of session names which doesn't include speaker names, it's not so clear that this is a good idea in the first place. Unless you have a strong reason not to, I'd suggest that the sessions page behave the same way as the tracks and room pages and include the speakers' names, meaning that searching by them works.

That the day buttons have no effect on the schedule page is presumably a separate bug which might be worth fixing anyway.

**Comment by geekyd** [comment]
@rolandturner Agreed. Thank you for the feedback, will make the speaker names searchable :)

**Comment by geekyd** [comment]
@rolandturner We have added the functionality to the application :)

**Comment by rolandturner** [comment]
@geekyd That's great, thank you. I take it that it hasn't yet been rolled out to the live site? (I'm still seeing the same behaviour.)

(Also: I had misunderstood the function of the date buttons; I thought they filtered, in fact they just jump to the date in the existing list, which is working fine.)

**Comment by Princu7** [comment]
@rolandturner There were some problems with deployment. We have fixed them. The changes should be reflected now on the live site. Thanks for opening this issue 
And Yes, you are absolutely correct about the working of the date buttons :)

**Comment by rolandturner** [comment]
That's now working well, thanks.

I am now noticing that the date buttons on the Tracks page appear to have no effect at all after a search (but work correctly on page load, and also in Schedule and Rooms).

**Comment by geekyd** [comment]
@rolandturner Thanks for reporting the issue, the problem is with the multiple copies of the same id of the date being generated after the search is done.

@Princu7 @aayusharora We need to change the current format for displaying the date and track name from 
Track name
Date
To something like rooms page where we have a single date and the names of rooms follow, that will fix the issue.

**Comment by Princu7** [comment]
@geekyd Please go ahead. Thanks :)

**Comment by geekyd** [comment]
@Princu7 @aayusharora @mariobehling 
The tracks page currently uses the following pattern for the heading of each track.
Date
track 1
Date
track 2
The date can be repeated.
And the date buttons point to the first track heading of the date. So when the user searches and uses the date buttons they don't function properly as the buttons point to something that is not visible on the viewport. To solve this issue we need to change the design pattern to something like rooms page where that data is sorted using the date and the headings are as follows
Date 
room 1
room 2

Date 2 
room 1 ..

We need to use a similar pattern to overcome the issue.
Please provide your opinion on the solution and suggest a better solution Thanks :)

**Comment by geekyd** [comment]
https://geekyd.github.io/eventApplication/tracks.html
Please check this link I have made some changes. The search is working as expected, the date buttons are functional and the navbar also seems to work.

**Comment by Princu7** [comment]
Works good. Please make a PR. We can then review it and maybe think of better solutions, if any. Thanks
