### ISSUE TITLE
Space missing before company of speakers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1140]
On the tracks and rooms page there is a space missing in front of each speakers company. It should be: 
Speaker Name (Speaker Company). Right now it is: Speaker Name(Speaker Company).

![screenshot from 2017-03-09 06-24-14](https://cloud.githubusercontent.com/assets/1583873/23727006/5a120650-0491-11e7-800a-1b2ba25355d0.png)

**Comment by sumedh123** [comment]
@mariobehling  I saw that the tracks.hbs and rooms.hbs has note that not to modify those files. What do I need to change in order to make changes in those templates?

**Comment by geekyd** [comment]
@sumedh123 You will have to change the tracks.hbs and rooms.hbs files. Just add a space between `{{name}}{{#if organisation}}({{organisation}})` name and if statement. :)

**Comment by dinesh-sirvi** [comment]
can I do this?

**Comment by sumedh123** [comment]
@mariobehling  Fixed this. PR got merged.

**Comment by Princu7** [comment]
@sumedh123 Thanks. Closing this :)
