### ISSUE TITLE
Schedule: Date buttons overlapping in mobile version

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1143]
The dates are overlapping in small screens on mobiles.

![screenshot_2017-03-10-09-59-08](https://cloud.githubusercontent.com/assets/1583873/23779000/85572f9c-0578-11e7-9a4a-4e13fc471a8a.png)

**Comment by dinesh-sirvi** [comment]
will try to fix this...

**Comment by sumedh123** [comment]
@mariobehling  Can I know the screen size that you tested this on ? I checked it on multiple sizes and it is working fine.

**Comment by Princu7** [comment]
Yeah. Seems to be fine. Maybe the previous pull request fixed it? @mariobehling Could you please recheck? Thanks!!

**Comment by mariobehling** [comment]
Good! I love it when bugs get fixed unintentionally! Cheers.
