### ISSUE TITLE
Schedule: Move time info to the very left instead of indenting

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1144]
The left time column is indented on mobile views. We need to make use of the whole screen. Therefore please avoid the indenting on mobile views.

![screenshot_2017-03-10-09-59-08](https://cloud.githubusercontent.com/assets/1583873/23779037/d1a05194-0578-11e7-8d35-558899a7ae58.png)

**Comment by geekyd** [comment]
I will fix it :)

**Comment by geekyd** [comment]
I'm busy solving other issues, if anyone wants to fix this issue please let me know. Thanks :)

**Comment by vatsalsura** [comment]
@geekyd Can I try to solve this?

**Comment by geekyd** [comment]
@vatsalsura Yes go ahead.

**Comment by vatsalsura** [comment]
@geekyd May I have the link to Open-event API endpoint?

**Comment by geekyd** [comment]
@vatsalsura Use this
https://eventyay.com/api/v1/events/6

**Comment by vatsalsura** [comment]
@geekyd and where do I align the time? On the very left of to the day/date? IMHO aligning it to the very left of the screen won't look good.

**Comment by geekyd** [comment]
@vatsalsura align it to the left most of the container.

**Comment by vatsalsura** [comment]
@geekyd Aligned time-info to the main container.
![screenshot from 2017-03-13 17-11-05](https://cloud.githubusercontent.com/assets/10852939/23853414/71f2f7e6-0812-11e7-82e4-1c0a02745ad4.png)

**Comment by vatsalsura** [comment]
@geekyd Please review PR #1168

**Comment by vatsalsura** [comment]
I think this issue is solved. Hence close it please...!!
