### ISSUE TITLE
Schedule: Make search bar full width on small screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1145]
The search bar has its own row on mobile screen. It should make use of the full 100% width on small screens.

![screenshot_2017-03-10-09-59-08](https://cloud.githubusercontent.com/assets/1583873/23779087/258e7128-0579-11e7-82f6-37cfe59a9903.png)

**Comment by dinesh-sirvi** [comment]
will fix this...

**Comment by sumedh123** [comment]
@dinesh-sirvi  Already opened a PR.

**Comment by dinesh-sirvi** [comment]
no problem @sumedh123
