### ISSUE TITLE
Schedule: Buttons for days and "Show Starred" should have same size occupying 100% of width

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1146]
Days buttons and "Show Starred" are occupying one row, but they have different sizes. Expected: The buttons should have one size and possibly occupy 100% of the width.

![screenshot_2017-03-10-09-59-08](https://cloud.githubusercontent.com/assets/1583873/23779143/917a6be4-0579-11e7-9866-acdda3fc269d.png)

**Comment by dinesh-sirvi** [comment]
I'm on it...

**Comment by dinesh-sirvi** [comment]
Is this okay??
![screenshot_20170310-174723](https://cloud.githubusercontent.com/assets/10358362/23795203/47a45034-05ba-11e7-9e00-4e2443e6fac9.jpg)

**Comment by Princu7** [comment]
Looks Great. Please make a PR. Thanks

**Comment by Princu7** [comment]
Work done. Closing this
