### ISSUE TITLE
Add gitter room link as banner in the readme

### ISSUE THREAD

**Issue by sudheesh001** [fossasia/open-event-webapp#115]
Gitter room: https://gitter.im/fossasia/open-event-webapp

Add it as a banner. Here's a banner cheatsheet http://ricostacruz.com/cheatsheets/badges.html

Banner should look like
[![Gitter chat](https://badges.gitter.im/fossasia/open-event-webapp.png)](https://gitter.im/fossasia/open-event-webapp "Gitter chat")

**Comment by daminisatya** [comment]
@sudheesh001 I found the banner link in the read me section. 
![selection_014](https://cloud.githubusercontent.com/assets/6227784/13195277/64d4040c-d7d4-11e5-9a9f-c5a1ff31863c.png)

**Comment by sudheesh001** [comment]
False report sorry. Missed looking at it.
