### ISSUE TITLE
Adding a service worker for offline access of generated webapp

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-webapp#1152]
@mariobehling @championswimmer @aayusharora 
We should add a service worker to the generated webapp so as to-

* make the website function offline,
* increase online performance by reducing network requests for certain assets,
* provide a customized offline fallback experience.

**Comment by Princu7** [comment]
Yes. Good idea. There are plans for doing this in future. But First, we need to focus on removing all the small bugs present in the web app before adding any features or enhancement to it. :+1:

**Comment by geekyd** [comment]
@anu-007 This is a great idea.

**Comment by anu-007** [comment]
@Princu7 i will desing a service-worker which updates itself in background so that any changes that are done is cached by the new service-worker and When the currently open pages of the webapp are closed, the old service worker will be killed and the new service worker will take control.

**Comment by Princu7** [comment]
Seems great. Let's wait for other's inputs. There are already many existing issues and bugs in the web-app so it would be better if we could solve them first and then move on to the other areas since adding any feature right now would inevitably bring in more bugs. It would be great if you could help with them. Thanks!

**Comment by anu-007** [comment]
@Princu7 ok i will keep that in mind in future.Thanks!

**Comment by Princu7** [comment]
You can surely take this up in future when the web-app has stabilized more.

**Comment by aayusharora** [comment]
@anu-007 It would be good to know your plans about `make the website function offline`. What other functionalities we can introduce using service workers.

**Comment by sudheesh001** [comment]
> increase online performance by reducing network requests for certain assets

Storing the assets in the application instead of using a CDN for the assets ? Not sure if that's really a good idea, many servers hosted have bandwidth limit caps. that's why CDNs come in handy and improve speed.

If the intention is to make the webapp work offline, there should probably be a no asset approach to doing it.

**Comment by anu-007** [comment]
@aayusharora @sudheesh001 the idea is to precache all the static assets in users browser cache and for dynamic assets, we should use run-time caching along with background sync so as to keep our dynamic content updated.Service worker API does support caching for all CDN resources. We can also use cacheAPI which provides a storage mechanism for request/response object pair that is cached as a part of service worker lifecycle, which eliminates the storing of CDN assets in our app and ultimately bandwidth limit caps will no longer be a problem.
Thanks !!!

**Comment by anu-007** [comment]
@aayusharora making the web app to available offline is not enough, the goal is to make the web app to be **interactive** even offline for example users should be able to star a schedule, track or room when offline these activities can be stored in indexedDB  in JSON format and when the connectivity comes these are sync with the server and the user is notified with the help of a push notification when background sync is completed.
