### ISSUE TITLE
Integrating the web-app as a microservice in the open-event server

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1153]
We can easily create an event using the open event orga server. One of the major goals is to be able to integrate the web app with the server as a microservice. That is, the user can click on the generate web app button on the server after creating an event and then receive a notification that the website generation has started and he will get a notification regarding the event site soon.  When the event site is generated, we have to send a notification to the server that the event generation has completed which will appear in the messages section of the user's dashboard.

You can read more about it here:
https://github.com/fossasia/labs.fossasia.org/issues/184

This issue is meant to be done at a later stage. The main focus is on solving the currently existing bugs present in the web app.

**Comment by sudheesh001** [comment]
Do you mean that this has to be dyanmic website generation for each event ? What exactly does a microservice do here ? Why the microservice approach ?

**Comment by aayusharora** [comment]
@sudheesh001 Thanks, this project aims to act as a plugin for open-event orga-server. 
` Do you mean that this has to be dynamic website generation for each event`
The webapp generates static pages once it gets data from the API or zip.
`Why the microservice approach?`
We want this to be loosely coupled inside orga-server, hence microservice seems best.
Thanks.

**Comment by Princu7** [comment]
@sudheesh101
@aayusharora Explained it really well. The term microservice is used loosely here. The common definition of microservices generally relies upon each microservice providing an API endpoint, often but not always a stateless REST API which can be accessed over HTTP(S) just like a standard web page. Here, it acts more of a type of plugin into the eventyay(orga) server providing an API endpoint to help generate the static event websites directly by clicking on a button.

We already have two methods implemented in the web-app for the generation: JSON zip file and API endpoint of an event. The web-app will act as a microservice(plugin) which will provide an API endpoint(http://opev-webgen-dev.herokuapp.com/generate) which will leverage the existing method of the generation of event websites through the API endpoint of an event along with a few additional components(authentication and notification).

**Comment by sudheesh001** [comment]
I think as of now this is no where close to a microservice and cannot even be called that way loosely. What you're proposing is a web service with an HTTPS api endpoint. The reason for not using microservices over http is the transport overhead. it's better to let the individual stateless services communicate among themselves internally than make a public HTTP call.

This calls for 2 approaches
- Actually make this a microservice approach. If so, then what's the container deployment strategy ?
- Just leave it as an all in one web service API endpoint providing the API for openevent server to use.

Your proposal seems to be falling more on part 2 and I would love to see if those changes are made to that :smile: . Sorry if the review seems harsh, it isn't meant to be.

**Comment by Princu7** [comment]
@sudheesh001 No problem. Thanks for the review :) You are right. I should have been more rigorous with the wording of the process. Sorry :sweat_smile:  I think we should leave it as a web service which provides an API endpoint for the orga server to use and generate an event website.

I will correct the terminology used in my proposal. Also, regarding securing the API end-point, this process should work:

* Orga Server and Web-app server share a private key.

* Upon receiving a generation request from the client, the orga server will create a unique HMAC(hash) representing it’s request to the web-app server. It does this by combining the request data (email address, API endpoint of the event, event name) and hashing the blob of request data along with the private key.

* The orga-server then sends that HASH to the server, along with all the arguments and values it was going to send anyway.

* The web-app server gets the request and re­generates it’s own unique HMAC (hash) based on the submitted values using the same methods the client used.

* The web-app server then compares the two HMACs, if they are equal, then the server trusts and runs the request.

Please guide about any more changes that I should do? Thanks!!

**Comment by Princu7** [comment]
@aayusharora @sudheesh001  I have updated the proposal. Please review it. Thanks

**Comment by geekyd** [comment]
@niranjan94 We need your guidance regarding this issue. Please guide us with the best practices to be followed for the integration of the server and generator. Thanks.

**Comment by niranjan94** [comment]
@Princu7 @geekyd @aayusharora 

We could go for an approach similar to the one that has been implemented recently in the open event android app generator project. 

What I have done there is,
- The android app generator runs on it's own standalone isolated deployment (container) on google cloud container engine.
- It exposes a HTTP API at https://droidgen.eventyay.com 
- The organizer server or anyone else can make API calls there to start the generation process. 

We'll probably need a similar approach here too. See https://github.com/fossasia/open-event-android/tree/development/apk-generator/v2 (the generator + job queue server) and https://github.com/fossasia/open-event-android/tree/development/kubernetes (the kubernetes deployment configuration)

But then, here we have some issues that haven't been fixed there yet.

App generation is a long process. We cannot keep the HTTP connection open for so long and nor can continuously poll the API on the generator server for status. Instead we have two options
- Open a websocket connection and get live status updates. 
- Or, when making the API call to start the generation, pass along a callback endpoint. The generator will make a request to the callback url once the generation is done along with the URL to download the app or an error message if generation failed. (easier and straightforward)

^ This is something that needs to be discussed about.

**Comment by Princu7** [comment]
@niranjan94 Thanks for the guidance. Really appreciate it. Web-app is currently deployed on Heroku and its REST API is exposed on http://open-webgen-dev.herokuapp.com/api. It accepts POST request containing the details of the event.

What I originally thought to do is that we send a POST request to the generator and send an acknowledgment response back to the server. That way, the client would not be stuck forever wating for the response. Then we carry on the job for generating the event website. When the event generation is complete, we can send a response(success or failure) back to the notifications API(maybe) which could show on the user's dashboard and tell him the details about the process. Also, if the process was successfull, the server would automatically send a mail to the user contaning the link of the app for download. Opening a websocket connection seems not much fruitfull.

**Comment by niranjan94** [comment]
> What I originally thought to do is that we send a POST request to the generator and immediately send an acknowledgment response back to the client. That way, the client would not be stuck forever wating for the response. 

Exactly. That's what I suggested in the second point about the callback URL ... 

1. The orga-server will make a call to app generator with event data and a unique callback url. 
2. The app gen will return a json response for that API call denoting the process has started 
3. Once generation is done, the app gen will make a call to the provided callback url in step 1 with the generated app's download link as the payload.
4. now the orga-server can do anything it wants when it receives the data. (it can show a notification, send email etc etc) and the app gen need not care about what the server does with the info.

**Comment by geekyd** [comment]
@niranjan94 Thanks for guiding.
I considered the websocket approach as it is easier to implement but it is not as flexible. We will be Implementing the REST API on the generator which will be exposed on the specified URL, where the server will trigger the generation. The generator will generate the web-app and send a notification with the links and push a mail to the organiser. This approach seems feasible as well as flexible as not only server but other applications like susi can trigger the REST API of the app generator.

**Comment by Princu7** [comment]
@niranjan94 @geekyd Ok. Will work on the REST API then. I commented earlier about the authentication stuff to prevent mis-use of the generator API. Here it is. Please review and suggest improvements. 

* Orga Server and Web-app server share a private key.

* Upon receiving a generation request from the client, the orga server will create a unique HMAC(hash) representing it’s request to the web-app server. It does this by combining the request data (email address, API endpoint of the event, event name) and hashing the blob of request data along with the private key.

* The orga-server then sends that HASH to the server, along with all the arguments and values it was going to send anyway.

* The web-app server gets the request and re­generates it’s own unique HMAC (hash) based on the submitted values using the same methods the client used.

* The web-app server then compares the two HMACs, if they are equal, then the server trusts and runs the request.

**Comment by niranjan94** [comment]
@Princu7 the authentication implementation is clean. But we'll have to figure out how're we're going to properly share the private key with the server and webapp generator across deployments.

I'd say, let's finish the API implementation first and get the flow working. Authentication can be dropped in once that is done

**Comment by Princu7** [comment]
@niranjan94 Ok. Nice. Thanks :smile_cat:

**Comment by geekyd** [comment]
Yeah. We should first get the integration working and then add the authentication once we have it working.
@niranjan94 Thank you for your guidance. 😄

**Comment by sumedh123** [comment]
@Princu7 @geekyd Authentication using HMAC( hash ) is really a good idea. Thanks @Princu7
