### ISSUE TITLE
Implementing push notifications facility to the generated web-sites

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1154]
This is a feature which could benefit a lot of the attendee/speakers. Currently, there is not much interaction between the event sites and the users. Users can bookmark the sessions but this is as far as it goes. As soon as the history is cleared, all the bookmarked sessions data is gone. There is no notification regarding the bookmarked sessions when they are about to happen.

Push notifications on the web is a new technology which enables us to send a push notification from the server to the client even when the actual site is closed. We don't need the event website open in order to receive the notification. This feature makes extensive use of service workers and FCM Server.

This comes under the improving the interaction aspects of the web-app. We can read more about it here
https://github.com/fossasia/labs.fossasia.org/issues/184

It is to be done at a later stage. More focus should be given on removing the existing bugs in the generator and the event web sites.

**Comment by sudheesh001** [comment]
What about other ways in which you can engage users ? Can you inform users about the sessions over facebook messenger ? Not everyone would be comfortable to use an app and enable push and so on. There might be many who would check the messenger app or such chat apps way more than opening up this app and checking. This issue probably needs to be expanded.

**Comment by aayusharora** [comment]
The android client provides notifications to users for their bookmarks session 10 minutes before their starting time.  Our goal is to keep the user engaged.
@sudheesh001 facebook messenger can be one of the features but we can't rely on it, I have seen people in the conference who don't use fb and messenger apps.
Also, I don't think the app should be open for seeing the notification, we only need to open the browser.
@Princu7 Can you propose the model for doing this ?

**Comment by geekyd** [comment]
@aayusharora We can create a service worker that will check if the events are about to start. If the event is about to start say 10 minutes to go. We will create a notification for the user, as a reminder of the event.
The notification will be for the bookmarked events.

Another approach we can take is to add reminders features by letting users add the event details to there calendars. Which will be handy for the speakers as well as the attendees.

**Comment by Princu7** [comment]
@aayusharora I have created a draft of my proposal . It contains all the technical details regarding service workers and notifications model. I have shared it on Google groups and to you on Gitter. Please review. Thanks

**Comment by Princu7** [comment]
Ok. Just saw that reviews were added. Will improve upon it. Thanks.

**Comment by Princu7** [comment]
@sudheesh001 Thanks for the comment. @aayusharora @geekyd Already explained it really well. 

The best part about push notifications is that they don't require the actual site to be open. The only requirement is the browser. If the browser is open, then we will directly receive the notifications from a website if we have authorized it to do so. On the android platform, the notifications feature is kind of native and from a long time. The recent addition of service workers has opened doors to notifications on the open web. The user can enable the push button for one time and then forget about it. 

The part about FB and other messaging apps is cool and can be implemented. Another idea is to do a google calendar integration.

**Comment by sudheesh001** [comment]
> The best part about push notifications is that they don't require the actual site to be open. The only requirement is the browser. If the browser is open, then we will directly receive the notifications from a website if we have authorized it to do so.

But this means I should open the app / website on my phone and works either as push notification to android phone in case of an app or a chrome web notification. When messengers already have all of these systems built in place, why not just use them ? Any messenger app on which this is integrated should be able to use the same push notifications and features. I don't see what's new being proposed here.

**Comment by Princu7** [comment]
@sudheesh001 Yes. What you said is correct. But we can't fully rely on the chat apps. I guess most of the people do use either the app or the event website or both during the conference for checking out the sessions and speaker details and timings and stuff multiple times during the day. So, instead of relying on other services for displaying notifications, why not introduce the functionality natively? The event android app already has this feature for a while and we wanted to catch up to that. We can add the integration with the messenger apps in conjunction with this feature, though. And again, Thanks for sparing your time to help me on this stuff :+1: I really appreciate it :relaxed:

**Comment by sudheesh001** [comment]
Many users face app fatigue because of the number of apps. Here's a document from [fortune](http://fortune.com/2016/08/16/app-fatigue-is-taking-a-toll-on-smartphone-owners/) to back up my claim. Though I don't deny that an app should be released for this, I think having it integrate with the top apps that already exist on the app is a better way of gaining users.

People would rethink if they'd have to download an app and install it and would definitely use it if it's provided with something they already have. Also the webpage/webapp accessible from a browser is what is definitely needed. I don't find faults in what you've mentioned or the reason why you want to stick to an app, I am simply proposing a better way to improve the app and the usage of the orga server.

**Comment by mariobehling** [comment]
I am closing this issue as it is out of scope at the moment.

**Comment by agbilotia1998** [comment]
@geekyd @mariobehling @aayusharora I am implementing this feature with google-calendar notifications with an extra feature of adding the event to the calendar.
