### ISSUE TITLE
Design broken on schedule page

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1155]
It seems like due to some recent commits, the design of the schedule broke down a little.
Screenshots:
Initial
![screenshot from 2017-03-11 12-07-23](https://cloud.githubusercontent.com/assets/8847265/23821283/730724e2-0653-11e7-8030-b6969855674a.png)
Faulty Look
![screenshot from 2017-03-11 12-07-10](https://cloud.githubusercontent.com/assets/8847265/23821285/7de06342-0653-11e7-8b31-af1f25075d15.png)
Correct look
![screenshot from 2017-03-11 12-07-31](https://cloud.githubusercontent.com/assets/8847265/23821287/8aba884a-0653-11e7-97f5-db7798c8776e.png)

**Comment by Princu7** [comment]
If anyone wants to take up this issue, please go ahead. Thanks!!

**Comment by sumedh123** [comment]
@Princu7  Does this happen for every item? coz on my browser, it's working fine.

**Comment by Princu7** [comment]
@sumedh123 Nah. This is the fault. It doesn't happen on every item. It happens on only some of them. Like the one shown in the example in the screenshots. For example, the creative booth sections session doesn't display correctly but the XL Tech session shows correctly.

**Comment by sumedh123** [comment]
@Princu7  There are too many items that it is difficult to find which one has fault. :-P

**Comment by aayusharora** [comment]
It's not breaking of design @Princu7, when you are having x items in a single row, and you click any of them, the content appears just below them.
