### ISSUE TITLE
Searching in starred mode shifts to searching in normal mode

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1156]
When we are in starred mode looking at the bookmarked sessions and search for a session, the search is performed on all the sessions even if they are not bookmarked.

**Ideal Behaviour** :
In starred mode, the search should be performed on only the starred sessions. Not on all the global sessions.

**Screenshots**:
Initial view
![screenshot from 2017-03-11 12-37-41](https://cloud.githubusercontent.com/assets/8847265/23821418/9ca13334-0657-11e7-87bd-d8958596b838.png)
Starred view
![screenshot from 2017-03-11 12-37-57](https://cloud.githubusercontent.com/assets/8847265/23821422/b1eb2e5c-0657-11e7-8940-874b62305c58.png)

**Comment by geekyd** [comment]
@Princu7 I will take care of this :)

**Comment by Princu7** [comment]
@geekyd Have you started working on this issue? If you a bit busy with some other bugs, I can take up this one :)

**Comment by geekyd** [comment]
@princu7 Sorry about the delay was busy with my midterms, I'm almost done with the fix, will be sending a PR soon. :)

**Comment by Princu7** [comment]
@geekyd Ok. Great. No problem :smile:
