### ISSUE TITLE
Smooth scrolling of website

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-webapp#1160]
Due to large content on the rooms, tracks, there is a bit laggy behaviour of scrolling leading to poor UX. I want to have everyone's inputs. :)

**Comment by geekyd** [comment]
@sumedh123 Okay. What is your suggestion ?

**Comment by Princu7** [comment]
I am a little confused regarding this. Could you guys please upload a video or a gif showing the problem, please? Thanks!!
