### ISSUE TITLE
Space between speaker images on speakers page

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-webapp#1161]
Currently on the speakers page, the images of the speakers are attached to each other leading to poor UI. Maybe some space would make them look good. Opinions @Princu7  @mariobehling  @aayusharora 
![speakers](https://cloud.githubusercontent.com/assets/17925669/23828440/8516dec6-06f7-11e7-92c0-593aa995b912.png)

**Comment by Princu7** [comment]
@sumedh123 The weird thing with UI is that the experience is different for every person :smile:. There have been many detailed discussion previously leading up to the current UI of the page. That being said, there is always scope of improvement!! It would be really great if you could show a demo or a prototype of the proposed UI which you would like to have on the page. We can pick up from that point. Thanks!!

**Comment by sumedh123** [comment]
Its just a little fix.
![fossasia](https://cloud.githubusercontent.com/assets/17925669/23829107/e52a1d6c-070d-11e7-9e6f-29e719ec8f27.png)

**Comment by Princu7** [comment]
@sumedh123 Nice. It looks better than the previous in my opinion. Let's wait for other's inputs. Thanks for showing a mockup.

**Comment by geekyd** [comment]
@sumedh123 This looks better. Thanks for pointing it out. :)

**Comment by sumedh123** [comment]
Shall I get it fixed? @geekyd

**Comment by geekyd** [comment]
@sumedh123 lets wait from inputs from others :)
