### ISSUE TITLE
Automatic deploy sometimes halts in between the upload

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1162]
It seems like images are not able to properly upload on Github currently when we are deploying FOSSASIA Summit on Github. This problem didn't exist before. Currently working on a fix.

![download 1](https://cloud.githubusercontent.com/assets/8847265/23831490/9fb1d168-0748-11e7-9dcf-28414ea0aa92.jpg)

**Comment by geekyd** [comment]
@Princu7 I was gonna open the issue, please also change the text "Press the button below to start" when the deploy is initiated to "Press the button below to abort".

**Comment by geekyd** [comment]
@Princu7 The problem occurs randomly, may be it is due to timeout. I tried the feature 3 times and did not get any error. I think increasing the time interval for requests will fix the issue.

What is your opinion on this?

**Comment by Princu7** [comment]
@geekyd Thanks for the confirmation. I was also testing it out on Heroku and found no error. Actually, the time interval between requests is quite elastic(1 second) and shouldn't cause any problem. Sometimes, the Heroku servers are down which means they can't properly download or upload file. In this case, when the uploading and committing of a file takes time on Github, it throws a `Socket Hang Up` error. I guess this is what was happening on Heroku at that time. The servers were not functioning properly and hence there were so many errors while uploading the image file.

I tested on my unstable internet connection and got a few errors of this type. You can see it in the screenshot below:

![screenshot from 2017-03-12 18-21-32](https://cloud.githubusercontent.com/assets/8847265/23832039/31aefdfc-0753-11e7-989a-fd8bc0169c3f.png)

**Comment by geekyd** [comment]
@Princu7 That's awesome the issue is solved automatically 😄 . There is one problem that still exist in the deploy functionality, the progress bar stops when an error occurs but the log says the app is successfully deployed. Can you look in to it?

**Comment by Princu7** [comment]
@geekyd Thanks for reminding for changing the text  _Prese below button to start to Press below button to abort_ when the build is initiated. I will send a pull request regarding this soon. And could you please clarify more regarding the error point. Do you mean the errors apart from the event files upload and commit? Like failure while creating of the repository in the user's github account?

**Comment by geekyd** [comment]
@Princu7 It seems the errors apart from upload errors halt the progress bar, it should get reset if such case occurs. While using deploy, the progress bar halted at 89% but the logs were updating. It logged a success message but it failed.

**Comment by Princu7** [comment]
@geekyd Thanks for the details. I would surely look into it :)

**Comment by Princu7** [comment]
@geekyd I am having a little trouble reproducing the error. Could you please mention any one specific instance when the problem related to the halting of the progress bar occurs? Would be great if we could properly catch the bug and remove it. Thanks!!

**Comment by geekyd** [comment]
@Princu7 I tried to reproduce the error and found that the deploy sometimes halts without any notification please check the screen shot.
![screen shot 2017-03-14 at 12 54 12 am](https://cloud.githubusercontent.com/assets/12807846/23906019/ce47e4ee-08f2-11e7-9b27-46ae82673bab.png)

**Comment by Princu7** [comment]
This issue was partially solved. Hence re-opening this :)

**Comment by Princu7** [comment]
@geekyd If the deploy halts sometimes during the upload of a file, I think it might be happening because of some Heroku server problem. It might be the case that the Heroku server might be not working properly and hence the file is not getting uploaded and committed. In that case, timeout should occur after some time and a failed message should be displayed. How long did it got stuck at that point? 

It's really difficult to fully get the issue which is causing the error :smile:. What do you suggest?
