### ISSUE TITLE
alignment and position of color-coded bullets on tracks,rooms and schedule pages

### ISSUE THREAD

**Issue by anu-007** [fossasia/open-event-webapp#1166]
the color coded divs should present above the div's of tracks,rooms and schedule pages and are aligned  with these div's will be more informative instead of present at the end.

proposed UI-
![alt text](https://github.com/anu-007/assets/blob/master/Screenshot%20from%202017-03-13%2014-33-51.png?raw=true "proposed UI")

**Comment by sumedh123** [comment]
@anu-007  You are proposing this UI for any small screens or all?

**Comment by anu-007** [comment]
@sumedh123 this UI is for small screens where there color coded bullets move at the bottom of the page.

**Comment by mariobehling** [comment]
This feature does not improve the functionality so much and we could discuss what is best for hours and days. We need data and we only get data when we have users. Priority is to fix the remaining bugs and integrate the app as a microservice with the Open Event Server.

One we have lots of users we can do A/B testing.

The UI you are showing here is also not the one that works on mobile small screens.

Let's not over-engineer and rather focus on getting issues solved that prevent user from using this app. Closing it therefore. Cheers.
