### ISSUE TITLE
Unsorted sessions in speakers popbox

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1169]
**Speakers page**
The sessions in the popbox are not sorted according to the start time.

eg. For speaker Alessandro Volpato 
![screen shot 2017-03-13 at 6 01 34 pm](https://cloud.githubusercontent.com/assets/12807846/23854419/5a6b497a-0817-11e7-970b-7fd69554b464.png)

**Expected behaviour**
The sessions in the popbox are sorted by the start time of the session.

**Comment by sumedh123** [comment]
@geekyd  I will work on this. Rather than using helpers in handlebars, it is beneficial to sort the data in backend and the iterate as in handlebars. Can you tell me where can I get the backend files?

**Comment by Princu7** [comment]
@sumedh123 Look in the `generator.js` file :)

**Comment by geekyd** [comment]
@sumedh123 You need to look in `fold.js` and `generator.js` :)

**Comment by dinesh-sirvi** [comment]
Can I take this issue..?

**Comment by sumedh123** [comment]
@geekyd  @Princu7  Can you tell me what the foldByTrack, foldByDate, foldBySpeakers, foldByTime functions do? and how the fold.js and generator.js are linked? I am finding it quite unclear to understand.

**Comment by Princu7** [comment]
@dinesh-sirvi @sumedh123 is already working on this issue. Please take up other open issues. 

An event consists of many sessions which have a theme(tracks) and the place where they take place(rooms). So all these functions `foldByTrack` or `foldByDate` do what their name suggests. They organize the sessions according to tracks and date respectively. For eg- `foldByTrack` makes a list of all the different tracks(Like Machine Learning, Artifical Intelligence) and then pushes the sessions into their relevant tracks. `foldByDate` organizes the sessions according to their dates. Please look at the event JSON files to get a more clear idea of the sessions and their properties.

**Comment by Princu7** [comment]
@sumedh123 Look for the function `getAllSessions` in `fold.js` file. It returns the list of sessions associated with a speaker. This variable is titled `speakersession`. You just need to sort this list with the start time of the session as a key. It should do the required job I guess.

**Comment by sumedh123** [comment]
Thanks @princu7. I ll take a look.

**Comment by sumedh123** [comment]
@Princu7  I tried sorting speakersession. I don't know why but its not working.

**Comment by geekyd** [comment]
@sumedh123 Can you share what changes have you made?

**Comment by geekyd** [comment]
@sumedh123 Please add a sortKey property to the `speakersession` the value of this should be YY-MM-DD HH:MM and sort the `speakersession` before the return by this sort key. It should solve the issue. :)

**Comment by sumedh123** [comment]
I am using the sort function in js
![fossasia](https://cloud.githubusercontent.com/assets/17925669/24152396/80951288-0e71-11e7-99a2-ae0e643d2eda.png)

**Comment by geekyd** [comment]
@sumedh123 Please use this instead `speakersession.sort(byProperty('sortKey'))` , sortKey will be same as described in the previous comment.

**Comment by sumedh123** [comment]
I tried that also but still it's not working. @geekyd

**Comment by geekyd** [comment]
Okay let me check.

**Comment by geekyd** [comment]
@sumedh123 It seems to work please use 
`sortKey: moment.utc(session.detail.start_time).local().format('YYYY-MM-DD HH:MM')`
& `speakersession.sort(byProperty('sortKey'))`

I was able to get the required results 

**Before**
![screen shot 2017-03-21 at 9 52 38 pm](https://cloud.githubusercontent.com/assets/12807846/24158157/8dd180fc-0e81-11e7-9589-a7420c9d4fac.png)

**After**
![screen shot 2017-03-21 at 9 54 24 pm](https://cloud.githubusercontent.com/assets/12807846/24158158/8dd6b5c2-0e81-11e7-95a7-1449d2da341b.png)

**Comment by sumedh123** [comment]
@geekyd Got it. I was making a typo. fixed it now. Thanks.
