### ISSUE TITLE
Add a Home Button to the Deployment Page

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1173]
On the Github deployment page, after the user has deployed the event site on his gh-pages, there is no button available on the page to go back to the generation page. The user has to manually type the  address or press the back button to go the home page of the app.

**Expected**
The deployment page should have a home button which takes the user back to the generation page.

**Comment by sumedh123** [comment]
@Princu7  A button at bottom of the page?

**Comment by Princu7** [comment]
@sumedh123 Yeah. Just add it wherever you think it would appear good with regards to the aesthetics of the page :)

**Comment by sumedh123** [comment]
Okay @princu7
