### ISSUE TITLE
Correct a small mistake in Documentation

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1177]
There is a small mistake in the documentation of the project. One of the headings has gone wrong. Please correct it.

![fossasia-open-event-webapp- open event web app generator http---opev-webgen-dev herokuapp com](https://cloud.githubusercontent.com/assets/8847265/24002214/2957617c-0a86-11e7-97fe-530f0ddbe6f7.jpg)

**Comment by AnshulMalik** [comment]
I'll do it :)
