### ISSUE TITLE
Left Navigation Bar not proper.

### ISSUE THREAD

**Issue by AmayAgrawal** [fossasia/open-event-webapp#118]
![screenshot from 2016-02-24 17 57 57](https://cloud.githubusercontent.com/assets/12967238/13285408/74a07312-db20-11e5-95e8-e529449f9ac1.png)

As seen in the above screenshot I am at present in the sessions section.Now in the second  image I swap to the track section.

![screenshot from 2016-02-24 17 58 56](https://cloud.githubusercontent.com/assets/12967238/13285812/de6144a0-db22-11e5-805a-1d417a50d31d.png)

As we can see that in the left navigation bar We can see that the focus is still on the sessions as well as tracks section

**Comment by SilentFlame** [comment]
@AmayAgrawal can you please tell me how to run the app locally, as I have made changes as per to resolve this issue but unable to test if I'm right or not.
Please help.

**Comment by aayusharora** [comment]
@SilentFlame, after cloning the repository, go to open-event-webapp and run command gulp ,if you don't have dependencies installed ,you have to first take them through gulp.

**Comment by SilentFlame** [comment]
@aayusharora facing problem in setting gulp.
on 
`$> npm install gulp-install` I got 
```
open-event-webapp@0.0.2 /home/speedy/GITHUB/Fossasia/open-event-webapp
└── gulp-install@0.6.0  extraneous

npm WARN open-event-webapp@0.0.2 No license field.
```
and on 
`$> gulp` I got 
```
No command 'gulp' found, did you mean:
 Command 'gslp' from package 'ghostscript' (main)
gulp: command not found
```

Unable to understand.

**Comment by championswimmer** [comment]
sudo npm install -g gulp

That way you can use gulp as a command

**Comment by SilentFlame** [comment]
@championswimmer thanks as gulp now is set.
but got this output on running that.
```
$> gulp

[19:04:13] Using gulpfile ~/GITHUB/Fossasia/open-event-webapp/gulpfile.js
[19:04:13] Starting 'webserver'...
[19:04:14] Finished 'webserver' after 186 ms
[19:04:14] Starting 'styles'...
[19:04:14] Finished 'styles' after 2.54 ms
[19:04:14] Starting 'default'...
[19:04:14] Finished 'default' after 5.12 μs
[19:04:14] Server started http://localhost:8080
[19:04:14] LiveReload started on port 35729
Error in plugin 'sass'
Message:
    assets/scss/main.scss
Error: Undefined variable: "$conf".
        on line 38 of stdin
>> 	font-family: map-get($conf, font-family),
   ----------------------^

[19:04:14] gulp-inject 64 files into index.html.
```
and terminal stopped at a halt.
and on ` http://localhost:8080` its `unable to connect`.
can you please have a look.

**Comment by championswimmer** [comment]
Reinstall sass on your system.

Issue with your node plugins

**Comment by aayusharora** [comment]
@championswimmer ,@SilentFlame ,there is no issue with the plugins ,I got the same one at first time ,marked it here Error in Terminal ,figure out one basic sass error in gulp #121.

**Comment by aayusharora** [comment]
It will be solved after merging of PR #122, @SilentFlame ,you can continue ,it will not hamper.

**Comment by SilentFlame** [comment]
@aayusharora yes I saw that, but is it resolved as in the PR i saw some comments not conforming that.
@championswimmer  still the problem pertains, after reinstalling the `sass` via npm.

please provide suggestions.

**Comment by ashutoshsaboo** [comment]
@SilentFlame You can try executing `sudo npm install` in the directory of the cloned repo of `open-event-webapp`. Also, did you attach `sudo` to all commands while installing gulp and other modules? Try doing with `sudo` once maybe.

**Comment by aayusharora** [comment]
@SilentFlame ,the comments there are not remove one file main.css which gets generated automatically on starting gulp.Otherwise ,the pull-request and issue looks perfect to me.
@championswimmer suggestions please.
PR to consider: #122

**Comment by SilentFlame** [comment]
I guess the nav bar is on **right**.  :smiley: 
or can say depends upon which view you consider.  :wink:

**Comment by SilentFlame** [comment]
@AmayAgrawal  please review the PR #131  so as to check as have I done all what is needed to resolve this issue.

**Comment by ashutoshsaboo** [comment]
@SaptakS @joerx @daminisatya @mariobehling @jig08 @AmayAgrawal @championswimmer I have pushed a PR - https://github.com/fossasia/open-event-webapp/pull/135 which resolves this issue. Could someone review the PR, please! Thanks! :smiley:
