### ISSUE TITLE
Google map not getting loaded in the homepage

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1182]
**Actual Behaviour**
The google map is not loading properly

**Expected Behaviour**
The maps should show the location of the event.

**Screenshots of the issue**
![screen shot 2017-03-17 at 12 52 14 am](https://cloud.githubusercontent.com/assets/12807846/24014743/11f047a8-0aac-11e7-9158-6964d0aa3c9e.png)

I'm working on the fix.

**Comment by Princu7** [comment]
@geekyd Try reloading the page. It should work after that :)

**Comment by Princu7** [comment]
@geekyd Try reloading the page. It should work after that :)
![screenshot from 2017-03-17 00-56-48](https://cloud.githubusercontent.com/assets/8847265/24014910/ad28fe5e-0aac-11e7-8849-6b59238364ed.png)
I reloaded the page and it did work.

**Comment by geekyd** [comment]
@Princu7 Thanks, I had to reload it thrice to get it working. Closing the issue.

**Comment by Princu7** [comment]
@geekyd No problem at all. I have faced this problem before. We should actually investigate why does this behaviour happens. Any ideas?

**Comment by geekyd** [comment]
I'm working on gulp minification, I have made a window.initMap function it fixed the issue on my local machine, will deploy it on test server as soon as its done. Lets see if it help. What do you suggest ?

**Comment by Princu7** [comment]
Sounds good. Let's wait how it runs on the test server. Thanks :)
