### ISSUE TITLE
Clicking on speaker sessions, do not lead to the respective session

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1185]
**Actual Behaviour**

- go to speakers page
- click on speaker photo
- click on the associated speaker session

**Expected Behaviour**

it should lead to the tracks page showing the sessions detail.

**Comment by geekyd** [comment]
@aayusharora Currently it leads to the respective session in tracks page.

**Comment by aayusharora** [comment]
Can you please check the mobile version

**Comment by sumedh123** [comment]
@aayusharora  In mobile it does not navigate anywhere.

**Comment by geekyd** [comment]
@sumedh123 Are you working on this?

**Comment by sumedh123** [comment]
@geekyd  I am taking a look. Still if you want, you can go ahead :+1:

**Comment by geekyd** [comment]
@sumedh123 Almost done with the fix. Thanks.
