### ISSUE TITLE
Bookmarked sessions not synchronized on all pages

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1192]
**Actual Behaviour**

Currently, the bookmarked sessions are local to one page only. For example - a bookmarked sessions on the tracks page is not bookmarked on the schedule page.

**Expected Behaviour**

Since the sessions are same, it only makes sense that the effect of bookmarking a session on a particular page should affect the other pages also. They should work in a global scope with respect to the event rather than being localized to a single page. 

**Screenshots of the issue**
The bookmarked sessions are different on different pages.
`Schedule page`
![screenshot from 2017-03-20 08-54-20](https://cloud.githubusercontent.com/assets/8847265/24087953/ec3df70c-0d4a-11e7-8465-d513d64e629d.png)
`Tracks page`
![screenshot from 2017-03-20 08-54-36](https://cloud.githubusercontent.com/assets/8847265/24087957/f76f691c-0d4a-11e7-804b-6eea2c2445d2.png)

**Would you like to work on the issue?**

Yes.

**Comment by geekyd** [comment]
@Princu7 Great find. go ahead. :)
