### ISSUE TITLE
Add information about gulpfile to the documentation

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1193]
Recently, gulp was added to the project for concatenation and minification of js and CSS files. It has significantly reduced the no of requests for the static assets and increased the speed of loading of the pages. The google insights score has also been increased.

The task is to add information about gulpfile.js to the documentation of the project. This will help to make the documentation more complete and help the contributors.

**Comment by geekyd** [comment]
@Princu7 I will be making the changes to the documentation :)
