### ISSUE TITLE
No info message shown while deploying the event site on Github

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1194]
**Actual Behaviour**
Due to some recent changes, it seems some problem has crept on the deployment page. When a user deploys the event site on Github, there are no info or error messages displayed on the page. Only the progress bar is shown.

**Expected Behaviour**
The info message about the files uploaded and committed should be shown below the progress bar. Same with the error message. Also, show the link of the GH-pages after the event site generation has completed.

**Steps to reproduce it**
Generate an event site and click on the deploy button.

**Screenshot**
`Current`
![screenshot from 2017-03-20 21-06-18](https://cloud.githubusercontent.com/assets/8847265/24107579/23489408-0db1-11e7-887a-db35619ad96a.png)
`Previous`
![screen shot 2017-03-14 at 12 54 12 am](https://cloud.githubusercontent.com/assets/12807846/23906019/ce47e4ee-08f2-11e7-9b27-46ae82673bab.png).

**Comment by sumedh123** [comment]
@Princu7  I guess there's a problem in sockets.

**Comment by Princu7** [comment]
@sumedh123 Might be. I reverted the recent additions that were made to the deployment page locally and deployed the site again. The info and the error messages were displaying correctly. Could you please see why this problem appeared after making changes in the deploy.html file? The change was simply related to adding a button on page. Thanks!!

**Comment by sumedh123** [comment]
@Princu7 Looking towards the developer tools, the info and error messages are seen there....they are just not appearing on the webpage. And yes before adding the home button, I was not able to see the info and all stuff.

**Comment by sumedh123** [comment]
@Princu7 Still I ll take a look and report asap.

**Comment by Princu7** [comment]
@sumedh123 Thank you so much :) Since the info and error messages are showing on the browser console, then we can safely conclude that the problem is not related to the sockets. We are receiving the socket events related to the errors and the progress which are then being printed to the console. They are just not appearing on the webpage. We just have to figure out why that is happening.
