### ISSUE TITLE
UI of session div becomes bad in case of many speakers

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1196]
**Actual Behaviour**
The user interface breaks down a little when there are many(4 or more) speakers presenting a single session.

**Expected Behaviour**
The user interface of multiple speakers sessions should remain consistent and similar to other sessions

**Screenshots of the issue**

Bad UI on the summit page
![screenshot from 2017-03-20 21-59-47](https://cloud.githubusercontent.com/assets/8847265/24112048/52d82bfe-0dbe-11e7-8cd8-1f57765abb4e.png)

Comparing it with the eventyay tracks page
![screenshot from 2017-03-20 22-45-38](https://cloud.githubusercontent.com/assets/8847265/24112344/3f82601e-0dbf-11e7-86a1-5aa67126de16.png)

**Comment by oanarosca** [comment]
May I work on this? :smile:

**Comment by geekyd** [comment]
@oanarosca Please go ahead :)

**Comment by oanarosca** [comment]
What do you think would be the best thing to do in this situation? Increase the width of the Track card, increase the percentage occupied by the speakers' pictures (in the attached image, the pics and the names both occupy 50%) or maybe some other approach?
![screenshot from 2017-03-24 23-52-25](https://cloud.githubusercontent.com/assets/3405816/24314962/0892f7ea-10ed-11e7-82cb-1a4dc4bdb289.png)

**Comment by Princu7** [comment]
@oanarosca Thanks. The screenshot looks good. This approach, giving the speakers photo section a maximum width of 50% and a minimum width of 50% to the speaker description should work fine in most of the cases. Actually, this is what has been implemented on the eventyay page itself. Do you have any other better alternatives in mind? If yes, then splurge :)

**Comment by oanarosca** [comment]
Moved the categories to the top in order to expand the Track cards width:
![screenshot from 2017-03-25 13-26-31](https://cloud.githubusercontent.com/assets/3405816/24321835/b1168c1c-115e-11e7-84c1-267bae6e1a61.png)

**Comment by Princu7** [comment]
Thanks. That's a good solution. Actually, there already have been discussions regarding moving the tracks information bar to the top of the page. But, it was eventually decided to not work upon and continue with the existing implementation. If we only expand the width, the div will accommodate more speakers and their description but the same issue will occur if we increase the number of speakers again. I think it will be better if we just implement the above-discussed way of giving 50% width of track div to speakers photo and description.

**Comment by aayusharora** [comment]
@onarosca @princu7 Changing width or geometry by JS always result in FSL i.e forced synchronous layout. Please avoid this.
