### ISSUE TITLE
Center Images on mobile

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1204]
Page : Home 
![designbug](https://cloud.githubusercontent.com/assets/12194719/24320029/5c528200-1152-11e7-8b3f-f92b8010bec4.png)

**Comment by sumedh123** [comment]
@aayusharora  In my case it is displaying correctly : 
![fossasiaindex](https://cloud.githubusercontent.com/assets/17925669/24320274/1e0a0864-1158-11e7-915c-23e04c3807c1.png)

**Comment by sumedh123** [comment]
@aayusharora In my case it is displaying correctly. Can you check once again ? 
![fossasia](https://cloud.githubusercontent.com/assets/17925669/24320425/0e5e017e-115b-11e7-9746-10eab1060ce1.png)

**Comment by aayusharora** [comment]
Not sure, @sumedh123 I am using chrome canary. @geekyd @Princu7 can verify on browsers and we can close this then.

**Comment by geekyd** [comment]
Seems to work on chrome(canary as well) and safari

**Safari**

![aa101c06-2688-442a-9c36-8e156c53d0e1](https://cloud.githubusercontent.com/assets/12807846/24320659/93749e64-115f-11e7-8b95-38ed2138fd1a.jpeg)

**Canary**

![894b44fd-0a1d-4643-85a5-9dd947d25fc7](https://cloud.githubusercontent.com/assets/12807846/24320676/e755e074-115f-11e7-83e9-2fdd596199d3.jpeg)

**Comment by Princu7** [comment]
Yeah. Seems to work on mine too.

**Comment by sumedh123** [comment]
@aayusharora @Princu7 @geekyd Might be something bad with canary. That's what canary is for. Testing :)

**Comment by sumedh123** [comment]
@Princu7 @geekyd @aayusharora See what I got here when I varied the screen size in developer tools : 
![hello](https://cloud.githubusercontent.com/assets/17925669/24329879/750a02d0-1230-11e7-9482-ed9b50601622.png)

**Comment by sumedh123** [comment]
I don't know why but the above problem happens sometimes only.

**Comment by sumedh123** [comment]
The above problem happens sometimes only.

**Comment by agbilotia1998** [comment]
@Princu7 @aayusharora @sumedh123 @geekyd can I work on this issue?

**Comment by Princu7** [comment]
@agbilotia1998 Sure. Go Ahead :+1:  Thanks!
