### ISSUE TITLE
Apply Grid Layout option for schedule, track and rooms 

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1205]
- The user should be able to view schedule, tracks and rooms in forms of horizontal table.
- Give a select box to choose layout option.
Sample :
![56](https://cloud.githubusercontent.com/assets/12194719/24320109/8866610c-1154-11e7-98f8-75e2dc8635d6.png)

**Comment by Princu7** [comment]
@aayusharora This issue is almost similar to an already existing issue #1048. Please check. Thanks!!

**Comment by aayusharora** [comment]
Sure Closing via #1048
