### ISSUE TITLE
Removing Redundancy from Track Page

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1206]
![67](https://cloud.githubusercontent.com/assets/12194719/24320130/fa914f4e-1154-11e7-8e93-9cc7a1f89270.png)

- The dates are REDUNDANT written two times, once in the pills and then in the track filter bar.
- Remove the pills bar and filter content on the basis of track bar only.

Process 
-   Input: User clicks on 17 Jan on tracks bar.
-   Output: Tracks appear for the given dates and the page content is filtered according to date.

**Comment by geekyd** [comment]
@aayusharora We should toggle between the specific tracks container for the date when the user click the date button. By default all the dates are shown. if user clicks a specific date, only tracks of that date is shown. What is your opinion?

**Comment by aayusharora** [comment]
Yes, in that way we can get rid of the above date-pills bar which is confusing to users. @geekyd

**Comment by Princu7** [comment]
@aayusharora There is already an issue regarding this #1176. Please check. Thanks!!

**Comment by mariobehling** [comment]
I am unclear if this is a real issue.

Both navigation bars serve a different purpose and provide different actions.

1. The upper bar provides a direct link and it works in the same way on schedule, tracks and rooms page.
2. The bar below only exists on tracks and rooms page. 

Now as I can see the proposed solution is to change the way the upper bar works on tracks and rooms page. We will have the same buttons on schedule and tracks/rooms page, but they work in different ways: On the schedule page link to the date section, on the tracks/rooms page expand to show more information.

We need to think this through more and maybe change the whole design of this on all pages. As a design principle, please follow this: The same button needs to perform the same action on all pages.

**Comment by geekyd** [comment]
@mariobehling @aayusharora If we are to abide by the proposed design principle, then we can 

- Remove the date pills from rooms and tracks page and use the navbar for the dates and direct links to tracks and pages. We will be using the date pills on the schedule page though. 
                                                              **OR**
- We can stick to the current UX for simplicity.

Would love to hear your opinions. Thanks. :)

**Comment by mariobehling** [comment]
@geekyd I am unclear what is the right direction. I propose to take a general look at other sites and check out options. Some users asked to separate the session sections to become separate pages. We could also add options to the overview page. So the user can choose. Until we are clear what options there are it is hard to take a decision on details. As a goal for this summer I also see to develop this app into a progressive web app with offline capabilities. What is necessary to achieve this?

Please follow up on this here https://github.com/fossasia/open-event-webapp/issues/1228

**Comment by geekyd** [comment]
Closing this. It was solved with #1262
