### ISSUE TITLE
Compare Performance of Jimp and Sharp Library

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1209]
**Compare performance of `Jimp` and `Sharp`**

This was originally proposed by @aayusharora. Currently, we are using `sharp` module for resizing and converting the images. The problem with `sharp` are

* It is not entirely native and depends on few C++ libraries to work correctly
* Does not work correctly on Windows
* Less Developer Support

`Jimp` is a library completely written in Javascript and doesn't need any other dependencies for its execution. So, it should work well on Windows. But, it might be a bit slow when compared to sharp. The goal is to compare the results of `sharp` and `jimp` and if the results don't differ substantially, then switch over to `jimp`

I am working on this issue :)

**Comment by geekyd** [comment]
@Princu7 This is a great proposal, we can also check the performance of `gulp-imagemin`. I think it can help in lowering the size of the images.

**Comment by Princu7** [comment]
@geekyd Thanks for the recommendation. I will try to check it out.

**Comment by Princu7** [comment]
So I tried to compare the performance of the two libraries `Sharp` and `Jimp` with regards to image conversion and compression. I used both the libs on the `FOSSASIA Summit` original `png` images data set. From what I have inferred, `Sharp` seems to blow away `Jimp` by a very large margin. It takes quite low time to convert and resize all the images while Jimp takes a considerable amount of time in processing the images. The difference in time is like night and day.

**Comment by Princu7** [comment]
I made a video to help show the comparison between the `Sharp` and `Jimp` library.

https://www.useloom.com/share/b7c4740593784f7aaacf9f809240b541

 As we can see from the video itself, `Sharp` takes quite less time to convert all the images of speakers and sponsors. `Jimp` takes a very large amount of time as well as processing power to convert the same set of images on the system.

Regarding the `gulp-imagemin`, it seems to be an image minification library and doesn't seem to offer conversion between different image formats and resizing options.

**Comment by aayusharora** [comment]
Nice, comparison. This is probably due to the runtime of JS, we are not going forward with jimp than @Princu7
