### ISSUE TITLE
Error in Terminal ,figure out one basic sass error in gulp

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#121]
![1](https://cloud.githubusercontent.com/assets/12194719/13361947/c1c7276c-dce7-11e5-9ff8-3c16e7f25a36.png)

**Comment by aayusharora** [comment]
solved here #122

**Comment by SilentFlame** [comment]
needs to be closed now as now no such error is happening atleast for me.
![shot](https://cloud.githubusercontent.com/assets/9693795/13838683/f4d0e5fe-ec3b-11e5-8679-48dc1953dc78.png)

@aayusharora you can close this issue.
