### ISSUE TITLE
Moving towards Progressive Webapp ( Performance Report: Lighthouse )

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1211]
- We have done some great work on performance optimizations and UI on all platforms. Congo to all: +1: 
- We need to provide the user, the feeling of a natural app on mobile.
[PWA ](https://developers.google.com/web/progressive-web-apps/)

- We need to follow some checkpoints for Progressive Web app, here is the report of the Webapp performance. Reference [lighthouse](https://github.com/GoogleChrome/lighthouse)

[openeventwebapp.pdf](https://github.com/fossasia/open-event-webapp/files/890457/openeventwebapp.pdf)

- We need to work together according to the performance report and generate the report after each change that relates to this issue.

@mariobehling @championswimmer 
I will love to hear the views from the team.

**Comment by geekyd** [comment]
Great idea @aayusharora. Moving towards PWA will be very good for the application and the user experience. A lot of work to be done on this. Its exciting. Can not wait to get started. :)

**Comment by Princu7** [comment]
@aayusharora Thanks for being a fantastic mentor and guide. Congo to all for the fantastic work. Thanks for generating the report. We will follow the guidelines and generate the report when implementing the features related to the service workers.

**Comment by sumedh123** [comment]
@aayusharora @Princu7 @geekyd Congo to all! And thanks for being great mentors all the time! Lets implement this feature.

**Comment by championswimmer** [comment]
Here are some of the things we had plans in last few years, and we had not implemented, and I believe are crucial to take the webapp forward - 

- Having option to add themes (so organisers can select among 2-3 different themes to use)
- Progressive/deferred loading. If number of sessions/speakers is too much, we should load page wise or on scrolling.

**Comment by Princu7** [comment]
Giving the feature to change the theme of the site by the user itself according to his/her liking would be a great thing to have on the web app.  That is, we can implement a setting page on the event site where we can give the option to change the theme and feel of the website. This way, the user will have a better experience and don't need to abide by the organizer choice of the default theme.

**Comment by geekyd** [comment]
Progressive loading and adding themes sound good for the web app. We can provide the choice of themes to the organizer on the generate web app page where we can add these templates for the organizer by adding a small select template button with the themes listed, organizer can click on them to see preview and select one from the templates. 

We have started moving in direction of the progressive loading by adding lazy load. We should extend the as @championswimmer has suggested

**Comment by geekyd** [comment]
Progressive loading and adding themes sound good for the web app. We can provide the choice of themes to the organizer on the generate web app page where we can add these templates for the organizer by adding a small select template button with the themes listed, organizer can click on them to see preview and select one from the templates. 

We have started moving in direction of the progressive loading by adding lazy load. We should extend the as @championswimmer has suggested

**Comment by sumedh123** [comment]
@championswimmer @aayusharora We can keep the theme selector at the webapp generator page itself. We ll let the user generate the webapp and later let him preview each theme and select one from it.

**Comment by aayusharora** [comment]
@geekyd @Princu7 @sumedh123 We are clear with the goals by seeing the report, I will suggest making them as separate issues and start working for PWA.

**Comment by aayusharora** [comment]
@geekyd @Princu7 @sumedh123 Also we already have a commented version of theme concept. We can start with that code.

**Comment by sumedh123** [comment]
Sure @aayusharora

**Comment by Princu7** [comment]
@aayusharora I will open the issues regarding PWA and start working on some of them. Also, we should also open some issues for the theme feature in the web app. It will be good to have a central place where all the discussions regarding the themes should take place. Also, what is your opinion on where this feature should be provided? Showing it on the generator page would be a comparatively easy. But providing this option on the event site itself would be pretty great. This way, the user can change the theme according to his liking and not according to the organizer.

**Comment by Princu7** [comment]
@aayusharora I also have opened an issue #1220  regarding the multiple theme support in the web app.  We can have discussions regarding the themes on that topic and keep the history clean on this issue. Please have a look at that. If something seems lacking, please make the appropriate edits and add additional details to them. Thanks!!

**Comment by anu-007** [comment]
@aayusharora instead of generating lighthouse report after each change we can automate this process by customizing  .travis.yml file by adding lighthouse in this file and ask it to run against the generated web app and write a script in which we open the JSON file that lighthouse is spitting out and look for the lighthouse score in that JSON file and perform a validation for a pass or a fail built for example if the lighthouse score is below 75 we call it a fail built and vice versa.

**Comment by Pravandan** [comment]
When there is a large no of speakers we could have lazy loading so as not to clog the network.I think we should have different themes for different events or why not let the organiser select the colour combination himself?

**Comment by agbilotia1998** [comment]
@geekyd @mariobehling @aayusharora  can we close this, as this is resolved by #1576

**Comment by agbilotia1998** [comment]
Closing this as we have enables PWA support through #1576
