### ISSUE TITLE
Schedule: Implement a calendar view

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1215]
Currently a proper calendar view of the schedule is missing. Please implement a view similar to the calendar view of the web app.

On each page give the option 
* List View
* Calendar View

**Comment by sumedh123** [comment]
@mariobehling You mean to say that the user would be able to choose one option on the schedule page from calender and list, and display the further schedule accordingly. Is that?

**Comment by aayusharora** [comment]
@sumedh123 Yes, A user should be able to switch between these two views. The Calender View is also termed as grid view as discussed earlier. 
Are you willing to work for this ?

**Comment by geekyd** [comment]
@sumedh123 Have you started working on this issue?

**Comment by sumedh123** [comment]
@geekyd I am having my exams now. If you want, please proceed. Thanks.

**Comment by geekyd** [comment]
@sumedh123 Thanks for the update. I will be proceeding with the issue. Best of luck for the exams 👍

**Comment by aayusharora** [comment]
@geekyd Please update with any progress on this issue. This is an important to have at the moment.

**Comment by geekyd** [comment]
@aayusharora Sorry for replying so late, there was an internet ban in my city, so I had no access to the internet. I have started working on this issue I will send a PR in a couple of days. Sorry for the problem caused.

**Comment by muskanbararia** [comment]
Is it still open? Can I work on it?

**Comment by geekyd** [comment]
@muskanbararia I'm in the middle of solving this issue. If you want you can take up some other issue. Thanks :)

**Comment by geekyd** [comment]
Update : @aayusharora @mariobehling I have made progress on this issue please check https://open-event-web-appp.herokuapp.com. Almost done with this issue will be sending a PR soon.

**Comment by Princu7** [comment]
@geekyd Good work :) Looks nice. Some suggestions from my side:
* The color of the text containing the name of the event is not quite readable in some cases. Example:
![screenshot from 2017-04-23 10-21-12](https://cloud.githubusercontent.com/assets/8847265/25310903/add80398-280e-11e7-8b73-ed7b1b44e03f.png)

* It would be great if we do something like the eventyay where on clicking on a session, we can get more detailed information about it i.e description of the session and the name of the speakers presenting it. Even a redirect to the corresponding tracks page would be nice.
![screenshot from 2017-04-23 10-21-28](https://cloud.githubusercontent.com/assets/8847265/25310905/b938680e-280e-11e7-8429-5445f2165d93.png)

**Comment by geekyd** [comment]
@Princu7 Thank you for the feedback. Its not yet complete, I will be adding the hover to each session for displaying additional information. I will change the colour of the text as you suggested. I will be sending a PR soon. Thanks :)

**Comment by sumedh123** [comment]
@geekyd Yeah. I agree with @Princu7 . Black color of the font would look good on every background.

**Comment by mariobehling** [comment]
The display is not yet suitable for end users.

**Comment by geekyd** [comment]
@mariobehling Thank you for the feedback. I have tried to implement a similar UX to the one we have on eventyay.com. Please elaborate what needs to be improved so that we can get it ready for the end user.

**Comment by aayusharora** [comment]
@geekyd We need to work more here.
- Get rid of scrollbars
- Make the container full-width
- Add styles to make UI more familiar.
- Use `cursor: pointer ` on hover.

This will not work.

![scollbar](https://cloud.githubusercontent.com/assets/12194719/25382028/91e4120a-29d3-11e7-9aa1-af44cf190daf.png)

**Comment by aayusharora** [comment]
@geekyd  Can you try something like this 
![123](https://cloud.githubusercontent.com/assets/12194719/25382120/f2097d46-29d3-11e7-8fec-77a8a8cec77f.png)

**Comment by geekyd** [comment]
@aayusharora Okay I will work on the points you referred to, and update you with the changes soon.

**Comment by aayusharora** [comment]
- For grid layout, you can take away the side panel tracks at the footer. Please also ensure the styles remain consistent with other pages.
- You can take popovers styling from speakers page.

**Comment by geekyd** [comment]
@mariobehling @aayusharora I have made some changes to the calendar view. Its not yet complete working on optimisations and UX improvements will send a PR soon.Please check the demo server and let me know if im working in the correct direction.

Link of server:
https://open-event-web-appp.herokuapp.com/

**Comment by aayusharora** [comment]
Hi @geekyd, Good improvement, Please make it more concise so that it fits on the screen without X-axis scrollbar.
To do this, You can make the above boxes `small`  Ex : Here .. Talk1 Talk2 ... etc. 
-  Also the text is not wrapping in divs `use word-wrap: break-word` in CSS for this.

**Comment by geekyd** [comment]
@aayusharora Making the columns smaller is a good solution but it wont fit the names of room which exceed the width. One solution can be to have different sizes for each column. Please let me know what you think.

**Comment by aayusharora** [comment]
`One solution can be to have different sizes for each column.`
This is a website generated from the generator, you can not specify different sizes for each column.

**Comment by aayusharora** [comment]
@geekyd Only option is to make a column a bit smaller so that they all come on screen without the scroll bar.
- If the text exceeds the max-column width, wrap it inside the box.
- If the number of columns exceeds the table width on screen, then introduce the X-axis scrollbar.
This can be done using `overlay: scroll`
