### ISSUE TITLE
Using Selenium for automated testing of generated event sites

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1217]
`Selenium` is a browser automation library. Most often used for testing web applications, Selenium may be used for any task that requires automating interaction with the browser. In our case, it can be leveraged for automatic testing of the generated event sites. Currently, after every commit related to the improvement of event websites, we have to manually test the functioning and consistency of the site. We have to check for any regressions in the new version. Selenium will help us to eliminate this rudimentary step and prove to be helpful to both the contributors as well as the maintainers.

On top of my head, these are some of the areas where we can write tests using Selenium:
    
* Ticket section
* Search Bar
* Bookmark feature
* Date and Tracks Navigation Bar
* Different UI issues
* Dead Links
* Tweet section

There are different libraries for different languages for writing tests in Selenium. For `node`, we have the `selenium-webdriver` library. If it seems feasible, we can add the tests script to trigger on every request sent to the repo. It would help us to prevent regressions and maintain consistency. Would love to hear opinions, suggestions and even more tests. Thanks!!

**Comment by geekyd** [comment]
We need to add selenium in the application. It will ease the testing process and we can do Dom component testing using the browser automation.

**Comment by sumedh123** [comment]
@geekyd @Princu7 Actually yes. We have been into a situation where merging a PR broke a part of app. Then we had to correct it again to make it working. This is good idea. :+1:

**Comment by Princu7** [comment]
@aayusharora Please provide feedback on this issue. In my humble opinion, we should maybe proceed with this issue first instead of working on other features. There have been many times where we had to revert a commit or make another request to fix the regressions introduced due to a faulty commit.  Using Selenium could help to catch some of those regressions earlier and reduce the manual labor. Please consider it. Thanks :)

**Comment by aayusharora** [comment]
@Princu7 this can go parallely along with other issues. You can proceed with this, if you are willing to do so. Thanks
