### ISSUE TITLE
Progressive Web App: Create a web-app Manifest

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1219]
The web app manifest provides information about an application (such as name, author, icon, and description) in a JSON text file. The purpose of the manifest is to install web applications to the home screen of a device, providing users with quicker access and a richer experience. Web app manifests provide the ability to save a site bookmark to a device's home screen. Though we can use a web app manifest on any site, they are required for progressive web apps.

**Comment by sumedh123** [comment]
@Princu7 Sure. It will also contain the icon sizes used for push messages, description, orientation etc.

**Comment by aayusharora** [comment]
Nice start @Princu7.

**Comment by abhishek71994** [comment]
I have started learning angular and I have tested out a basic service worker. Can I contribute? I want to be involved because I find PWA to be the next big thing and it also acts as a new challenge. Also am new to open sourcing so, yeah.

**Comment by aayusharora** [comment]
@abhishek71994 Hi, Please start contributing, You are good to go.

**Comment by abhishek71994** [comment]
Ummm... It would be so helpful if you could tell me where to start?

**Comment by jajodiaraghav** [comment]
Claiming this issue as no update was made for a month.
