### ISSUE TITLE
Enable multiple theme support in the webapp

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1220]
As suggested by @championswimmer and @aayusharora, this is an integral feature for improvement of the web app which would also prove to be helpful to both the organizers and users. Most of the organizers and users will not like to create or view the event sites having the same design over and over again. To solve this problem, we can provide a multiple theme support in the web app. 

We already have the basic template of the themes ready in the `_scss` folder. We have to improve upon this basic structure and implement the feature.

**Comment by sumedh123** [comment]
@Princu7 @aayusharora I will work on this issue. I am having my exams right now but still I will try my best to implement. :)

**Comment by Princu7** [comment]
@sumedh123 No problem at all. There is no hurry :)

**Comment by sumedh123** [comment]
@aayusharora @Princu7 Do we need to desing all new themes or just change the color scheme of the existing theme to provide a new look ?

**Comment by aayusharora** [comment]
I will be more convinced if somebody can give a design that is more simple and less confusing. That can become a separate theme.

**Comment by sumedh123** [comment]
@aayusharora I 'll try to show you design asap. If everybody finds it well and good, I 'll implement the same as a new theme.

**Comment by aayusharora** [comment]
Thanks @sumedh123

**Comment by sumedh123** [comment]
@aaysuh

**Comment by sumedh123** [comment]
@aayusharora Is there any restriction on using the frameworks? In our current theme we are using bootstrap. Can I make the theme with any other framework other than bootstrap?

**Comment by aayusharora** [comment]
@sumedh123 It will be better if we stick to bootstrap. We can try other options later.
Well, If you have something creative in mind, I will love to know that.
We can discuss this once you will provide the mockups.
Note: We provide the functionality to the user to download the generated website, We want the zip to be of minimum size. It would be complicated to have "bootstrap based files" for choice1 and some other framework based files for choice2 when the user downloads the app.

**Comment by agbilotia1998** [comment]
@geekyd I will work on this.

**Comment by agbilotia1998** [comment]
@geekyd can we close this as #1713 is already opened?

**Comment by agbilotia1998** [comment]
Closing this as #1713 is already opened.
