### ISSUE TITLE
Tweet display not working anymore

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1229]
The tweet display on the generated app is not working anymore.

**Comment by sumedh123** [comment]
@mariobehling I 'll get it checked.

**Comment by geekyd** [comment]
@sumedh123 Any updates? This is an important issue.

**Comment by sumedh123** [comment]
@geekyd Please proceed if you can.

**Comment by geekyd** [comment]
@mariobehling @sumedh123 It seems that the query for loklak api is not returning any result, this is causing the issues. please have a look at this link http://api.loklak.org/api/search.json?q=fossasia%20from:fossasia it does not return anything.

**Comment by sumedh123** [comment]
@geekyd Yes, you are correct. Look at the developer tools console. There is no data fetched and it shows the error that "cannot read the property 'text' of undefined."

**Comment by geekyd** [comment]
@mariobehling @sumedh123 I contacted loklak on gitter, the loklak server due to recent changes only stores tweets that are one month old. Fossasia twitter handle has no new tweets for the specific time frame,  that's why we are not seeing any tweets on the web app.

**Comment by mariobehling** [comment]
@geekyd What about the OSCALconf? It was neither working as far as I could see. There are tweets. Did you try this out with another twitter account? 

http://loklak.org/api/search.json?timezoneOffset=-120&q=from%3AOSCALconf

**Comment by geekyd** [comment]
@mariobehling I think the problem is with the change of query structure of loklak api. The client that we are using in the web app has outdated query syntax. I contacted loklak and they provided the new syntax will be sending a PR soon.

**Comment by mariobehling** [comment]
Good job. As you understand the issue now, please help to solve the same issue here:
* https://github.com/fossasia/loklak-webtweets
* https://github.com/fossasia/fossasia.org

Please always use api.loklak.org instead of loklak.org.
Thanks!

**Comment by geekyd** [comment]
@mariobehling Okay I will solve the issues for the required applications. I have updated the PR changed the url to api.loklak.org. Thanks
