### ISSUE TITLE
UX issue in search By Title, Search By Speaker

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#123]
![2](https://cloud.githubusercontent.com/assets/12194719/13373314/3a3163fa-dd8a-11e5-8618-1d22716a382e.png)

**Comment by aayusharora** [comment]
Is their a need to show Day3 , Day4, even if the search item is in Day2 only. I think only the valid information should be there. For example: Here String match is only with Day 2 ,so Day3 and Day4 must be hidden.

**Comment by SaptakS** [comment]
I guess we shouldn't show the info which is not required. @creativepsyco

**Comment by aayusharora** [comment]
Solved here #124

**Comment by aayusharora** [comment]
![correct](https://cloud.githubusercontent.com/assets/12194719/13406777/5bd375b2-df4b-11e5-8707-2acd6095ad21.png)

**Comment by aayusharora** [comment]
@championswimmer ,Its good to close , PR merged already #124

**Comment by ashutoshsaboo** [comment]
So, Can this issue can be closed? Since, I  guess the PR #124 is merged already! @championswimmer

**Comment by aayusharora** [comment]
PR already merged #124
