### ISSUE TITLE
Downloaded app to local PC does not show speaker images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1230]
Please see below.

![screenshot from 2017-04-25 12-50-07](https://cloud.githubusercontent.com/assets/1583873/25381912/d6c28da2-29b5-11e7-9fc0-2ca45096fe7a.png)

**Comment by geekyd** [comment]
@mariobehling I tried to test by using the https://eventyay.com/api/v1/events/6 for Fossasia summit. The downloaded app does not seem to have the above issue. All the speakers images are loaded properly. Can you please specify what source was used to generate the app?

**Comment by geekyd** [comment]
@mariobehling I have tested this on local machine. The downloaded app works as expected, loads all the images, on local machine.

**Comment by Princu7** [comment]
It works now. Closing
