### ISSUE TITLE
Recent changes resulted in missing spaces and disalignment

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1231]
E.g. 

* [x] sidebar tracks are disaligned and do not have a space next to dots.

![screenshot from 2017-04-25 12-51-31](https://cloud.githubusercontent.com/assets/1583873/25382018/32a8375c-29b6-11e7-8636-b957a6fa02b1.png)

* [x] Dates and other buttons have different distance and are disaligned.

![screenshot from 2017-04-25 12-57-02](https://cloud.githubusercontent.com/assets/1583873/25382159/c0fd61d0-29b6-11e7-9b5f-4f3257b4140a.png)

* [ ] New colors that don't follow previous design have been introduced and buttons are not separated.

![screenshot from 2017-04-25 12-57-57](https://cloud.githubusercontent.com/assets/1583873/25382202/e43a4d48-29b6-11e7-8b96-d03333c2b7ff.png)

* [x] Schedule page sessions don't have space between them
![screenshot from 2017-04-25 13-09-18](https://cloud.githubusercontent.com/assets/1583873/25382557/7df7457a-29b8-11e7-932d-f60014ecfb1e.png)

**Comment by mariobehling** [comment]
* [ ] Dates and other buttons still disaligned. They are not in the same exact row.

![screenshot from 2017-04-25 12-57-02](https://cloud.githubusercontent.com/assets/1583873/25382159/c0fd61d0-29b6-11e7-9b5f-4f3257b4140a.png)

**Comment by sumedh123** [comment]
@mariobehling Please review.
Screenshots for the change : 
![alignment](https://cloud.githubusercontent.com/assets/17925669/25523929/1e7f06da-2c26-11e7-9c35-0a84e8c68ddd.png)
![pills](https://cloud.githubusercontent.com/assets/17925669/25524006/6036d530-2c26-11e7-9107-994e8fbc6d40.png)

**Comment by mariobehling** [comment]
Search bar also still disaligned on all pages.

![screenshot from 2017-04-30 11-48-36](https://cloud.githubusercontent.com/assets/1583873/25563348/0427c864-2d9b-11e7-836a-3541847df909.png)

**Comment by mariobehling** [comment]
The style of the list view and calendar view button is not changed to encompass now border. This is not as expected. There should be a border. Not sure, when this was changed.

**Comment by Princu7** [comment]
Solved via recent PRs.
