### ISSUE TITLE
Calendar View: Improve use of space

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1233]
For calendar view:

1. Please make use of complete white area. Just keep a small space on left and right within the area to match the design.

2. Move sidebar with tracks below calendar in that view.

**Comment by mariobehling** [comment]
Nice improvements of the last merge, but please also improve the following:
* Please make use of complete white area. 
* Please ensure you use the exact same area. Keep the heading date e.g. "Sunday, 14th May" in the same spot as in the list view

![screenshot from 2017-04-27 20-03-13](https://cloud.githubusercontent.com/assets/1583873/25497355/92b138c2-2b84-11e7-9c65-eb0beb24f91d.png)

**Comment by geekyd** [comment]
@mariobehling I have made made the columns smaller to ensure that we try to show as much information as possible without having the scroll bars on the view. So thats why the view is small for the dates which have less number of rooms. However we can increase the width of the columns if required.

**Comment by mariobehling** [comment]
If additional session info is shown, avoid internal scroll bars and overlap following areas. Compare to implementation of open event orga server.

![screenshot from 2017-04-27 20-09-53](https://cloud.githubusercontent.com/assets/1583873/25497696/b9959770-2b85-11e7-9fa5-79a9c1b350e0.png)

**Comment by mariobehling** [comment]
> However we can increase the width of the columns if required.

If there are too many columns we need some kind of internal scroll bottom bar I guess. If there are 4 or 5 columns please use the full width.

Please make it work in a way that the columns work well if there are 3 columns, 4, 5, 6, and more. What is the best solution? Please propose a suitable solutions that makes good use of the space and which is flexible as well.

**Comment by geekyd** [comment]
One solution that will ensure a flexible view will be in Javascript

1. Calculating the width of the view and the container of the view.
2. If the width of view is less than the container we will calculate the difference by
`Difference = WidthContainer - WidthView`
and divide it by the number of columns n
`Offset = Difference/n`
3. Adding offset to the width of each column.

**Comment by aayusharora** [comment]
Thanks @mariobehling 
`Please make it work in a way that the columns work well if there are 3 columns, 4, 5, 6, and more. What is the best solution? Please propose a suitable solution that makes good use of the space and which is flexible as well.`
- Because the table has dynamic data. There will be a certain maximum limit after which the scrollbar have to be introduced.
- Use max-width of the table with column sizes as `display:inline-block` giving them the size required for the content. 
Note: Please don't use any `jQuery` or `JS` that will become a performance bottleneck in future.
- When the table have full width of parent container and the content does not fit in table use scrollbar with CSS.  Handling overflow using `overflow: overlay`
- Please use minimum javascript because it will stop the page from loading even if the user is not focussed and does not click the Calender View button.
- There can be 90% or more we can achieve only by using CSS.

**Comment by geekyd** [comment]
@aayusharora currently 
All the columns have a min-width and a max-width. The display property of the div is set to inline block.This is good if we have the width of the table more than the threshold, which will inroduce a scroll bar. However I'm not clear how will we utilise the space without using js. Please guide.

**Comment by aayusharora** [comment]
@geekyd Which space are you talking about.
Can you give a snapshot so that I can think a propose a solution, if it can be done through CSS.

**Comment by geekyd** [comment]
As @mariobehling suggested we need to make use of the white space of the page. 
Please check this. Thanks :)
![92b138c2-2b84-11e7-9c65-eb0beb24f91d](https://cloud.githubusercontent.com/assets/12807846/25499444/10d0229e-2ba9-11e7-8cbb-a8c364f98b5e.png)

**Comment by aayusharora** [comment]
Why can't we make this table full width below the search bar? As the tracks colors bar is intend to be near the footer in the grid view.

**Comment by geekyd** [comment]
@aayusharora If you will check the HTML we have `calendar` which has `times` which contains the time and `rooms` which contains all the rooms each of them have class 'room'. If we make the width of rooms 100% then it wont solve our purpose as in css of `room` we have specified min-width and max-width. it wont fill its parent and remain unchanged.

**Comment by aayusharora** [comment]
@geekyd  Correct, Thanks. 
JS seems an only solution for this problem right now for the `table having less width than container`, please go ahead with this and we will do future improvements.
But please handle the other stuff using CSS.

**Comment by aayusharora** [comment]
Please check the comment and the scope of improvement for web performance.
https://github.com/fossasia/open-event-webapp/pull/1246/files

**Comment by geekyd** [comment]
Closing this. as further discussion is on #1256
