### ISSUE TITLE
Testing: Test app with OSCAL event and open issues where necessary

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1235]
OSCAL is an event using Open Event. The API is here: https://eventyay.com/api/v1/events/47

Please test the app with this event and report issues.

**Comment by aayusharora** [comment]
@geekyd  @Princu7  @mariobehling would you suggest generating an app for OSCAL for each PR merge so that we can test better. What are your suggestions?

**Comment by mariobehling** [comment]
@aayusharora Well, the idea is that people test actively. I don't see that we need to add this to auto deployment. The event will be over in couple of weeks as well.
