### ISSUE TITLE
Autoscrolling too slow

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1236]
Autscrolling to sessions or events is still too slow. It is ok to have this effect, but it should be super fast, e.g. from the following button. Users should not have the feeling that they are waiting for the effect to finish. Please make it very fast.

![screenshot from 2017-04-25 13-24-04](https://cloud.githubusercontent.com/assets/1583873/25383056/91ebcc70-29ba-11e7-9945-d642b7118440.png)

**Comment by Princu7** [comment]
Working on it. Will fix it soon :)
