### ISSUE TITLE
Changing the source of gh pages to FOSSASIA summit

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1243]
Changing the source of gh-pages from OSCAL back to FOSSASIA Summit.

**Comment by aayusharora** [comment]
For testing purposes of oscal, it was changed to oscal end point. Any reasons for changing back to this @geekyd @Princu7.

**Comment by geekyd** [comment]
@aayusharora 
@mariobehling Suggested that we should only use FOSSASIA Summit for the gh-pages. Also the auto deployment was not working after the change of the source for gh-pages.

**Comment by aayusharora** [comment]
Where is it suggested @geekyd. Can you please relate this to that issue.

**Comment by geekyd** [comment]
@aayusharora Please check the chat on gitter.

**Comment by mariobehling** [comment]
@aayusharora You have changed the source without any info or issue. That is why it is changed back.
