### ISSUE TITLE
OSCAL : Text not clearly visible for sessions

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1245]
The text for sessions with darker background colour is not visible clearly. We can either change the colours for the event or dynamically detect if the colours used in background are dark or light and make text colour light or dark accordingly.

Please share your opinions regarding to this issue.

**SCREENSHOT**
![screen shot 2017-04-28 at 1 30 05 am](https://cloud.githubusercontent.com/assets/12807846/25501964/60bd7d2a-2bb2-11e7-9040-035f723ebb65.png)

**Comment by Princu7** [comment]
Exactly. I was thinking about it too. The colors of the tracks have been defined by the organizers themselves so it wouldn't be wise to change them. What we can do is make a function which tells whether the track color is dark or light. If it is dark, then use the white font color and if it is light, then use the black font color.

**Comment by geekyd** [comment]
A corresponding issue was opened on orga-server please check [#3554](https://github.com/fossasia/open-event-orga-server/issues/3554)
