### ISSUE TITLE
Ensure consistency across pages - Improve schedule and other pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1249]
We need to ensure consistency across pages. The schedule page has items located differently to other pages.

* Location of list/calendar view date heading is different to tracks/rooms page. 
* Areas are not aligned in one left line. Indent is varying.
![screenshot from 2017-04-29 13-21-42](https://cloud.githubusercontent.com/assets/1583873/25555166/6935ef22-2cdf-11e7-83f6-173cc6b316ed.png)
![screenshot from 2017-04-29 13-21-22](https://cloud.githubusercontent.com/assets/1583873/25555170/709b7354-2cdf-11e7-88a1-4e6de9491595.png)
* buttons have different widths in mobile view. Please make "show starred" and "search" into the same width as date buttons on all pages
* List View and Calendar View buttons should share half the area of one line in mobile view.
![screenshot from 2017-04-29 13-27-12](https://cloud.githubusercontent.com/assets/1583873/25555195/ea8e7a1c-2cdf-11e7-9b85-5042a43e53db.png)
* Get rid of wasted empty space on right and left in mobile view on all pages
* Align all content on left and right in one line
![screenshot from 2017-04-29 13-31-04](https://cloud.githubusercontent.com/assets/1583873/25555215/76dfd7b8-2ce0-11e7-96a5-b5abe9ee8b84.png)

**Comment by anu-007** [comment]
@mariobehling I would like to work on this issue.

**Comment by geekyd** [comment]
@anu-007 Go ahead 👍

**Comment by sumedh123** [comment]
@anu-007 Are you working on this one?

**Comment by anu-007** [comment]
@sumedh123 currently  I am working on #1260 ,you can take this one.

**Comment by Princu7** [comment]
It has been fixed by older PRs. Closing
