### ISSUE TITLE
Add full screen pop-out option of calendar view similar to orga server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1251]
Add pop-out option of calendar view next to the date heading similar to orga server.

![screenshot from 2017-04-30 11-46-00](https://cloud.githubusercontent.com/assets/1583873/25563336/a82e55b4-2d9a-11e7-8596-a56a2ee0cc47.png)

**Comment by ParthS007** [comment]
@geekyd @mariobehling Is this issue still persists?

**Comment by geekyd** [comment]
@ParthS007 Yes we need a full-screen version of the schedule similar to eventyay.

**Comment by ParthS007** [comment]
@geekyd Do I need to add a button like this ?
![image](https://user-images.githubusercontent.com/24358501/34672293-ef197488-f4a3-11e7-9143-a452eecdc6cc.png)

**Comment by geekyd** [comment]
@ParthS007 Yes you also need to implement the full-screen view of the schedule.

**Comment by aswinzz** [comment]
@geekyd can i work on this issue?
