### ISSUE TITLE
Implement ics/ical to sync calendars with schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1253]
Propose and implement ics/ical to sync with calendars.

**Comment by geekyd** [comment]
@mariobehling This is a great feature for the webapp. The speakers and users can add the sessions to their calendars. I have proposed something similar in my GSOC proposal letter. The idea is to create a calendar, and provide a button for sessions which will let them save the sessions directly to their calendar. I have proposed to use google calendar api, for creating a public calendar with all sessions added to it.

**Comment by Princu7** [comment]
@mariobehling Just to be sure, we want to provide a button to the users that will export the whole schedule of the event to an ics file on click? Please guide. Thanks!!
