### ISSUE TITLE
Footer: Use local license button and provide correct link

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1255]
* [ ] Please use the small Creative Commons buttons instead of large buttons.
* [ ] Store buttons on the itself. Do not embed external buttons.
* [ ] Use the correct link to the actual license
* [ ] There is a link to the organizer, e.g. "© 2017 FOSSASIA and Science Centre Singapore." with a wrong link. Take out that link.
* [ ] Behind "The website and it's contents are licensed under Creative Commons Attribution 4.0 International License." or similar add the following: "The site was generated using the Open Event format on the [eventyay](https://eventyay.com) [site generator](https://webgen.eventyay.com). Please submit [issues here](https://github.com/fossasia/open-event-webapp/issues)."

**Comment by Lplenka** [comment]
I am new to FOSSASIA, this issue seems to be small. I will start with this Issue. Claiming this one.
