### ISSUE TITLE
Performance Improvement in Table view  

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1256]
Hey, @geekyd @Princu7 This is not the right approach to set width and current width every time the page loads with JS.
I hope you guys understand the effects of this on the performance of the app.
Proposed approach with some reasoning:

Can we do this calculation on the server calculation of offset we already know the column width and we already know the number of columns?
After getting the offset as a handlebar variable, we can add it to HTML DOM element using CSS style.
Please comment your suggestions @geekyd @Princu7. :)

**Comment by aayusharora** [comment]
## How to calculate column width on Server?
Assuming we have a full-width container that will be 100vw ( 100% of the viewport ) which is generally 1280px.
I doubt why we need anything from frontend, we can structure the table like this.

Calculate the width the table needs from server => It will be calculated as
container width = no. of columns * width per column
Assuming we always want to give a table a full width.
width per-column = container width / no.of columns ( calculated at server )
This can be sent back to the client to take CSS.
Hope this helps :)

**Comment by geekyd** [comment]
@aayusharora We can go with what you are suggesting, But I'm not quite sure that would have any influence over the load speeds of the page. The function adjustCalendar() is only triggered when the user is in the calendar view and not onLoad of the page. If we really want to improve the load time of the page we should

- Not execute the display() function onload. That would significantly help as on load we don't need to trigger it as it takes all the sessions of the page and checks if it should be displayed or not.

Please share your views on this.

**Comment by aayusharora** [comment]
@geekyd I always suggest measuring the improvements.
Wherever a JS is involved making a CSS change, most importantly Layouting which is changing here, the whole cycle of `Layout => Paint => Composite` takes place which affects the performance.
Also if it contributes to performance increment of say 1ms ( which is very small ) but it will vary linearly with the data.

**Comment by aayusharora** [comment]
@geekyd Can you please comment the file here that uses `display()` function code, I will see if that can be optimized and will create a separate issue.

**Comment by geekyd** [comment]
@aayusharora `display()` is used in schedule, tracks and rooms page.

**Comment by Princu7** [comment]
@aayusharora @geekyd I highly apologize for not being able to help and catch up with the recent issues. My end semester exams are currently going on. Been really busy preparing for it. Sorry again. Hope you understand. Thank you!!

**Comment by Princu7** [comment]
@aayusharora @geekyd When the page is loaded, `display()` function takes in all the sessions and checks whether they are bookmarked or not. If they are bookmarked, then they are shown as marked otherwise not. When the user further clicks on the show starred button, `display()` function is again invoked to show the bookmarked sessions and vice-versa.

**Comment by geekyd** [comment]
@Princu7 According to me when the page is first loaded we don't actually have to iterate over all the sessions to check for bookmarked sessions. As I can see we are using `id` of the element to store the bookmarked sessions in `localStorage`. On first load we can simply need to change css of the button that can be done by iterating over sessions stored in `localStorage`and change the css.We should only trigger it only if user triggers the `show stared`button. This would be less costly. Please share your opinion.

**Comment by Princu7** [comment]
Yeah, that should work :+1: . It would be great if we could measure the performance gains by using the alternative method.
