### ISSUE TITLE
Move search to top bar in mobile view

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1258]
In the mobile the search bar should be moved to the main menu bar similar to the Android app.

Please show a search button and expand this search button into a search field on click.

![screenshot_2017-05-01-13-02-37](https://cloud.githubusercontent.com/assets/1583873/25579226/41c8a220-2e76-11e7-864f-14fdf8bd60e5.png)

**Comment by utkarshnath** [comment]
@mariobehling I would like to work on this

**Comment by Princu7** [comment]
@utkarshnath Please proceed. There is no one working on it presently. Thank you so much!!
