### ISSUE TITLE
Change behavior of gray day buttons and related changes on tracks and rooms page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1259]
This is a follow up to earlier discussions about the date buttons on the different pages. There are two kinds of buttons for dates on the pages. The question is: How can the functionality of these two buttons be united. The idea of this issue is: The dark gray buttons should act in a way like the date buttons in the calendar view. 

The desired functionality is: 

* On click 
  * a) expand to show tracks or rooms and 
  * b) show event data of specific date (similar to behavior of date buttons in calendar view).

![screenshot from 2017-05-01 14-08-27](https://cloud.githubusercontent.com/assets/1583873/25579423/224ed1a6-2e78-11e7-83b4-f2d605ec9ee0.png)
_In the screenshot, if the user clicks "18th May" the information below should be showing 18th May instead of 17th May._

* Secondly as the top date buttons are not required anymore, please take them out.

* Thirdly: Change the look and position of the buttons on the "Schedule" page to match the other pages.

**Comment by geekyd** [comment]
@mariobehling Nice solution. I did something similar to the issue #1206 in the PR #1123, but used the upper date buttons for implementing the functionality. I will make the changes according to the specification.

**Comment by sumedh123** [comment]
@mariobehling @geekyd I think we should change the colors of the buttons. They are quite confusing. I mean in they are not highlighted in current state and it might misguide the user in which view is he using the app. i.e List view or calender one. An active button would prove helpful with some colors. Opinions?

**Comment by mariobehling** [comment]
@sumedh123 One thing is functionality. We can go step by step. You can propose other colors in a separate issue. Surely the colors are related, but let's fix one thing at a time. If we focus on one thing at a time in issue, I hope to speed up our development process. Honestly, I think we need to improve here, but I am not sure, how to achieve this - less discussion and faster code production. Maybe one issue and solution at a time can help. So, we align by working together instead of needing too much discussions. Let's try this, ok?

**Comment by sumedh123** [comment]
Sure @mariobehling .
