### ISSUE TITLE
Mobile View: Move in (slide on top) menu from right instead from top down

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1260]
In mobile view, please change the menu dropdown to be a slide on top menu moving in from the ride side. Occupy the whole height of the screen.

![screenshot from 2017-05-01 15-53-16](https://cloud.githubusercontent.com/assets/1583873/25581156/534743ca-2e86-11e7-899e-db9449d7aeab.png)

Ensure to slide "on top" from the right side of the screen. This way we make it more similar to our Android app. A sidebar is also more similar to FOSSASIA website.
![screenshot from 2017-05-01 15-54-31](https://cloud.githubusercontent.com/assets/1583873/25581191/8ac6089a-2e86-11e7-8686-aeab6b560793.png)

**Comment by anu-007** [comment]
@mariobehling please review ( https://github.com/fossasia/open-event-webapp/pull/1270 )

**Comment by mariobehling** [comment]
The sidebar should cover the whole area from top to down.

**Comment by ihsavru** [comment]
@mariobehling  I would like to work on this issue. I'm confused if you want the sidebar to cover the entire screen because it is already covering top to down but not the entire width. :sweat_smile:

**Comment by geekyd** [comment]
@agbilotia1998 @ParthS007 Can you have a look at this? Lets fix these minor issues.

**Comment by ParthS007** [comment]
ok @geekyd

**Comment by agbilotia1998** [comment]
@geekyd I guess it is fixed.
