### ISSUE TITLE
Security Vulnerability: Update Brace Expansion

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1261]
Affected versions: Pior or equal to 1.1.6
Fixed versions: 1.1.7
Solution: Upgrade to version 1.1.7 or later.
Credit: kamael
Sources: https://nodesecurity.io/advisories/338 
https://github.com/juliangruber/brace-expansion/issues/33 
https://github.com/juliangruber/brace-expansion/pull/35 
https://github.com/juliangruber/brace-expansion/pull/35/commits/b13381281cead487cbdbfd6a69fb097ea5e456c3

**Comment by Princu7** [comment]
Updated in one of the previous PRs. Closing this issue :)
