### ISSUE TITLE
Align buttons and all right side content in one line

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1264]
The content and buttons have been changed and are no longer aligned in one line. Please align them again.

![screenshot from 2017-05-04 23-13-31](https://cloud.githubusercontent.com/assets/1583873/25725270/8d4fccc2-311f-11e7-9d79-1896d9d28df8.png)

**Comment by geekyd** [comment]
@mariobehling The screen shot seems to be of the app before the last PR. The date buttons were removed in the last PR.
Please check 
https://fossasia.github.io/open-event-webapp
