### ISSUE TITLE
Improve "Show Starred" and "Show All" and change position

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1265]
Please change the "Show Starred" and :"Show All" as follows:
1. Rename it to only "Starred" and "All".
2. Move the buttons behind the "Search" on the right hand sid
3. Expand the "date, track or rooms" area that is available now in width to fill the space (ensure this works also for longer events of more than two days)

![screenshot from 2017-05-04 23-22-11](https://cloud.githubusercontent.com/assets/1583873/25725573/dd035bd4-3120-11e7-8821-a7f8651cb2bc.png)

**Comment by Princu7** [comment]
Working on this :) Will try to send a patch soon. Thanks!!

**Comment by Princu7** [comment]
Closed via #1275
