### ISSUE TITLE
Port to Angular2

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#127]
Just putting this here. Let's just first discuss this. This will be **MAJOR WORK** so no jumping the gun on this. Plus it won't be considered acceptable to lose any functionality that the existing Angular1 app already has

**Comment by aayusharora** [comment]
@championswimmer,I was having the idea to shift the app to Angular2.After research ,I found out Angular Material which is used here with Angular 1 is still in development phase I'm Angular2.

**Comment by championswimmer** [comment]
It is not imperative to **have to** use the same UI. 
It is important to match up the feature set only
