### ISSUE TITLE
Add a "My event" section to the web app

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1273]
The generated web application should have a "My events" which will contain all the events the user bookmarks. We can extend the current bookmark feature and introduce a separate panel for the user's event. The user will be able to add sessions to the "My events" and have a personalised experience. We will also provide one click "Save to calendar" feature which will allow the user to save the event schedule to his/her calendar.

Reference : https://events.google.com/io/schedule/?section=may-17

@mariobehling @aayusharora @Princu7 Please share your opinions.

**Comment by Princu7** [comment]
Seems to be a good idea. Not entirely sure about a whole dedicated page but the calendar feature would be neat.

**Comment by mariobehling** [comment]
For this kind of feature you would need an accounts system. We can do this using the orga server, but this feature would first need to go into server and should be working across the server, web app and Android app. In any case it needs to be discussed in the server project first, but I also think other issues have a higher priority as there as a number of bugs that need to be fixed first before opening a new chapter. Therefore closing it here.

**Comment by geekyd** [comment]
@mariobehling Fair enough. We shall discuss this after we are done fixing current high priority issues. We can integrate it with the notification sever once its done. Thank you for your input.
