### ISSUE TITLE
Rooms Page shows speaker photo twice on expansion

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1276]
The speaker photo on the top should disappear similar to tracks page.
![screenshot from 2017-05-15 11-57-46](https://cloud.githubusercontent.com/assets/1583873/26052448/d5037ee4-3965-11e7-9dda-a848eb0cc4c4.png)

**Comment by geekyd** [comment]
The issue was solved in #1279, Closing the issue.
