### ISSUE TITLE
Logo height not scaled resulting in increase top bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1277]
The logo should be scaled to fit the top bar area. Currently it results in the expansion.
![screenshot from 2017-05-15 12-03-05](https://cloud.githubusercontent.com/assets/1583873/26052660/77dc9fb0-3966-11e7-92c3-d6321dc98ac7.png)

**Comment by geekyd** [comment]
@mariobehling This is a duplicate issue please check #1074

**Comment by aayusharora** [comment]
Closing this via duplicate #1074 @mariobehling @geekyd 
Please check `how to use transform: translate()` property of CSS to fixed this.
Thanks.
