### ISSUE TITLE
Adapt Font color depending on new API info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1281]
The font color is now set in the Orga server depending on the background color either black or white.

Please re-use the same color as in the schedule of the server. Follow up with the orga team about the API implementation and use color defined.

![screenshot from 2017-05-16 15-42-18](https://cloud.githubusercontent.com/assets/1583873/26108957/446c7824-3a4e-11e7-9868-9083e1526a27.png)
![screenshot from 2017-05-16 15-44-20](https://cloud.githubusercontent.com/assets/1583873/26109033/8d8f54b8-3a4e-11e7-9e86-0f08c89882f5.png)

**Comment by geekyd** [comment]
@mariobehling I'm working on this.

**Comment by Princu7** [comment]
@geekyd I have already started working on this. Discussed it in the chat. :smile:

**Comment by geekyd** [comment]
Okay go ahead :smile:
