### ISSUE TITLE
Only add speakers and sessions to the generated site, that are accepted or confirmed

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1286]
Currently speakers get added to the speakers page, that are not `accepted` or `confirmed`. Please take the status of speakers into account and only show speakers that are really participating.

Check if relevant API info is available here: https://github.com/fossasia/open-event-orga-server/issues/3621

**Comment by geekyd** [comment]
@mariobehling I'm working on this.
