### ISSUE TITLE
Codacy not commenting on pull request anymore

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1288]
From the past some time, `codacy`, which is used for maintaining the code quality of the repo and check the quality of a pull request, is not working anymore.

I checked the reason by going to the codacy site and saw that due to some reason, GitHub integration of the codacy is turned off. This is the reason why the codacy is not able to comment on the pull requests anymore.

![codacy](https://cloud.githubusercontent.com/assets/8847265/26300204/103c9870-3efb-11e7-8e22-1f9fe07e0af8.jpg)

Would be great if an admin could turn it back on and switch on the comments.
`Link`: https://www.codacy.com/app/championswimmer/open-event-webapp/dashboard

@mariobehling @championswimmer @aayusharora Please help. Thanks!!

**Comment by aayusharora** [comment]
Well, I guess it was turned off intentionally, as it was making the PR's problematic by not accepting.
@championswimmer Will you please check if you have rights to enable this.

**Comment by mariobehling** [comment]
I activated it in my account now. Not sure, what happened. Please check if it is working again in a bit.

**Comment by Princu7** [comment]
@mariobehling It still doesn't work. The official repo seems to be associated with the @championswimmer  account so only he would be able to turn it back on.
