### ISSUE TITLE
Unable to close some sessions dialog box

### ISSUE THREAD

**Issue by manipalsingh013** [fossasia/open-event-webapp#129]
When right slider is not at top, unable to close some sessions as close button is not in screen view and there isn't any way to scroll it up.

To reproduce:
1. Go to Sessions
2. Click on some session, I tried "Finding Europe: Collaborative Journalism in Times of Crisis"

Found this in Firefox when the zoom level is set to 100%
![screenshot from 2016-03-07 03 37 06](https://cloud.githubusercontent.com/assets/13970876/13557453/ae489ece-e416-11e5-8f85-1af39a4c22aa.png)

**Comment by manipalsingh013** [comment]
Basically I'm unable to scroll with the dialog box open. So some text is also not viewable, in this case can't see any Speakers name(although when I zoom out to like 30%, 5 speakers were there).

**Comment by AmayAgrawal** [comment]
@manipalsingh013 Try it on the http://fossasia.github.io/open-event-webapp/#/sessions.I know that u must have tried it on your local server but by some reasons it is not display properly in local server but it is properly displaying here.You can check it out whichever session u want on the main link given above.

**Comment by manipalsingh013** [comment]
@AmayAgrawal I tried it on the link that you gave and yes its working fine there, any possible reason for such behavior on localserver? is it using some different branch?

**Comment by SilentFlame** [comment]
@manipalsingh013 
Works fine for me locally too.
![picci](https://cloud.githubusercontent.com/assets/9693795/13609264/2f2a691a-e57e-11e5-9271-3e0d51ea3f1b.png)

Either you may have Zoom more than 100% or might something else.

**Comment by ashutoshsaboo** [comment]
@manipalsingh013 Yes, it works fine everywhere, as @SilentFlame pointed out. please check your zoom level - You can press `Ctrl+0` to reset the zoom level to `100%` and then check. :smiley:

**Comment by VivekProHacker** [comment]
No its not working fine on the given link also. [http://fossasia.github.io/open-event-webapp/#/sessions](http://fossasia.github.io/open-event-webapp/#/sessions) .

It should work with all zoom level.
![open event](https://cloud.githubusercontent.com/assets/10754928/13635605/ed64eb36-e622-11e5-9454-6c37aa03a4a3.png)

**Comment by SilentFlame** [comment]
unable to understand the issue now, as it works fine on all levels of zoom for me. 
I think I'm unable to follow you on this, can you please be elaborate on the issue you are facing?

**Comment by championswimmer** [comment]
tested on ubuntu/windows on firefox/chrome

works on all zoom levels.
