### ISSUE TITLE
Integrate selenium testing in the project

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1291]
In order to avoid regressions introduced in the generated event sites on merging of PRs, we have decided to move to selenium testing to check the functionality of the site before merging of PR. To integrate it is a bit tricky since Selenium doesn't work natively on Travis CI and we have to use Sauce Labs (free for open source projects) for running the tests. The procedure is a bit convoluted but I managed to get it running on my fork.

Here is the link which describes a part of the procedure:
https://docs.travis-ci.com/user/gui-and-headless-browsers/

I will be working on this and add the support to the official repo. Thanks!!

**Comment by geekyd** [comment]
@Princu7 This is great!
