### ISSUE TITLE
Avoid dependencies on external services

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1292]
We have a dependency on the Google Api in the service without a real need, e.g. https://fonts.googleapis.com/css?family=Open+Sans:400,600,300 We could also use another font. The issue with this dependency is, that we are sharing our data without any need and if people are offline the browser tries to connect to the web for no apparent reason slowing down the page.

Please take out the dependency and implement another solution for the font.

**Comment by Princu7** [comment]
There are two things that we can do:-
* Replace the font with a different font.
* Try to implement a solution which enables us to use google font even when the website is being viewed offline.

The former option is simple while the latter would require some work to do. However, I feel that the current 'Open Sans' font looks really neat and aesthetic and a lot of other people use it too. So, I am kinda leaning towards the later option. I could be wrong though. Please guide. Thanks!!

**Comment by geekyd** [comment]
@mariobehling @Princu7 

If we are going to use open sans we can use
- [gulp-google-webfonts](https://github.com/battlesnake/gulp-google-webfonts) it will download the font while generation of web-app and create a .woff file for it.
- We can directly add .woff files using https://github.com/FontFaceKit/open-sans

**Comment by mariobehling** [comment]
The solution "Replace the font with a different font" or the idea of @geekyd both work for me. Just decide what you prefer.

**Comment by aayusharora** [comment]
@geekyd please proceed with saving it when the webapp is generated.

**Comment by mariobehling** [comment]
@Princu7 I am assigning this to you as @geekyd is focusing on other parts of Open Event. Please help to resolve this issue.
