### ISSUE TITLE
Code Formatting and Cleanup: Remove/Comment dead code areas and fix indentation

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1297]
**Actual behavior**
* The standard to be used is 2 spaces but there are many areas where 4 spaces or any other number of spaces are used. 
* There are many files with mixed indent.
*  There are parts of code where the control never reaches. Aka, the dead code.

**Expected behavior**
* No mixed-indent files.
* No dead code.
* Consistent indentation in all the files.

**Would you like to work on this issue?**
Yes. I am working on it.

**Comment by aayusharora** [comment]
Can you please Refactoring into consideration while doing this.
Also it will be better if we can follow some good guidelines for Refactoring code of the Generator so that it is easily maintainable.
You can open a separate issue for this.

**Comment by Princu7** [comment]
@aayusharora Sure. Actually, I have started working on the Selenium testing part. I will open an issue for it though and get to it as soon as I get some spare time. Thanks!!
