### ISSUE TITLE
Refactor Code of the Generator

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1300]
The code of the generator has grown in the size over the past few months. But there are very few comments in between, parts of it are repeated at times and some part of it is not used anymore which make it difficult to understand at first by a contributor. Also, the code seems to follow the old ES5 standard. It would be great if we could refactor the code of the generator, make it more easy to understand and adapt the code in accordance with the newer standards of the language.

**Comment by mariobehling** [comment]
This is low priority now and we need to focus on getting the project ready for more users. Please improve code-quality while working on issues continuously. We have limited resources in the web app and therefore refactoring it out of scope. Therefore closing it.
