### ISSUE TITLE
Fault in search algorithm in the generated website.

### ISSUE THREAD

**Issue by Lplenka** [fossasia/open-event-webapp#1304]
**Actual Behaviour**

The search in schedule, tracks, speakers & rooms pages is little faulty. The search algorithm is not working for few cases.

**Expected Behaviour**

The search should be very smooth and should work even if you correct the same search string which you wrote incorrectly.

**Steps to reproduce it**
I produced this error in FOSSASIA 2017 website. Here is the link [https://demolp.github.io/FOSSASIASummit/schedule.html](https://demolp.github.io/FOSSASIASummit/schedule.html)

1-If you search "Keynote", then you get the results as soon as you type till "Keyn" 
2-Obviously when you type "keynde", you won't get the results. 
3-Erase the added wrong characters such that search string becomes "Keyn", you still don't get results.
4- Complete the search string to "Keynote", you still don't get the output.

Here is the gif showing the error. Please open to see the error.

**Gif showing the error**

![errorinsearch](https://cloud.githubusercontent.com/assets/13533873/26691338/64e7eaf6-471a-11e7-85c9-714e92bade26.gif)

**Would you like to work on the issue?**
Yes, I have proposed a fix to this in PR #1303

**Comment by Princu7** [comment]
Thanks for opening this issue. The fun part is that I found it too and was about to report it but you were faster on this one. Hehe :smile:

**Comment by Princu7** [comment]
Thanks for the PR. Excellent work. Closing this now. Also, to automatically close an issue after merging of the PR, you can add special keywords like "Fixes #issueno" or "Closes #issueno". The format is to be closely followed otherwise the issue won't get closed. Thanks!! 
https://help.github.com/articles/closing-issues-via-commit-messages/
