### ISSUE TITLE
Provide an option to show sessions on its own page instead of expanding it

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1314]
This is a feature request, that could help us to get Mozilla using Open Event. So, there could be two ways to generate the web app:
a) A web app where the sessions expand as of now and
b) A web app where the sessions have their own page as in sched.org e.g. here: https://sanfranciscoallhandsjune2017.sched.com/

Please implement this in a way, that the user could choose this on the generators page through toggle or button.

**Comment by Princu7** [comment]
@mariobehling @aayusharora  @CosmicCoder96 @anu-007 @geekyd @harshitagupta30 @sumedh123 @utkarshnath

So, I have been thinking of ways on how can we do this. One of the options is to make a separate individual session template file. Then if the user has selected the option of a single page for each session, then we can generate HTML page for each single individual session by feeding the session object into the template and place all the pages generated into a separate folder named `session` for clarity. The name of the page can be given as 'session_(session_id)'. Now when the user clicks on the preview of the session on the different pages, we can directly send him to the dedicated page created for the session by looking up on its id.

Please guide on this. Any better options and alternatives? Thanks!!

**Comment by geekyd** [comment]
As the generated webapp is static in nature, the approach you have mentioned is the way to go. Thanks!

**Comment by Princu7** [comment]
@mariobehling @aayusharora @geekyd So I have been working on this for some time. I have created a basic prototype. Please check and suggest. Thanks:
* Provides a toggle option to select the type of session style: single or expanded
* If a single dedicated page for each session is created, then during the generation phase, HTML page for every single session is generated with all the correct links. Since the session can be large, they are saved inside of a folder named `session` rather than outside. They are saved with word "session" appended with the `ID` of the session.

Server: http://secure-meadow-20680.herokuapp.com
Singe Page Sesson Event:  http://princu7.github.io/open-event-webapp

**Comment by geekyd** [comment]
The single page is looking very good. Great work @Princu7.

**Comment by mariobehling** [comment]
Good job! Some improvements that are needed.

* The single page still has some link element in the heading (which is not a link)
* The scroll up button makes the page jump instead of smooth scroll
* The bookmark/start button does not work
* The share feature does not work
* Please make the rooms name into a link to the rooms list of the day
* Please make the tracks name into a link to the track of the day
* Sidebar menu does not work in mobile view

**Comment by aayusharora** [comment]
@Princu7 This is a good start.

- Have we thought about the zip size it will increase.
- Can we apply the same approach for speakers, which is the main requirement during the conference.

**Comment by Princu7** [comment]
@mariobehling Thanks for the review. Will make the changes you requested.

@aayusharora I tried this one on the FOSSASIA Summit. The zip size of the expandable session version was around 5 MB while the size of the single session page version was around 5.9 MB so not much of a difference I guess. Well, We can do the same for speakers but I haven't thought about it properly yet. Once we get this issue resolved, we would get to it next. Thanks!!

**Comment by aayusharora** [comment]
@princu7 ok, that sounds good.
