### ISSUE TITLE
scrolling behaves differently on speakers page.

### ISSUE THREAD

**Issue by SilentFlame** [fossasia/open-event-webapp#132]
Sometimes it works something similar to sessions like:
![right](https://cloud.githubusercontent.com/assets/9693795/13614184/454f8ee8-e595-11e5-966d-b6a6885b59d4.png)

but sometimes doesn't like :
![wrong](https://cloud.githubusercontent.com/assets/9693795/13614189/4a615556-e595-11e5-949f-e218b74cc607.png)

this all happens in alternate clicks on speakers tab on left.
also the top header of search by name and org should stay static while scrolling down.

**Comment by ashutoshsaboo** [comment]
@SaptakS @joerx @daminisatya @mariobehling @jig08 @AmayAgrawal @championswimmer I have pushed a PR - https://github.com/fossasia/open-event-webapp/pull/135 which resolves this issue. Could someone review the PR, please! Thanks! :smiley:
