### ISSUE TITLE
Highlight the current date for which schedule is showing

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-webapp#1323]
**Actual Behaviour**

Currently, the "schedule" tab doesn't distinguish between the dates whose schedule is clicked and visible at the moment from others, through colours. They look the same.

**Expected Behaviour**

When a particular date's schedule is being shown, that date should be highlighted or there should be some distinction like in "tracks" tab.

**Screenshots of the issue**

<img width="929" alt="screen shot 2017-06-09 at 5 01 31 pm" src="https://user-images.githubusercontent.com/21010060/26973820-d944f36e-4d35-11e7-8c81-d2767457035e.png">

**Would you like to work on the issue?**
No, @Princu7 shall be able to solve this I think.

**Comment by Princu7** [comment]
Closed via #1336
