### ISSUE TITLE
Default speaker image at present can be replaced for better visuals

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-webapp#1325]
**Actual Behaviour**

The current default speaker image is very dark and large and I think it doesn't look very appealing. Instead, it clutters the web page in a way with the magnified dark defaults all over the page.

**Expected Behaviour**

We should replace the defaults with something more subtle. for instance, we can use the following:-

![default_user](https://user-images.githubusercontent.com/21010060/26974591-a60d4998-4d39-11e7-9959-e15f637365f1.png)

Or we could also use the default images as speaker's initials like in mozilla event website:-

<img width="1184" alt="screen shot 2017-06-09 at 5 33 28 pm" src="https://user-images.githubusercontent.com/21010060/26974619-cb7828f6-4d39-11e7-8589-5589db89d366.png">
 This looks much more cluster-free and neat.

**Screenshots of the issue**
Currently:-

<img width="1274" alt="screen shot 2017-06-09 at 5 30 03 pm" src="https://user-images.githubusercontent.com/21010060/26974543-72eee5f8-4d39-11e7-931c-5c2cfd5a14a3.png">

**Comment by Lplenka** [comment]
Claiming this issue. Will work on this

**Comment by aayusharora** [comment]
@mahikaw We can't keep different placeholder images for different people. 
The app is generated by fetching the images from API or zip and replacing a single image for all as a placeholder if `image is not available`.

**Comment by mahikaw** [comment]
@aayusharora In that case, we shall replace it with this image?

![default_user](https://user-images.githubusercontent.com/21010060/26974591-a60d4998-4d39-11e7-9959-e15f637365f1.png)
