### ISSUE TITLE
Show complete schedule without filters (for all days) on start page of schedule/tracks/rooms page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1327]
Opening the app now shows only the schedule for the first days. There is a filter set, that results in the display of the first day only. Only show days for one day once a filter has been set - meaning when the user clicked on a specific day.

Ensure the same implementation on the pages
* Schedule
* Rooms
* Tracks

Compare: https://fossasia.github.io/open-event-webapp/schedule.html

**Comment by Lplenka** [comment]
@mariobehling claiming this issue, I will work on this.

**Comment by Princu7** [comment]
@lplenka Thanks so much. I have almost completed work on it. Please claim another issue :grinning: Thanks!!

**Comment by Lplenka** [comment]
Okay :grin:
