### ISSUE TITLE
Search fields: "Search" text does not have space to border

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1329]
Please ensure the "Search" text in the search fields across the apps have some spacing between the text and the border.

![screenshot from 2017-06-09 15-52-21](https://user-images.githubusercontent.com/1583873/26978422-cbffdd5e-4d2b-11e7-9dcc-e0adb2295653.png)

**Comment by Lplenka** [comment]
@mariobehling claiming this issue. Will improve the search box UI.
