### ISSUE TITLE
Speakers view all cards doesn't feel like clickable.

### ISSUE THREAD

**Issue by chanakaDe** [fossasia/open-event-webapp#133]
When we move cursor on the speakers card, it's just normal cursor. Not the clickable pointer icon.
Have to change

**Comment by chanakaDe** [comment]
Fix the issue and made a pull request

**Comment by SilentFlame** [comment]
@chanakaDe I guess this is done, have a look again, and please close the issue if it works as you expect.

**Comment by aayusharora** [comment]
@championswimmer , its already done and can be closed.
