### ISSUE TITLE
Sponsor name and type not visible along with the sponsor icons

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-webapp#1337]
**Actual Behaviour**
Only the sponsor icons show up, and so when there aren't any sponsors a white space comes up in the middle of other sponsors

**Expected Behaviour**

 

- [x] Names of the sponsors should also be displayed, so that in case of no sponsor image, it doesn't leave behind an awkward white space in the middle.

- [ ] There should be different sections/divisions made for distinct sponsor types.

**Screenshots of the issue**

Currently:-
<img width="1233" alt="screen shot 2017-06-12 at 11 23 08 pm" src="https://user-images.githubusercontent.com/21010060/27066699-a8336a3a-5023-11e7-8628-03e35a4ca8c7.png">

An example for showing up distinct sponsors:-
<img width="1128" alt="screen shot 2017-06-13 at 10 35 21 am" src="https://user-images.githubusercontent.com/21010060/27066761-0870cef6-5024-11e7-89d1-d33da6cb8b0b.png">

**Would you like to work on the issue?**
Yes.

**Comment by aayusharora** [comment]
@mahikaw We were using `Bootstrap tooltip` for mentioning Platinum and Rhodium sponsors.
On hover, it will show us the type of sponsor.
Please go ahead :)

**Comment by mahikaw** [comment]
@aayusharora Wouldn't it be better to classify the sponsors on the basis of their type, beforehand like in the above screenshot that I have provided?

**Comment by mariobehling** [comment]
@mahikaw As we see on some of the larger new examples dedicated sections for different sponsor levels seems a better solution. So, please proceed.

**Comment by aayusharora** [comment]
@mahikaw Any updates?

**Comment by mahikaw** [comment]
@aayusharora I am sorry I was busy with the samples. I will be working on the pending issues in this repo today.
