### ISSUE TITLE
Some bugs in webapp

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-webapp#1345]
**Actual Behaviour**

- Event links on Instagram are not supported.

- The "position" of speakers should appear under the image of the speaker along with the organisation.

**Screenshots of the issue**

<img width="1238" alt="screen shot 2017-06-17 at 10 54 46 pm" src="https://user-images.githubusercontent.com/21010060/27255004-3ff97864-53b2-11e7-8373-260f3b6267b4.png">

**Comment by Princu7** [comment]
@mahikaw The issues have been resolved. Please check and close it. Thanks :)
