### ISSUE TITLE
Scaling speaker images 

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-webapp#1346]
**Actual Behaviour**

Currently, of the image ratio is not 1:1, they appear with a black background to make them of that ratio.
This leads to improper scaling of images which doesn't look very nice.
<img width="1049" alt="screen shot 2017-06-18 at 3 05 33 pm" src="https://user-images.githubusercontent.com/21010060/27259747-a58ba8fc-5437-11e7-817c-eb103052be38.png">

**Expected Behaviour**

We could either stretch the image or add a black background.

-----
@mariobehling @aayusharora @princu7 Please give in your suggestions.

**Comment by mariobehling** [comment]
This is out of scope of the web app. The source files should be already scaled accordingly. Therefore closing it.
