### ISSUE TITLE
Add custom domain CNAME for gh-pages sched.eventyay.com

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1354]
Instead of the current custom domain, please use: sched.eventyay.com

@niranjan94 Please assist to redirect the subdomain CNAME to GitHub.

**Comment by niranjan94** [comment]
Will do @mariobehling

**Comment by niranjan94** [comment]
CNAME created (https://github.com/fossasia/open-event-webapp/commit/3a3d24bc2efcc4d86a0566c7112a7b13cf38294f) and DNS record updated. Will go live in a few mins. (Standard DNS propagation time)

**Comment by niranjan94** [comment]
@mariobehling http://sched.eventyay.com is live.
