### ISSUE TITLE
position of `Day-bar` is not proper when open in android.

### ISSUE THREAD

**Issue by SilentFlame** [fossasia/open-event-webapp#136]
It looks and works all-right when in `portrait` like:
![screenshot_2016-03-10-03-03-25](https://cloud.githubusercontent.com/assets/9693795/13651877/53f06118-e66f-11e5-93d3-6a5a42888ffe.png)
![screenshot_2016-03-10-03-03-43](https://cloud.githubusercontent.com/assets/9693795/13651876/53eb14ce-e66f-11e5-9f1e-4b087683779b.png)

but the day bar starts to come in center when used in `landscape` mode like :
![screenshot_2016-03-10-03-02-31](https://cloud.githubusercontent.com/assets/9693795/13651901/718ab9b2-e66f-11e5-9869-5b463bf2ff94.png)
![screenshot_2016-03-10-03-02-52](https://cloud.githubusercontent.com/assets/9693795/13651900/71893272-e66f-11e5-923a-205b98e5f5ee.png)

@mariobehling @sudheesh001 @Orbiter 
Is this an intentional feature or a bug?

**Comment by aayusharora** [comment]
@SilentFlame , not having this problem on my end .
Tested on : Nexus 5 , Samsung Galaxy and some more.
I am not sure if it is particular to one handset(less probable).
Check the new code once.

**Comment by aayusharora** [comment]
@SilentFlame ,update?

**Comment by SilentFlame** [comment]
@aayusharora now the `session` section doesn't display any information only the `search by tile` and `search by Speaker` is visible here.
can you please have a look and let me know.

**Comment by aayusharora** [comment]
@SilentFlame , looking fine here 
![screenshot_2016-04-10-16-32-05](https://cloud.githubusercontent.com/assets/12194719/14409898/dfbf4998-ff3d-11e5-8796-6c5b6adc8709.png)
