### ISSUE TITLE
The look of the test version not reflected on the main github repo.

### ISSUE THREAD

**Issue by SilentFlame** [fossasia/open-event-webapp#137]
I just fetched from upstream.
Its is not like as of the test version.
The test version looks something like this:
![test_version](https://cloud.githubusercontent.com/assets/9693795/13829243/f43dd606-ebeb-11e5-86f5-b37b096ef542.png)

and the main app looks like. 
![session](https://cloud.githubusercontent.com/assets/9693795/13829254/0b153748-ebec-11e5-8f51-20deaa58e31a.png)

I'm updating the changes.

**Comment by aayusharora** [comment]
@SilentFlame ,we can select the color and logo which seems changed, also there is uneven styling in the hosted app which I have already marked on gitter few days earlier
All are aware about it .

**Comment by SilentFlame** [comment]
@aayusharora 
That sounds great. so need to close It I guess.
Thanks

**Comment by aayusharora** [comment]
@SilentFlame ,yes :)

**Comment by SilentFlame** [comment]
@aayusharora so are all aware of the functionalities missing which are visible in the test version.?

like social links and all.

**Comment by aayusharora** [comment]
@championswimmer ?

**Comment by championswimmer** [comment]
The test version is built from fossasia16 branch 

I am setting it back to master

**Comment by SilentFlame** [comment]
would be better for us to test.
@championswimmer  is loklak.org is down from last few hours?

**Comment by aayusharora** [comment]
@SilentFlame ,the issue is same as of #154 , and will be resolved after  #156.This can be closed.

**Comment by championswimmer** [comment]
I'm thinking I'll deploy to bitballoon or something like that.

Force pushing to github pages is little hacky from Travis

**Comment by aayusharora** [comment]
@championswimmer , agree , I have tried it now for my personal project, it worked like a charm .

**Comment by championswimmer** [comment]
made manual update. working on travis+bitballoon now.
