### ISSUE TITLE
Back button on Single track pages

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1376]
There should be a back button on top left of individual track pages which leads to the main track page.

**Comment by Siddhant2016** [comment]
Can I start to work on this?

**Comment by geekyd** [comment]
@Siddhant2016 Sure go ahead :+1:

**Comment by Princu7** [comment]
@Siddhant2016 Web App Generator has two modes of generating the sessions which we can specify in the generator form. One is in the expandable session mode (in which all the sessions are displayed on a single page and we can click on them to expand them on the same page and get more detail). Like the one for this event
https://sched.eventyay.com/FOSSASIASummit/tracks.html

And the other one is the single session mode (in which all the sessions have a unique individual page for themselves. If we click on one the preview of them present on the tracks, rooms, schedule pages, the dedicated page for them will open). Like the one for this event
https://sched.eventyay.com/MozillaAllHands2017/tracks.html

The issue which I think is that we have to provide a back button for these above individual sessions. I am not entirely sure though. @geekyd @aayusharora Please confirm. Thanks!

**Comment by ansh-ptel** [comment]
@Siddhant2016 we have to enable the back button event in Web App Generator.
