### ISSUE TITLE
Recent sponosr and track list alignment changes are causing some UI issues

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1381]
After the recent changes made, some UI issues have appeared.
**Old**
![old](https://user-images.githubusercontent.com/8847265/27769323-e2adfed4-5f44-11e7-923a-33978723adaa.gif)

**New**
![new](https://user-images.githubusercontent.com/8847265/27769333-09cb09e4-5f45-11e7-88ba-4f107e0071a1.gif)

* The sponsor name should come underneath the image. But, it is appearing on the top of another sponsor which doesn't look good
* The text of the Map has become bold while it was normal font before
* The Track name list doesn't appear on the tracks page when we visit the site. It appears at the very end of the page.

@mahikaw Can you please look at these issues. Thanks :)

**Comment by aayusharora** [comment]
This is urgent. @mahikaw Please look into this.
