### ISSUE TITLE
unable to load data using new twitter wall 

### ISSUE THREAD

**Issue by SilentFlame** [fossasia/open-event-webapp#141]
@aayusharora can you please explain why such thing is happening.? have a look at the screenshot.
![shot](https://cloud.githubusercontent.com/assets/9693795/13891108/2ed293bc-ed75-11e5-942f-26683c7e479c.png)

**Comment by SilentFlame** [comment]
seems loklak.org is also down.

**Comment by aayusharora** [comment]
@SilentFlame , error solved , Check and close this :)

**Comment by SilentFlame** [comment]
@aayusharora sorry but the error still persists.
![shot](https://cloud.githubusercontent.com/assets/9693795/13931268/8c3afc10-efc8-11e5-999a-a4526e8aab8a.png)

would you like some help here? as I was also working on the web-app only. :)

**Comment by aayusharora** [comment]
@SilentFlame ,new code is not hosted , try running in your local.

**Comment by SilentFlame** [comment]
ok thanks.

**Comment by aayusharora** [comment]
@SilentFlame ,can we close this ?

**Comment by SilentFlame** [comment]
@aayusharora  yes.

**Comment by aayusharora** [comment]
@SilentFlame , Check this hosted one http://aayusharora.github.io/ , if it is working fine we can close it.
