### ISSUE TITLE
Add dependency for raven module in documentation

### ISSUE THREAD

**Issue by ihsavru** [fossasia/open-event-webapp#1418]
After the last commit, there is a need to install raven module when I tried to locally run the app using
`npm run start`

Therefore, I think we should add 
`npm install --save raven`
in the documentation for instructions on how to install on local machine.

Screenshot:
![screenshot from 2017-07-25 14-58-46](https://user-images.githubusercontent.com/22816171/28565623-62a097f2-714a-11e7-82ea-1c57375aa8ee.png)

**Comment by niranjan94** [comment]
Already part of `package.json`. You just need to run `npm install`
