### ISSUE TITLE
Integrate ICS download into download button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1438]
We already have a download button. All download should be integrated there. Simply convert this button and offer a dropdown menu with a) ics Download and b) png Download.

![screenshot from 2017-08-15 11-44-37](https://user-images.githubusercontent.com/1583873/29310848-ba02ba50-81af-11e7-95e1-27416e5a9576.png)

**Comment by Princu7** [comment]
Solved!
