### ISSUE TITLE
Instead of "Starred" use icons

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1445]
Instead of using show "starred" use icons:
* To show all starred sessions in the UI show a filled black icon
* To show all sessions in the UI show an icon which is unfilled
![ui-39-512](https://user-images.githubusercontent.com/1583873/29453927-acb383bc-840b-11e7-90a4-25356cb0432f.png)

**Comment by agbilotia1998** [comment]
Can I work on this?

**Comment by Princu7** [comment]
Sure. Go ahead @agbilotia1998 Thanks :)

**Comment by aayusharora** [comment]
@mariobehling  @Princu7 the star icon is already used to mark favorite sessions.

UX Inconsistencies
- It will be confusing for the user to identify starred and favourite sessions.
