### ISSUE TITLE
Mail send with a wrong download link to the user when the cloud upload of the event folder fails

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1452]
I mentioned this on this [PR](https://github.com/fossasia/open-event-webapp/pull/1451)  but opening a new issue for it now. This is the workflow-
* We generate the event folder and then upload to the cloud storage and get the URL of the uploaded folder.
* We then mail the user about the generated event which also contains a link to the uploaded event folder.

The question is what should we do when the upload to the cloud upload fails? Directly sending the mail to the user does not make sense since the download location of the uploaded event folder will be null.

So, we have two options maybe:-

* Don't send a mail to the user if the cloud upload fails.
* Send a different email telling that the cloud upload has failed and present the user the download link of the event folder currently present on the Heroku app itself along with the warning that it will expire within few hours.

Thoughts @aayusharora @geekyd @harshitagupta30 @agbilotia1998

**Comment by agbilotia1998** [comment]
@Princu7 I think it would be good if we send a different mail mentioning the cloud upload failure and providing download link of event folder on heroku.
