### ISSUE TITLE
Make the design of the live showcase site more closer to eventyay

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1459]
Make the display of the live showcase site https://sched.eventyay.com more closer to the front page of the httpa://open-event-frontend.herokuapp.com/

Screenshots:-
* Eventyay
![screenshot from 2017-08-25 16-34-36](https://user-images.githubusercontent.com/8847265/29711632-5a23f73c-89b3-11e7-92c7-8a5c9f70420b.png)

* Sched
![screenshot from 2017-08-25 16-35-38](https://user-images.githubusercontent.com/8847265/29711646-774235ae-89b3-11e7-98ed-732ce74e2b53.png)

**Comment by dhruv-dj** [comment]
I would like to work on this.

**Comment by geekyd** [comment]
@dhruv-dj Please go ahead!

**Comment by dhruv-dj** [comment]
Just a confirmation, eventyay should look more like open even home screen right? Not the other way round?
@geekyd

**Comment by geekyd** [comment]
@dhruv-dj It is the other way, the Open event web app should look more like the open event frontend.

**Comment by jajodiaraghav** [comment]
Claiming this issue as no update was made for a month.

**Comment by mariobehling** [comment]
The last PR is a good progress, but the issue is not solved entirely. Please make it closer to eventyay.

**Comment by hereisprabhat** [comment]
@mariobehling @geekyd I want to work on this. Please tell me how to proceed, as I am new to this project.
