### ISSUE TITLE
Error in expiry time of preview link sent through email

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1463]
**Actual Behaviour**

The email received shows wrong expiry time of preview link.Checkout the screenshot I created this webapp at 3:30 pm(IST). It shows expiry time to be 11:00 am.

**Expected Behaviour**
Correct expiry time should be sent via email.

**Steps to reproduce it**
Generate the webapp,notice the expiry time received in email.

**Screenshots of the issue**

![1](https://user-images.githubusercontent.com/21157929/29740521-f227b740-8a75-11e7-805b-a312fb1843c7.jpg)

**Comment by agbilotia1998** [comment]
@Princu7 @aayusharora please guide on this issue as on my localhost the preview expiry time is shown correctly as 5:00 pm.It may be that current time that it is getting is depending on server.But I guess the current time should of the place from where the app is created.

**Comment by Princu7** [comment]
@agbilotia1998 Thanks for pointing it out! Looking into this issue :+1:

**Comment by utkarsh-dixit** [comment]
@Princu7 I would like to work on this issue but i can't self assign any issues right now. Can you assign me to this issue ?
