### ISSUE TITLE
Fix sessions in speakers field for single page config

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1467]
**Actual Behaviour**
When the user clicks on the a session from speakers page it takes the user to tracks page in case of single session page events

**Expected Behaviour**
The sessions on speakers page should open in separate session page like in schedule page.

**Comment by stellargo** [comment]
@geekyd I understand the issue, would like to work on it. Could you assign it to me? or add me so I can self assign it?

**Comment by geekyd** [comment]
@stellargo Please go ahead.
