### ISSUE TITLE
Fix overflowing text in calendar view on schedule page

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1470]
**Actual Behaviour**
![screen shot 2017-09-20 at 12 40 18 am](https://user-images.githubusercontent.com/12807846/30610629-6820f2ca-9d9c-11e7-9886-31cba78dc086.png)

**Expected Behaviour**
The text should not overflow outside the session.

**Comment by shubhshrma** [comment]
I understand the issue and would like to take this up.It will be a good introduction to the project.

**Comment by zamhaq** [comment]
@geekyd could you assign this to me?

**Comment by geekyd** [comment]
@zamhaq Please coordinate with @shubhshrma as he has already claimed the issue.

**Comment by shubhshrma** [comment]
Yeah @zamhaq if you want we can work together but i won't like to leave this as I already started on it and it seems solvable as a newcomer.

**Comment by zamhaq** [comment]
@shubhshrma Its ok. You can work on it then.

**Comment by shubhshrma** [comment]
@geekyd do we want the text in all boxes (in calendar view of schedule) to be  only a single line and hide all overflowing text after ```...``` ? This would amount to majority of box space remain empty.

**Comment by mariobehling** [comment]
The first PR resulted in the disappearance of most of the text as "...". The implementation is not how it is supposed to be. If there is enough space there should be a line break - as it was before. I am reopening this issue therefore.
