### ISSUE TITLE
Add favicon to the generated web app

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1471]
**Actual Behaviour**
Currently there is no favicon in the generated web app

**Expected Behaviour**
The generated web app should have a favicon which is the logo of the organisation.

@Princu7 @mariobehling @aayusharora What do you think about this?

**Comment by zamhaq** [comment]
@geekyd Can I work on this ?

**Comment by geekyd** [comment]
@zamhaq Please go ahead!

**Comment by zamhaq** [comment]
@geekyd  The link for favicon.ico is already present in the `event.hbs` file. 
```
<link rel="shortcut icon" href="{{ eventurls.ico_url }}" type="image/x-icon" />
```
It seems `eventurls.ico_url` might not be correct

**Comment by geekyd** [comment]
@zamhaq Thanks for pointing out, seems like the favicon is not getting generated by the server or is missing in the event zips.
