### ISSUE TITLE
Schedule: Hide horizontal scroll when there are 3 or less columns

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1472]
**Actual Behaviour**
![screen shot 2017-09-28 at 5 12 59 pm](https://user-images.githubusercontent.com/12807846/30964793-71b0ca60-a470-11e7-9525-382a6eaa5051.png)

**Expected Behaviour**
There should be no horizontal scroll when the number of columns are 3 or less

**Comment by Roshanjossey** [comment]
@geekyd: I'd love to take this up and solve it

**Comment by lapmid** [comment]
@Roshanjossey hey can you please tell me in which file are you making changes

**Comment by Roshanjossey** [comment]
@lapmid, I haven't started yet. I was waiting for confirmation. You can take this up if you're interested

**Comment by aayusharora** [comment]
@Roshanjossey You can go ahead with this.

**Comment by Rahmeen14** [comment]
Hi! I am new to open source and would like to take this issue up if nobody else is working on it currently.
Thank you!

**Comment by highskillzz** [comment]
Started solving or can I take this up?

**Comment by geekyd** [comment]
@highskillzz I think you can go ahead with this.
