### ISSUE TITLE
Use of icon instead of starred on tracks and rooms page like schedule page.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1488]
Use of icon instead of starred on tracks and rooms page like schedule page.
![screenshot from 2017-10-07 00-25-42](https://user-images.githubusercontent.com/21157929/31293795-2a8cd41c-aaf6-11e7-9d3e-53ec14a43a19.png)

**Comment by yashrsharma44** [comment]
Do you mean to convert the stars to the circled icons on the right ?

**Comment by agbilotia1998** [comment]
@yashrsharma44 look at the screen shot there is a star icon beside search box, this is only on schedule page , it should be implemented on tracks and rooms page also where we have a button with text "Starred".
