### ISSUE TITLE
Add support to push notification

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1489]
We have currently service workers added for caching , we should implement support for push notifications too.

**Comment by geekyd** [comment]
@agbilotia1998 That's a great suggestion. Please propose an approach to this feature.

**Comment by S2606** [comment]
Claiming this issue since no response..

**Comment by agbilotia1998** [comment]
@geekyd for push notifications we would be needing a server side support should we use open-event-orgaserver or our own open-event-webapp one.Please give your suggestions.

**Comment by geekyd** [comment]
We need the server support from open-event-orga-server. Lets put this one for hold now until the server is stable.

**Comment by mariobehling** [comment]
Before we add new features we need the basics to work.
