### ISSUE TITLE
Displaying a message upon upload completion

### ISSUE THREAD

**Issue by invinciblycool** [fossasia/open-event-webapp#1490]
**Actual Behaviour**

As of now no message is displayed upon completion of an upload of a zip.

**Expected Behaviour**

It would be better, if a message is displayed maybe saying "Upload complete" to ensure that the upload has been finished and the button to Generate Webapp can be clicked.

**Steps to reproduce it**

Try uploading any zip.

**Would you like to work on the issue?**
 Yes!!

**Comment by ItachiUchiha1998** [comment]
I will like to contribute to this issue .. if cool?

**Comment by ItachiUchiha1998** [comment]
Can u help me to run it locally? 
while running npm install  : Unexpected end of input at 1:5623
npm ERR! ctories":{},"dist":{"shasum":"a7ec4ca8779378f6b2627ba342f529c8d118719

while using command npm run install its showing : Cannot find module 'connect-domain'

**Comment by invinciblycool** [comment]
Actually the chat room is more appropriate for these kind of questions. Try posting the error log there.
https://gitter.im/fossasia/open-event-webapp

**Comment by agbilotia1998** [comment]
@mariobehling please close this as it is fixed now with PR #1494 being merged.

**Comment by invinciblycool** [comment]
@agbilotia1998 Can I close it. Actually I opened it. :smile:

**Comment by invinciblycool** [comment]
Closing as #1494 fixes this.
