### ISSUE TITLE
Add favicon to event overview page

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1495]
**Actual Behaviour**

Favicon is missing for https://sched.eventyay.com/

**Expected Behaviour**
Add favicon to https://sched.eventyay.com/. Reference file : https://github.com/fossasia/open-event-webapp/blob/development/src/backend/overviewSite/index.html

**Comment by lapmid** [comment]
@geekyd is it open still

**Comment by saurabh30** [comment]
@geekyd is it open still?

**Comment by agbilotia1998** [comment]
@saurabh30 the issue is still open but a pull request is already opened for this..
