### ISSUE TITLE
index.html: Only provide version link not id

### ISSUE THREAD

**Issue by stellargo** [fossasia/open-event-webapp#1509]
**Actual Behaviour**

The whole commit id is being displayed in the latest version.

**Expected Behaviour**

There is no need to display the id, instead only providing the link to open the github source code should be fine.

**Screenshots of the issue**

![screen shot 2017-10-19 at 6 09 51 pm](https://user-images.githubusercontent.com/27735438/31771196-cd5e87ec-b4f8-11e7-96c2-ca981a30968d.png)

**Would you like to work on the issue?**

Yes

**Comment by mariobehling** [comment]
Please see my comments in the PR and open a new issues taking this into account.
