### ISSUE TITLE
Sponsor tab getting twitterwall error

### ISSUE THREAD

**Issue by PMArtz92** [fossasia/open-event-webapp#151]
![capture](https://cloud.githubusercontent.com/assets/11062030/14009545/f25a1a9e-f1b2-11e5-8275-0128e66c1808.PNG)

Anyone know about this??

**Comment by aayusharora** [comment]
@PMArtz92 ,sorry for the late reply , I am running the same fine on my local machine.

**Comment by aayusharora** [comment]
@PMArtz92 , By seeing your error ,I can suggest you to
1. Check if oe.twitterwall is present in your app.js.

**Comment by PMArtz92** [comment]
@aayusharora ill check that :)

**Comment by aayusharora** [comment]
@PMArtz92 , is it good to close ?

**Comment by aayusharora** [comment]
check this http://aayusharora.github.io/

**Comment by aayusharora** [comment]
@championswimmer , You can close this ,if it seems go to close.

**Comment by PMArtz92** [comment]
yes this is fine, sorry i was away from computer.
