### ISSUE TITLE
Fix travis for the application

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1512]
**Actual Behaviour**
The travis build is failing for each PR. Please check https://travis-ci.org/fossasia/open-event-webapp/builds/290453248?utm_source=github_status&utm_medium=notification

**Expected Behaviour**
The travis must pass for each build.

This is a known issue in travis :
```
No output has been received in the last 10m0s,
this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by shubhshrma** [comment]
I'd like to work on it.
