### ISSUE TITLE
Add feature to add the event to calendar

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1513]
**Actual Behaviour**

Currently the user can not add the event to his/her calendar

**Expected Behaviour**

Lets add a feature where the user can add the event to the calendar. 
There are many ways in which we can have this feature, I'm listing some here:
1. Provide a single button to add the event to the calendar
2. Add feature to add individual session to the calendar

@mariobehling @Princu7 @aayusharora Please share your thoughts about this. Please feel free add more information if I missed something.

**Comment by highskillzz** [comment]
I would like to take this up.

**Comment by geekyd** [comment]
@highskillzz Please go ahead!

**Comment by abishekvashok** [comment]
@highskillzz are u still working on it. @geekyd @highskillzz can I work on this pls?

**Comment by highskillzz** [comment]
@abishekvashok I havent started working on it as I have exams now but by all means do take it up.

**Comment by abishekvashok** [comment]
Ok then work it :)

**Comment by shubham3211** [comment]
I would like to work on this.

**Comment by tech4GT** [comment]
Is someone working on this or i can i claim?

**Comment by highskillzz** [comment]
Plz do

**Comment by tech4GT** [comment]
Can you please also tell me where should i place the button?😅

**Comment by tech4GT** [comment]
@geekyd as of now the app does provide download as ics option so can you please clarify what exactly needs to be done?

**Comment by agbilotia1998** [comment]
I am working on this.

**Comment by agbilotia1998** [comment]
Added this feature in #1967, closing this issue.
