### ISSUE TITLE
Translations needed for JSON definition list of all repos and filemasks, so they can be imported to weblate 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event-webapp#1514]
[https://github.com/fossasia/labs.fossasia.org/issues/231](https://github.com/fossasia/labs.fossasia.org/issues/231)

Please refer to this issue for more info.

**Would you like to work on the issue?**

no

**Comment by isuruAb** [comment]
@ParthS007 please add the issue here. poster URL is not working.

**Comment by ParthS007** [comment]
@isuruAb Now the link is working

**Comment by shubhshrma** [comment]
@ParthS007 Does this still needs work?

**Comment by geekyd** [comment]
@ParthS007 Any updates, Is this issue still there?

**Comment by agbilotia1998** [comment]
@geekyd @ParthS007 is the issue still there?

**Comment by ParthS007** [comment]
The parent issue is closed now so closing this :+1:
