### ISSUE TITLE
UX issue : Binding Variables without Data Binding

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#152]
![123](https://cloud.githubusercontent.com/assets/12194719/14053771/b31e5028-f2f9-11e5-8121-4d957c7756a3.png)

**Comment by aayusharora** [comment]
Whenever the webapp loads , for some fraction of seconds this comes up ( snap shot above)

**Comment by championswimmer** [comment]
Let it be. No possible solution, because we have to take name from config
file

**Comment by aayusharora** [comment]
@championswimmer ,Check this #153
We can not do it for the page title but yes we can stop angular to show its data-binding till it binds the variables using ng-cloak.

**Comment by aayusharora** [comment]
@championswimmer , I have changed the PR #153 , now changes are in main.css.
I can close this issue after the review of the PR .

**Comment by aayusharora** [comment]
Closing it , its merged :)
