### ISSUE TITLE
Travis Build is showing error

### ISSUE THREAD

**Issue by aashutoshrathi** [fossasia/open-event-webapp#1520]
**Actual Behaviour**

Travis Build showing error

**Expected Behaviour**

Travis needs to be relinked with repository

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Log for the issue**

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.
![image](https://user-images.githubusercontent.com/21199234/32360906-2d0e4528-c080-11e7-8820-c8fb3ff94c66.png)

**Would you like to work on the issue?**

I think maintainer can link Travis only.

**Comment by geekyd** [comment]
@aashutoshrathi Thanks for reporting this. There is already an issue opened for this #1515. 
Closing this
