### ISSUE TITLE
Webapp menu should close if clicked outside the menu container

### ISSUE THREAD

**Issue by jajodiaraghav** [fossasia/open-event-webapp#1524]
**Actual Behaviour**
Webapp menu does not close if clicked outside the menu container

**Expected Behaviour**
Webapp menu should close if clicked outside the menu container

**Steps to reproduce it**
Click the Menu Icon on Navbar. Menu Opens. Click anywhere outside the menu.

**Log for the issue**

Provide console logs for the issue here

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
Yes
Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by ItachiUchiha1998** [comment]
i would like to work on it.

**Comment by jajodiaraghav** [comment]
@ItachiUchiha1998 I have already claimed this issue

**Comment by ItachiUchiha1998** [comment]
ya ok .. i have already resolved the issue though.

**Comment by jajodiaraghav** [comment]
Me too
