### ISSUE TITLE
Updation of URL links and logo of other projects in Menu item

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event-webapp#1530]
**Actual Behaviour**

Presently the URL links and logo of items in menu item is outdated

**Expected Behaviour**

URL Links and logo should be updated

**Screenshots of the issue**
![screenshot-2017-11-22 webapp generator](https://user-images.githubusercontent.com/24358501/33099744-ea2508f2-cf37-11e7-8eaf-a9460ab3030b.png)

**Would you like to work on the issue?**

Yes

**Comment by pandyamarut** [comment]
I would Like to work on this issue.
please provide me the path to file so i can access easily and look into the issue.
thanks!
