### ISSUE TITLE
Addition of container to couple all the UI elements

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event-webapp#1532]
**Actual Behaviour**

Presently there is no container used .

**Expected Behaviour**
After addition of container, UI will look clean

**Would you like to work on the issue?**
Yes

**Comment by knrt10** [comment]
Yes . Would you please direct me to the files .

**Comment by ParthS007** [comment]
I am working on this Issue @knrt10

**Comment by duttaditya18** [comment]
@ParthS007 Can I work on this? What exactly needs to be done in which page?

**Comment by geekyd** [comment]
@ParthS007 Any updates?

**Comment by duttaditya18** [comment]
@geekyd I will start to work on this. Can you tell me what exactly needs to be done in this issue?

Sorry for being late.

**Comment by geekyd** [comment]
@duttaditya18 Sure! @ParthS007 Can you please elaborate ?

**Comment by ParthS007** [comment]
@duttaditya18 Please see this https://badgeyay-dev.herokuapp.com/ . All the elements in this are container , same thing should be in open-event-webapp.

**Comment by duttaditya18** [comment]
@ParthS007 So a box container? All right! I am on it!
