### ISSUE TITLE
Add Feature to make RadioButton Labels clickable.

### ISSUE THREAD

**Issue by knrt10** [fossasia/open-event-webapp#1535]
**Actual Behaviour**

These Labels are not clickable
<ul>
<li><strong>Choose Session Style</strong> <br/>
     <ul>
         <li>Single</li>
          <li>Expandable</li>
    </ul>

</li>
<li><strong>Choose your data source</strong>
     <ul>
         <li>Upload your own JSON files</li>
          <li>API endpoint of event on OpenEvent
</li>
    </ul>
</li>
</ul>

**Expected Behaviour**

These Labels should be clickable.

**Would you like to work on the issue?**

Yes

**Comment by duttaditya18** [comment]
On it!

**Comment by himanish-star** [comment]
@knrt10 are u still working on this issue . If yes I'll remove my PR

**Comment by knrt10** [comment]
@himanish-star  I already did it .
