### ISSUE TITLE
Overview page design columns broken

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1557]
Please help to fix the column break in some resolutions.

![screenshot from 2017-12-21 13-25-53](https://user-images.githubusercontent.com/1583873/34255787-8e65c48e-e652-11e7-89ff-d8d71217542a.png)

**Comment by agbilotia1998** [comment]
@mariobehling I think its fixed in #1556

**Comment by geekyd** [comment]
Closing this issue.
This issue was resolved in #1556
