### ISSUE TITLE
Making Open Event Webapp a PWA

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1567]
The screenshot of lighthouse audit suggests that we are not ready for a PWA.

We need to work on the following issues step by step to increase the score for PWA and to get closer to PWA checklist.

![screen shot 2017-12-24 at 5 39 40 pm](https://user-images.githubusercontent.com/12194719/34326420-755d46ac-e8d1-11e7-84f1-ee61af0a2f71.png)

**Comment by ParthS007** [comment]
@aayusharora  I want to work on it, Can you tell me how to proceed?

**Comment by ParthS007** [comment]
@aayusharora  I found a resource related to it, Can we have to go through this [Checklist](https://developers.google.com/web/progressive-web-apps/checklist)

**Comment by agbilotia1998** [comment]
@aayusharora please review #1549 it adds manifest.json to open event webapp.

**Comment by agbilotia1998** [comment]
@ParthS007 @mariobehling we can close this, as open event webapp is now a PWA.
