### ISSUE TITLE
problems with twitterwall layout

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#158]
![screenshot from 2016-04-08 04 42 53](https://cloud.githubusercontent.com/assets/1327050/14369799/8f675d86-fd45-11e5-8985-efbbf17fd019.png)

Doesn't look good. and only one row.

**Comment by aayusharora** [comment]
@championswimmer , I have checked that , it's working fine . Can you please check it once again may be the loklak server was slow at that time to return the response.

**Comment by aayusharora** [comment]
![1](https://cloud.githubusercontent.com/assets/12194719/14374900/1b341312-fd79-11e5-8e8d-b5912126b72c.png)

**Comment by aayusharora** [comment]
@championswimmer ,any update?

**Comment by aayusharora** [comment]
@championswimmer , After checking again and again ( 1 out of 20 attempts), I got the same error as you 
got , it seems a loklak error , any idea how to remove it.

![1](https://cloud.githubusercontent.com/assets/12194719/14412422/2073c35a-ff80-11e5-932d-e69a301630f8.png)
