### ISSUE TITLE
Theme selection not working.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1581]
**Actual Behaviour**

Light and Dark theme selection not making any difference.

**Expected Behaviour**

The generated webapps should differ depending on theme selection.

**Would you like to work on the issue?**

Yes.

**Comment by geekyd** [comment]
@agbilotia1998 This is a duplicate of https://github.com/fossasia/open-event-webapp/issues/1220

**Comment by agbilotia1998** [comment]
Oh okay! Closing this as #1220 is already opened.
