### ISSUE TITLE
Generator page not visible when hovering over email choices on page.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1591]
**Actual Behaviour**

Generator page not visible when hovering over email choices on page.

**Expected Behaviour**

Generator page should be visible on hovering.

**Comment by abishekvashok** [comment]
@agbilotia1998 are you working on it?

**Comment by agbilotia1998** [comment]
You can work on this.

**Comment by abishekvashok** [comment]
Thanks @agbilotia1998

**Comment by abishekvashok** [comment]
Bug preview
![screenshot_20180108_174939](https://user-images.githubusercontent.com/8947010/34670543-cf8203ee-f49c-11e7-96a2-36c68a5116d6.png)

**Comment by geekyd** [comment]
Closing this due to issue https://github.com/fossasia/open-event-webapp/issues/1608, please take up some other issue. Thanks :)
