### ISSUE TITLE
Parallelize Travis build

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event-webapp#1601]
**Actual Behaviour**

Presently,Travis takes a lot of time to execute

**Expected Behaviour**

After parallelizing, Travis will take very less time as compared to present execution time.

**Would you like to work on the issue?**

 I would like to work on it but suggestions required.

Please give your views @mariobehling @geekyd @agbilotia1998 @Princu7 @aayusharora

**Comment by ParthS007** [comment]
I am thinking to run sample tests Parallel and then run the selenium tests. It will reduce a lot of execution time if it is implemented successfully.

**Comment by geekyd** [comment]
@ParthS007 I think this will significantly reduce the time for travis. Please go ahead.

**Comment by agbilotia1998** [comment]
@ParthS007 most of the time of travis is consumed in generating samples.So if we run these tests in parallel I guess we can reduce the build time.

**Comment by ParthS007** [comment]
@geekyd  @agbilotia1998  I have studied it and now I have two methods:
First one is to divide the tests into multiple files and then call them ( I found some useful thing related to it on [Stackoverflow ](https://stackoverflow.com/questions/28229424/how-to-set-execution-order-of-mocha-test-cases-in-multiple-files))
The second one is set an env variable for each instance, then run the tests, in the tests file, we can add if clauses and run only a test if that corresponding env. Variable matches.
Which way to go?

**Comment by agbilotia1998** [comment]
@ParthS007 I guess the first method won't work for us as the two processes would run one after the other even if we place their corresponding tests in different files.The second one could help if it creates separate builds for each instance.

**Comment by mariobehling** [comment]
What we need is a working deployment before any other improvements. We also need an app that can generate the FOSSASIA Summit for this year.
