### ISSUE TITLE
There was a problem at the time of the Email Confirmation and also the Reset Password

### ISSUE THREAD

**Issue by amryarios** [fossasia/open-event-webapp#1605]
** Actual Behavior **

- When I do email confirmation but in my gmail message does not appear a message request for email confirmation.
- At the time I reset the password in my gmail message does not appear perminataan reset password.
More info see screenshots.

** Expected Behavior **

- In order for email confirmation request to be sent directly to gmail and can confirm quickly
- At the time of the password reset request, the message is instantly sent to gmail quickly.

** Screenshots of the issue **

![bug2](https://user-images.githubusercontent.com/34100642/34677542-18c126ae-f4c3-11e7-957d-f980f7e607f1.PNG)
![bug3](https://user-images.githubusercontent.com/34100642/34677543-1907e972-f4c3-11e7-9c6f-1c732a454a2d.PNG)
![bug1](https://user-images.githubusercontent.com/34100642/34677544-195aaf36-f4c3-11e7-8f23-01592a25ea3a.PNG)

**Comment by highskillzz** [comment]
Can I start solving this issue?

**Comment by amryarios** [comment]
Ping @fossasia/website-admins

**Comment by amryarios** [comment]
okay, please tell me how to do it because i also want to know it as additional science for me
@highskillzz

**Comment by geekyd** [comment]
@amryarios Please open an issue in https://github.com/fossasia/open-event-legacy. This is not the correct project. Closing this :)
