### ISSUE TITLE
Confusing effect of whole page image when cursor off-page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1608]
I cannot find where this contribution was merged, but showcasing the app today resulted in a complete confusion of users. The App was very simple until recently. Somehow unnecessary UI elements were merged.

Please take out the effect to show an image over the whole page when the cursor is off-page.

![screenshot from 2018-01-08 19-36-30](https://user-images.githubusercontent.com/1583873/34686406-b5b5a33a-f4ab-11e7-9f3b-235dd00d1a14.png)

**Comment by ParthS007** [comment]
@mariobehling will do this asap 👍
