### ISSUE TITLE
Change Fossasia samples to FOSSASIA Summit

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1610]
The Fossasia samples and overview page should use FOSSASIA Summit as text.

**Comment by 0x48piraj** [comment]
I'm on it :+1:

**Comment by geekyd** [comment]
@0x48piraj We already have a PR for this issue. #1616

**Comment by 0x48piraj** [comment]
Ah, Okay.
@ParthS007 told me this. :blush:
