### ISSUE TITLE
Make all sample sites build with Travis on PR merge

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1625]
The sample sites should always build with Travis on PR merge.

Please always use the samples on https://github.com/fossasia/open-event and build the sample site on each deployment.

**Comment by abishekvashok** [comment]
Can I work on it pls?

**Comment by abishekvashok** [comment]
@geekyd we should test sites here right?

**Comment by agbilotia1998** [comment]
@mariobehling the same approach is being used, but the current changes are not getting reflected due to #1716
