### ISSUE TITLE
Add a background image and fix footer

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/open-event-webapp#1628]
**Actual Behaviour**
The app looks dul.
Also, sometimes footer starts to float.
> **_Reference : https://github.com/fossasia/badgeyay/issues/418_**

**Expected Behaviour**
It should be more appealing, and bug free.

**Steps to reproduce it**

Clicking on expandable items gets the footer floating.

**Screenshots of the issue**

It's a rare bug. I found it once only. But the code is buggy.

**Would you like to work on the issue?**

Yes.

**Comment by ParthS007** [comment]
@0x48piraj Footer have no problem, I am not able to reproduce the bug and there is no need for adding background Image 👍

**Comment by 0x48piraj** [comment]
@ParthS007 
Something like this ?
![image](https://user-images.githubusercontent.com/5800726/34726130-27402be2-f579-11e7-8c41-77b93057ea04.png)

I have used css gradient *(avoided image caching)*

**Comment by 0x48piraj** [comment]
Also, see : https://github.com/fossasia/badgeyay/pull/419

Same bug was solved in badgeyay.

This is my commit : https://github.com/0x48piraj/open-event-webapp/commit/d7409798bb44f57aa074bb227ed36d16cb050839

**Comment by ParthS007** [comment]
No @0x48piraj  It is not needed at all. In previous PRs background is like that only but I have reverted these changes yesterday. Please read Mario's comment here https://github.com/fossasia/open-event-webapp/pull/1578

**Comment by ParthS007** [comment]
Footer is working fine 👍

**Comment by 0x48piraj** [comment]
I'm closing this. Thanks @ParthS007 and @mariobehling :100:
