### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by naveentherocker** [fossasia/open-event-webapp#1643]
**Actual Behaviour**

Containers are not been used Properly and many minor design Issues

**Expected Behaviour**

Beautiful Website

**Steps to reproduce it**

Fixing the UI

**Would you like to work on the issue?**

Yes

![sched eventyay com_ pc](https://user-images.githubusercontent.com/16055010/34830090-d7013dec-f708-11e7-9274-fc1fd067a64a.png)

**Comment by geekyd** [comment]
@naveentherocker Have a look at #1459

**Comment by naveentherocker** [comment]
@geekyd Please Check the PR and Tell If I must do anything to make it closer to #1459
