### ISSUE TITLE
Add more sister projects

### ISSUE THREAD

**Issue by arjunpandey2003** [fossasia/open-event-webapp#1654]
**Actual Behaviour**

not all prjects in menu bar

**Expected Behaviour**

More were added

**Steps to reproduce it**

Update html file add image

**Would you like to work on the issue?**

Yes I am

**Comment by arjunpandey2003** [comment]
Eg badgeyay and phimpme

**Comment by saarthakchats** [comment]
I am also adding some other projects, not the same,e as the ones you have added.
