### ISSUE TITLE
Incorrect link of venue in sessions page 

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1658]
**Actual Behaviour**
Currently on the sessions page if a venue is clicked the page redirects to the rooms page but the page does not scroll to the correct venue.

**Expected Behaviour**
When venue is clicked inside the sessions page the page should redirect to rooms page, scrolling to the clicked section.

**Steps to reproduce it**
- Go to https://sched.eventyay.com/MozillaAllHands2017/sessions/session_1001.html
- Click on the venue `Yosemite Room`

**Comment by agbilotia1998** [comment]
@geekyd I am working on this.
