### ISSUE TITLE
improve code quality 

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1685]
**Actual Behaviour**
The codacy is currently rating the project `B`

**Expected Behaviour**
Improve the codacy grate to A+.

**Comment by ParthS007** [comment]
I want to work on this issue

**Comment by geekyd** [comment]
@ParthS007 Sure go ahead.

**Comment by geekyd** [comment]
@ParthS007 Any updates on this?

**Comment by mariobehling** [comment]
As I see a PR has been merged. There are many issues that are nice to have but right now I cannot generate a working app and Travis has not been working for a very long time. Let's keep issues only for major features and bugs that we need in order to get this app working again.
