### ISSUE TITLE
Error and success both getting printed in log

### ISSUE THREAD

**Issue by jaybhairaviya** [fossasia/open-event-webapp#1704]
![screenshot from 2018-01-31 22-19-53](https://user-images.githubusercontent.com/17911468/35638255-a5f4555c-06dc-11e8-8ebd-90d3697af69b.png)

Here both the success and error message is getting printed if an **error occurs**. Is this an expected behaviour?

**Comment by jaybhairaviya** [comment]
@geekyd what are your views on this?

**Comment by agbilotia1998** [comment]
@jaybhairaviya are you testing on your local machine?

**Comment by jaybhairaviya** [comment]
![screenshot from 2018-02-01 22-52-15](https://user-images.githubusercontent.com/17911468/35693009-dab4c2b0-07a2-11e8-9516-0421dca2987c.png)

Yes i m running on local machine. I just generated a hardcoded error to check the error logging message. If u check the screenshot in the comment, the function is not ending after printing error log msg but continuing to the success part of the code.

**Comment by agbilotia1998** [comment]
@jaybhairaviya the function should not end actually,it should continue to work but the error is needed to be resolved.Please share the console logs.

**Comment by jaybhairaviya** [comment]
![screenshot from 2018-02-01 23-15-14](https://user-images.githubusercontent.com/17911468/35694074-1fedea7a-07a6-11e8-84ac-4b0f3f31c816.png)
@agbilotia1998 As i said i had hardcoded the error, so the log wont be able to help i think. But if u see the screenshot, the blue highlighted code is the edit i m suggesting. If u check below, the lines marked with RED are the present code lines which very well exit the callback and make the code move to next async task.

**Comment by mariobehling** [comment]
This seems to be expected.
