### ISSUE TITLE
Improve menu of Web app generator 

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event-webapp#1710]
**Actual Behaviour**
Currently , menu has old logo and improper alignment
![image](https://user-images.githubusercontent.com/24358501/36052416-a2fb3c24-0e13-11e8-8bc6-0e091f0fc0d9.png)

**Expected Behaviour**
It should be like as in loklak or susper.
![image](https://user-images.githubusercontent.com/24358501/36052569-3e134a9e-0e14-11e8-999e-55388688a314.png)
![image](https://user-images.githubusercontent.com/24358501/36052594-5bff0822-0e14-11e8-9a75-73f4a76c5bd2.png)

**Would you like to work on the issue?**

No, any beginner can take this up 👍

**Comment by shubham3211** [comment]
I am working on this.
