### ISSUE TITLE
gh-page rebuild failing.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1716]
**Actual Behaviour**

gh-page rebuild is failing.

**Expected Behaviour**

All webgen assosciated websites should reflect new changes.

**Would you like to work on the issue?**

Yes, but would need write access to this project.@mariobehling please check this.

**Comment by geekyd** [comment]
@agbilotia1998 You can send PR to the gh-pages branch manually. We can try it & see if the auto deploy on gh-pages start working again.

**Comment by agbilotia1998** [comment]
@geekyd @mariobehling  I would be needing gh-token of this repository to test if the problem is something like travis-ci timeout or something else.

**Comment by agbilotia1998** [comment]
The issue is still there.

**Comment by agbilotia1998** [comment]
@mariobehling @geekyd @ParthS007 please check this screenshot
![gh-pages issue](https://user-images.githubusercontent.com/21157929/37158075-783e5a0e-2310-11e8-9c50-a991a9c1d180.png)

**Comment by ParthS007** [comment]
@agbilotia1998  I think there is problem with token , will check this :+1:
