### ISSUE TITLE
Apps with expandable sessions page are not properly spaced out

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-webapp#1718]
**Actual Behaviour**
The Apps with expandable sessions page should be properly spaced out.
**Expected Behaviour**
The Apps with expandable sessions page should be properly spaced out.
**Steps to reproduce it**
Put it in a div container.
**Screenshots of the issue**
![screen shot 2018-02-16 at 10 29 12 pm](https://user-images.githubusercontent.com/31013104/36319331-9a7b1ba0-1368-11e8-8d70-6488005a8a7e.png)

**Would you like to work on the issue?**
Yes

**Comment by harsh-jindal** [comment]
This issue is only there when we open it with https://sched.eventyay.com/
If we open it from our local repository this issue is not seen.
@mariobehling Can you help me on how to go about it?

**Comment by agbilotia1998** [comment]
@harsh-jindal the view that you are showing is older one, the new changes are not getting reflected as mentioned in #1716,we will fix it soon. BTW you can checkout the new design of this page on your machine by installing this project  and running tests.
