### ISSUE TITLE
No back to top option on the main page

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-webapp#1719]
**Actual Behaviour**
There is no back to top option on the main page.
**Expected Behaviour**
There should be a back to top option on the main page.
**Would you like to work on the issue?**
YES

**Comment by ashupednekar** [comment]
I would like to work on this issue

**Comment by harsh-jindal** [comment]
@ashupednekar I'm already working on this

**Comment by ashupednekar** [comment]
Fine

**Comment by mariobehling** [comment]
Low priority. What we need is a working app before we go into other details.
