### ISSUE TITLE
The error message of email and other fields should be shown in appropriate colour

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-webapp#1725]
**Actual Behaviour**
The error message for email and other fields is not shown in appropriate colour.
**Expected Behaviour**
The error message for email and other fields should be shown in appropriate colour.
**Screenshots of the issue**
![screen shot 2018-02-18 at 1 59 48 am](https://user-images.githubusercontent.com/31013104/36345404-8d1b6748-144f-11e8-94c2-fd30628e609f.png)
![screen shot 2018-02-18 at 2 04 55 am](https://user-images.githubusercontent.com/31013104/36345427-fe70fd90-144f-11e8-8eb8-fa90ec88d4eb.png)
**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Low priority. Please help with fixing Travis first.
