### ISSUE TITLE
Add feature to show short description when hovered on an event

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-webapp#1732]
**Actual Behaviour**
No feature to provide a short description of the event without opening it.
**Expected Behaviour**
Add a feature to provide a short description of the the event.
**Steps to reproduce it**
This is can implemented by giving a "Quick info" or "Quick overview" option to come on hover of the event.Clicking on which a dialog box to open giving a short description about the issue.
Other way is to directly make the starting text describing the event to appear when hovered upon so the user gets a brief idea about the event.
**Would you like to work on the issue?**
YES

**Comment by agbilotia1998** [comment]
@harsh-jindal in expandable session style it is already implemented.Instead of the short description, whole description is being provided in current implementation.

**Comment by harsh-jindal** [comment]
@agbilotia1998 Okay.But my idea was instead of opening every event we could have a short description of it so the user does not need to open each and every event to get brief idea about the event.Don't know whether this will be helpful or not.Opinions?

**Comment by mariobehling** [comment]
Let's solve existing issues and make the design work first.

**Comment by harsh-jindal** [comment]
@mariobehling Okay 👍
