### ISSUE TITLE
Images on sample paged are scaled out or ratio

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1735]
Unfortunately this did not show up earlier as Travis did not work. Now we can see it: The images are scaled out of ratio. They are wider and faces look expanded (e.g. Google IO, FOSSASIA Summit 2010, Mozilla All Hands 2016 etc.): https://sched.eventyay.com/

Someone increased the width of the image area, but did not scale and crop the images accordingly. The image area is very wide as well and it feels unnatural.

![screenshot from 2018-03-01 12-27-52](https://user-images.githubusercontent.com/1583873/36842591-673d93e2-1d4c-11e8-99d8-2275010c2ee8.png)

**Comment by harsh-jindal** [comment]
@mariobehling Claiming!!
