### ISSUE TITLE
Make "Tracks filter" work on rooms page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1737]
All items should be clickable and result in filtering content.

![screenshot from 2018-03-01 12-52-52](https://user-images.githubusercontent.com/1583873/36843531-83fd9ac4-1d4f-11e8-9058-0be1ceb6cca5.png)

**Comment by harsh-jindal** [comment]
@mariobehling Claiming 🚀

**Comment by harsh-jindal** [comment]
@ItachiUchiha1998 I'm working on this.

**Comment by harsh-98** [comment]
@harsh-jindal add the eventlistener on the tracks list item such that on clicking, the cards can be filtered by the value of the div with innerHTML `blacktext`. Look [here](https://github.com/fossasia/open-event-webapp/blob/development/src/backend/templates/rooms.hbs#L241).

Then set the display property none on others none and  for the matching items use the display:block.

**Comment by harsh-jindal** [comment]
@harsh-98 Thanks.

**Comment by shubham3211** [comment]
can i work on this issue?

**Comment by shubham3211** [comment]
I am working on this.
