### ISSUE TITLE
Implement Tracks and Rooms filter on schedule page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1739]
The schedule page does not have filter options. Please implement Tracks and Rooms filter on schedule page and make all items clickable as on other pages.

![screenshot from 2018-03-01 12-52-52](https://user-images.githubusercontent.com/1583873/36843588-af064d7e-1d4f-11e8-99ab-a4cd4b9bfd53.png)

**Comment by shubham3211** [comment]
i would like to work on this
