### ISSUE TITLE
Provide a link to tracks and rooms to show e.g. "all sessions on all days"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1740]
Provide a link to tracks and rooms to show e.g. "all sessions on all days"

With the current version it seems it is not possible anymore to link to a complete track as the filters need to be clicked. Is there any way to see all sessions of e.g. the track "Blockchain" of all days in one view? A direct link to all track sessions that one can set from the start page is needed. https://2018.fossasia.org/event/tracks.html -> show all Blockchain tracks from all days. How can I do it?

**Comment by agbilotia1998** [comment]
@mariobehling, working on this.
