### ISSUE TITLE
Add option to insert Google Analytics into all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1743]
Google analytics would be a good option to track which sessions are interesting to people. Please add an option to add the Google tracker info into the generator UI and add the tracking code into every page.

**Comment by PrP-11** [comment]
I would like to work on this but I don't have any idea about google analytics. Can you tell how to proceed for this issue.

**Comment by harsh-98** [comment]
Hi @PrP-11  - are you still working on this? I have a patch ready to go, didn't notice that you had expressed interest :)

**Comment by ParthS007** [comment]
@harsh-98 Its good that you have worked on this but please follow best practices and help others also. I hope you understand and please read this if you haven't https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/.

**Comment by harsh-98** [comment]
@ParthS007 I had the patch ready about 3-4 days ago but due to some work i wasn't able to make PR.
