### ISSUE TITLE
Filters are not linkable - provide links to tracks etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1749]
With the current version it is is not possible to link to a complete track as the filters need to be clicked. Is there any way to see all sessions of e.g. the track "Blockchain" of all days in one view?

We need a direct link to all track sessions that I can set from the start page. https://2018.fossasia.org/event/tracks.html -> show all Blockchain tracks from all days.

**Comment by shubham3211** [comment]
I would like to work on this issue.

**Comment by agbilotia1998** [comment]
@mariobehling this has already been resolved in #1745

**Comment by aayusharora** [comment]
Can we close this @mariobehling?

**Comment by agbilotia1998** [comment]
@mariobehling can we close this?

**Comment by agbilotia1998** [comment]
Since it is fixed and tests have also been added for the same. Closing this.
