### ISSUE TITLE
Direct Link to session shows session behind top bar and not extended

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1755]
If the user clicks a link to a session, the session should not be hidden partly behind the top bar and it should be expanded. Currently it is not as expected. It should be a bit below and expanded.

![screenshot from 2018-03-05 22-54-41](https://user-images.githubusercontent.com/1583873/37001967-77e6ff42-20c8-11e8-973f-1726c1e68a82.png)

**Comment by harsh-98** [comment]
I am working on this but do you meant by `expanded`. That part isn't clear to me.

**Comment by agbilotia1998** [comment]
Fixed with #1762 closing it.
