### ISSUE TITLE
Direct link to session on venue page not showing results

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1758]
Using a venue link such a https://2018.fossasia.org/event/rooms.html#venue-4450 does not show a result anymore.

![screenshot from 2018-03-06 03-45-48](https://user-images.githubusercontent.com/1583873/37011521-e17496e0-20f0-11e8-9996-8d4eebbbd238.png)

**Comment by shubham3211** [comment]
I would like to work on this issue
