### ISSUE TITLE
Support old and new API in current development branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1759]
At some point the old API was taken out and now we have two branches that become incompatible more and more. Instead the dev branch should support both APIs, including the one in APIv1 branch.

**Comment by harsh-98** [comment]
I would like to work on this.

**Comment by harsh-98** [comment]
@mariobehling can u provide me with information on which api are there in open-event-webapp.

**Comment by harsh-98** [comment]
@agbilotia1998 I think I asked for working on this issue though I appreciate ur PR.
