### ISSUE TITLE
jshint is not understanding angular

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#176]
jshint is showing error , for some of the best Angular styles ["John Papa"](https://github.com/johnpapa/angularjs-styleguide) or [Todd Motto](https://github.com/toddmotto/angularjs-styleguide)" , Infact some errors are like this
![1](https://cloud.githubusercontent.com/assets/12194719/14585329/9e30dcbc-048d-11e6-97f6-0a06e1231dfe.png)
 
@juslee , Please consider this http://stackoverflow.com/questions/26288367/does-jshint-understand-angular

**Comment by championswimmer** [comment]
Some are due to these lint frameworks optimised for nodejs these days,
where you cannot use a var without declaring.

Here you can ignore the 'used before declared' warnings as long as the
required js files are included in index.html

**Comment by aayusharora** [comment]
Thanks @championswimmer , I agree but we can include angular as well by creating .jshintrc file .
@juslee , consider #177

**Comment by aayusharora** [comment]
Not fixed Still

**Comment by aayusharora** [comment]
@juslee , Tried this may be it would work  #179
