### ISSUE TITLE
Improve the UI of email field

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-webapp#1768]
**Actual Behaviour**
The email field looks good but can be made better by adding a icon there.
**Expected Behaviour**
The email field should have a email icon.
**Screenshots of the issue**
![screen shot 2018-03-10 at 1 09 48 pm](https://user-images.githubusercontent.com/31013104/37239554-09e0fb7a-2464-11e8-827e-c06366c2ce8d.png)

**Would you like to work on the issue?**
YES

**Comment by asp2809** [comment]
Can you tell clearly where exactly you want the icon to be placed?
As I am a little confused regarding the same.

**Comment by agbilotia1998** [comment]
Resolved in #1880
