### ISSUE TITLE
Not able run app on local server unknown error

### ISSUE THREAD

**Issue by sk9331657** [fossasia/open-event-webapp#1773]
![not running](https://user-images.githubusercontent.com/17084322/37359386-7608a288-2713-11e8-8769-37f0c4eb82b8.png)

**Comment by sk9331657** [comment]
@mariobehling Please See to it.

**Comment by rohan598** [comment]
The application is running on the local server. 
You need to ensure that all the node modules have been installed properly. In your case, node-sass seems to be the issue, reinstall it. We can carry out rest of the discussion on gitter. 
This is similar to issue #1748, so we can close it.
