### ISSUE TITLE
Improve implementation of top menu by converting to drop-down on small screens.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1775]
Here is a screenshot how it should look somehow.

![screenshot from 2018-03-14 18-30-06](https://user-images.githubusercontent.com/1583873/37398002-0c1eeec2-27b8-11e8-890c-51ec32718912.png)

You can also take inspiration on sched.com, even though it is a different concept.
e.g. here https://ossna2017.sched.com/

**Comment by AdityaHirapara** [comment]
@mariobehling can I take this?

**Comment by geekyd** [comment]
@AdityaHirapara Sure, go ahead!

**Comment by AdityaHirapara** [comment]
@geekyd Should I add home link ,even though it is in title ?

**Comment by mariobehling** [comment]
@AdityaHirapara I am unclear what you mean by home link. Rather than requesting people to discuss in issue, just go ahead and we will sort it out when there are PRs. Keep it up!
