### ISSUE TITLE
Overlap in search speaker filed in small screen view

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1776]
Please check out the overlap issues here and resolve it:

![screenshot from 2018-03-14 18-22-46](https://user-images.githubusercontent.com/1583873/37398155-88201c9e-27b8-11e8-9088-c1f19554d20f.png)

**Comment by rohan598** [comment]
@mariobehling Can I have a go at it ?

**Comment by rohan598** [comment]
I have found the error and rectified it and will be sending a pull request for the same.

**Screenshots**
###### Screen width <= 450px
![screen shot 2018-03-16 at 5 43 33 pm](https://user-images.githubusercontent.com/25100847/37520339-9b604ffa-2942-11e8-910e-31d9c9dc185a.png)
###### Screen width > 450px and  <=600px
![screen shot 2018-03-16 at 5 44 09 pm](https://user-images.githubusercontent.com/25100847/37520340-9d4f66e8-2942-11e8-959d-611bae048995.png)
###### Screen width > 600px
![screen shot 2018-03-16 at 5 44 23 pm](https://user-images.githubusercontent.com/25100847/37520372-badfe804-2942-11e8-9c16-9ce519c3e88e.png)

**Comment by Aakash-DD** [comment]
Is this still there, i want to work on this
