### ISSUE TITLE
Renew HTTPS certificate  

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#1777]
It seems like that the website http://sched.eventyay.com has an expired https certificate.
Since it has HSTS policy, it is imposible to overwrite the security policy and view any content for Modern Browser. 
@mariobehling Can you look into this?

**Comment by mariobehling** [comment]
@aayusharora How avoid HSTS? We are setting the domain on Google Cloud currently. Differently to Cloudflare, there is no easy way to take care of it.

**Comment by agbilotia1998** [comment]
@mariobehling @aayusharora https://sched.eventyay.com is working now, but https://webgen.eventyay.com is still not working. Can you look into the issue?

**Comment by aayusharora** [comment]
@mariobehling I guess, you have the access for this, can you please check this once?

**Comment by agbilotia1998** [comment]
As discussed, https://webgen.eventyay.com is closed for the time. Closing this issue.
