### ISSUE TITLE
Reduce size of Star button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1780]
The star button has a different size than the left-hand buttons. Please help and reduce the size and match the design of the other buttons on the left.

![screenshot from 2018-03-18 13-56-30](https://user-images.githubusercontent.com/1583873/37563099-5586c144-2ab4-11e8-891f-bd2b917ec998.png)

**Comment by AdityaHirapara** [comment]
@mariobehling I would like to work on this.

**Comment by AdityaHirapara** [comment]
@mariobehling ,Do you want it on all pages or only on shedule page??
