### ISSUE TITLE
Filters not available in mobile view

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1781]
Please add a filter icon into the mobile view and show the filters as a drop-down menu.

The filter icon should go in front of (left of) the search bar as below.

![screenshot from 2018-03-18 13-56-30](https://user-images.githubusercontent.com/1583873/37563140-27cfacc4-2ab5-11e8-9620-f34a1f9bd244.png)

Desired Filters:

![screenshot from 2018-03-18 13-50-39](https://user-images.githubusercontent.com/1583873/37563149-4771d818-2ab5-11e8-9103-95a9af3d1371.png)

**Comment by vsnehil92** [comment]
@mariobehling I would like to work on this issue

**Comment by rohan598** [comment]
I have solved this issue and will be sending a pull request for the same.
