### ISSUE TITLE
Rooms list not sorted alphabetically

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1783]
Please check that all rooms are sorted alphabetically on all pages.

![screenshot from 2018-03-20 08-27-25](https://user-images.githubusercontent.com/1583873/37629253-be859b2e-2c18-11e8-94e8-99feea6c5fc6.png)

**Comment by rohan598** [comment]
May I work on this issue ?

**Comment by ItachiUchiha1998** [comment]
can i work on this issue?

**Comment by rohan598** [comment]
I have solved this issue and have sent a pull request for the same.
