### ISSUE TITLE
Calendar view showing wrong times

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1785]
The calendar view shows the wrong time which is half an hour earlier than on the list view.

Please see below and help to solve it.

Correct:
![screenshot from 2018-03-23 00-39-13](https://user-images.githubusercontent.com/1583873/37784472-da30f8de-2e32-11e8-83ac-4c0887e189f9.png)

Wrong:
![screenshot from 2018-03-23 00-38-25](https://user-images.githubusercontent.com/1583873/37784464-d5d2d6cc-2e32-11e8-9a12-332a253dd423.png)

**Comment by shubham3211** [comment]
I would like to work on this

**Comment by the-dagger** [comment]
@shubham3211 Thanks, but can you make the same fix in https://github.com/fossasia/2018.fossasia.org

The live website for the event is hosted here.

**Comment by shubham3211** [comment]
@the-dagger schedule.html is a minified file I need the zip file or api to generate it again.

**Comment by aayusharora** [comment]
Hi @shubham3211
Here is the api end point 
https://eventyay.com/api/v1/events/275

**Comment by shubham3211** [comment]
@aayusharora I have made a pull request :-https://github.com/fossasia/2018.fossasia.org/pull/618
