### ISSUE TITLE
Room heading missing while applying track filter on rooms page

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1794]
**Actual Behaviour**
The room name is not displayed when track filter is applied on the rooms page. 

**Expected Behaviour**
The name of the room must be displayed with or without any filter.

**Steps to reproduce it**
- Go to rooms page 
- Click on a track from the right menu.

**Screenshots of the issue**

**Without filter**
![screen shot 2018-03-26 at 1 52 49 pm](https://user-images.githubusercontent.com/12807846/37891578-58b0f566-3107-11e8-85d9-07b597ba702b.png)

**With Filter**
![screen shot 2018-03-26 at 1 54 02 pm](https://user-images.githubusercontent.com/12807846/37891579-58fcfda8-3107-11e8-87a4-eecb9fbe4e9b.png)

**Comment by agbilotia1998** [comment]
@geekyd all same tracks are not in the same room, so how to display the rooms heading which are different for the same track?

**Comment by AdityaHirapara** [comment]
I would like to work on this.
