### ISSUE TITLE
UI Design & Template

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-webapp#181]
We need to improve the UI for the webapp so that it is more user friendly. I think we should go with material design.

These templates can be modified to suit the needs I feel:
http://flatfull.com/themes/materil/angular/#/app/dashboard
http://shapebootstrap.net/item/1524963-evento-free-music-event-template/live-demo

Give your proposals below.

**Comment by aayusharora** [comment]
[gentelella](https://github.com/puikinsh/gentelella) is the decided theme .
