### ISSUE TITLE
Add "Video" button to session and adapt design accordingly

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1810]
A number of events have videos. Please add a video button to the schedule as below.

![screenshot from 2018-04-03 17-09-02-a](https://user-images.githubusercontent.com/1583873/38244615-d29df628-376d-11e8-8840-4142b7f31485.png)

**Comment by rohan598** [comment]
I'll be doing this along with issue #1809

**Comment by agbilotia1998** [comment]
@mariobehling since the track button, video button and slides button would do the same job (collapse in the div - in expandable session type), can we embed them in the same div itself?
