### ISSUE TITLE
Pop-box is inflating all the items

### ISSUE THREAD

**Issue by yashLadha** [fossasia/open-event-webapp#1825]
**Actual Behaviour**

Pop box is inflating all the items and not considering the length of the calendar and due to which it extends to its full length.

**Expected Behaviour**

There should be a maximum limit to which the entries should be inflated and remaining should be contracted.

**Steps to reproduce it**
Just click on any event in calendar view

**Screenshots of the issue**

![screenshot from 2018-04-16 17-35-17](https://user-images.githubusercontent.com/18033231/38808184-d4c7aabe-419c-11e8-84a8-6aa37d408edf.png)

**Would you like to work on the issue?**

Yes

**Comment by yashLadha** [comment]
@geekyd Views ??

**Comment by casyazmon** [comment]
I'm working on this issue!!

**Comment by yashLadha** [comment]
Please read the issue description before taking up the issue.

**Comment by yashLadha** [comment]
I am working on the issue. See the issue description.
