### ISSUE TITLE
Fix the position of helper text when there is no search result

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1832]
**Actual Behaviour**

Currently the no result found text is rendered right next to the search box.

![b2072dc7-1fe5-4237-ad8e-aeaf75674614](https://user-images.githubusercontent.com/12807846/39285808-0c3da88e-4938-11e8-862c-c4b440034ca5.png)

**Expected Behaviour**

The text should render below the date filter where the schedule is loaded.

![b2072dc7-1fe5-4237-ad8e-aeaf75674614 1](https://user-images.githubusercontent.com/12807846/39285813-11bf6de2-4938-11e8-80f2-bc73ca0d50e6.png)

**Comment by geekyd** [comment]
@abhishek71994 Sure please go ahead

**Comment by abhishek71994** [comment]
@geekyd could you tell me how to recreate this?
When I ``` npm start ```
I get
```
reqDomain.dispose();
TypeError: reqDomain.dispose is not a function
    at Domain.<anonymous> (/Users/abhihk95/Desktop/react-apps/open-event-webapp/node_modules/connect-domain/lib/connect-domain.js:17:14)
    at Domain.emit (events.js:159:13)
    at Domain._errorHandler (domain.js:109:23)
    at process._fatalException (bootstrap_node.js:379:33)
```

**Comment by agbilotia1998** [comment]
@agarwalprashasti, yes the issue is still open.

**Comment by abhishek71994** [comment]
@agarwalprashasti go for it.
