### ISSUE TITLE
Events with V1 not getting generated

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#1840]
Using this API link https://eventyay.com/api/v1/events/200 the event generator gets stuck at 40% and does not show an error in the log. Please investigate and fix.

![screenshot from 2018-05-08 12-35-14](https://user-images.githubusercontent.com/1583873/39752708-90294be8-52bc-11e8-85ed-6a22124b26e6.png)

Using: http://opev-webgen-dev.herokuapp.com/

**Comment by agbilotia1998** [comment]
Working on it.
