### ISSUE TITLE
Implement task queue in the project.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1856]
**Actual Behaviour**

In the current implementation of open-event-web app multiple users cannot generate an event at the same time, only the recent triggered event is generated and generation of all the former ones is halted.

**Expected Behaviour**

We need to enable multiple web-apps generations by implementing queue data structure for the series of requests triggered by users from the open-event platform. This would prevent the loss of requests from the user and enable the creation of event for every request.

**Steps to reproduce it**

Generate any two web apps simultaneously.

**Would you like to work on the issue?**
Yes.

**Comment by agbilotia1998** [comment]
@geekyd should we improvise the file upload structure or change the entire structure to the queue based such that we do not lose the request?

**Comment by geekyd** [comment]
@agbilotia1998 Lets go for task queuing solution to tackle this problem.

**Comment by agbilotia1998** [comment]
Okay, @geekyd.

**Comment by geekyd** [comment]
@agbilotia1998 Any progress?

**Comment by agbilotia1998** [comment]
@geekyd I am working on this, was busy on experimenting since the API is working fine can we make a post request with the name of the uploaded file on the generator.
