### ISSUE TITLE
Travis Failing due to expected value of broken links

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1863]
**Actual Behaviour**

Travis test is failing due to invalid expected count of broken link.

**Expected Behaviour**

The expected count should be 1 instead of 0.

**Would you like to work on the issue?**

Yes.

**Comment by geekyd** [comment]
@agbilotia1998 Are the links broken because of no sponsor data for FOSSASIA 2018?

**Comment by agbilotia1998** [comment]
@geekyd one of the sponsor's link is giving `Page not Found` error in Fossasia Summit 2017 sample, that's why the travis is failing.
