### ISSUE TITLE
Invalid Zip Error

### ISSUE THREAD

**Issue by jalakoo** [fossasia/open-event-webapp#1865]
**Actual Behaviour**

Invalid Zip error reported - No web app generated.

**Expected Behaviour**

Web app generated. For sample or own configuration file.

**Steps to reproduce it**
1. Successful 1-click setup onto heroku. [Test instance here](https://digitalvelocity-open-event-web.herokuapp.com)
2. Open Event WebApp Generator form appears correctly
3. Uploading a .zip file of Open Event Format Scheme successful
4. Clicking on `GENERATE WEBAPP` always produces an `ERROR: Invalid Zip`

**Log for the issue**

When using the sample `Droidcon17.zip` and `FBF817.zip` files I get `TypeError: Cannot convert undefined or null to object`

When using my own configuration scheme I got: `ERROR:Invalid ZipKnow More
Error: /app/src/backend/../../dist/test@tealium.com/tempproject2/json/sessions: ENOENT: no such file or directory, open '/app/src/backend/../../dist/test@tealium.com/tempproject2/json/sessions'`  -- even though the `sessions` json file definitely exists (tried an empty json array as well as a populated one).

**Screenshots of the issue**

<img width="317" alt="screen shot 2018-05-19 at 11 26 41 am" src="https://user-images.githubusercontent.com/960717/40271812-942e43f8-5b57-11e8-90fb-b2fff16bb9e1.png">

**Would you like to work on the issue?**

I don't understand the existing framework well enough to contribute at this time.

**Comment by agbilotia1998** [comment]
@jalakoo, I tested the deployment link given above. It is working fine, please select API version to v2 for the samples, as the samples you are using are of v2 format. For any other queries, please use our gitter channel. Closing this for now.
