### ISSUE TITLE
Increase speed of development iteration

### ISSUE THREAD

**Issue by joeytwiddle** [fossasia/open-event-webapp#1882]
When a developer writes new code, it is helpful if they can test that code really quickly.

The faster we can make the code-build-test iteration, the more work each developer will be able to do per hour.

I am not quite sure how to achieve this, so we may want to brainstorm.

1. ~**Improve/automate the build process**: a) Make it so I can build without having to reload the generator page, fill it out, and upload the zip file again. b) Inform me properly when the build ends. Sometimes the progress bar stops at 40% or 70% but when the console shows "SendGridError: Response error" it has actually finished.~

2. **Automatic builds**: We could add a task `npm run watch` which would automatically trigger a new build whenever the source code is changed (e.g. using [nodemon](https://www.npmjs.com/package/nodemon)). This won't be *much* faster, but it will be less effort for the developer. They can read code or make commits instead of manually restarting the build each time they want to test. (If you can create a command that performs a build, I can make a nodemon task for it.)

3. **Incremental builds**: One way to achieve fast rebuilds is with an incremental compiler: when a source file changes, it will build **only** those files in the output which are affected by that source file.

    GNU Make and Node's [Gulp](https://www.npmjs.com/package/gulp) and Create-React-App and Webpack work that way.

    Our build process is quite dynamic, because the event's JSON file is also part of the "source" configuration. But Javascript is a dynamic language, so I think it should be possible to achieve what we want using Gulp.

**Comment by joeytwiddle** [comment]
1. Hey you are right! Problem 1 is not happening for me today. The build is faster and easier. :) (Previously it had been re-downloading and processing the images every time. I don't know what changed, but I do fetch and rebase each day.)

2. Right, we could use `nodemon -i dist -i build ` to ignore changes to those folders, or we could use `nodemon -w src -w test` to watch only those folders.

**Comment by agbilotia1998** [comment]
Fixed with #1931
