### ISSUE TITLE
Best way to integrate the webapp with gentelella

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#189]
Hi ,
As [gentelella](https://github.com/puikinsh/gentelella)  was accepted as a theme by everyone , What should be the best way for the integration ? 

As gentelella is jquery based , it does not follow MVC architecture of Angular JS . Hence a best modular approach is needed .
The snapshot is the MVC architecture we follow in the webapp .
![3](https://cloud.githubusercontent.com/assets/12194719/15118390/9a8b22a4-1629-11e6-8eaf-d78f21808cf5.png)

**Comment by aayusharora** [comment]
@championswimmer , Now it will be clear to you .

**Comment by mariobehling** [comment]
Before getting more into depth here, please propose theming options https://github.com/fossasia/open-event-webapp/issues/202 and goals in user story https://github.com/fossasia/open-event-webapp/issues/200.

**Comment by aayusharora** [comment]
Closing this :) , it is for Webapp v2.
