### ISSUE TITLE
Make filter look better

### ISSUE THREAD

**Issue by shubham3211** [fossasia/open-event-webapp#1890]
Improve the filter as on https://ossna2017.sched.com/
**Screenshots of the issue**

<!—-Where-ever possible add a screenshot of the issue.-—>
![filter](https://user-images.githubusercontent.com/19900978/40557893-4866e232-606f-11e8-9a56-b303859149e9.png)
**Would you like to work on the issue?**
Yes

**Comment by joeytwiddle** [comment]
What is wrong with how it looks now? :innocent: Have you heard of any complaints or difficulties from users?

**Comment by shubham3211** [comment]
@joeytwiddle No , but the one available on https://ossna2017.sched.com/ is better.

**Comment by agbilotia1998** [comment]
Closing this, as the issue is fixed with #1893
