### ISSUE TITLE
Removing Codacy and continuing with Codeclimate

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#190]

**Comment by juslee** [comment]
@aayusharora and @championswimmer please justify why codeclimate is better than codacy.

**Comment by championswimmer** [comment]
![screenshot from 2016-05-12 20 47 25](https://cloud.githubusercontent.com/assets/1327050/15219824/d52587f0-1882-11e6-9769-91eb32e72b49.png)
Basically issues like this thrown by Codacy. 

we have to use mixed quotes so that inner quotes are escaped from the outer ones.

**Comment by championswimmer** [comment]
![screenshot from 2016-05-12 20 49 11](https://cloud.githubusercontent.com/assets/1327050/15219876/06061e5c-1883-11e6-90e7-d948b02fb970.png)
Codeclimate is also smarter. Tells stuff like when codeblocks have a lot in common (so you can refactor away some functionality into a function)

**Comment by aayusharora** [comment]
Some issues are very irrelevant like 
![2](https://cloud.githubusercontent.com/assets/12194719/15220553/8ba2cd6a-1885-11e6-94c6-6221a1b06332.png)

and 

![3](https://cloud.githubusercontent.com/assets/12194719/15220562/92f32556-1885-11e6-8124-161e237fc608.png)

**Comment by aayusharora** [comment]
@juslee @championswimmer  Whats the decision for it ? Are we continuing with Codacy or codeclimate?

**Comment by championswimmer** [comment]
Only @juslee can do it, as codacy is authorised via his account I believe

**Comment by championswimmer** [comment]
done
