### ISSUE TITLE
Speakers section heading not shown

### ISSUE THREAD

**Issue by techac** [fossasia/open-event-webapp#1916]
**Actual Behaviour**

In the current version if we try to generate the webapp
![generating settings](https://user-images.githubusercontent.com/33215722/40974540-81e34fc2-68e5-11e8-92c0-c4f6ffdf2f3e.png)
we get no heading in the speakers section
![speakers section](https://user-images.githubusercontent.com/33215722/40974643-cc8a53c2-68e5-11e8-84d7-ad26832fbc43.png)

**Expected Behaviour**

it should show the heading...

**Would you like to work on the issue?**
Yes

**Comment by agbilotia1998** [comment]
@techac thanks for reporting but the heading is visible to me, please check https://sched.eventyay.com/Droidcon2017/speakers.html
Please post your doubts in the gitter channel. Closing this issue.
