### ISSUE TITLE
Write the Swagger API

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#195]
To begin with at least - make swagger API, publish the YAML file on http://github.com/fossasia/open-event under gsoc2016, and treat it is the canon by server and client guys.

**Comment by championswimmer** [comment]
Once we are swagger-compliant, the webapp can use this https://github.com/swagger-api/swagger-js

**Comment by juslee** [comment]
shouldn't this be under open-event-orga-server?

**Comment by championswimmer** [comment]
Or under open-event umbrella.
It's common to everyone really

**Comment by championswimmer** [comment]
What do you suggest? Move it to server or open-event

**Comment by championswimmer** [comment]
Started making it here https://github.com/championswimmer/openevent-api
The live version will be here 
http://championswimmer.github.io/openevent-api

**Comment by mariobehling** [comment]
@championswimmer I am also a bit confused. Please move this issue to the server component. 

At the moment I am not clear what is your proposal. Please let us get some clear ideas first, what we want to achieve. We want to avoid developing lots of stuff, that will not get ready to be used. First step, please improve the scraper. We can use it as a basis.

And also right now, please help to define a feature list https://github.com/fossasia/open-event-webapp/issues/200

**Comment by championswimmer** [comment]
Ok continuing discussion on #200
