### ISSUE TITLE
Removing Material Dependencies and creating dashboard by gentelella

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#198]
@juslee  , The work will include lot of code addition and removal hence should be kept in a different branch .

**Comment by aayusharora** [comment]
Solve here #199 , I think we should carry this in a separate branch .

**Comment by mariobehling** [comment]
@aayusharora I did not see a discussion about the integration of gentelella here and I am not sure, if it is the best approach. Currently I am missing screenshots of where we are heading.

Also, probably following the web app of this year's FOSSASIA and OpenTechSummit will give us a basis that works already. 

Currently there are a number of open issues e.g. to add audio files to the schedule of OTS. If we can add all those missing features to OTS we would have a perfect solution to continue for the web app. 

Therefore please start with solving OTS issues https://github.com/OpenTechSummit/2016.opentechsummit.net/issues

**Comment by mariobehling** [comment]
As we are moving away from the first version web app, I am closing this issue. We should have a separate issue for the V2.
