### ISSUE TITLE
Caption not clickable in overview site.

### ISSUE THREAD

**Issue by agbilotia1998** [fossasia/open-event-webapp#1985]
**Actual Behaviour**

The caption in the overview site is not clickable, unlike the main eventyay site.

**Expected Behaviour**

The caption should also be clickable along with the image.

**Would you like to work on the issue?**

Yes

**Comment by abdoulstarter** [comment]
i would like to work on this issue. please assign this to me.Thanks

**Comment by abdoulstarter** [comment]
Great job
