### ISSUE TITLE
Create a Feature List and User Stories

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#200]
The first version of the web app had some nice features like search but unfortunately was slow. For FOSSASIA we developed a simple web app and we extended features for the OpenTechSummit schedule. In order to understand where we are heading next, please formulate a user story. Our new starting point for a web app should be the FOSSASIA/OpenTechSummit web app for now.

User Stories for the Web app:
1. Attendee (What can an attendee do with the app)
2. Speaker (What can a speaker do with the app/ At the beginning a speaker might just be able to do the same as an attendee.)
3. Organizers (specifically organizers, that use the web app as a stand alone generator for the generation of their schedule. Refer to https://github.com/fossasia/open-event-webapp/issues/203)

**Comment by mariobehling** [comment]
@championswimmer Please chime in.

**Comment by aayusharora** [comment]
@mariobehling , @championswimmer , I have already started it .

**Comment by mariobehling** [comment]
@aayusharora Please use a Google doc, where we can see the progress and add ideas: https://docs.google.com/document/d/1rR-GoS61Tq9WhiDlwLEu6whCf4SZ12uChXHClvK6eis/edit

We can then publish the outcome here.

**Comment by aayusharora** [comment]
Do we want something like that https://docs.google.com/document/d/1P_ezcjD11l4T22BjicGWPTq1K0gbpsPgQbhLoR699cY/edit?usp=sharing

**Comment by aayusharora** [comment]
@mariobehling , According to me the frontend will be the combination of Editor( orga server UI ) and
a viewer ( Webapp itself ) which will work in cohesion . Do I have to add features of only Webapp in the document . Please correct me if I am wrong .

**Comment by juslee** [comment]
Create an issue for each user story. Break down the user story to more user stories if you cannot finish it in 1 day.

Update the user stories with what was understood in the previous discussions in the other issues.

**Comment by aayusharora** [comment]
@juslee , I will do it .
