### ISSUE TITLE
Should we add tooltips too the frontpage?

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-webapp#2002]
**The problem**

Right, now when you open the frontpage you'll see this 
![image](https://user-images.githubusercontent.com/2415206/42433763-033cce4c-8351-11e8-8175-d476272eba92.png)
The thing is for a new user, they might have no idea what's the difference between version1 or version2, they might have no idea what kind of json to upload, or what kind of valid api endpoint the application expects, so it would be nice to make these a bit more clear for the users.

**Comment by agbilotia1998** [comment]
We would be adding documentation for this.
