### ISSUE TITLE
Propose theming options for Web App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#202]
As organizers might want to integrate the web app in their website, we could offer a zip that they could download and deploy on their server. In order to stick to the organizers website design, it would be good to offer theming for the web app. As discussed in #201 an organizer user could choose a theme and color and the app is generated with this theme.

@aayusharora @championswimmer: Please propose an implementation model to achieve this.

**Comment by championswimmer** [comment]
@aayusharora @mariobehling 
I suggest we create one basic bootstrap based theme (and later work on making more themes)

Like the open-event-scraper works, we'll make a theme in form of a jade/handelbars template, so that when the generator runs the json via it, a complete webpage is generated.

**Comment by championswimmer** [comment]
Closing this as we already have started implementing our theming.
