### ISSUE TITLE
Creating Flow for the Webapp .

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#206]
Once #204 is clear , I will be able to make the flow of webapp .

**Comment by juslee** [comment]
Create the flow. It is clear now. @aayusharora

**Comment by aayusharora** [comment]
![flow](https://cloud.githubusercontent.com/assets/12194719/15615216/9aef768a-2445-11e6-8807-3ca3c1b42504.png)

**Comment by aayusharora** [comment]
@juslee , @mariobehling  , This will be the flow for the app .

**Comment by aayusharora** [comment]
@juslee , can I close it .
