### ISSUE TITLE
create basic app directory structure

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#208]
document the purpose of all directories and where what will go.

**Comment by championswimmer** [comment]
commits - 
 - initial directory structure - https://github.com/fossasia/open-event-webapp/commit/e948244b4eff44f3c73e3b5fe28bf62684e87062

**Comment by championswimmer** [comment]
@aayusharora 

I am using this as a reference to set it up 
https://github.com/mgechev/angular2-seed

**Comment by championswimmer** [comment]
I have made a PR here 
https://github.com/fossasia/open-event-webapp/pull/210

It is not ready it. I will get the basic skeleton structure corresponding to what Open Event needs (Sessions, Speakers etc)

**Comment by aayusharora** [comment]
@championswimmer , got it .
