### ISSUE TITLE
Add Section "Organized by .."

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#2090]
Please add a section with white background and full-width "Organized by..." below the tweet section.

![screenshot from 2018-09-01 21-17-08](https://user-images.githubusercontent.com/1583873/44949304-fe1f6880-ae2e-11e8-95a4-5abf440930a5.png)

**Comment by Dharmesh-Poddar** [comment]
I would like to work on it .Can I move ahead

**Comment by geekyd** [comment]
@Dharmesh-Poddar Yes, please go ahead.

**Comment by Dharmesh-Poddar** [comment]
thanks man!!

**Comment by Dharmesh-Poddar** [comment]
where is the tweet section which is specified

**Comment by sarnava1** [comment]
@Dharmesh-Poddar are you still working with this?

**Comment by tathagat2006** [comment]
I would like to resolve #2090. @mariobehling can I?
