### ISSUE TITLE
Space between text and image too large in Featured Speaker section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#2092]
The space between the image and the text/name on the right is too large. 
* Please implement it in the same way as the keynote speaker section on https://2018.fossasia.org
* Ensure the top is aligned with the picture as on the FOSSASIA website

![screenshot from 2018-09-02 08-45-53](https://user-images.githubusercontent.com/1583873/44952984-d828b100-ae8c-11e8-99fd-6e106eb36d3b.png)

FOSSASIA.org

![screenshot from 2018-09-02 08-48-42](https://user-images.githubusercontent.com/1583873/44953001-25a51e00-ae8d-11e8-8340-84fc03d3d784.png)

**Comment by YashRE42** [comment]
I'd like to work on this.

**Comment by Ananthavijay** [comment]
Could u give the link @mariobehling

**Comment by sarnava1** [comment]
@Ananthavijay are you still working with this?
