### ISSUE TITLE
Ticket link on footer should direct to Ticket Page instead of top button

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#2094]
The ticket link in the footer directs to the top instead of ticket link.

Please direct that link to the ticket page directly.

![screenshot from 2018-09-07 12-58-51](https://user-images.githubusercontent.com/1583873/45215522-fb44cd80-b29d-11e8-91b8-26fa3b41b9c2.png)

**Comment by Ananthavijay** [comment]
in which page @mariobehling
