### ISSUE TITLE
Getting this issue on running npm start... what is this??

### ISSUE THREAD

**Issue by pranav1698** [fossasia/open-event-webapp#2105]
**Actual Behaviour**
I am getting the following after locally installing the project, and using `npm run start`

`> open-event-webapp@2.0.0 start /home/pranav1698/Desktop/open-source/open-event-webapp
> node src/app.js

node[20721]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8d20d0 node::Abort() [node]
 2: 0x8d21a5  [node]
 3: 0x9075f7 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
 4: 0xb89f5b  [node]
 5: 0xb8bef2 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x1cd66115c01d 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! open-event-webapp@2.0.0 start: `node src/app.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the open-event-webapp@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pranav1698/.npm/_logs/2018-09-24T19_10_04_409Z-debug.log
`
even though the dependencies are installed without any error, 

**Expected Behaviour**
After the installation of dependencies, it should open up the site in the browser as expected but is not happening at this moment...

**Steps to reproduce it**
Probably a problem in the code 

**Log for the issue**
Provided above

**Screenshots of the issue**
console error provided above

**Would you like to work on the issue?**

**Comment by agbilotia1998** [comment]
This is an installation related problem, the app is working fine.
Please ask installation related queries on the gitter channel, closing this for now.
