### ISSUE TITLE
open-event-webapp not deploying

### ISSUE THREAD

**Issue by aaqaishtyaq** [fossasia/open-event-webapp#2118]
**Actual Behaviour**
The latest version of open-event-webapp not working on the local machine as well as on Heroku.
But the strange thing is all CI build are passing.

**Expected Behaviour**
when someone tries to run the project, he/she will be able to run on the local machine as well as deploy it directly on Heroku.

**Steps to reproduce it**
* Deploy the webapp directly to Heroku.
* Run the project on local machine.

**Screenshots of the issue**
* ```npm run start```
<img width="1671" alt="screenshot 2018-10-09 at 12 53 54 am" src="https://user-images.githubusercontent.com/22131756/46629503-aa571c00-cb5e-11e8-94a5-b13fb2659685.png">

* npm logs
<img width="1671" alt="screenshot 2018-10-09 at 1 02 06 am" src="https://user-images.githubusercontent.com/22131756/46629597-0f127680-cb5f-11e8-891e-0abbc472787a.png">

**Would you like to work on the issue?**
Yes, i would like to work on the issue. I would be great if someone helps me get this issue fix.

**Comment by pg07codes** [comment]
is this fixed now?  @aaqaishtyaq
