### ISSUE TITLE
Removing Unnecessary Dependencies of gentellela

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#214]
1 .The theme has various dependencies which we don't need now . 
2. The features or all the working with gentellela will be in the form of reusable Angular Directives . For reference  TwitterWall has three directives , singletweet.js , width.js , backgrounddirective.js which are reusable .
@mariobehling , Do you have something more to add here . Please elaborate .

**Comment by mariobehling** [comment]
I am not clear on this. We also want to be able to copy/paste newer versions in future. Another point is, as Justin Lee mentioned, we can also use another bootstrap theme in future.

So, I would not really spent a lot of time on this right now. What we hope to see is - code that makes the app work. We can also clean up later.

**Comment by aayusharora** [comment]
@mariobehling  ,we have already discussed to make it work in that way , i.e the theme concept . I am clear with it . Let me add it to different Milestone than .
