### ISSUE TITLE
Side bar Fix for gentelella 

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#222]
Gentelella shows sidebar which is not fixed with scroll , gives bad view , You can see the whitespace in the image .

![6](https://cloud.githubusercontent.com/assets/12194719/15671100/b322ea86-2731-11e6-8e37-fba9ecf37c44.png)

**Comment by aayusharora** [comment]
@juslee , solved by PR #222.
After solving 
![8](https://cloud.githubusercontent.com/assets/12194719/15674451/6bf99d4e-2745-11e6-99bb-46b619a4c6c9.png)

**Comment by mariobehling** [comment]
Moving away from web app V1. Closing this issue therefore.
