### ISSUE TITLE
Webapp Generator Component 1: Create a Web Page with Form Elements to upload.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#238]
The first version of this page can be very simple without css etc. Please include:
* [ ] Email
* [ ] Apps Name
* [ ] JSON for speakers, sessions, tracks, locations etc.
* [ ] Generate and Download Button

![selection_032](https://cloud.githubusercontent.com/assets/6565270/15830700/6f7881dc-2c37-11e6-8c84-df1aa4f83f62.png)
(Compare to Android App Generator: https://github.com/fossasia/open-event-android/issues/382)

**Comment by aayusharora** [comment]
![4](https://cloud.githubusercontent.com/assets/12194719/15867118/461c7e70-2cea-11e6-9a9a-2d358a79eb95.png)

**Comment by aayusharora** [comment]
![9](https://cloud.githubusercontent.com/assets/12194719/15867265/23e400ca-2ceb-11e6-8fac-92e8e3cead14.png)

**Comment by aayusharora** [comment]
Solved here https://github.com/fossasia/open-event-webapp/pull/241

**Comment by aayusharora** [comment]
@mariobehling  It is done  Closing it :)
