### ISSUE TITLE
Configure builder to use esbuild and reduce the overall build time

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-webapp#2394]
The generation of site comprises of the following steps:

1. Downloading the assets from ZIP/server. This includes JSON and images/audio/slides
2. Running template engine and generating HTML from the JSON files
3. Copying JS and CSS files and minifying and bundling them

Only the first step is something which should be allowed to be slow. Running the template engine should not take more than a second and copying and minifying the JS and CSS files is not transpiling huge trees of node_modules like in react, vue or ember. It's using traditional JS/jQuery which just needs minification. Thus, it is unacceptable for website generator to take more than 2 seconds except for the downloading part. It is literally just copying files here and there.

Please reduce the time it takes to build a site and use esbuild https://github.com/evanw/esbuild to speed up the process even more

**Comment by dhruvjain99** [comment]
@iamareebjamal I noted down the time taken by different steps in the web generation process by logging. The html-minifier npm package used to minify the html template compiled by the handlebars is taking 3-4 seconds, rest of the steps combined not even take more than 1.5 seconds to complete (excluding the error generated by the mailing server in the end). If you know any alternative for html-minifier which is fast, please let me know.

**Comment by iamareebjamal** [comment]
I don't think we need to minify the HTML, so just remove it
