### ISSUE TITLE
Replace Travis with GitHub Actions

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-webapp#2412]
Travis has shut down its open source plan. Please shift to GitHub actions

**Comment by dhruvjain99** [comment]
I am working on this

**Comment by dhruvjain99** [comment]
@iamareebjamal do we have to run the test only for specific branches (master and development)? If this is the case then I'll add filter in the workflow otherwise I'll keep it open.

**Comment by iamareebjamal** [comment]
open

**Comment by dhruvjain99** [comment]
@iamareebjamal it is quite weird to find circleci working once i.e. all test cases passed but now the same workflow when rerun, one test file fails with the same error which was coming earlier.
If I change the resolution of the display by passing args, the tests pass for that file but fail for the other.

**Comment by iamareebjamal** [comment]
Please create a PR and disable that test. Something is better than nothing

**Comment by dhruvjain99** [comment]
@iamareebjamal Can we schedule a 15 minutes meet in order to discuss the issue so that I can screen share and show the behavior of the ci?

**Comment by iamareebjamal** [comment]
https://meet.jit.si/eventyay-technical

**Comment by dhruvjain99** [comment]
@iamareebjamal I have tried using the latest stable google chrome and its driver, but it is still failing on some new tests now and tried changing the screen resolutions as well but to no avail.

**Comment by iamareebjamal** [comment]
Create the PR please. Something is better than nothing
