### ISSUE TITLE
Fix email sending logic

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-webapp#2413]
Email sending step fails after generation, please fix it

**Comment by sachin-duhan** [comment]
can I work on this issue?

**Comment by btapash** [comment]
I am working on this!

**Comment by Sloth-Panda** [comment]
Would like to take this issue

**Comment by guptapranav4299** [comment]
I would like to work on this issue @iamareebjamal

**Comment by sans2801** [comment]
Hello @iamareebjamal I'd like to know if the issue is open and pending

**Comment by palakshivlani-11** [comment]
@iamareebjamal  Can I work on this issue.

**Comment by mariobehling** [comment]
Looks like this is no longer valid.
