### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [fossasia/open-event-webapp#2639]
I would like to create a file contributing.md and add following -
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

**Comment by pratistha-05** [comment]
Can I work on this as I'm just exploring open sourcing?

**Comment by khareyash05** [comment]
Ya sure @pratistha-05

**Comment by Ash-KODES** [comment]
Can I work on this @khareyash05 ? I think old assinee is inactive
