### ISSUE TITLE
fix the layout of the buttons

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#264]
@aayusharora The buttons have gotten a bit muddled up, please fix the layout on it 
![screenshot from 2016-06-10 17-49-00](https://cloud.githubusercontent.com/assets/1327050/15964006/bd2f1dc4-2f33-11e6-8e93-98be14789dbd.png)

**Comment by aayusharora** [comment]
@championswimmer , doing it

**Comment by championswimmer** [comment]
Is done. Closing
