### ISSUE TITLE
Add a button to upload logo for the webapp

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#265]

**Comment by mariobehling** [comment]
What is this about? The logo is already defined in the JSON.

**Comment by aayusharora** [comment]
@mariobehling  , it was decided today in the discussion , that we need this  @championswimmer, if the json contain the logo itself than we can take it from there.

**Comment by mariobehling** [comment]
@aayusharora Which discussion? Which issue?

**Comment by championswimmer** [comment]
Ok we can take it from here 
https://github.com/fossasia/open-event-webapp/blob/master/mockjson/event.json#L58
