### ISSUE TITLE
 View schedule according to tracks and time

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#268]
![7](https://cloud.githubusercontent.com/assets/12194719/15990095/9d37a026-3092-11e6-83bf-362ce6910182.png)
@mariobehling, @championswimmer, @juslee I want to work for this mockup, Its bit challenging when we have to do it with tpl. But, I will try to have something like this .

Details about Mockup
1. Tracks are denoted by colors.
2. On  click, of each track, description of the track is shown. 

- [x] Make a file tracks.tpl compile it and make it available in ZIP when a user clicks on generate app.
- [x] Design Markup for the tracks.tpl.
- [x] Write SASS file for tracks.tpl.
- [x] Add an anchor in navbar of schedule.tpl, view by tracks.
- [x] Add Markup for Pop-over , on clicking on each tag.
- [x]  Add SCSS and JS for Pop-over.
- [x] Bind data in pop-over.

**Comment by mariobehling** [comment]
Please provide a description and screenshots before you implement it. So others can give feedback first.

**Comment by aayusharora** [comment]
@mariobehling , working on it .

**Comment by mariobehling** [comment]
Ok, great. Looks like, we can also use it in the server then. Cheers.

**Comment by aayusharora** [comment]
@mariobehling  @championswimmer  All done with PR #296 #300. UI improvement still needed.
