### ISSUE TITLE
heroku not loading bootstrap

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#294]
@championswimmer see this for reference :
![5](https://cloud.githubusercontent.com/assets/12194719/16076993/d94730c2-32fe-11e6-8466-faf1478d2fa2.png)

Error in Console 
![6](https://cloud.githubusercontent.com/assets/12194719/16077069/45a1d538-32ff-11e6-9976-2960836513e9.png)

**Comment by championswimmer** [comment]
![screenshot from 2016-06-16 20-52-36](https://cloud.githubusercontent.com/assets/1327050/16122341/4d8445f0-3404-11e6-8686-795165739ff0.png)

Working in the OR #297
