### ISSUE TITLE
Generator: Make the script download the images and audio in API response

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#298]
If an API endpoint is given, it will have audio and speaker image urls in the json response.
Make the generator.js download and save them locally to assets/audio and assets/img folders.

FUTURE: Make this optional with a checkbox in the generator. 
option1 : Download and save images and audio with the webapp (makes huge zip)
option2: Always live-load audio and images from remote URLs. (may not work with CORS etc)
Organiser weighs pros and cons of both options and choses accordingly.

**Comment by championswimmer** [comment]
@mariobehling Take a look. Does this make sense. Anything to add or improve in this feature ?

**Comment by mariobehling** [comment]
Good idea. Yes, make this optional.

**Comment by championswimmer** [comment]
completed all features via this https://github.com/fossasia/open-event-webapp/pull/370
