### ISSUE TITLE
tracks view: [bug] content going under the titlebar

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#299]
![screenshot from 2016-06-17 01-12-09](https://cloud.githubusercontent.com/assets/1327050/16130844/98dbcc70-3428-11e6-876c-f9398ef4cd4b.png)

OS : Ubuntu 16.04
Browser: Firefox 46.0.1

**Comment by championswimmer** [comment]
@aayusharora please check this out

**Comment by aayusharora** [comment]
@championswimmer please check this now https://github.com/fossasia/open-event-webapp/pull/296 it seems that CSS is not loaded in your browser.

**Comment by aayusharora** [comment]
After the loading of CSS it will get margin-top as 8%

**Comment by championswimmer** [comment]
solved
