### ISSUE TITLE
Responsivity of Tracks page

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#301]
It should support the break points

(min-width:320px) { /* smartphones, iPhone, portrait 480x320 phones */ }
(min-width:481px) { /* portrait e-readers (Nook/Kindle), smaller tablets @ 600 or @ 640 wide. */ }
( min-width:641px) { /* portrait tablets, portrait iPad, landscape e-readers, landscape 800x480 or 854x480 phones */ }
 (min-width:961px) { /* tablet, landscape iPad, lo-res laptops ands desktops *
 (min-width:1025px) { /* big landscape tablets, laptops, and desktops */

**Comment by aayusharora** [comment]
Solved here #312.

**Comment by championswimmer** [comment]
Done.
