### ISSUE TITLE
Use track.json to bind the color associated with each track  

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#302]
Currently session.json is used to take out the information of tracks. But, it does not contain data such as **track color** which will be decided by the organizer.
Hence, binding of the color is not done yet.

- [x]  Parse track.json 
- [x] Extract data and bind colors to track.tpl.

**Comment by aayusharora** [comment]
@championswimmer @juslee Solved here https://github.com/fossasia/open-event-webapp/issues/302

**Comment by championswimmer** [comment]
Awesome.  Looks good!
