### ISSUE TITLE
Write tests for the folding script

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#306]
We need tests for the functions in `fold.js` 

We can test them using the mockjson folder (as a source of example jsons).

**Comment by aayusharora** [comment]
@championswimmer , What we are using for it ? I am finding Jasmine as a suitable option.

**Comment by championswimmer** [comment]
@aayusharora Was thinking the same. 
Was evaluating mocha vs jasmine. We can go with jasmine. Is looking suitable to me

**Comment by aayusharora** [comment]
Tasks to be done 

- [ ] Set up Jasmine with node-jasmine.

- [ ]  Run the tests for fold.js and app.js

**Comment by aayusharora** [comment]
@championswimmer @mariobehling  Setup done #326
