### ISSUE TITLE
Images not coming in pop-over track

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#313]

**Comment by championswimmer** [comment]
src fields are blank. gotta fix track folding

**Comment by aayusharora** [comment]
are you working for the same already ?

**Comment by aayusharora** [comment]
I am not seeing it corrected after fixing the jsons

**Comment by championswimmer** [comment]
I will do this. You can work on the other views. I have to look at the JSON formats for v2 migration, and also for downloading of images and audios anyway.

**Comment by aayusharora** [comment]
cool :)

**Comment by aayusharora** [comment]
Thanks @championswimmer  Solved #338
