### ISSUE TITLE
Mockup for schedule according to Rooms

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#328]
![18](https://cloud.githubusercontent.com/assets/12194719/16232433/36d64c04-37d3-11e6-9d4e-a4a2ed45e0f8.png)
@mariobehling @championswimmer  Any other suggestions ?

**Comment by mariobehling** [comment]
Sorry, but I do not understand it. It should be a table.

**Comment by aayusharora** [comment]
@mariobehling, ok Let me clear the design
1. Each session has a start date which is there at left side of card.
2. The right side of card contains the room information, currently I don't have much to relate with [microlocation.js](https://github.com/fossasia/open-event-orga-server/tree/development/samples/ots16).
3 . The Cards are sorted according to date and time.
Do we want simple than that, just a table https://events.google.com/io2016/schedule#day1, similar to that ?

**Comment by championswimmer** [comment]
| Day/Time   | Hall 1   | Hall 2   | Hall 3   | Hall 4   |
|------------|----------|----------|----------|----------|
| Day1: 9am  | Session1 | Session2 | Session3 | Session4 |
| Day1: 10am | Session5 | Session6 |          |          |
| Day2: 9am  |          | Session7 |          | Session8 |
| Day2: 10am | Session9 |          |          |          |
| Day2: 1pm  |          |          |          |          |

**Comment by championswimmer** [comment]
@aayusharora, I think @mariobehling means a format like this ^

Am I right @mariobehling  ?

**Comment by aayusharora** [comment]
@mariobehling @championswimmer I am still in doubt, if this design is suitable.
Reason 1. The number of halls mentioned as Hall 1 etc in horizontal <thead> will increase. Hence a scrollbar will have to be there on xaxis.

**Comment by aayusharora** [comment]
![4](https://cloud.githubusercontent.com/assets/12194719/16306730/5fc4e464-3967-11e6-927e-5e0128cc08cb.png)

**Comment by aayusharora** [comment]
@championswimmer @mariobehling  Can you please check this table format ? Here there are two columns one is session name and second column is Room Information with time.

**Comment by mariobehling** [comment]
@aayusharora Please proceed as outlined by @championswimmer Cheers.

**Comment by aayusharora** [comment]
Ok @mariobehling  Thanks

**Comment by championswimmer** [comment]
If you think it'll take too much horizontal space, make it like this 


| Day/Time   | <   Hall1   >  |
|------------|----------------|
| Day1: 9am  | Session 1      |
| Day1: 10am | Session 2      |
| Day2: 9am  |                |
| Day2: 10am | Session 3      |

| Day/Time   | <   Hall2   >  |
|------------|----------------|
| Day1: 9am  | Session 4      |
| Day1: 10am |                |
| Day2: 9am  | Session 5      |
| Day2: 10am | Session 6      |


The "<" and ">" buttons are to change locations

**Comment by championswimmer** [comment]
@mariobehling does that look better

**Comment by championswimmer** [comment]
| Day/Time   | Session   |
|------------|-----------|
| *Hall 1*   |           |
| Day1: 10am | Session 1 |
| Day2: 9am  | Session 5 |
| Day2: 10am | Session 6 |
| *Hall 2*   |           |
| Day1: 9am  | Session2  |
| Day2: 10am | Session3  |
| Day2: 11am | Session4  |
