### ISSUE TITLE
API: Migrating to the new server API

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#334]
Sample json files for V2 are availabel here 
https://github.com/fossasia/open-event-orga-server/tree/development/samples/ots16

We have to start with modifying out fold.js functions to suit the new format. The differences aren't too many.

**Comment by aayusharora** [comment]
Yup, I will also contribute to this

**Comment by championswimmer** [comment]
Since fold.js needs significant rewrite for this, we can look at offloading some work to frontend js files ?

**Comment by championswimmer** [comment]
Like I had mentioned before, we can make a openevent.js library for frontend. The .json files will be present along with index.html anyway, so the clientside js lib can live-load the data (like we do in Angular like webapps)

**Comment by aayusharora** [comment]
I like the idea for Openevent.js library and directly accessing its functions on front-side. But, can we make this an issue for later milestone. This will require significant changes on both Frontend and Backend.

**Comment by championswimmer** [comment]
@aayusharora will assign the frontend library-fication on a later milestone, correct !

**Comment by aayusharora** [comment]
Yeah correct @championswimmer.

**Comment by aayusharora** [comment]
all done !!!
