### ISSUE TITLE
Adopt import to import zip with all JSON files

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#336]
In the Orga-Server we changed the JSON import/export into a zip file with all files inside. Please implement this for the app generator too. So users can import a the zipped JSON files instead of single files.

**Comment by championswimmer** [comment]
A zip containing all the JSON files ?

**Comment by aayusharora** [comment]
@championswimmer , it's like only one option to upload => and then admin zip will extract multiple files.
Now only one button from frontend to upload JSON's.

**Comment by the-dagger** [comment]
@championswimmer @aayusharora How do you plan to upload the zip file to the server?
Since on the Android side, we are using an Apache server, I couldn't find any specific resources for it.

**Comment by aayusharora** [comment]
@championswimmer  I am working for this .

**Comment by aayusharora** [comment]
Solved by PR #411
