### ISSUE TITLE
Add the tuples microlocation in sessions.json according to V2 API

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#346]
Consider this to update sessions.json present in mockjson folder.
https://github.com/fossasia/open-event-orga-server/blob/development/samples/ots16/sessions.json

**Comment by aayusharora** [comment]
@mariobehling  @championswimmer  Solved here #347

**Comment by mariobehling** [comment]
I cannot look right now at the details of this commit, but just to be sure: Are you sticking to the JSON/Api outline here? https://github.com/fossasia/open-event-orga-server/blob/master/docs/API.md

There is a dedicated API for microlocations. More details are also here: https://open-event.herokuapp.com/api/v2/

Please confirm that you are implementing the 7 APIs/JSONs now.

**Comment by aayusharora** [comment]
@mariobehling , I have followed the guidelines of the V2 API , Currently I have only added the microlocations according to https://github.com/fossasia/open-event-orga-server/blob/development/samples/ots16/sessions.json . so that I can start with Room page.Yes I will stick to the links provided above.

**Comment by championswimmer** [comment]
That's right @aayusharora , i prefer this approach too

**Comment by aayusharora** [comment]
Thanks Its done #347 Closing this :)
