### ISSUE TITLE
Choosing the downloading option doesn't load images

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#396]
Images get successfully downloaded but come on the page on refresh.
![22](https://cloud.githubusercontent.com/assets/12194719/16522204/e0092f38-3fb9-11e6-84c4-667064967b71.png)
![23](https://cloud.githubusercontent.com/assets/12194719/16522208/e46a7f3c-3fb9-11e6-8d8a-4ebeb53387d9.png)

**Comment by championswimmer** [comment]
They are not present first time ? 
They come after refresh ? 

Does it work if hosted with `http-server` or `python -m SimpleHTTPServer` ? 
I think this happens only when working on file:// mode

**Comment by championswimmer** [comment]
@aayusharora can you check again ? 

I just tried, and it seems to work

**Comment by aayusharora** [comment]
Works fine on Heroku .
