### ISSUE TITLE
discrepancy in session start times in rooms.html

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#398]
<img width="783" alt="screen shot 2016-07-02 at 11 22 28 am" src="https://cloud.githubusercontent.com/assets/1327050/16538617/5b1c2ad0-4047-11e6-893d-5d14db75365c.png">
How can so many sessions start all at 0930 in  the same room ?

**Comment by aayusharora** [comment]
@championswimmer  Please check sessions.json, most of it is marked with start_time 7:30 with after a 'utf-2' comes out to be 9:30.

**Comment by aayusharora** [comment]
Can we close this ? @championswimmer

**Comment by aayusharora** [comment]
Please reopen if you find it a bug @championswimmer .
