### ISSUE TITLE
[v2 event.json] move services -> social_links

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#410]
new api
![screenshot from 2016-07-04 23-16-16](https://cloud.githubusercontent.com/assets/1327050/16567530/599d3490-423d-11e6-92be-9b41107431e1.png)

old api
![screenshot from 2016-07-04 23-16-22](https://cloud.githubusercontent.com/assets/1327050/16567531/59a65318-423d-11e6-82aa-5ea69598a644.png)

**Comment by mariobehling** [comment]
Please give us text instead of screenshots of code. You can use markup, if you want it to look different.
