### ISSUE TITLE
Add new features to the webapp

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#452]
@mariobehling @aayusharora 

Let us jot down some more new features that we can add to the webapp in the next few milestones.

**Comment by aayusharora** [comment]
1. Infinite Scroll on speakers page
Features such as this can be implemented only when the data is fetched from the front-end side.
@championswimmer what's your suggestion ?

**Comment by championswimmer** [comment]
We can use js to load from the json (the jsons are avaialble in the zip file)

**Comment by mariobehling** [comment]
Closing this issue. If you propose new features, please create an issue with a specific feature proposal.
