### ISSUE TITLE
Only store files locally and do not give other options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#455]
As mentioned - many - times the goal of this app is to enable organizers to store data locally. Therefore we currently do not need options for external data storage even if it is big. Please stop adding more confusing choices for the user.

![screenshot from 2016-07-11 15 01 10](https://cloud.githubusercontent.com/assets/1583873/16731501/b5682588-4778-11e6-9b1b-3a018cde5283.png)

**Comment by championswimmer** [comment]
done
