### ISSUE TITLE
Increase sizes of social media buttons in speaker profile and other places 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#46]
Buttons are too small for mobile users.

**Comment by championswimmer** [comment]
Done here https://github.com/fossasia/open-event-webapp/pull/47

**Comment by mariobehling** [comment]
I see you have the republica test data now. Good! However there are not any social media buttons now.

**Comment by championswimmer** [comment]
Because the data returned from the json doesn't have the social links
anymore.

**Comment by mariobehling** [comment]
The relevant data is shown on the republica site. I wonder where the data comes from. If these fields are missing, please propose a change to the redata format and create a fork implementing necessary changes.

**Comment by mariobehling** [comment]
This issue has not been solved. Please cooperate with @rafalkowalski until the data is displayed.

**Comment by AmayAgrawal** [comment]
I have added much data here #111 .

**Comment by ashutoshsaboo** [comment]
Is this issue solved @mariobehling ? Can I work towards this?

**Comment by SaptakS** [comment]
@AmayAgrawal you can change the data in testapi for testing purpose but I guess that doesn't solve the problem of why the data is not available if its shown in republica site.

**Comment by ashutoshsaboo** [comment]
@mariobehling Please have a look at this PR - https://github.com/fossasia/open-event-webapp/pull/130 . Please suggest in case if any other changes are required. Thanks. :smile:

**Comment by SilentFlame** [comment]
@ashutoshsaboo 
just a humble suggestion, please before creating a PR check the directory in which you have changed files,
there might be soem files open for editing which creates a file `filename.extnsn~` , which is added while you commit with the original changes.
delete that file before pushing.
