### ISSUE TITLE
Using Compression Middleware

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#467]
@championswimmer @mariobehling The side is slow because of 65.2 MB of data that browser loads. 
This is not constant number and will increase as the amount of audio files and images increases.

Proposed solution 
I have gone through some links for best practices https://expressjs.com/en/advanced/best-practice-performance.html and find out the compression middleware.

I hope it will improve performance @championswimmer  what's your suggestion ?

**Comment by mariobehling** [comment]
Why does the browser need to load all audio files even if they are not clicked?

**Comment by aayusharora** [comment]
@mariobehling  Whenever we generate the webapp the links of photos and audio files are fetched from JSONS and a folder dist/audio and dist/images are made in which these files ( along with other files)  are saved.
the route /live/preview serves us a standalone folder which has all audio files and images. The images and audio are linked from the folders. Hence the browser loads all audios linked to it.

**Comment by championswimmer** [comment]
Using compression middleware would be a good idea

**Comment by championswimmer** [comment]
done
