### ISSUE TITLE
Implement standard project workflow

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-webapp#471]
Please implement the standard project workflow with a development branch. 
* [x] Keep the master dev branch to deploy to heroku.
* [x] Add a deployment to heroku from the dev branch.
* [x] Increase code coverage. (Why is it only 30%?)

**Comment by championswimmer** [comment]
@hpdang @mariobehling 
First two points are already done 

https://open-event-generator.herokuapp.com - for master
https://opev-webgen-dev.herokuapp.com - for dev

**Comment by mariobehling** [comment]
@championswimmer Thanks for adding the Heroku badge.

Please do add a "deploy to heroku" badge. It is not there. Second point is not done.

Please also include documentation in the /docs folder.

**Comment by championswimmer** [comment]
@mariobehling done point 2 now

**Comment by championswimmer** [comment]
@hpdang 56% is covered. In the next few days will cover even more. 

Please close the issue if all looks good :)

**Comment by mariobehling** [comment]
Thanks! Good job.
