### ISSUE TITLE
Add documentation and installation information

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#478]
There is a folder /docs now. Please add detailed information how to set up the app
* [x] locally
* [x] On a server
* [x] On Heroku
* [x] Also include screenshots
* [x] Update screenshots to latest app version
* [x] remove generator subdir in src, and de-nest the structure

**Comment by championswimmer** [comment]
add server deployment info here 
https://github.com/fossasia/open-event-webapp/pull/495

**Comment by mariobehling** [comment]
What about this issue? When will you remove the generator subdir in src, and de-nest the structure?

**Comment by championswimmer** [comment]
I put the PR twice. But there is always some PR or other pending, and
conflict arises and other high priority comes, so I keep it for later.

Since it changes the whole directory structure, that PR will conflict with
any other PR that is pending at that point of time.

**Comment by mariobehling** [comment]
Ok, got it. So, just make a PR for that change only and merge yourself right away.

**Comment by championswimmer** [comment]
Done via 
https://github.com/fossasia/open-event-webapp/pull/608
