### ISSUE TITLE
Implement clearer sorting of events unclear

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#48]
What is the sorting of sessions here? http://fossasia.github.io/open-event-webapp/#/sessions

A simple, but efficient way here as an example: http://2015.opentechsummit.net/programm.html

**Comment by championswimmer** [comment]
It is addressed here  
https://github.com/fossasia/open-event-webapp/pull/61

**Comment by mariobehling** [comment]
Has this been deployed? Please describe how this has been implemented and provide a screenshot. I do not see that this is fixed on the test site.

Additional point: It is loading very slow.

**Comment by championswimmer** [comment]
I'll update the test site.

For loading I'll open a new issue. Mohit has already mentioned that in his
comment and suggested a way to do it. I'll do so accordingly.

**Comment by championswimmer** [comment]
@mariobehling

Updated here http://fossasia.github.io/open-event-webapp/#/sessions

Segmentation by day is done. Loading is still slow, it'll improve once we
have pagination done. :)

**Comment by championswimmer** [comment]
https://github.com/fossasia/open-event-webapp/pull/65
