### ISSUE TITLE
Erroneous app link in README

### ISSUE THREAD

**Issue by jig08** [fossasia/open-event-webapp#488]
In `README` the link mentioned for usage as [https://open-event-generator.herokuapp.com](https://open-event-generator.herokuapp.com) seems erroneous.  

![screenshot from 2016-07-15 11 12 19](https://cloud.githubusercontent.com/assets/9291400/16878768/e11a39d6-4a7b-11e6-84d9-97f01fbc6222.png)

Also, I believe this is the link to generate events by importing JSON Files ?

**Comment by aayusharora** [comment]
Hi, @jig08 the URL is changed yesterday, updating in the readme in a minute 
Development branch : opev-webgen-dev.herokuapp.com 
Master Branch : opev-webgen.herokuapp.com

**Comment by jig08** [comment]
@aayusharora Thanks !

**Comment by championswimmer** [comment]
@jig08 @aayusharora fixed
