### ISSUE TITLE
Avoid popups and implement expansion instead

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#49]
Popups on phones result in additional clicks, e.g. speaker info - I have to close it in order to continue. Saving the user time is better.

Please implement expansion below the item instead. How expansion can work see here: http://2015.opentechsummit.net/programm.html

![screenshot from 2015-08-09 16 21 14](https://cloud.githubusercontent.com/assets/1583873/9155270/e3a38e4e-3eb2-11e5-89ec-9d57bd2007df.png)

**Comment by championswimmer** [comment]
@creativepsyco @mariobehling 

Should I remove popups for both speakers and sessions, or only speakers ? 

For sessions, if I remove popups, and make expandable lists, we will lose the option to have direct URL links to sessions 
like example : https://events.google.com/io2015/schedule?sid=ab8c9f91-b6d4-e411-b87f-00155d5066d7#day1/ab8c9f91-b6d4-e411-b87f-00155d5066d7

**Comment by mariobehling** [comment]
I think we need to consider, what is the best interface and test on different platforms. Let's move this question to later and focus on other things first.

**Comment by aayusharora** [comment]
Hi, @mariobehling ,I want to work on this bug. Can u assign it to me?

**Comment by championswimmer** [comment]
You can work on this regardless of who it is assigned to ;)

**Comment by aayusharora** [comment]
Thanks @championswimmer ,can you describe about the problem we are facing in removing popup from sessions?

**Comment by SaptakS** [comment]
I agree with @championswimmer that if we use expansion instead of popups for sessions, we wont be able to give direct url links to a particular session.

**Comment by aayusharora** [comment]
Hi @championswimmer  ,should it be done same for other pages ..like speakers .Also what about the sponsor page ,it is also like them ,should it also be changed?

**Comment by aayusharora** [comment]
I totally agree @SaptakS  ,but we can keep it as a design as suggested by @mariobehling .

**Comment by AmayAgrawal** [comment]
So basically we have to remove pop-up or let it be as it is.

**Comment by SaptakS** [comment]
That is what we were discussing on. Would really like to know your viewpoint as well. @championswimmer @mariobehling any further thoughts on this issue?

**Comment by AmayAgrawal** [comment]
I think also the pop-up looks good as we can direct url to particular session.We can implement something new particularly for mobile.Otherwise from pc point of view it sounds good.

**Comment by championswimmer** [comment]
I personally feel from a UX point of view, the popups are better. Plus
direct URLs work.

**Comment by SaptakS** [comment]
@championswimmer +1 on that

**Comment by AmayAgrawal** [comment]
I think that direct URL's of speaker as well as sessions is very useful.Because if we are seeing a information about particular session,then in the speaker section it should contain the speaker name as well as on clicking the link it should take on the information page about that speaker.
