### ISSUE TITLE
Make Dynamic Footer with popup dissimilar to sched.org

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#500]
The footer used by sched.org are not dynamic which causes basic problem for the last item to take its height 
![13](https://cloud.githubusercontent.com/assets/12194719/16956759/4ddd16b4-4df7-11e6-83df-99665a616c9f.png)

This will make a problem as it will not provide the pop-over height to take its space on page.

**Comment by aayusharora** [comment]
@mariobehling @championswimmer done with #502

**Comment by mariobehling** [comment]
@aayusharora It would be good to provide a link from now on to the sample webapp. Could you do that, please?

**Comment by aayusharora** [comment]
Will be providing link ahead. This is merged and good to close.
