### ISSUE TITLE
UX Improvement Track page

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#501]
- [x] Fix Responsiveness
- [x] Add speaker organisation and social links along with image
- [x] Change popover box to close on un-hover state rather than click as sched.org
- [x] Implement Dynamic Footer
- [x]  UX :Add Hover state to track hovered

**Comment by aayusharora** [comment]
@mariobehling  @championswimmer  Solved with PR #502

**Comment by mariobehling** [comment]
Please provide a screenshot in future.

**Comment by aayusharora** [comment]
Sure @mariobehling , closing this its done #502
