### ISSUE TITLE
Add Track names with their color codes on room page 

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#504]
The roompage has colorful session names but it's not written anywhere that which color is from which track. This is confusing for a user to go back to track page and check the room page again.
Please make the information available on room page as sched.org does.

- [x] Add title of track with the color it belongs too.
- [x] Make the portion work well on small screens as sched.org

**Comment by mariobehling** [comment]
Please ensure, you are using the color defined in the tracks.json. You can see an example here https://github.com/fossasia/open-event/blob/master/sample/OTS16/tracks.json

**Comment by aayusharora** [comment]
@mariobehling Yes, definitely all colors are coming from tracks.json.

**Comment by aayusharora** [comment]
Done here #527
