### ISSUE TITLE
Generator: Implement UI and backend to enter Github credentials and deploy to Github Pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#506]
Parent Issue: https://github.com/fossasia/open-event-webapp/issues/275

Please enable the user to deploy the website directly from the generator page to their github pages repository. 
* [ ] Ensure the user can choose the repository and 
* [ ] Check if it is possible that the user can create a repository when connecting the app with Github.
* [ ] Propose a UI and implement it
* [ ] Implement the backend so several users could use the deployment function at the same time

**Comment by championswimmer** [comment]
I have experimented with the github api today, and the github 'contents' api ( https://developer.github.com/v3/repos/contents/) provides no method to "force push" 

To be able to host gh-pages, we need force-push functionality.

**Comment by championswimmer** [comment]
@mariobehling can we close this for now ? 
I saw github apis (link in above comment), and it is not possible to force push to gh-pages. 
I am not sure without that, how we can implement this functionality.
