### ISSUE TITLE
Generator: Implement UI and backend to enter credentials and deploy website via ftp

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#507]
Parent Issue: https://github.com/fossasia/open-event-webapp/issues/275

Discuss the challenge to implement this and estimate the time required.

Please enable the user to deploy the website via ftp
* [x] Ensure the user can choose the folder and 
* [x] Check if it is possible that the user can create a folder
* [x] Propose a UI and implement it
* [x] Implement the backend so several users could use the deployment function at the same time

**Comment by championswimmer** [comment]
done here https://github.com/fossasia/open-event-webapp/pull/632
