### ISSUE TITLE
Web Generator: Ensure preview files/sites do not conflict with several users using app at same time

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#508]
Previously preview apps were saved at http://opev-webgen-dev.herokuapp.com/live/preview/ . They are now save at http://opev-webgen-dev.herokuapp.com/live/preview/emailaddress@email.com/eventname/ 

Even though it is unlikely that there are conflicts, there could be still conflicts. Please ensure that there are no conflicts if there are several users using the app at the same time. How do you ensure this?

Please propose and implement a solution. What about hashes?

**Comment by championswimmer** [comment]
If an app is being created at abc@xyz.com/eventone 
Then if someone tries to create with same parameters 
email = abc@xyz.com
app = eventone

We will give them an error saying an app using these names is already being generated, wait till it is built.

**Comment by mariobehling** [comment]
yeah, sounds good.

**Comment by championswimmer** [comment]
this feature exists.
