### ISSUE TITLE
Avoid internal page scroll bars

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#515]
A number of areas have internal scroll bars, e.g. speakers page and on scroll over session information on tracks page etc.

List all pages with internal scroll bar here and implement a style without scroll bars.

**Comment by aayusharora** [comment]
Hi,@mariobehling
Areas having scrollbars 
1. Pop-overs
2. Speaker section
Internal Scrollbars are not necessity but requirement. For example let's say the the speaker section. We don't want the cards to be of unequal sizes. So we fix the max-height of each card and if the speakers description exceeds the height we give a scrollbar to prevent overflow text.
Hence you can see for better UX
1. No scrollbar is present until you hover the card.
2. Only those cards have scrollbars whose speaker description exceeds maximum card limit. This is intentionally done and will not cause any problem.

Pop-overs
Currently in the design I have set height of pop-over as auto means it can take height according to data but Its necessary to set a maximum height.Obviously No internal scrollbar will come if number of speakers are less. Hence it depends on data just to cover overflow problem.

**Comment by mariobehling** [comment]
Ok, thanks for the listing. Now please implement

* [ ] No scroll bars in 1. Pop-overs
* [ ] Design with no scroll bars in 2. Speaker section (make a screenshot how it will look like.
* [ ] Ensure all works well in mobile
