### ISSUE TITLE
Test pages, images, links, design, on page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#516]
Before you implement more features, please test the whole site in detail, e.g.
* [x] images are not shown (no need for explanation, rather open an issue and outline a solution)
* [x] Check all links, e.g. home screen not linking to defined home
* [x] Rethink usability, why are there different font sizes in dropdown menu?
* [x] Pages in small resolution are not using full width and breaking style sometimes. Examples below.

Words broken and why not using space on the right?
![screenshot from 2016-07-23 05 43 42](https://cloud.githubusercontent.com/assets/1583873/17075602/bdacda94-5098-11e6-8cd3-3695af8af3b9.png)

Why not full width?
![screenshot from 2016-07-23 05 44 13](https://cloud.githubusercontent.com/assets/1583873/17075603/c1a6db54-5098-11e6-9354-ff4f3299a910.png)

**Comment by championswimmer** [comment]
assigning @aayusharora because he has worked on the styling of the pages mostly.

**Comment by championswimmer** [comment]
@mariobehling wanted a quick clarification. 

The "home" button should link to ? The "event_url" in the json or the sessions page ?

**Comment by mariobehling** [comment]
It depends on how we define it. At the moment it neither directs to the event_url nor the app start directory. The logo correctly links to the event URL. So, I think this is fine and we make the "Home" button direct to the "app root"

**Comment by championswimmer** [comment]
thanks! will do the same

**Comment by championswimmer** [comment]
home page link done here 
https://github.com/fossasia/open-event-webapp/pull/530

**Comment by aayusharora** [comment]
Null images replaced by generic image, Track page style not breaking now solved here #529
![1234](https://cloud.githubusercontent.com/assets/12194719/17193378/60d5117a-5470-11e6-9665-e4b68e3ed255.png)

**Comment by championswimmer** [comment]
Okay, images with links like this 
`photo.jpg?quality=89&w=800` 
are not working correctly

**Comment by aayusharora** [comment]
@championswimmer  It is done and can be closed

**Comment by aayusharora** [comment]
@championswimmer I am closing this, Please open another issue if you still find some images not working.
