### ISSUE TITLE
Use FOSSASIA event sample

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#517]
The OTS sample served well. To go into more detail, please use the FOSSASIA 16 sample for more detailed tests of events going over several days.

Event sample data: https://github.com/fossasia/open-event/tree/master/sample/FOSSASIA16

**Comment by championswimmer** [comment]
assigning this to myself. I will take responsiblity of this 

this is partly depending on this https://github.com/fossasia/open-event-orga-server/issues/1787 being resolved. once done, we might either have to make the .json suffix exception in our code, or if the suffix is dropped by server guys, we can go ahead and directly test.

**Comment by aayusharora** [comment]
@championswimmer i have already done this..  Will be pushing it today

On 24-Jul-2016 12:38 pm, "Arnav Gupta" <notifications@github.com> wrote:
>
> assigning this to myself. I will take responsiblity of this
>
> this is partly depending on this fossasia/open-event-orga-server#1787
being resolved. once done, we might either have to make the .json suffix
exception in our code, or if the suffix is dropped by server guys, we can
go ahead and directly test.

**Comment by championswimmer** [comment]
@aayusharora please wait for that issue to resolve. do not make changes before we have a solution on whether or not we will use .json extension

**Comment by championswimmer** [comment]
FOSSASIA sample data is working except images of speakers.

**Comment by championswimmer** [comment]
![screenshot from 2016-07-28 21-31-09](https://cloud.githubusercontent.com/assets/1327050/17219882/b5944aa6-550a-11e6-8fda-251ac5d13a39.png)
![screenshot from 2016-07-28 21-31-25](https://cloud.githubusercontent.com/assets/1327050/17219883/b597a160-550a-11e6-8c82-4d2044c60fda.png)

**Comment by aayusharora** [comment]
@championswimmer It is working fine but images of Speakers will be available after merging #521 as images are uploaded in ZIP itself.

**Comment by aayusharora** [comment]
1. Also All Tracks here are of same color because the colors in JSON is same.
2. Tracks are not sorted for which I am working on #532 will be generating a PR in a minute.
3. The above navbar should have a fixed height as the number of tracks that are on different date increases the navbar height will also increase which will create the problem for the heading to be visible.

Please report any other bug if you find here.

**Comment by championswimmer** [comment]
Okay. So I am closing the issue, because the images have to be covered in the existing issue https://github.com/fossasia/open-event-webapp/issues/520

**Comment by mariobehling** [comment]
Why has this issue been closed? I do not understand. The sample is still not here: http://fossasia.github.io/open-event-webapp/

Issues should be closed when they are solved. What kind of understanding of issues is it.

**Comment by championswimmer** [comment]
@mariobehling I thought this issue meant only that generator will work with FOSSASIA. 

Ok I'll upload the formed website to gh-pages too.

**Comment by championswimmer** [comment]
@mariobehling 
I have uploaded here http://fossasia.github.io/open-event-webapp 

there are a few bugs here and there... like the #track-name links are wrong. we'll fix them and close this issue

**Comment by mariobehling** [comment]
Anything that is wrong in the sample, can be fixed in the sample. It is a simple JSON in a repository, so you can simply go ahead and work on it where necessary.

**Comment by aayusharora** [comment]
@mariobehling I will work for this.
