### ISSUE TITLE
Fix Scroll bar issues and implement design without scroll bars

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#518]
Parent Issue: https://github.com/fossasia/open-event-webapp/issues/515#issuecomment-234709757

In the below screenshot you can see 4 scroll bars. There should only be one scroll bar, the one to scroll from top to down.

* [x] Ensure no scroll bars in the scroll over content
* [x] Ensure the page does not scroll from left to right
* [x] Ensure all is working well on mobile screens

![screenshot from 2016-07-23 12 59 46](https://cloud.githubusercontent.com/assets/1583873/17077601/8b783e46-50d5-11e6-8810-05509db7fc05.png)

**Comment by aayusharora** [comment]
@mariobehling  This will be solved after merging  #529 Please check
![1234](https://cloud.githubusercontent.com/assets/12194719/17191514/d293b1b2-5467-11e6-96e5-b3b75f295ec7.png)
![1236](https://cloud.githubusercontent.com/assets/12194719/17191582/2bf4e2ee-5468-11e6-9aa6-e29c7547e52a.png)
