### ISSUE TITLE
Grouping Sessions by Speakers?

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-webapp#52]
### Requirements

I think when I go to speakers panel, I should be able to see what sessions that they are delivering in the event.

If there are a lot of sessions, it becomes rather difficult to see it very clearly.

**Comment by SaptakS** [comment]
We can show the sessions every speaker is addressing in the popup.

**Comment by creativepsyco** [comment]
@SaptakS yes please go ahead. Do you have a screenshot?

Lazily loading a div below the speaker bio to show what he/she is presented in the form of small cards. Also will be better if we can make it a separate controller that way we can place it wherever we show speaker information. Shall I assign this ticket to you?

Something like 
![image](https://cloud.githubusercontent.com/assets/547235/10299723/4de84138-6c20-11e5-9a7b-17988ca9bb4f.png)

**Comment by SaptakS** [comment]
What I have made is something like this:
![screenshot from 2015-10-06 10-24-41](https://cloud.githubusercontent.com/assets/9530293/10300483/8dd6d8ce-6c14-11e5-9c79-8ad47ec8279a.png)
What you are saying can also be done. I would be happy if you assign it to me.

**Comment by creativepsyco** [comment]
Cool! Sounds good @SaptakS. I think just a small card layout with session title and time is okay. And upon clicking it sends you to the linked session.

**Comment by SaptakS** [comment]
Ok. Sounds good to me.

**Comment by SaptakS** [comment]
For the time being there is no image corresponding to sessions. So I am only showing the title.

**Comment by creativepsyco** [comment]
Sounds good to me.

**Comment by SaptakS** [comment]
https://github.com/fossasia/open-event-webapp/pull/77 Please check.

**Comment by SaptakS** [comment]
I think this issue was fixed..

**Comment by creativepsyco** [comment]
ok closing it down. Cheers!
