### ISSUE TITLE
Image Folder in Zip ( instead of URL's)

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#520]
@championswimmer, @mariobehling the JSON's we were using were containing the http URL's to fetch images.
But the user can also upload images and audio files in zip.While testing Fossasia16 data I encountered this problem.

- [x] Make the code work when user upload a folder name "images" in zip.
- [x] Make the code work when user upload audio as a folder name "audio" in zip.

**Comment by championswimmer** [comment]
@aayusharora @mariobehling 
This might involve a huge time for uploading the zip, please keep that in mind.

**Comment by aayusharora** [comment]
@championswimmer  We can close this after merging https://github.com/fossasia/open-event-webapp/pull/521

**Comment by aayusharora** [comment]
It is Done !!
