### ISSUE TITLE
Document images import and resizing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#523]
Document how images are imported and changed (resized, cropped) and describe ways to change this configuration in `docs/CONFIGURATIONS.md`.

**Comment by championswimmer** [comment]
@aayusharora @mariobehling 
Let's discuss the ideal size and format of 
 1. speaker images
 2. audio files

**Comment by championswimmer** [comment]
What I have in mind is

### speaker images
256x256 pixel (max). (if lower, we will upsample them) 
Speaker's face should be in the centre, as they will be centre-cropped on the sessions page. 
format = png or jpg

### audio files
format = ogg or mp3 or m4a 
max size = 50mb

**Comment by mariobehling** [comment]
> Speaker Images

We need different sizes for different areas, e.g. on speakers page the size should be bigger than on sessions page.

> audio files

Github has 100MB max size for normal uploads. So, let's use that one.

Regarding configuration: Could we have on file somewhere that holds all the configuration option of the system, e.g. image, audio sizes, email configuration and whatever comes up?

**Comment by championswimmer** [comment]
@mariobehling So we just need to document the configuration, or do we need to provide a json file to let user to configure what size he wants ?

**Comment by mariobehling** [comment]
Yes, if a JSON file could enable the config, then that would be good. We need to be able to adapt this later to our needs. Please create a JSON config then.
