### ISSUE TITLE
Create an event front page similar to the public event page on the orga server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#524]
There was a discussion about this before and we are now at the stage where this should be included.

* [ ] Please ensure all details are added to the page
* [ ] If info in the JSON are empty the specific area should not be generated

**Comment by championswimmer** [comment]
@aayusharora let's make this page index.html and the sessions page sessions.html

Sounds right @mariobehling  ?

**Comment by championswimmer** [comment]
Noting down what all we need to generate this - 

1. event banner
2. event title
3. event tagline (optional)
4. google map container with event location
5. event address box

**Comment by aayusharora** [comment]
@championswimmer Something like eventbrite does https://www.eventbrite.com/e/demo-event-tickets-26243339535?aff=ehomecard

**Comment by mariobehling** [comment]
@championswimmer Sounds good. Thank you.

**Comment by championswimmer** [comment]
@aayusharora, that event brite layout looks good to me. that's the type we have to make here too

**Comment by mariobehling** [comment]
@aayusharora @championswimmer As the title of this issue says "page similar to the public event page on the orga server", e.g. https://open-event-dev.herokuapp.com/e/9/

Additionally to eventbrite, it shows sponsors and speakers. Please move this info to the start page as well.

**Comment by championswimmer** [comment]
thanks @aayusharora 
this is done now
