### ISSUE TITLE
Move to ES6 on node side

### ISSUE THREAD

**Issue by abhishek97** [fossasia/open-event-webapp#528]
I was just reading through the source code and thought code readability can be greatly improved by using ES6 for all the backend code(although some ES6 is in use already at some random places), this will help make the code more readable and all the goodness ES6 has to offer.

Ex:
```javascript
module.exports = {
  distPath: distPath,
  cleanUploads: function(err) {
    fs.emptyDir(uploadsPath, err);
  },
  cleanDist: function(appFolder, err) {
    fs.emptyDir(distPath + '/' + appFolder, (emptyErr) => {
      fs.remove(distPath + '/' + appFolder, err);
    });
  }
// .... some more code 
};

````

would be like

```javascript
module.exports = {
  distPath ,

  cleanUploads(err) {
    fs.emptyDir(uploadsPath, err);
  },

  cleanDist(appFolder, err) {
   const path = `${distPath}/ ${appFolder}` ;
    fs.emptyDir(path, (emptyErr) => {
       fs.remove( path , err);
    });
  },

//.... some more code
};
```

I think that instead of just randomly droping ES6 syntax anywhere , we should define some convention for that or some existing one.  I would like to work on this if this kind of thing is acceptable.

**Comment by championswimmer** [comment]
@abhishek97 If you want you can work on converting all the backend side code to ES6. 

Please ensure that this can run on Node v5 and above. 

Use this table to ensure we are using only those ES6 features that Node 5 supports 
https://kangax.github.io/compat-table/es6/#node5

**Comment by championswimmer** [comment]
@abhishek97 are you working on this ?

**Comment by abhishek97** [comment]
@championswimmer yes , will be sending pr by the end of this week 👍

**Comment by championswimmer** [comment]
I'm  closing this now 
Please feel free to reopen when you have the PR ready for it 
@abhishek97
