### ISSUE TITLE
Pop-over not working on IPhone

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#534]
No popover appears when we click on track in IPhone. It is working on all mobile devices except that.

**Comment by aayusharora** [comment]
@championswimmer Solved by #535

**Comment by aayusharora** [comment]
It is Done !!

**Comment by aayusharora** [comment]
@championswimmer Can you please checkout this. I have tried various solutions. Its working in Chrome Inspector for IOS but not in the mobile. Apart from IOS its working in all other devices.

**Comment by mariobehling** [comment]
As we are using another effect now, I am closing this.

**Comment by alexagr** [comment]
Speakers page still uses pop-up and doesn't work on iOS devices. Reopening this.

**Comment by alexagr** [comment]
sorry - just tested this on iPhone 6 - popups are still not working, even though #896 is in

**Comment by shubham-padia** [comment]
@alexagr Noticed the problem on the iphone, I had only tested in on a safari desktop as i did not have any resources to test in on the iphone at that time :smiley: .

It is working fine on safari desktop as of now, am looking into the problem why it it is not working on the iphone.

![screenshot from 2016-11-13 17-42-50](https://cloud.githubusercontent.com/assets/13910561/20245489/c57d515c-a9c8-11e6-8458-ea05e0f01791.png)

**Comment by alexagr** [comment]
@shubham-padia I wonder why we are not using standard "popover" functionality from Bootstrap?
