### ISSUE TITLE
Speakers: Implement thought through sorting, info, photo and other features

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#54]
* [x] Standard sorting of speaker should be alphabetically. Currently I do not understand what is the sorting.
* [ ] Photo missing in detail view of speakers
* [ ] No links and social channels are given
* [ ] Link to organization missing in all views
* [ ] Sessions of the speaker missing
* [ ] No sharing of social media links
* [ ] Speakers overview starts with a comma
![screenshot from 2015-08-13 08 53 44](https://cloud.githubusercontent.com/assets/1583873/9244160/de48ffea-4198-11e5-93fe-1656c611ea8f.png)

Compare with RP for example:
![screenshot from 2015-08-13 08 51 16](https://cloud.githubusercontent.com/assets/1583873/9244135/b035a50e-4198-11e5-8000-a4e84cc72a5e.png)
https://re-publica.de/member/1004#profile-speaker

**Comment by championswimmer** [comment]
sorting is implemented via pull req https://github.com/fossasia/open-event-webapp/pull/65

**Comment by championswimmer** [comment]
details of speaker in speaker dialog being added here https://github.com/fossasia/open-event-webapp/pull/69

**Comment by NRDa27** [comment]
I would really like to work on implementing these features.

**Comment by AmayAgrawal** [comment]
almost all the things have been updated here #111 .Only speaker sessions is left.

**Comment by ashutoshsaboo** [comment]
@mariobehling Please have a look at this PR - https://github.com/fossasia/open-event-webapp/pull/130 . Please suggest in case if any other changes are required. Thanks. :smile:
