### ISSUE TITLE
Preview and Download buttons pop early then they should

### ISSUE THREAD

**Issue by abhishek97** [fossasia/open-event-webapp#549]
The `Preview` and `Download` buttons pop up before the generator has completed the tasks.

Don't know why this is happening , but am pretty sure it has something to do with [this](https://github.com/fossasia/open-event-webapp/blob/development/src/generator/backend/generator.js#L80-L173).

**Comment by aayusharora** [comment]
@abhishek97  Yes this is a bug, Do you want to work for this ?

**Comment by abhishek97** [comment]
Yes, i'd like to work on this

**Comment by aayusharora** [comment]
@abhishek97 ok, Go ahead :)

**Comment by championswimmer** [comment]
No it is not those set of lines

We are downloading images and audio asynchronously. We never wait for them to finish.
When we say "live render ready", it means everything except images and audio is ready. 

We need to fix this bug. I think though, we can show the live render at the current stage. But we should allow download only after images and audio has finished downloading.

**Comment by abhishek97** [comment]
@championswimmer however, the preview & download buttons pop up even before we have "live render ready" , right after "Cleaning the dist folder". 

also i notice something weird when you set a breakpoint [here](https://github.com/fossasia/open-event-webapp/blob/development/src/generator/backend/generator.js#L182) .

**Comment by championswimmer** [comment]
That happens because the front end animation is slow  (blinking text)

The buttons show up only after the live.ready event is received in socket,
not before that

**Comment by abhishek97** [comment]
so what should be the remedy? , change frontend code to be in sync with the events emitted rather than the blinking animation?

**Comment by championswimmer** [comment]
That'll spoil the UX. It wont look good. Let me figure out.

**Comment by championswimmer** [comment]
closing this issue for now. functionally, the buttons are working, even if they come a few seconds earlier.
