### ISSUE TITLE
API endpoint not working

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#555]
@championswimmer After last merge something has broken I am using https://open-event-dev.herokuapp.com/api/v2/events/9/sessions and its throwing me the error. 
![error](https://cloud.githubusercontent.com/assets/12194719/17309840/8198dec2-585e-11e6-8b15-ba19ebd9191a.png)

**Comment by championswimmer** [comment]
This is a malformed JSON file

https://open-event-dev.herokuapp.com/api/v2/events/9/sessions

Check using JSONLint

**Comment by championswimmer** [comment]
I'll still take a look at what might be wrong

**Comment by aayusharora** [comment]
@championswimmer Zip is working correctly , I will merge development into master https://github.com/fossasia/open-event-webapp/pull/552 when the endpoint work correctly. Can we check any other endpoint if https://open-event-dev.herokuapp.com/api/v2/events/9/sessions is malfunctioned ?

**Comment by championswimmer** [comment]
@aayusharora 
https://raw.githubusercontent.com/fossasia/open-event/master/sample/OTS16 this is working for me. have a look ?

**Comment by championswimmer** [comment]
https://open-event-dev.herokuapp.com/api/v2/events/9/speakers this does not even exist : (

**Comment by aayusharora** [comment]
Ok thanks @championswimmer this is not the problem from our site.
