### ISSUE TITLE
Don't Create Objects for same speakers

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#564]
@championswimmer In the current approach, If a speaker is taking sessions of two different session-type described in JSONS as two objects having same speaker name but all other things like microlocation different. 
It is creating two objects and hence we see repeated speaker photos.

The correct approach may be is to not create such objects again. What should be the unique key. Should I not create Speaker with the  same name?  In track page we do it like by creating slug which is the combination of date and track name.

**Comment by mariobehling** [comment]
Please fix the original sample JSON instead of implementing a work around. There is an issue here https://github.com/fossasia/open-event/issues/57 Please help to resolve it.

**Comment by aayusharora** [comment]
@mariobehling This issue is different from fossasia/open-event#57. It is quite possible that a speaker is associated with many sessions. In that case the code should be written such that it will map all sessions associated with the speaker under one speaker name.Currently, it is creating multiple entries even if JSON is correct.

**Comment by championswimmer** [comment]
as per the folding code, even if one speaker has multiple session, his name
should be present only once in the speaker page. is it not happening the
same right now ?

**Comment by championswimmer** [comment]
the speaker page should have exactly as many speakers as there are objects
in the /speaker endpoint.

right ?

**Comment by aayusharora** [comment]
Exactly, but it is working to /sessions endpoint Taking all speakers from sessions data and than mapping each with speaker information. 
The bug here is      
 "session_type": {
            "id": 19, 
            "name": "Workshop, 1/2 h"
        }, 
        "short_abstract": "", 
        "signup_url": null, 
        "slides": null, 
        "speakers": [
            {
                "id": 27, 
                "name": "Ulrike Thalheim", 
                "organisation": "metacollect"
            }, 
            {
                "id": 28, 
                "name": "Moritz Beber", 
                "organisation": "metacollect"
            }
and  "session_type": {
            "id": 20, 
            "name": "Lightning Talk"
        }, 
        "short_abstract": "", 
        "signup_url": null, 
        "slides": null, 
        "speakers": [
            {
                "id": 27, 
                "name": "Ulrike Thalheim", 
                "organisation": "metacollect"
            }, 
            {
                "id": 28, 
                "name": "Moritz Beber", 
                "organisation": "metacollect"
            }

**Comment by championswimmer** [comment]
@aayusharora yeah that sounds right to me

**Comment by aayusharora** [comment]
@mariobehling  @championswimmer Solved in #562
