### ISSUE TITLE
Map and Location Info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#57]
Can you confirm, that you get the map info from the redata file of republica? What additional location info is provided?

How can additional info be provided, possibly in subtabs?
* [x] address
* [ ] how to get there
* [ ] possible links to public transport
* [ ] link to the venue home page
* [ ] microlocations with layout and additional information e.g. address/how to get there

**Comment by championswimmer** [comment]
Re data has a couple of PNG files for data about locations INSIDE the
venue.

The main location data is only name of place and lat,long

**Comment by mariobehling** [comment]
Thanks for the info. Please ensure, that the relevant data is shown on the app. Please also refer to the original FOSSASIA app to see what kind of data is displayed. It is important that participants see how to get to each session.

**Comment by championswimmer** [comment]
merging https://github.com/fossasia/open-event-webapp/issues/51

Please check out how others are implementing map views e.g. Google.
Issues below. Please find more:
* [ ] use area on top, left and right in app view
* [ ] expand map to button area and avoid sidebar scrolls if it is not needed

**Comment by AmayAgrawal** [comment]
I think that you are talking for something lke this.
https://re-publica.de/en/getting-there
