### ISSUE TITLE
No proper layout in sponsor section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#571]
Please implement a proper layout, e.g. compare the following:

![screenshot from 2016-08-05 17 57 24](https://cloud.githubusercontent.com/assets/1583873/17442491/5977f5d8-5b36-11e6-932c-8e367d051e5c.png)

And
![screenshot from 2016-08-05 18 00 28](https://cloud.githubusercontent.com/assets/1583873/17442545/85a75f36-5b36-11e6-87d6-ed162cc30d08.png)

**Comment by aayusharora** [comment]
Its Done!!

**Comment by mariobehling** [comment]
Please fix: Sponsor images not aligned in middle of row (but in top of row). Expected is: Middle of Row.

**Comment by aayusharora** [comment]
Solved here #602
