### ISSUE TITLE
Add event description to top area similar to Eventbrite pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#575]
Compare here:

![screenshot from 2016-08-05 18 10 51](https://cloud.githubusercontent.com/assets/1583873/17442872/1c87f95a-5b38-11e6-93ad-11b64ed416f6.png)

**Comment by aayusharora** [comment]
@mariobehling  This is already added here by following orga UI https://github.com/fossasia/open-event-webapp/pull/568 Please merge this.

**Comment by mariobehling** [comment]
Good first step, but let's focus more on details. Implement as shown in the screenshot. Include:
* [ ] Overlap, link and Ticket Link
* [ ] Description in "readable" color

**Comment by aayusharora** [comment]
Done !!
