### ISSUE TITLE
Sorting According to date and time everywhere

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#577]
- [x] Remove confusion at all places regarding sorting
- [ ] Apply sessions speakers room pages inside dropdown name 'Schedule'

**Comment by aayusharora** [comment]
@mariobehling  Do we need the second point 

> Apply sessions speakers room pages inside dropdown name 'Schedule'

**Comment by mariobehling** [comment]
I don't understand it. Do you have a screenshot?

**Comment by championswimmer** [comment]
we have sessions speakers and rooms page separately now. no need for links in dropdown
