### ISSUE TITLE
Missing speakers and tracks color not reflected in session

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#578]
Please compare the details of http://2016.opentechsummit.net/programm/ with http://fossasia.github.io/open-event-webapp/sessions.html

Several items are missing
* [x] Names of speaker missing
* [x] Colors of tracks not reflected in time field

![screenshot from 2016-08-05 18 54 37](https://cloud.githubusercontent.com/assets/1583873/17444086/667f7a3c-5b3e-11e6-8e9f-85802963962d.png)

**Comment by aayusharora** [comment]
Done here #612
