### ISSUE TITLE
Map zoom not suitable and address missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#579]
As here the zoom level is not suitable:
![screenshot from 2016-08-05 19 06 38](https://cloud.githubusercontent.com/assets/1583873/17444357/d4c3d1d6-5b3f-11e6-8aa5-0abe69653f0f.png)

Address can be next to map as well as contact information, if provided.

![screenshot from 2016-08-05 19 07 47](https://cloud.githubusercontent.com/assets/1583873/17444385/f58cd30e-5b3f-11e6-95fe-97b6970092cd.png)

**Comment by aayusharora** [comment]
@mariobehling I have solved this here #656

**Comment by mariobehling** [comment]
Please make the area width 100% and take out "Get me there.

**Comment by mariobehling** [comment]
Zoom level still not suitable. The visible area should be as below.

![screenshot from 2016-08-19 20 54 54](https://cloud.githubusercontent.com/assets/1583873/17820894/43e51b50-664f-11e6-8389-18928d9d7f57.png)

**Comment by aayusharora** [comment]
Ok , need more zooming doing it @mariobehling

**Comment by mariobehling** [comment]
Cannot see this closed in the test page.

**Comment by aayusharora** [comment]
@mariobehling Its done :+1:

**Comment by mariobehling** [comment]
Please make 
* [ ] the area 100% as discussed here https://github.com/fossasia/open-event-webapp/issues/579#issuecomment-241104235 (Please compare to the fossasia event sites map area e.g. here http://2016.fossasia.org )
* [ ] Increase height

![screenshot from 2016-08-26 15 02 49](https://cloud.githubusercontent.com/assets/1583873/18006144/80855d64-6b9e-11e6-9240-d53bee73140f.png)

**Comment by aayusharora** [comment]
@mariobehling This will contradict with https://github.com/fossasia/open-event-webapp/issues/690 second point. The content area for map can not be 100% ? Section area is already 100%.

**Comment by mariobehling** [comment]
no, because this is not a text area. Please compare to fossasia event sites.

**Comment by aayusharora** [comment]
ok .. thanks

**Comment by aayusharora** [comment]
Done !
