### ISSUE TITLE
grouping and sorting of sessions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#58]
The overview misses important information. 
* [x] date
* [x] speakers (+link to speaker)
* [x] language
* [x] type
* [x] level

What is the sorting of sessions?
* [x] They could be sorted by time and date. Currently, I do not recognize what is the sorting.

Please compare with RP: 
![screenshot from 2015-08-13 09 07 52](https://cloud.githubusercontent.com/assets/1583873/9244371/dfcf1b22-419a-11e5-953d-fb52268dd526.png)

App:
![screenshot from 2015-08-13 09 10 37](https://cloud.githubusercontent.com/assets/1583873/9244406/312deaac-419b-11e5-9e70-dd7e3bc47465.png)

**Comment by championswimmer** [comment]
The overview wouldn't have detail data like speaker name, location etc. But it needs to be grouped and sorted properly.

**Comment by mariobehling** [comment]
Sure, the overview needs details like location and time. It does not need the detailed description. Please see the RP example.

**Comment by championswimmer** [comment]
Yes but Google IO shows only Event title. It shows details only on clicking the session and opening dialog. 

Why do we have to make the UI exactly like re:Publica ?

**Comment by mariobehling** [comment]
It's not about the UI. As you can see Google IO also has info about date and time and additional features like adding talks to a list. What cool features are in the web app? Hope to see something.

**Comment by championswimmer** [comment]
sorting is implemented via this https://github.com/fossasia/open-event-webapp/pull/65

**Comment by championswimmer** [comment]
language type and level added here https://github.com/fossasia/open-event-webapp/pull/69

**Comment by championswimmer** [comment]
speaker name added here https://github.com/fossasia/open-event-webapp/pull/70

**Comment by championswimmer** [comment]
location support will be added when orga-server supports location data
