### ISSUE TITLE
Implement Schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#581]
The app is still missing a schedule similar to sched.org where all sessions that are taking place at the same time show up in the list.

![screenshot from 2016-08-05 19 20 10](https://cloud.githubusercontent.com/assets/1583873/17444722/cfca4640-5b41-11e6-8d49-92229095ab4a.png)

![screenshot from 2016-08-05 19 23 40](https://cloud.githubusercontent.com/assets/1583873/17444775/249f9b7a-5b42-11e6-8645-d41a95de8093.png)

**Comment by championswimmer** [comment]
done
