### ISSUE TITLE
In Tracks Page make session name background in track color

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#586]
For the new track page (former session page) make the color of the session name in track color similar to sched.org.

![screenshot from 2016-08-05 23 35 07](https://cloud.githubusercontent.com/assets/1583873/17451290/f286cc3e-5b65-11e6-94d4-d3ab953b287c.png)

**Comment by championswimmer** [comment]
@mariobehling we made the session times according to track color instead
