### ISSUE TITLE
Implement updates and a better Rooms Page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#587]
* [x] Add dates on top of page (not in the menu)

![screenshot from 2016-08-05 23 22 39](https://cloud.githubusercontent.com/assets/1583873/17451397/c9aa8c78-5b66-11e6-9d52-fc16e6dbcebd.png)

* [x] Rename Rooms Page to "Venue" (there can be locations that are not rooms)
* [x] Change table to better reflect sorting by rooms similar to below

![screenshot from 2016-08-05 23 37 21](https://cloud.githubusercontent.com/assets/1583873/17451362/88f2c542-5b66-11e6-9471-7ae8c79fdc81.png)

* [x] Clicking on session should expand to show information similar to tracks page

![screenshot from 2016-08-05 23 35 07](https://cloud.githubusercontent.com/assets/1583873/17451370/a2911210-5b66-11e6-8364-b11369028d41.png)

**Comment by championswimmer** [comment]
point 1 done here https://github.com/fossasia/open-event-webapp/pull/613

**Comment by aayusharora** [comment]
@mariobehling @championswimmer Taking this

**Comment by aayusharora** [comment]
Closed via #688
