### ISSUE TITLE
Detail View of Sessions lacking info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#59]
Missing info:
* [x] Type
* [x] Date
* [ ] Microlocation
* [ ] Social Sharing links
* [ ] Speaker info and photo, link to website

As an example please compare with:
![screenshot from 2015-08-13 09 13 28](https://cloud.githubusercontent.com/assets/1583873/9244453/9a8afa9e-419b-11e5-99be-40a0664572a0.png)
https://re-publica.de/session/purpose-entry

**Comment by championswimmer** [comment]
type and date added here https://github.com/fossasia/open-event-webapp/pull/69

**Comment by championswimmer** [comment]
speaker names added here 
https://github.com/fossasia/open-event-webapp/pull/70

**Comment by AmayAgrawal** [comment]
So from where can I get the location that where a particular session is going to held.I have seen the microlocation file.At present it consists of three locations "stage 2","stage 7","hall 3".So can u please let me know how to implement this.Also I am working on option of social link sharing.

**Comment by ashutoshsaboo** [comment]
Hi @championswimmer @mariobehling 

I pushed a PR - https://github.com/fossasia/open-event-webapp/pull/130 . It resolves the last point. It adds the Speaker photo, info and link to website. Please review the PR and merge it.

Thanks! :smile:
