### ISSUE TITLE
Implement twitter section using loklak

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#590]
* [x] Use code of https://github.com/fossasia/fossasia-loklak-webtweets
* [x] Develop section (background gray, font black) instead of sidebar
* [x] Include link to twitter page

![screenshot from 2016-08-06 19 09 04](https://cloud.githubusercontent.com/assets/1583873/17458119/5e538a4e-5c09-11e6-88b4-11a090b318d7.png)

**Comment by championswimmer** [comment]
@mariobehling at bottom of the page ?

**Comment by mariobehling** [comment]
Before footer maybe. We can move the sections later. For now it is important to get the feature.

**Comment by aayusharora** [comment]
@championswimmer @mariobehling Working for this

**Comment by mariobehling** [comment]
Please increase section to 100% width as shown in example.

**Comment by aayusharora** [comment]
Done !!

**Comment by championswimmer** [comment]
done now
