### ISSUE TITLE
Footer working with popover on Speaker page

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#592]
Same as previous Track page we need a dynamic footer that works with popover.

- [x] Implement a solution same as previous Track page to get footer working.
- [x] Make Speaker page work on Mobiles

**Comment by mariobehling** [comment]
Please stick to the feature of issue and follow best practices: How is the speaker section related to the footer?

> Implement a solution same as previous Track page to get footer working.

Which previous track page? Screenshot?

**Comment by aayusharora** [comment]
@mariobehling The poovers comes with absolute height which is not known to the browser. Hence footer remain fixed and popover goes till the end.
According to UX, footer should always be at the bottom of the page whatever the situation is.
Consider the wrong layout 
![22](https://cloud.githubusercontent.com/assets/12194719/17461497/d0287d80-5cab-11e6-8aa1-67bee2ada792.png)

 https://github.com/fossasia/open-event-webapp/issues/500

**Comment by aayusharora** [comment]
done !!
