### ISSUE TITLE
Frontpage bug report

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#594]
The goal of the web app project is to have a generic solution to generate a website for an event. Events can be small or big with lots of tracks. Sometimes they do not have speakers or event a logo. We need to cater for the different events in order to have a successful outcome. The open-event repo already provides three different samples that should be continuously tested.

There are a number of issues when generating Ehealth Africa for example including the following (but also others not mentioned below):
* [x] If no logo is provided there is a missing image sign. Expected behaviour: There should be a text of the Event Name if no logo provided.
* [x] Background image is provided, but does not show up.
* [x] Date and Time should be written properly. Currently: Thu, 30th Jun AT 19:00 \ Expected: Thursday, 30th June at 19.00
* [x] Description is difficult to read and does not render HTML properly
* [x] Sponsors: There are no sponsors, so this area should not be there.
* [x] Copyright: There is no license: There should not be Copyright Info therefore.

![screenshot-files championswimmer in 5000 2016-08-07 10-20-16](https://cloud.githubusercontent.com/assets/1583873/17461341/9874e454-5c89-11e6-9114-2c4f591d2b50.png)

**Comment by championswimmer** [comment]
@mariobehling @aayusharora 
I have solved some issues in #597 , #598 , #599 

Please check and merge

**Comment by aayusharora** [comment]
@championswimmer @mariobehling  **Description is difficult to read and does not render HTML properly** Solved #605

**Comment by aayusharora** [comment]
@championswimmer Can you check Sponsor Images sub-issue . The container is still shown with empty data. Not able to figure out the problem.Checked with EhealthAfrica data.
![12345](https://cloud.githubusercontent.com/assets/12194719/17621718/f02a12be-60b2-11e6-8cbc-6097d9dcae03.png)

**Comment by championswimmer** [comment]
@aayusharora I'll take a look

**Comment by championswimmer** [comment]
moving last point to https://github.com/fossasia/open-event-webapp/issues/620
