### ISSUE TITLE
Upload zip in background and show progress bar for upload

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#595]
Currently the user does not get any info, if uploads of files work successfully. Please implement:
* [x] Upload of zip in background right after zip file has been chosen
* [x] a progress bar to show upload (next to the file uploader for example or substituting it)
* [ ] an x-cross to cancel upload if desired 
![screenshot from 2016-08-07 11 42 22](https://cloud.githubusercontent.com/assets/1583873/17461648/23b76af0-5c94-11e6-8136-b1a061fd8bc3.png)
* [x] Show "Generate App" button only when upload is finished

**Comment by championswimmer** [comment]
@mariobehling doing point 1 is faulty. if user wants to change zip file (if he selects wrong zip by mistake) then ?

**Comment by championswimmer** [comment]
addressed this here 
https://github.com/fossasia/open-event-webapp/pull/618

**Comment by mariobehling** [comment]
The user currently has to wait a long time and does not see any progress of the upload. Also when the user wants to generate the app, it stays at 0% for a long time - cause probably because the upload is still going on. But: There is no visual feedback. 

So, the progress bar of the app generation currently does not provide so much value, if we do not have an instant upload in the background and a progress bar.

**Comment by championswimmer** [comment]
Ok I'll add progress times for uploading too

**Comment by championswimmer** [comment]
done via https://github.com/fossasia/open-event-webapp/pull/646

**Comment by mariobehling** [comment]
Current implementation is not logic yet. The progress bar is below the ftp form?

You are part of the discussion in this issue: https://github.com/fossasia/open-event-android/issues/548#issuecomment-240404879

There was an example that shows a standard implementation of many web services.

On the top you see the "Choose a file" field. 

After the file is chosen, it displays a progress bar.

![screenshot from 2016-08-17 15 08 50](https://cloud.githubusercontent.com/assets/1583873/17737261/90515158-648c-11e6-8752-aa36ae1b8a33.png)

**Comment by championswimmer** [comment]
upload gets cancelled if user selects different file using browse button. so cancelling functionality works too.
