### ISSUE TITLE
Speakers Page bug scaling and no html rendered

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#603]
* [x] In smaller screen resolution the images are not always in a ratio 1:1 as a square
* [x] html is not rendered in the description when provided
* [x] description is off-screen on standard mid-size screen resolution

![screenshot from 2016-08-09 09 28 29](https://cloud.githubusercontent.com/assets/1583873/17508179/f723fc0c-5e13-11e6-94d2-5a3c6399035e.png)

![screenshot from 2016-08-09 09 23 23](https://cloud.githubusercontent.com/assets/1583873/17508239/43dec02c-5e14-11e6-9f87-0596dc6c40d2.png)

**Comment by championswimmer** [comment]
fixed via https://github.com/fossasia/open-event-webapp/pull/611
