### ISSUE TITLE
Broken download link is sent when there are spaces in app's name

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-webapp#604]
I tried sending `name` with spaces in it via the API but that resulted in invalid download link.
Input <br>
![screenshot-area-2016-08-09-150411](https://cloud.githubusercontent.com/assets/6565270/17511917/d7e30318-5e42-11e6-8e07-2152232df1ca.png)
email <br>
![screenshot-area-2016-08-09-150650](https://cloud.githubusercontent.com/assets/6565270/17511928/ee1136a0-5e42-11e6-9663-59df6eb65b53.png)

**Comment by championswimmer** [comment]
Thanks for pointing out. Will fix it

**Comment by championswimmer** [comment]
fixed now
