### ISSUE TITLE
Send notification to orga-server if web app is generated to proper user

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-webapp#617]
@championswimmer @aayusharora If Web App is generated please send a notification to orga server

I've created notification API:

http://127.0.0.1:8001/api/v2/#!/notifications/post_user_notifications.

> Code sample: 
> curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
>   "action": "WebApp is generated",
>   "message": "string",
>   "email": "rafal@wp.pl",
>   "title": "string"
> }' 'http://127.0.0.1:8001/api/v2/events/1/notifications'

**Comment by championswimmer** [comment]
I believe you mean `open-event-dev.herokuapp.com` and not `127.0.0.1` @rafalkowalski  ?

**Comment by rafalkowalski** [comment]
Exactly, sorry for mistake ;)

**Comment by rafalkowalski** [comment]
@championswimmer Please check how to connect with API. I've explained it in andoid app https://github.com/fossasia/open-event-android/issues/585

**Comment by championswimmer** [comment]
Thank you!

**Comment by rafalkowalski** [comment]
@championswimmer  have you tried to send notifications?

**Comment by Princu7** [comment]
Can I work on this @mariobehling

**Comment by Princu7** [comment]
Hello @sch00lb0y . It is suggested that you first talk to the assignees of an issue before solving it cause they might have already done some work on that issue which will be nullified and it will be a waste of time and effort. :)

**Comment by mariobehling** [comment]
@Princu7 @sch00lb0y Yes, would be good to avoid double work, but let's work together now. @Princu7 Could you help to review, please? We want to get step by step to peer-review processes. Cheers.

**Comment by Princu7** [comment]
@mariobehling @sch00lb0y No problem at all. I had looked at the thread of the open event android tackling this same issue and it seems to be a two step process. First we have to login to the open event orga-server with a registered emall id. After we post our email address and password to the concerned url, we get an access token. Using that access token we have to post the notification regarding the successful build of the web-app. 

In the current implementation, we are directly posting the notification to the open-event-organizer url. Most probably, the server won't accept it and return an error. It might also be possible that the open event orga server now accept direct notifications in which case the current setup should work comfortably. I will check it and notify. Thanks.

**Comment by sch00lb0y** [comment]
@Princu7 @mariobehling sorry for the inconvenience.here after it won't happen again

**Comment by Princu7** [comment]
@sch00lb0y No worries at all. Welcome to the community. :smile:

**Comment by Princu7** [comment]
@mariobehling  @sch00lb0y  Like I said, currently the server is returning an error. I put some _console.log()_ instructions to check the response of the server. Here it is-

```
 { status: 'NOT_AUTHORIZED',
     field: null,
     message: 'Authentication credentials not found',
     code: 401 } 
```
I am currently trying to make it work using the credentials. Will notify when done!

**Comment by Princu7** [comment]
@mariobehling  @sch00lb0y There are multiple issues to be mentioned. You need to have a registered email id with permissions to login into the open-event orga server. I looked into the open-event-android and used the _harshit dwivedi's_ _email_ and _password_ which were visible in the code. Public display of email and password is not a good practise and we should do some steps to avoid it.

After using those credentials, Now there is no authentication error but instead we get faced with 'event does not exist' error. Here is the reply of the server if I make a post request containing notification information to the url
 https://open-event-dev.herokuapp.com/api/v2/events/1/notifications

```
{ field: null,
     message: 'Event does not exist',
     status: 'NOT_FOUND',
     code: 404 }
```
I am not sure what is causing the error.Maybe there is some API issue. Please guide @mariobehling . What should we do? Should I ask over the guys at open-event orga server about this?

**Comment by mariobehling** [comment]
@Princu7 The issue is, that there cannot be an app for an non-existing event. This feature is intended for people who use the server to run an event. Let's postpone this issue for now and come back at a later point.

**Comment by sch00lb0y** [comment]
@mariobehling @Princu7 okay.
