### ISSUE TITLE
Implement Footer with bottom menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#619]
Please follow the style below (from FOSSASIA):
![screenshot from 2016-08-12 22 40 37](https://cloud.githubusercontent.com/assets/1583873/17636508/d622ae0a-60dd-11e6-8b7a-56810dc8478b.png)

Implement:
* [x] Instead of "About" in the middle show here copyright info
* [x] In the left menu show following links
   * [x] About -> Links to description
   * [x] Tickets -> to Ticket page
   * [x] Tracks
   * [x] Rooms
   * [x] Speakers
   * [x] Back to top

**Comment by mariobehling** [comment]
Please ensure all icons have the same color.

**Comment by aayusharora** [comment]
- [ ] Make section gray
- [ ] Correct layout
- [ ] Find out reason for copyright info and solve it

**Comment by aayusharora** [comment]
Done #649
