### ISSUE TITLE
Loaders are cheap, use `em

### ISSUE THREAD

**Issue by creativepsyco** [fossasia/open-event-webapp#62]
After adding re:Data format, the payload has suddenly increased, the web app client hangs a bit when switching from Sessions to Speakers and so on.

* Page the API to retrieve X items and then keep refreshing when the person scrolls to bottom.
* Show a loader progress circular bar, to tell the user that a refresh is ongoing
* On switching tabs, perhaps cancel the request to load?

**Comment by championswimmer** [comment]
implemented here https://github.com/fossasia/open-event-webapp/pull/64
