### ISSUE TITLE
Improve styling of top bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#620]
Desired style as below:
![screenshot from 2016-08-12 22 47 33](https://cloud.githubusercontent.com/assets/1583873/17636667/f8327aa6-60de-11e6-927b-44379f0bb74d.png)

Major changes include:
* [x] Change background color of top bar to white
* [x] align menu and icons right
* [x] reduce social media size of icons and distance between them
* [x] Make top menu items capital and do not make them bold
* [x] Change font to same font as on header at fossasia.org
* [x] Do not show sections like speakers, tracks, if those jsons are not available

**Comment by aayusharora** [comment]
> Do not show sections like speakers, tracks, if those jsons are not available
Issue #629 for it. All covered except this

**Comment by mariobehling** [comment]
* [ ] Please ensure top menu text has the same gray color as in example. Compare to fossasia event sites.

**Comment by aayusharora** [comment]
Done via #704
