### ISSUE TITLE
Background Image not working with zip upload 

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#623]
Checked all cases, it is working in every case like API but not when uploaded in zip

**Comment by championswimmer** [comment]
done

**Comment by mariobehling** [comment]
Thanks, it is added now, but should be centered vertically in the middle if it is not cropped. Currently we see the top area of the fossasia photo in the sample with parking cars - not so interesting.

**Comment by aayusharora** [comment]
Will do it now @mariobehling

**Comment by mariobehling** [comment]
The overlay is also too dark. Can hardly see the image below.

**Comment by aayusharora** [comment]
Done
