### ISSUE TITLE
 Do not show sections like speakers, tracks, if those jsons are not available

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#629]
Parent Issue #620 

- [x] Pages in footer
- [x] Pages in Navbar
- [x] Sponsor section

**Comment by aayusharora** [comment]
@championswimmer This needs to be solved first, Can you help in this?

**Comment by aayusharora** [comment]
@championswimmer  Please help in the issue with sponsor section. I have tried this but can't able to figure out the problem.

**Comment by championswimmer** [comment]
ok I'm taking a look now

**Comment by aayusharora** [comment]
@championswimmer Done!!
