### ISSUE TITLE
Schedule showing up buggy

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#637]
Please find out what is the cause of the issues with wrong displays and solve them. Starting point could be the sample file and sorting by the generator.
* [x] Lots of demo sessions show up, where there should not be a demo session
* [x] Times are wrong, e.g. wrong order and wrong times like lunch at 10.16 AM

http://fossasia.github.io/open-event-webapp/tracks.html

![screenshot from 2016-08-15 20 53 51](https://cloud.githubusercontent.com/assets/1583873/17675568/92bfe638-632a-11e6-80e8-27a1596bc9b7.png)

**Comment by championswimmer** [comment]
This seems to be because the JSON does not have timestamps with timezones. 
I will update the JSON with singapore timezones

**Comment by mariobehling** [comment]
Ok, but it does not explain why there are different times on the different pages generated by the web app.

**Comment by championswimmer** [comment]
pending discussion on this 
https://github.com/fossasia/open-event-orga-server/issues/2234

**Comment by championswimmer** [comment]
times are fixed and start from 09:30 now. 

![screenshot from 2016-08-23 00-50-15](https://cloud.githubusercontent.com/assets/1327050/17868239/ac59ed90-68cb-11e6-8192-f22bb4506aaf.png)
![screenshot from 2016-08-23 00-50-24](https://cloud.githubusercontent.com/assets/1327050/17868240/ac5eb3ac-68cb-11e6-9c3a-c32ca9f77b72.png)
![screenshot from 2016-08-23 00-50-32](https://cloud.githubusercontent.com/assets/1327050/17868241/ac61649e-68cb-11e6-9847-f027e9a5bec9.png)
