### ISSUE TITLE
documentaion and distribution todos

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#647]
- [x] add docs for AWS, GC and DO deployment
- [x] remove mockjsons 
- [x] link to open-event FOSSASIA sample
- [x] improve and correct text in Readme, add choice of technologies

**Comment by championswimmer** [comment]
thank you so much @mariobehling for doing points 1 and 4

**Comment by mariobehling** [comment]
@championswimmer I think this is a misunderstanding. Those points are not done entirely. I just added some documentation and empty mds to draw the path.

**Comment by championswimmer** [comment]
installation docs added
