### ISSUE TITLE
New Upload functionality not working with large zip

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#650]
Not able to generate Webapp with larger zip.
The fossasia sample works for me sometimes, but sometimes it completes blue bar and the button remains deactivated.
I have already mentioned this in https://github.com/fossasia/open-event-webapp/pull/646
@championswimmer Please confirm and check this issue.
![45](https://cloud.githubusercontent.com/assets/12194719/17774567/e1f65572-6571-11e6-98e1-05c37ff1a581.png)

**Comment by championswimmer** [comment]
let me try disabling the animations on the frontend and see.
