### ISSUE TITLE
Allow user to upload zip files only

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-webapp#657]
As of now, the user is allowed to upload any file to the server.
This is a blocker as uploading a file which is not `zip` breaks the build and the progressbar gets stuck on "Copying JSON files"
I have already fixed this in the android generator [https://github.com/fossasia/open-event-android/pull/615](https://github.com/fossasia/open-event-android/pull/615) and found out that the webapp generator has the same issue.
Please consider fixing this.

**Comment by the-dagger** [comment]
@championswimmer If you wan't i can send a PR fixing this.
I did it already in the android generator.

**Comment by aayusharora** [comment]
@the-dagger Please go ahead :)
