### ISSUE TITLE
Zip Loader work on local but not working on Heroku

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#662]
@championswimmer Checked it with Fossasia Zip, due to this https://opev-webgen.herokuapp.com/ is not longer working. I guess @mariobehling was talking about same problem and now I realised that.
Is this heroku specific?

**Comment by mariobehling** [comment]
@aayusharora Please test on the dev version: http://opev-webgen-dev.herokuapp.com

But did not work for me yet here neither.

**Comment by aayusharora** [comment]
Solved
