### ISSUE TITLE
Use standard style in speakers page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#670]
The speakers page has a different style to the other pages. It is unclear why. Please use the same style in all pages, e.g. white background in middle space, same size of fonts as in other pages, same heading etc.

**Comment by mariobehling** [comment]
Heading still different to other pages.

**Comment by aayusharora** [comment]
Heading 333( Hex) On speaker page After PR #708

**Comment by championswimmer** [comment]
ok now it is done @mariobehling
