### ISSUE TITLE
Rooms page bugs: Missing date links, session time confusing, no session info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#671]
The rooms page is still missing basic information including
* [x] no date top links (like in tracks page)
* [x] no expanded session info on click (like in tracks page)
* [x] confusing time format - it should be the same as on tracks page
* [x] Room name Dalton Hall repeating

**Comment by aayusharora** [comment]
@mariobehling @championswimmer Taking this

**Comment by aayusharora** [comment]
Closed via #688

**Comment by mariobehling** [comment]
Thank you, good progress. Now, please ensure the implementation on the page stay within out design and follow the content display of other pages, e.g. the tracks page

* [ ] Ensure in the un-expanded session you show the same information as on the unexpanded version of the tracks pages, e.g. Show: A Funny Thing Happened On My Way To The Science Centre, Harish Pillay (RedHat), Keynote of 20 minutes
* [ ] Ensure you use the same font and color of font as in other pages, including
   * [ ] Time
   * [ ] Text/description/icons etc in expanded section
   * [ ] Align date buttons in the same way as on tracks page

**Comment by mariobehling** [comment]
Please use our gray color set for text.

![screenshot from 2016-08-28 09 07 04](https://cloud.githubusercontent.com/assets/1583873/18032215/ef93b2b2-6cfe-11e6-9efb-5f3ec065cdf8.png)

**Comment by aayusharora** [comment]
Completed this via #719 #722
