### ISSUE TITLE
Line break in footer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#672]
Please ensure automatic line breaks in location in footer.

![screenshot from 2016-08-22 06 28 20](https://cloud.githubusercontent.com/assets/1583873/17843731/d32ce9e4-6831-11e6-8599-00cecd56a9f9.png)

**Comment by mariobehling** [comment]
@aayusharora At http://fossasia.org the center column of the footer is a bit longer and the right part moved more to the right. It looks more natural. Could you implement that in this footer as well, please?

**Comment by aayusharora** [comment]
Yes doing it @mariobehling

**Comment by aayusharora** [comment]
![56](https://cloud.githubusercontent.com/assets/12194719/17980963/403d9f66-6b1f-11e6-8096-421773d90e89.png)
