### ISSUE TITLE
Speakers information does not show session location and no link to session on tracks page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#676]
![screenshot from 2016-08-22 17 15 36](https://cloud.githubusercontent.com/assets/1583873/17860087/744ae59c-688c-11e6-8e28-bf312bb3c6fa.png)

* [x] Does not show session location
* [x] Does not link to session information on tracks page with expanded section

**Comment by aayusharora** [comment]
@mariobehling @championswimmer Taking this

**Comment by aayusharora** [comment]
@mariobehling Solved via #686

**Comment by mariobehling** [comment]
Please ensure style as in sample style is followed:
* [ ] Text below images: Align left and keep same height of both a) speaker name b) company/project
* [ ] Text area on overlay: Ensure speaker description text is in standard gray color

![screenshot from 2016-08-26 17 55 41](https://cloud.githubusercontent.com/assets/1583873/18011714/9213d0ca-6bb6-11e6-97dd-47411680a781.png)

**Comment by aayusharora** [comment]
@mariobehling @championswimmer Taking this :)

**Comment by aayusharora** [comment]
Both task done @championswimmer @mariobehling  It can be closed now via #712

**Comment by mariobehling** [comment]
Seems like color has been changed on speakers page. The company info was in a lighter gray. Let's keep that.

Expected look:

![screenshot from 2016-08-28 09 00 46](https://cloud.githubusercontent.com/assets/1583873/18032197/30277a6c-6cfe-11e6-8c35-300207815ab5.png)
