### ISSUE TITLE
Rooms page errors of time and rooms

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#677]
![screenshot from 2016-08-22 17 21 07](https://cloud.githubusercontent.com/assets/1583873/17860210/f0d6c7de-688c-11e6-9214-9c935f3ce838.png)

Please move times back to left side of the table and ensure room only shows up once.

**Comment by championswimmer** [comment]
@aayusharora will you take a look at this ? your earlier PR moved the times into the boxes.

**Comment by aayusharora** [comment]
@championswimmer Working for this

**Comment by championswimmer** [comment]
thanks, done via https://github.com/fossasia/open-event-webapp/pull/685

**Comment by aayusharora** [comment]
Rooms still repeating

**Comment by aayusharora** [comment]
@championswimmer Figured that out Please check the spaces in front off Dalton hall in data https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/sessions#L48 This is the reason for creating two objects. Can you remove this?

**Comment by championswimmer** [comment]
done https://github.com/fossasia/open-event/pull/92
