### ISSUE TITLE
Necessary Design Fixes - Use same design, font, width on all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#690]
* [x] On Front page make order as follows: 1. Description, 2. Featured Speakers, 3. Twitter area, 4. Sponsors, 5. Map Area, 6. Footer

* [x] On Front page ensure all text areas stick to the same area width and distances including header logo/text and footer area

![screenshot-fossasia github io 2016-08-23 23-45-26](https://cloud.githubusercontent.com/assets/1583873/17911494/137448d2-698e-11e6-8858-1ed852cb7f60.png)

* [x] On all pages ensure the used area has the same width as the front page
   * [x] Track page area is not as wide as front page
   * [x] Rooms page - the days are indented differently, area not as wide as front page

![screenshot-fossasia github io 2016-08-23 23-45-26](https://cloud.githubusercontent.com/assets/1583873/17911924/b9d4513e-6990-11e6-8c0c-1c7f3cb2f750.png)

* [x] On all pages ensure that headings have the same size, style, height -> Should use the same css
![screenshot from 2016-08-24 00 00 27](https://cloud.githubusercontent.com/assets/1583873/17911607/c584f0b2-698e-11e6-830f-781ec30f74b5.png)
![screenshot from 2016-08-24 00 00 08](https://cloud.githubusercontent.com/assets/1583873/17911611/caccf74a-698e-11e6-8d16-6827943fb1c2.png)
![screenshot from 2016-08-23 23 59 52](https://cloud.githubusercontent.com/assets/1583873/17911616/ce492df8-698e-11e6-916c-aeadf002365a.png)

* [x] On all pages ensure text uses the same style, size, color (same css wherever possible), e.g. have a look at the rooms page: Font has different color. Why not gray anymore?

* [x] Ensure all expansion and other effects have no delay. We want everything to feel fast, e.g. on rooms page.

**Comment by championswimmer** [comment]
@mariobehling so twitter and maps section should not be full width you want to say ? 

but you only wanted them to be full width 
(point no 2)

**Comment by championswimmer** [comment]
@mariobehling also, header on front page as same area width as content area 

<img width="1192" alt="screen shot 2016-08-24 at 4 27 38 pm" src="https://cloud.githubusercontent.com/assets/1327050/17928337/de06c956-6a17-11e6-86ab-16d06b690e26.png">

**Comment by championswimmer** [comment]
also heading is same, because we use the same template for header on all pages.

**Comment by mariobehling** [comment]
@championswimmer This issue is about the text/content width, not about the full width of sections. Please compare to the recent fossasia event sites or any other standard design implementations. It seems like you are using a different style on each page. Use the same css across all pages.

**Comment by aayusharora** [comment]
>  Ensure all expansion and other effects have no delay. We want everything to feel fast, e.g. on rooms page
@mariobehling  there is no delay on my system, @championswimmer Can you please check and close this if all looks good.
Everything covered except that.

**Comment by mariobehling** [comment]
Will be testing and closing this after I have tested in detail.

Please continuously upload new versions to the test site to ensure we always test the latest version.

**Comment by championswimmer** [comment]
@mariobehling can you test and let us know if there any places that looks slow ? I tests and everything feels fast and responsive enough
