### ISSUE TITLE
Tweet Area: Use standard color and increase height of area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#699]
Currently the area is a bit squeezed and colors are not matching. Please:
* [x] use standard gray color and css
* [x] Increase height of area (compare to fossasia event sites)

![screenshot from 2016-08-26 15 06 31](https://cloud.githubusercontent.com/assets/1583873/18006224/deadf626-6b9e-11e6-8324-303e6866f9ef.png)

**Comment by aayusharora** [comment]
@mariobehling 
>  use standard gray color and css
Do we want something like this just with increased height?
![45](https://cloud.githubusercontent.com/assets/12194719/18006941/9db9cca0-6bbf-11e6-9860-0bfb4a0726a4.png)

**Comment by mariobehling** [comment]
black font -> standard gray font. Don't change background.

**Comment by aayusharora** [comment]
Done via #706
