### ISSUE TITLE
Erroneous Line Breaks in Track Info Areas

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#700]
There are breaks right after the colored dots in the track info areas, that should not happen.

![screenshot from 2016-08-26 15 12 03](https://cloud.githubusercontent.com/assets/1583873/18006413/a547f660-6b9f-11e6-814b-c89f671dc7c3.png)

**Comment by shubham-padia** [comment]
@mariobehling @aayusharora  #713 intends to resolve this issue , please review that.

**Comment by aayusharora** [comment]
@shubham-padia Please check my comment here #713

**Comment by aayusharora** [comment]
@mariobehling @championswimmer Solved by PR #714
