### ISSUE TITLE
Footer menu links not working on all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#701]
* [x] About page not correctly linked from all pages
* [ ] Ticket link should link to "ticket area" on start page
* [x] Scroll to top should use scrolling feature

![screenshot from 2016-08-26 15 15 15](https://cloud.githubusercontent.com/assets/1583873/18006474/fa905bbc-6b9f-11e6-8dec-3ccb619f593b.png)

**Comment by shubham-padia** [comment]
@championswimmer Can i work on this ?

**Comment by shubham-padia** [comment]
@championswimmer Can I work on this ?

**Comment by shubham-padia** [comment]
@championswimmer I've implemented a solution for this issue, should I send a Pull Request for review ?

**Comment by shubham-padia** [comment]
@mariobehling @championswimmer Please review #733 .

**Comment by championswimmer** [comment]
@shubham-padia no it means ticket should link to index.html#ticketbutton

**Comment by shubham-padia** [comment]
@championswimmer  please review #735 for ticket link.
