### ISSUE TITLE
Fix syntax errors on all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#702]
Looks like there are a number of syntax errors. Please fix them.

![screenshot from 2016-08-26 18 43 26](https://cloud.githubusercontent.com/assets/1583873/18013129/122ea93c-6bbd-11e6-849c-e04eb8d2cffd.png)

**Comment by aayusharora** [comment]
Done Via #709 I do not find this much errors, find only one in console which I have solved, Please reopen if this is not yet solved.
