### ISSUE TITLE
Ensure all section headings in same style use the same class

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#703]
Different sections in the same kind of style are using different div classes or setup. Please ensure all are using the same. 

Looking good for example is the area "proudly.."

![screenshot from 2016-08-26 18 46 48](https://cloud.githubusercontent.com/assets/1583873/18013307/bd70ec10-6bbd-11e6-97a8-96f936e1b70d.png)

The section "featured speaker" should follow the same style/implementation:

![screenshot from 2016-08-26 18 47 05](https://cloud.githubusercontent.com/assets/1583873/18013337/d3c73618-6bbd-11e6-8136-5a7cfa0ed310.png)

**Comment by championswimmer** [comment]
has been done at PR #707

**Comment by aayusharora** [comment]
Closed via #708

**Comment by mariobehling** [comment]
Thank you. Please see comment here https://github.com/fossasia/open-event-webapp/pull/708#issuecomment-242923728

Please only close issues after PRs have been merged and confirmed solved.

**Comment by aayusharora** [comment]
@mariobehling @championswimmer  Button also aligned now. Please close this.

**Comment by mariobehling** [comment]
With section heading - same style - it was not related to the alignment. The main goal is to have a consistent font and distance above and below the heading.

Please compare this to FOSSASASIA event sites. There are different alignment, but all section headings have the same height.

Event site:
![screenshot from 2016-08-28 08 35 33](https://cloud.githubusercontent.com/assets/1583873/18032065/7cf43e38-6cfa-11e6-9933-c97d3a54003b.png)

Current generated site with little heading space:
![screenshot from 2016-08-28 08 33 58](https://cloud.githubusercontent.com/assets/1583873/18032068/8f81ce80-6cfa-11e6-9619-2f9f0eb28703.png)

**Comment by championswimmer** [comment]
done at #726 

![screenshot from 2016-08-29 14-08-42](https://cloud.githubusercontent.com/assets/1327050/18045779/2c79a814-6df2-11e6-9437-b2c7f70e3526.png)

**Comment by mariobehling** [comment]
There are different alignment, but all section headings have the same height.

* [ ] The last change also seems to have the area of "Proudly supported" increase more than required.
* [ ] Alignment should be as on fossasia event sites: Featured speakers should be left aligned. Alignment should be in line with the respective design.

**Comment by mariobehling** [comment]
Please compare to http://2016.fossasia.org/

![screenshot from 2016-08-29 11 39 13](https://cloud.githubusercontent.com/assets/1583873/18047435/426af250-6ddd-11e6-90ef-2876e6d4788c.png)

**Comment by mariobehling** [comment]
![screenshot from 2016-08-29 11 40 26](https://cloud.githubusercontent.com/assets/1583873/18047465/663cef62-6ddd-11e6-8f25-c2fffd15de2b.png)
