### ISSUE TITLE
Schedule Page: Text not aligned, no link to speaker

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#715]
Please see screenshot below:
* [x] Text not aligned in one line
* [x] No link to speaker implemented
* [x] Name of track missing (Please add.) 
![screenshot from 2016-08-28 08 53 30](https://cloud.githubusercontent.com/assets/1583873/18032166/f3aa4bc4-6cfc-11e6-8c9c-9b3443a5b14c.png)

![screenshot from 2016-08-28 08 38 27](https://cloud.githubusercontent.com/assets/1583873/18032090/383ff29a-6cfb-11e6-8f57-625780988bb8.png)

**Comment by aayusharora** [comment]
Solved via #720

**Comment by mariobehling** [comment]
All text should be in one ligne. The solution provided only aligns bottom text of the area.

**Comment by mariobehling** [comment]
![screenshot from 2016-08-29 17 35 09](https://cloud.githubusercontent.com/assets/1583873/18057158/1dd520f0-6e0f-11e6-94e6-fbe1d42c504d.png)

**Comment by aayusharora** [comment]
Verified this with http://fossasia.github.io/open-event-webapp/schedule.html  app. Looking fine now

**Comment by championswimmer** [comment]
@aayusharora, looks good to me as well
