### ISSUE TITLE
Footer: Align location icon and address info on same line

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#716]
Please align location and address info on the same line (top).

![screenshot from 2016-08-28 08 46 41](https://cloud.githubusercontent.com/assets/1583873/18032127/4aeed0ae-6cfc-11e6-9922-cc8144ce6f18.png)

**Comment by shubham-padia** [comment]
@aayusharora can i work on this, i'd like to contribute ?

**Comment by aayusharora** [comment]
Yes @shubham-padia go ahead

**Comment by shubham-padia** [comment]
@aayusharora  please review #721
