### ISSUE TITLE
Link to speaker missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#717]
The speaker page has a link to the session track, but the "Schedule, Tracks, Room" page do not have a link to the speaker. Please help to fix this.

E.g. make the speaker name and picture link to the speaker on the speakers page with bigger photo.

![screenshot from 2016-08-28 08 55 44](https://cloud.githubusercontent.com/assets/1583873/18032177/74dfcd04-6cfd-11e6-8a46-c3a1e58acd28.png)

**Comment by aayusharora** [comment]
Its Done !!

**Comment by mariobehling** [comment]
* [ ] On tracks page, please only make the speaker name itself into a link. Click on a white area next to the speaker currently open the link. Expected behaviour is, that this white area expands the section

![screenshot from 2016-08-29 11 51 02](https://cloud.githubusercontent.com/assets/1583873/18048569/34c01396-6de3-11e6-9bb2-a008e9aef40d.png)

* [ ] On schedule page after scroll over the "hand symbol" that indicates "there is a link" shows up throughout the whole area. Expected behaviour: It should only show up over links.

* [ ] Links to speakers have anchors like "#3". Expected anchor would be "#SpeakerNameID"

**Comment by championswimmer** [comment]
doing via https://github.com/fossasia/open-event-webapp/pull/734

**Comment by championswimmer** [comment]
all 3 points covered

**Comment by championswimmer** [comment]
deployed to gh-pages,can be tested
