### ISSUE TITLE
On tracks page implement same style as on rooms page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#718]
We had started with the style on the tracks page, but it has evolved since then. Please implement the same style on the tracks page therefore as on the rooms page to keep the app style consistent.

(First solve the design issues/bugs on the rooms page, please.)

**Comment by jainaman224** [comment]
@mariobehling Can I work on this issue please...?

**Comment by jainaman224** [comment]
@mariobehling Sir, where should I add video, audio and slide section on tracks page and I am performing clean up for application.scss .

**Comment by mariobehling** [comment]
@jainaman224 Please propose where it could be suitable.

**Comment by aayusharora** [comment]
@mariobehling I think the issue needs to be updated .
