### ISSUE TITLE
Ensure left side bar in schedule and rooms page is same style

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#723]
As below the left area of the schedule page should use the same style/width like the rooms page.

Please change the schedule page to the same as the rooms page.

![screenshot from 2016-08-28 20 25 55](https://cloud.githubusercontent.com/assets/1583873/18035874/a3fa0cd8-6d5e-11e6-9be9-de0b661ca89e.png)

**Comment by mariobehling** [comment]
@aayusharora Does not seem solved in latest test version. Left side bar still has different width.

**Comment by championswimmer** [comment]
this is done now, and up on gh-pages. can be checked. 

http://fossasia.github.io/open-event-webapp/rooms.html
http://fossasia.github.io/open-event-webapp/schedule.html
