### ISSUE TITLE
Reduce empty white areas between middle and right block

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#730]
On rooms page

* [x] Expand middle block
* [x] Move right block to the right a bit

![screenshot from 2016-08-29 12 36 09](https://cloud.githubusercontent.com/assets/1583873/18048940/75327fa2-6de5-11e6-81df-4712eba813ad.png)

**Comment by aayusharora** [comment]
Done !!

**Comment by mariobehling** [comment]
Please reduce the space between middle block and right block. Currently on some resolutions the right block is slightly overlapping with the edge on its right. Please:
* [ ] Slightly expand middle block
* [ ] Slightly move right block more to the left

![screenshot from 2016-08-30 16 44 46](https://cloud.githubusercontent.com/assets/1583873/18093812/83927f88-6ed1-11e6-8198-98ec0e48aa0e.png)
