### ISSUE TITLE
Rooms page - event dates - links not using scroll effect

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#738]
Tracks and Schedule pages are using the scroll effect but the rooms page date links do not.

* [ ] Please implement the scroll effect for date links 
http://fossasia.github.io/open-event-webapp/rooms.html

**Comment by championswimmer** [comment]
deployed  http://fossasia.github.io/open-event-webapp/rooms.html

@mariobehling  you have to wait till the whole page loads before the scrolling functionality works (it is in js, so scroll.js must load, untill it loads, normal href-id linking works).
