### ISSUE TITLE
Implement a more standard conform generated site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#751]
Currently the site has a folder "dependencies" with different files. When the site is generated, please move files to more standard conform folders as follows.

From dependencies folder in generated sites move:
* [ ] css to `/css`
* [ ] the folder `fonts` to into the root directory
* [ ] js files into `/js`
* [ ] avatar.png into the folder `images`

Finally, please
* [ ] delete folder/do not generate folder "dependencies"

**Comment by Princu7** [comment]
@mariobehling  Can I take this up?

**Comment by Princu7** [comment]
@mariobehling Please test the app here
https://tranquil-temple-31388.herokuapp.com/

**Comment by shubham-padia** [comment]
@mariobehling Looks like this issue has been resolved via #851. Please update the issue. Thank you.
