### ISSUE TITLE
Schedule Page: Align name, organization left and track left

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#760]
In some long name cases name and organization could look broken. Also alignment of track should be left.

On schedule page please align:
* [ ] name left
* [ ] organization left
* [ ] track left

![screenshot from 2016-08-31 22 59 05](https://cloud.githubusercontent.com/assets/1583873/18146260/fc6a5c20-6fce-11e6-8dc6-f3ff415bd936.png)

**Comment by shubham-padia** [comment]
@mariobehling @aayusharora Could not quite understand what is meant by name left and organization     left. If the following result suffices, please merge #761 

![after](https://cloud.githubusercontent.com/assets/13910561/18150209/9f82327a-6fd4-11e6-8d7d-e6985e2cec60.png)
