### ISSUE TITLE
Use expandable text on Schedule page instead of pop-ups (similar to Rooms page)

### ISSUE THREAD

**Issue by alexagr** [fossasia/open-event-webapp#762]
Expandable text layout - as currently implemented on Rooms page - looks and feels much better on mobile than pop-ups. Moreover it works across all mobile platforms - both Android and iOS. The suggestion is to implement expandable text layout on Schedule page, similar to Rooms page.

**Comment by alexagr** [comment]
I've hacked initial implementation of the idea - take a look at http://limmudfsu.org.il/test
It seems to work perfectly fine (to my taste) on all tested platforms, namely:
- Chrome (Windows 7)
- Firefox (Windows 7)
- Mobile Chrome (Android 5.1)
- Safari (iOS 9)

![schedule1](https://cloud.githubusercontent.com/assets/12842507/18157115/167b02e0-7024-11e6-9adf-11e2a8961847.png)

**Comment by alexagr** [comment]
![sched2](https://cloud.githubusercontent.com/assets/12842507/18157193/8a9e9038-7024-11e6-8e7e-34df3b93d7ef.jpg)

**Comment by alexagr** [comment]
And that's what it'll look like on mobile

![sched3](https://cloud.githubusercontent.com/assets/12842507/18157242/daf79624-7024-11e6-88aa-289e7a391515.jpg)

**Comment by aayusharora** [comment]
@alexagr It looks nice to me. We can have this. It is good implementation to replace popovers. Thanks 
Please generate the PR.
