### ISSUE TITLE
App getting stuck at Compiling the HTML pages from templates with latest FOSSASIA sample

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#773]
I updated the latest FOSSASIA samples, but there are probably still inconsistencies in the file.

This might result in the latest build with the FOSSASIA zip getting stuck at 70%.

Please provide logs and info.

![screenshot from 2016-09-02 02 54 09](https://cloud.githubusercontent.com/assets/1583873/18189207/049dad4e-70b9-11e6-9bc9-a1b308051d14.png)

**Comment by alexagr** [comment]
This sometimes happens for me too; but if I click again on "GENERATE WEBAPP" this 
disappears and the app gets fully generated. I assumed that it has something to do with the attempt to send e-mail (that fails due to lack of proper key).
