### ISSUE TITLE
Show name, affiliation and link on dropdown speakers info

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#783]
When the dropdown info of the speaker is shown it does not show the speaker's name and affiliation.

Please add the info into the gray area and a share link ![screenshot from 2016-09-05 19 32 18](https://cloud.githubusercontent.com/assets/1583873/18264844/e5169a0a-7412-11e6-9794-f6a8337d5b0a.png)

![screenshot from 2016-09-06 09 16 14](https://cloud.githubusercontent.com/assets/1583873/18264852/e8ff5210-7412-11e6-85d4-44ebdcd0053d.png)

**Comment by shubham-padia** [comment]
@mariobehling Can i work on this ?

**Comment by shubham-padia** [comment]
please review #785 .
