### ISSUE TITLE
Links not working on Tracks page Speakers name to redirect to particular Speaker

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#789]
http://fossasia.github.io/open-event-webapp/speakers.html#1 Links like that are not working now.
Steps To Reproduce 
1. Go to sample site tracks page http://fossasia.github.io/open-event-webapp/tracks.html
2. Click the name of any speaker like Mario Behling (OpenTech Society) in the card. The link http://fossasia.github.io/open-event-webapp/speakers.html#2 will redirect on Speaker page but not point to exact Speaker.

**Comment by mariobehling** [comment]
Where is that needed? Please try the latest version and feel free to upload the latest generated version. No need to submit issues for old versions.

**Comment by aayusharora** [comment]
@mariobehling Added Steps to reproduce

**Comment by tadityar** [comment]
I can confirm this issue, the link in the speaker's name does not point to the correct anchor (the picture does, though). Will create a PR to resolve this.

**Comment by aayusharora** [comment]
@tadityar Thank you Please go ahead :)

**Comment by aayusharora** [comment]
Done !!
