### ISSUE TITLE
let organiser chose his font 

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#79]
Ideal case : Organiser should be able to set font in one place in config, and it gets changed everywhere

For now: Just extend the main css with coverage for all main classes and apply fonts on them. 
Changing fonts will have to work by Find&Replace All across the css.

**Comment by creativepsyco** [comment]
I think we probably need a simplified styling approach: fonts, colors, headings etc. all can be defined by a config file which can be injected into Sass etc during css generation & would make for a better approach. What do you think? Is it achievable? I kind of feel the styles on the website could use a little bit of uplift.

**Comment by leto** [comment]
:+1: to making the font configurable easily in a config file. Also we may want to look into including the iconic font Font-Awesome by default: https://fortawesome.github.io/Font-Awesome/icons/

**Comment by creativepsyco** [comment]
Sounds good :+1:

**Comment by SaptakS** [comment]
I would like to do this fix.

**Comment by SaptakS** [comment]
Should I generate a separate .css file from sass or should I change in the leaflet.css using sass?

**Comment by creativepsyco** [comment]
upto you, whichever you think is easier to implement and has more impact, you can imagine that one one organization can organize multiple events, so I would suppose that sass can help, using some variables etc.

**Comment by SaptakS** [comment]
Yeah I am doing in sass/scss for the purpose. I will read from the config.js the theme they want and then accordingly set the variables in sass. And then inject using gulp. Sounds ok?

**Comment by creativepsyco** [comment]
yep sounds okay.

**Comment by championswimmer** [comment]
@SaptakS  leaflet.css is for the leaflet module. We are using main.css for our webapp. Do not modify any css we are importing from the modules.

**Comment by SaptakS** [comment]
I guess this issue has already been resolved during GCI. #89
