### ISSUE TITLE
Enhance speaker box

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#791]
Please always follow British/US style of punctuation, e.g. no space before a full stop etc.

![screenshot from 2016-09-08 19 45 38](https://cloud.githubusercontent.com/assets/1583873/18360171/3c4ad804-75fd-11e6-9543-8045a8792b12.png)

On speakers page please implement the following:
* [ ] Make name bold
* [ ] Use full width of available area for name and company
* [ ] Don't leave space within brackets, Incorrect: ( Ant Websytems ...), Correct: (Ant Websystems Co. Ltd) - no space after first bracket and no space before last bracket. -> please use US style of punctuation
* [ ] Do not make company bold

**Comment by shubham-padia** [comment]
@mariobehling Sorry for the punctuation mistakes. Name and organisation widths were kept in such a  way, so that they do not overflow to the next line. 
Please review #792

**Comment by mariobehling** [comment]
Got closed automatically, but above points are not fully implemented yet.
