### ISSUE TITLE
Add .codeclimate.yml

### ISSUE THREAD

**Issue by tadityar** [fossasia/open-event-webapp#797]
I got curious about the 1.5 Codeclimate GPA and noticed a lot of warning about using ES6 syntax. Since we're using ES6 anyway (in eslint) why don't we set the `esnext` of codeclimate to true and eliminate a lot of issues at once? :D

**Comment by mariobehling** [comment]
@tadityar Would be great, if you work on this.

**Comment by tadityar** [comment]
ok I'll work on this then

**Comment by tadityar** [comment]
welp I just realized how old the last passing development build on codeclimate is. This is due to the error caused by `no-extra-parens` config in .eslintrc. After removing some extra options on this config, the build passed and there were no es6 errors reported (although we still have other errors)

**Comment by aayusharora** [comment]
this is done !! Thanks @tadityar
