### ISSUE TITLE
Implement simple search capabilities of app

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#799]
Implement simple search capabilities of app similar to https://github.com/OpenNews/srccon-schedule (Website here http://schedule.srccon.org/#_show-all)

Type in keyword and get only show list of items that match below.

![screenshot from 2016-09-11 09 35 11](https://cloud.githubusercontent.com/assets/1583873/18415915/4731c8ce-7803-11e6-9adb-8bca7020cfb5.png)

@championswimmer You had done something like that before. The implementation of OpenNews is pretty fast. Can we follow the same approach? What needs to be done?

**Comment by jainaman224** [comment]
I would like to work on this issue, If given a chance.

**Comment by mariobehling** [comment]
Great. Thank you.

**Comment by mariobehling** [comment]
Please have a look below, where the search bar could be. 
![screenshot from 2016-09-18 14 17 40](https://cloud.githubusercontent.com/assets/1583873/18615876/9c8d1018-7db1-11e6-94e7-6b2eeea4d75e.png)

**Comment by jainaman224** [comment]
Okay, I will implement it and send a PR for both these pages.
Is search bar on speaker page is good enough or require some styling...?

**Comment by mariobehling** [comment]
* [ ] Please just use "Search" instead "Search name, organization, session and description". 
* [ ] Add "Search" into the search box instead of outside. So, if people click on it, "Search" disappears and they can add their search terms.

**Comment by mariobehling** [comment]
Also, let's keep it gray only. Red should be reserved for other functions/links etc.

**Comment by mariobehling** [comment]
Please keep the search bar very simple and unintrusive.

See this example:

![search_none](https://cloud.githubusercontent.com/assets/1583873/18626263/2c57e3e2-7e54-11e6-8088-6dce4683d309.png)

Also check, that UI works in all resolutions. See issue below:

![screenshot from 2016-09-19 10 31 59](https://cloud.githubusercontent.com/assets/1583873/18626295/652c62b0-7e54-11e6-9e67-6c972ea9a04f.png)

**Comment by jainaman224** [comment]
@mariobehling Can you please review https://jainaman224.github.io/open-event-webapp/speakers.html and https://jainaman224.github.io/open-event-webapp/rooms.html.

**Comment by mariobehling** [comment]
Good job! Please make a PR. 

After that, next steps are:
* tracks/venue page 
* Make the search bar in the same line with date line (currently it is not exactly the same line - see screenshot below) and enhance mobile screen view

![screenshot from 2016-09-19 15 20 42](https://cloud.githubusercontent.com/assets/1583873/18633483/d55a629e-7e7c-11e6-9d51-891f63708b34.png)

**Comment by mariobehling** [comment]
Oh, just realized: In your test setup the track info sidebar disappears. Please check. It should be there as below:

![screenshot from 2016-09-19 15 24 24](https://cloud.githubusercontent.com/assets/1583873/18633569/3ee8c264-7e7d-11e6-8297-6cadac4bb278.png)

**Comment by jainaman224** [comment]
Reference for this issue: #817 #824 #827
