### ISSUE TITLE
add support as hosted webapp

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#80]
We'll be needing webmanifests to make this supported as a hosted webapp. 

There are three ways "hosted" webapps are packaged. 
Firefox uses manifest.webapp
Chrome uses manifest.json 

And there is an upcoming w3c standard for manifest.webmanifest that is to support progressive webapps.

**Comment by creativepsyco** [comment]
Why is it needed, is it for the purpose of packaging it as a stand alone app?

**Comment by championswimmer** [comment]
I feel it will have a good thing to have. Having the said manifests, make
the app "look like" its a packaged app.

If the user goes to the site twice, Chrome asks 'Do you want to add a
shortcut to Desktop'. Firefox OS will do the same. Opera and Safari on iOS
supports too.

Basically it's taking a cue from the Progressive Web Apps article Mario
shared some time back.
It allows partial features of installable web apps (without having to
actually package it and put it on an app store)
It also helps in providing offline facilities when user wants to view pre
cached data without having internet. Which is not possible without having a
webapp manifest.

**Comment by mariobehling** [comment]
Yes, I think it is a great idea.

**Comment by nikunjness** [comment]
I'm including task for this in GCI task list.

**Comment by championswimmer** [comment]
@nikunjness  Have you added to task list ? Could you add me as mentor to it too

**Comment by nikunjness** [comment]
@championswimmer yes, I did. I will add you as a mentor.

**Comment by championswimmer** [comment]
This is at a nominal level done. The webapp works as a hosted webapp. Some rough edges are there, and more metadata needs to be added to the manifests, but I am closing the issue
