### ISSUE TITLE
Schedule/Venue Page: Box area not always linkified

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#800]
Some areas of box areas on rooms/venue and schedule are not linkified to allow expansion on click.

![screenshot from 2016-09-11 10 25 38](https://cloud.githubusercontent.com/assets/1583873/18416107/65c05038-780a-11e6-9bf3-762419c209ab.png)

**Comment by aayusharora** [comment]
It works fine for me. @mariobehling Can you please specify browser and OS. It seems to be a browser specific issue.

**Comment by mariobehling** [comment]
Tried it on different browser (Chrome/FX) and Linux. Please try all areas and different sessions by moving the cursor slowly. Please ensure that all areas linkified.

**Comment by Princu7** [comment]
@aayusharora  @mariobehling  I have tried it on firefox and can confirm the bug. I have been on it for some time but couldn't exactly pinpoint the cause of the bug.Same css class is used for all the rooms which set the cursor to pointer when someone hovers on them. But still some of them works fine and others don't. Any ideas regarding what could cause it?

**Comment by shubham-padia** [comment]
@mariobehling The issue is caused by track names on the right as seen in the screenshot below.
![screenshot from 2016-09-13 06-34-02](https://cloud.githubusercontent.com/assets/13910561/18458265/5c41fc54-797d-11e6-8e80-d451e5c39fca.png)

I've tried to fix this in #806. Please review it.
