### ISSUE TITLE
Fix and clean up html/css on speakers page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#801]
On speakers page

* [x] Take out implementation of designs from html page and if required implement as css or better: reuse existing style
* [x] Align all text and elements on one line
* [x] Minimize the use of different font styles, sizes and colors
* [x] Reduce height of empty white space at bottom

![screenshot from 2016-09-11 13 33 04](https://cloud.githubusercontent.com/assets/1583873/18416995/1049b64c-7825-11e6-815d-520ac0e675c7.png)

**Comment by mbad0la** [comment]
@mariobehling can I try to get this resolved?

**Comment by mariobehling** [comment]
@mbad0la Would be great. Thank you.

**Comment by jainaman224** [comment]
I would also like on this ...? @mbad0la can we work together on this issue...?

**Comment by mbad0la** [comment]
@jainaman224 I'm done with the code locally. I just have to test it out once.
The delay is due to my mid-semester exams this coming week. I'll let you know though, if some problem comes up.

**Comment by aayusharora** [comment]
@mbad0la Is it done ?

**Comment by jainaman224** [comment]
Please close this issue if already implemented.
Else assign me this issue please, I would like to work on this.

**Comment by jainaman224** [comment]
@mariobehling Please mark boxes which are implemented. May be there is difference between your expectation and current implementation.
