### ISSUE TITLE
Speakers Page: On small screens left align pop up text in same way as on big screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#802]
Currently the pop-up texts of speaker info on small screen are centered. Please use the same style as on big screens and do not change alignment.

![screenshot from 2016-09-11 13 45 41](https://cloud.githubusercontent.com/assets/1583873/18417064/5e7e70cc-7826-11e6-9c25-ff4398d2adc1.png)

**Comment by Princu7** [comment]
I have found the bug. I will send in a pull request soon.

**Comment by aayusharora** [comment]
This is done #805
