### ISSUE TITLE
Cursor does not behaves properly on the tracks page

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#807]
It doesn't change to pointer. And sometimes it changes to text selection. Not sure whether it is done deliberately or not. The user will not know that on clicking there, more detailed description of the session will display.
![screenshot from 2016-09-13 16-58-25](https://cloud.githubusercontent.com/assets/8847265/18472220/b5ad3686-79d3-11e6-8d74-8ca1075cb0f7.png)
 
The bug is quite simple to fix and if it is is not deliberately done, I will send a request soon.

**Comment by mariobehling** [comment]
Yes, please send a PR. Thank you.
