### ISSUE TITLE
Disable tab in navbar

### ISSUE THREAD

**Issue by jainaman224** [fossasia/open-event-webapp#809]
Would it be better to disable tab in navbar for current page rather reloading it...?
Currently, if we click on same tab it reloads the page.

**Comment by aayusharora** [comment]
@jainaman224 Which tab . Can you please provide steps to reproduce.

**Comment by jainaman224** [comment]
Talking about this code.

```html
    {{#if timeList}}
         <li class="navlink"><a id="schedulelink" href="schedule.html">Schedule</a></li>
      {{/if}}
```

If we are on same page. It will be better if we add any class to it to disable that 'li' tag. Instead of reloading that page or we can use it as go to top.
