### ISSUE TITLE
Html minifier should be included in docs

### ISSUE THREAD

**Issue by jainaman224** [fossasia/open-event-webapp#813]
While running npm, I discovered that html-minifier does not come pre installed in npm. We need to add it explicitly. Therefore, isn't it better to include in documentation to assist developers...?
Link I referred to install html-minifier is https://www.npmjs.com/package/html-minifier.

**Comment by aayusharora** [comment]
I don't understand this. Please check you have npm install  first. It's already here https://github.com/fossasia/open-event-webapp/blob/development/package.json#L35.

**Comment by jainaman224** [comment]
Ohh ok sorry, I have not seen that you have update package.json. Still I will see, why it was not installed itself. May be there is a conflict.
