### ISSUE TITLE
Bad Layout Speakers page on Mobiles

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#815]
By some previous PR's , Speaker page layout is disturbed on Small screens.
![4](https://cloud.githubusercontent.com/assets/12194719/18566800/f984df04-7bb2-11e6-84f2-15470c036fea.png)
- [ ] Shift popover exactly below the image.
- [ ] Remove X-axis scrollbar

**Comment by Princu7** [comment]
In the current implementation, on small screen the pop-up box is displayed from the centre of the image. So we have added a class which adds a necessary left margin to make the pop-up box shift to the left to make it coincide with the image.  The problem with that is that the different small screen sizes will require different left margin for perfect overlap. So we have to add various more screen sizes and the corresponding left margin for making the pop up come directly under the screen. The previous pull request left out some cases so it was working on devices with width size 320-360px but looked a bit abrupt on 500px wide screens.There might be better solutions but we will have to think for those. I am willing to work on this. Just need some guidance.

**Comment by Princu7** [comment]
@aayusharora Not exactly the same thing as asked, but please do check out this page I made after doing some changes . Run it on different screen sizes and it should not look bad in general. 
https://princu7.github.io/websiteTest/speakers.html
There are some cases where we don't want to shift the popovers exactly below the image. Suppose the width of the screen is 700px then only one picture of width 300px will come in a single row. If we shift popovers exactly below the image, then a lot of the white space will be wasted(400px to be precise). A better alternative than that would be just to display the picture in the middle and let the pop-over have the full size of the screen. It does look neat and clean.
For example-
Intended version
![screenshot from 2016-09-16 15-52-17](https://cloud.githubusercontent.com/assets/8847265/18583028/dedf04cc-7c25-11e6-808a-bb35c1d304d5.png)

Alternative version
![screenshot from 2016-09-16 15-53-07](https://cloud.githubusercontent.com/assets/8847265/18583043/eb180040-7c25-11e6-9a4a-de066b200a6a.png)

The second looks a tiny bit better. Views and suggestions?

**Comment by aayusharora** [comment]
@Princu7 The second view is destroyed badly. To improve 
Follow the first view.

**Comment by Princu7** [comment]
@aayusharora Ah. My bad. No problem. I will implement keeping the first view in mind. Will Ping you as soon as I am done with it. Thanks for the feedback.

**Comment by Princu7** [comment]
@aayusharora I am sorry but I got confused after your edit. We are supposed to go with the first view or second view?

**Comment by aayusharora** [comment]
@Princu7 I am convinced for this on Tablets or only for some CSS breakpoint range. Thanks

**Comment by Princu7** [comment]
@aayusharora Thanks. I will send a request soon.
