### ISSUE TITLE
Text difficult to read on some colours

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#816]
For example in the room page, the black text is difficult to read and looks unaesthetic on some colours.
Example
![screenshot from 2016-09-16 21-40-11](https://cloud.githubusercontent.com/assets/8847265/18592921/c5c6cfac-7c56-11e6-8d56-586f2fadab50.png)
![screenshot from 2016-09-16 21-40-53](https://cloud.githubusercontent.com/assets/8847265/18593082/682aab9c-7c57-11e6-9be3-04d3b7c5b8dc.png)

I think it would be better if we could change the font colour on those background to something else like white or something.Views and suggestions? If possible, I would like to work on this issue.

**Comment by aayusharora** [comment]
> I think it would be better if we could change the font colour on those background to something else like white or something.
@Princu7  What are your plans ?
1. Taking classes or div's whose Track Colors are brown and make their text color to light/ white by using Javascript can be done.
2. I am not sure the UI issues that will arrive, Can you provide a prototype ?

**Comment by Princu7** [comment]
@aayusharora
1. I have an alternative solution. There are maybe 15 distinct colours used for the sessions. In the template files in which the div's are being generated, we get their colours from the _`color`_ property stored in the sessions object.If we could add another property named "text-colour" to the sessions object, then we can directly set the font-colour by writing _`font-color:{{{text-color}}}`_ in the template file. We will be able to set the text-colour of our liking without using any client-side javascript code.

2. I will try to provide the prototype as soon as I can. A bit delay may happen because of the oncoming examinations. Sorry.

**Comment by Princu7** [comment]
@mariobehling  @aayusharora 
I apologize for a little delay in tackling this issue. So I made some changes in the server side code as in the above mentioned way to make the colours look more neat and tidy. Here are the screenshots comparing the differences.
Old
![old1](https://cloud.githubusercontent.com/assets/8847265/18839769/d2685dea-8429-11e6-8767-0e4268b9ee92.png)
New
![new1](https://cloud.githubusercontent.com/assets/8847265/18839780/dd3b3efe-8429-11e6-915f-aec3c1ede06b.png)
Old
![old2](https://cloud.githubusercontent.com/assets/8847265/18839791/e42f6398-8429-11e6-88e4-7b36b36825e2.png)
New
![new2](https://cloud.githubusercontent.com/assets/8847265/18839813/fa935414-8429-11e6-8588-04de2812144f.png)
Please review and suggest. Thanks

**Comment by Princu7** [comment]
@mariobehling  @aayusharora  Any reviews and suggestions on this issue? I have already completed it. Need some feedback. Thanks!!.

**Comment by mariobehling** [comment]
The sample file is just - a sample. The choice of colors depends on the organizer, that is set in the organizer server. I do not see a perfect solution at the moment and for now I think the existing solution is - good enough. We have lots of other issues of higher priority. The choice of color of tracks and font, should ultimately be set by the orga server or in the json files, not by the web app.

**Comment by Princu7** [comment]
@mariobehling Makes perfect sense. Thanks for explaining!!

**Comment by aayusharora** [comment]
The track colors are chosen by user, hence it is not feasible to set `text-color`. I don't think this is needed. Please reopen if you see any other use case :)
