### ISSUE TITLE
Add error information in case build fails

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#819]
![screenshot from 2016-09-21 15 55 27](https://cloud.githubusercontent.com/assets/1583873/18713985/92123b58-8014-11e6-98a7-b374cc52efb2.png)

Please add a simple triangle in the area "copying assets". 

Expected behaviour: After the login is finished or failed the user can see the log info.

There can be a triangle button with the log info that can be expanded by the user, if wanted, something like "> See build logs"

**Comment by Princu7** [comment]
Can I take this up @mariobehling

**Comment by mariobehling** [comment]
@Princu7 Yes, sure. Please post screenshot on how you implement it here. Thank you.

**Comment by Princu7** [comment]
@mariobehling I have done some work on this issue. First I have classified the log messages into three types  - 
'Info' - Describes some task which is being done or started.
'Success' - Describes the successfull completion of an event or task.
'Error' -  Describes a task that has failed. It will have the option of viewing the detailed information about the error.

The logs are generated on the go i.e. user can view the log while the app is being generated in real time.I will add some screenshots and the working demo app as soon as I am finishing it. Please give some suggestions and advice. Thank you
