### ISSUE TITLE
Reduce empty white area in generator site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#820]
Please see below which white areas height to reduce.

![screenshot from 2016-09-21 15 56 38](https://cloud.githubusercontent.com/assets/1583873/18714146/22842f34-8015-11e6-9d46-681535cae21b.png)

![screenshot from 2016-09-21 15 56 19](https://cloud.githubusercontent.com/assets/1583873/18714156/2774a8ac-8015-11e6-8ae2-a595a0521474.png)

**Comment by jainaman224** [comment]
I would like to work on this.

**Comment by aayusharora** [comment]
Go for it @jainaman224

**Comment by jainaman224** [comment]
@mariobehling @aayusharora how does this look now...?

![screenshot from 2016-09-22 15-59-49](https://cloud.githubusercontent.com/assets/13117482/18744923/9d74d1bc-80dd-11e6-90e0-1f725df2e5aa.png)

![screenshot from 2016-09-22 16-01-14](https://cloud.githubusercontent.com/assets/13117482/18744947/d38f4124-80dd-11e6-8b21-f8d21ea77afb.png)

**Comment by mariobehling** [comment]
Thank you. Yes, this is the way to go.

Could you make the distance between the areas same, so:
* [ ] Same space between email field and next field; same space between App's Name and Choose your source; same space between API endpoint and Link to Open Event API and so forth?
* [ ] Please also move up the "Generate Webapp" button and reduce the height of the area with the build info
