### ISSUE TITLE
Avoid internal scroll bars in small resolutions/mobile screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#822]
On the start page there is an internal scroll bar, which is ok in large resolutions but not suitable for mobile/small screens. Please see below.

Expected behaviour: Instead of scroll bars area is expanded.

![screenshot from 2016-09-21 16 48 48](https://cloud.githubusercontent.com/assets/1583873/18716374/e3639436-801c-11e6-8f80-54f3ede002c1.png)

**Comment by jainaman224** [comment]
@mariobehling I am unable to find this internal scroll bar. 

![screenshot from 2016-09-25 19-40-51](https://cloud.githubusercontent.com/assets/13117482/18815805/04010064-8358-11e6-8327-df4ea4c57045.png)

**Comment by jainaman224** [comment]
@mariobehling There should be scroll bar to see full description about speaker.
![screenshot from 2016-09-25 19-49-03](https://cloud.githubusercontent.com/assets/13117482/18815837/2248ee3c-8359-11e6-8e8f-efb478c7faa2.png)
I am unable to find a way to read full description on devices that do not support touch.

I would like to work on removing outer scroll bar on small devices.

**Comment by mariobehling** [comment]
ok, great.

**Comment by shubham-padia** [comment]
@mariobehling Unable to recreate this issue. Cannot find internal scrollbars in small screens right now. Please recheck or add steps to recreate the issue.

**Comment by shubham-padia** [comment]
@mariobehling Sorry for the inconvenience, found it .
