### ISSUE TITLE
Start Page: Increase space to map

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#823]
The address text is attached directly to the edge of the map. Please increase the indent/space in this area.

![screenshot from 2016-09-21 17 01 41](https://cloud.githubusercontent.com/assets/1583873/18716494/50f3a108-801d-11e6-9f7a-45f4b9d329ff.png)

**Comment by Princu7** [comment]
@mariobehling  How does this look?
![screenshot from 2016-09-22 02-34-46](https://cloud.githubusercontent.com/assets/8847265/18728999/82632a88-806d-11e6-84fa-121c0251b175.png)

**Comment by mariobehling** [comment]
Good.

**Comment by jainaman224** [comment]
Is this issue resolved...? If not, I would like to work on this and I have done same for orga-server.

**Comment by mariobehling** [comment]
It was resolved, but not linked unfortunately.
