### ISSUE TITLE
Navbar on small devices

### ISSUE THREAD

**Issue by jainaman224** [fossasia/open-event-webapp#829]
@mariobehling @aayusharora navbar on small devices can be improved by some social media icons.

![screenshot from 2016-09-25 19-40-51](https://cloud.githubusercontent.com/assets/13117482/18815816/5cf923d6-8358-11e6-888a-6e74894097b0.png)

**Comment by mariobehling** [comment]
Interesting point, but I do not see your suggestion, what exactly you would like to have or to do. I have opened an issue with some suggestions, but I am not sure if this is the same as what you want. I am closing this issue as there is no clear outline, what specifically needs to get done. An issue about improving the nav bar in small resolution is here: https://github.com/fossasia/open-event-webapp/issues/835
