### ISSUE TITLE
Unnecessary Margins in Sessions/Speakers details

### ISSUE THREAD

**Issue by MaxBorsch** [fossasia/open-event-webapp#83]
<b>Summary</b>
When you navigate to the Sessions or Speakers page and then select one of the listed speakers/sessions, extra details will pop up. The details view has an extra empty h2 tag that adds unnecessary margins above and below itself. I noticed that the Track details also has this, however the h2 tag in the Track details has text in it, so the margins look OK. I have included images showing this.

<b>Steps to Reproduct Bug:</b>
1. Start server locally, navigate to web app page. (http://localhost:8080/)
2. Click on Speakers tab or click on Sessions tab.
3. Select a Speaker or Session from the list.
4. The details view will show, in the details view there should not be an extra empty h2 tag that adds unnessesary margins. 

The empty h2 tag is shown here:
![unnessesary element](https://cloud.githubusercontent.com/assets/2924585/11674603/793777e4-9df0-11e5-9861-5dbcc6db238f.png)

Shows unnecessary margins:
![speakers bad](https://cloud.githubusercontent.com/assets/2924585/11674604/7939c350-9df0-11e5-9987-f492de44b0e3.png)

Track details, which has a title so margins look good:
![tracks good](https://cloud.githubusercontent.com/assets/2924585/11674270/2149b630-9ded-11e5-9b85-5ce1fdce29c6.png)

**Comment by aayusharora** [comment]
Hi @MaxBorsch I want to work on this bug. Can you assign it to me ?

**Comment by MaxBorsch** [comment]
Ok, how do you assign an issue? (I¹m not very familiar with GitHub)

From:  aayusharora <notifications@github.com>
Reply-To:  fossasia/open-event-webapp
<reply+002ca029781f652778424c384a841f1bff911fdb2664d99c92cf000000011284242d9
2a169ce073889ef@reply.github.com>
Date:  Saturday, December 12, 2015 at 1:06 PM
To:  fossasia/open-event-webapp <open-event-webapp@noreply.github.com>
Cc:  Max Borsch <maximborsch@gmail.com>
Subject:  Re: [open-event-webapp] Unnecessary Margins in Sessions/Speakers
details (#83)


Hi @MaxBorsch <https://github.com/MaxBorsch>  I want to work on this bug.
Can you assign it to me ?


Reply to this email directly or view it on GitHub
<https://github.com/fossasia/open-event-webapp/issues/83#issuecomment-164172
809> .

**Comment by nikunjness** [comment]
Hi @aayusharora, 

@mariobehling or @creativepsyco will be able to assign this to you. Are you GCI student? because there's task to fix this bug in GCI.

**Comment by aayusharora** [comment]
No,I am not a GCI student .

**Comment by PiotrKowalski** [comment]
I'd like to do it. But I've got claimed another task. What should I do it? Wait to review claimed task? 
I've just solved problem only thing is to pull request

**Comment by PiotrKowalski** [comment]
Indeed, you think about it? http://scr.hu/3e1h/ryii6
 I will repair this. Give me a sec.

**Comment by MaxBorsch** [comment]
I have it fixed (hopefully) and pull requested. You probably shouldn't spend time on tasks that you haven't claimed yet. Also it wasn't the CSS that was the problem, you had to do a small angular fix.

**Comment by PiotrKowalski** [comment]
Oh, okey. Could you tell me where you fixed ? You know I would like to know where I should have repaired it

**Comment by MaxBorsch** [comment]
You can check what I changed by looking at my pull request and clicking "Files Changed" it will show you what I changed.

**Comment by daminisatya** [comment]
I din't get the exact bug. PFA.
![selection_022](https://cloud.githubusercontent.com/assets/6227784/13196539/90bf5040-d7f6-11e5-8fdc-418da52ccd68.png)
![selection_023](https://cloud.githubusercontent.com/assets/6227784/13196540/97606682-d7f6-11e5-94da-13c9f2422ef3.png)

The dialog box in tracks section has an extra space between the crumbs and the title. It was left out for subtitle. But I put an ng show directive there to dynamic add the subtitle when present.
