### ISSUE TITLE
Date not clickable and break into two parts on small screens

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#831]
Here is the screenshot demonstrating the issue.
![screenshot from 2016-09-26 21-57-36](https://cloud.githubusercontent.com/assets/8847265/18842923/5d7e6e88-8434-11e6-8f32-3e3316a1921d.png)
I played around with it and this is how it looks after some change
![screenshot from 2016-09-26 21-58-11](https://cloud.githubusercontent.com/assets/8847265/18842940/6e0d7d3e-8434-11e6-892e-a505519cdaf8.png)

@mariobehling @aayusharora
Thoughts and suggestions?

**Comment by poush** [comment]
Please close this issue if it is already solved
