### ISSUE TITLE
top left logo should link to "Home" directory instead of same page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#834]
The top left logo links to the current page at the moment. It should link to the home directory. I have missed the pull request where someone changed this as it was like that before.

![screenshot from 2016-10-04 14 06 40](https://cloud.githubusercontent.com/assets/1583873/19073788/25db408c-8a3d-11e6-8774-d5985a511ff5.png)

**Comment by jainaman224** [comment]
I would like to fix this bug with issue 835.

**Comment by jainaman224** [comment]
@mariobehling please review https://issue835.herokuapp.com/ .

**Comment by mariobehling** [comment]
Thank you. Please provide a link to the sample github pages setup in future, if possible to help everyone save time.

Please link to "/" - home directory instead of "/index.html". Cheers.

**Comment by aayusharora** [comment]
Thanks @jainaman224
