### ISSUE TITLE
Small Resolution: Show icons for main tabs and move social icons to hidden menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#835]
Right now in small screen resolutions the social icons show up as the main menu and the dropdown menu shows the links of the web app.

![screenshot from 2016-10-04 14 27 25](https://cloud.githubusercontent.com/assets/1583873/19074110/daf68c3c-8a3e-11e6-975d-d904941a61f3.png)

The main menu should show the main links instead of external social media links. Therefore please implement as follows in small screen resolutions:
- [ ] Show icons for the main web app links in the top menu: Home, Schedule, Tracks, Rooms, Speakers
- [ ] Keep the dropdown menu as is, but move the social media icons into the last row (in one line) as in the example on http://fossasia.org 

![screenshot from 2016-10-04 14 32 56](https://cloud.githubusercontent.com/assets/1583873/19074226/84044fe4-8a3f-11e6-8e82-8b20dc16a560.png)

**Comment by jainaman224** [comment]
I would like to work on this.

**Comment by jig08** [comment]
@jainaman224 Sure, go ahead.

**Comment by jainaman224** [comment]
@mariobehling @jig08 how does it look now...?
![screenshot from 2016-10-05 11-51-34](https://cloud.githubusercontent.com/assets/13117482/19103051/2d98ad68-8af2-11e6-88b2-d34945ae3561.png)

**Comment by jig08** [comment]
>main web app links

Didnt get you ?

**Comment by jainaman224** [comment]
Can you please see the first implementation, mario Sir wants i.e.
> Show icons for the main web app links in the top menu: Home, Schedule, Tracks, Rooms, Speakers

**Comment by mariobehling** [comment]
@jainaman224 Thank you, dropdown is already the way we need it now. Please deploy the sample on your github and provide links. Screenshot do not give the full picture always. Also please add icons on the top for Home, Schedule etc...

**Comment by jainaman224** [comment]
@mariobehling please review https://issue835.herokuapp.com/ .

**Comment by mariobehling** [comment]
@jainaman224 Thank you. Please make a PR. This is a good first step. Next step is to add icons in the top bar.

Please help us and make it easier for us to review: In future, please make PRs and show us the final site.

**Comment by jainaman224** [comment]
@mariobehling Sure sir, sorry for delay caused because of health concerns.

**Comment by jainaman224** [comment]
Please suggest me icons for rooms and tracks page.

**Comment by mariobehling** [comment]
@jainaman224 Please check out https://openclipart.org and tell us, what you think is suitable. Cheers.

**Comment by aayusharora** [comment]
@jainaman224  Are you working on this ?

**Comment by jainaman224** [comment]
@aayusharora Currently I am bit busy. I will work after 1 month, if it is ok. Sorry, for not informing.

**Comment by Tikam02** [comment]
sir can i contribute to this issue.

**Comment by Princu7** [comment]
@jainaman224 Are you working on this issue?

**Comment by Tikam02** [comment]
Actually in http://fossasia.org website when menu bar is clicked the page moved to left side:Like this 
![foss-page](https://cloud.githubusercontent.com/assets/10548085/21253502/47372c24-c385-11e6-8b13-031feb7f7412.png)
![foss-page1](https://cloud.githubusercontent.com/assets/10548085/21253508/54421f0a-c385-11e6-8e3b-389e15ba3a54.png)
 we can do is just make a simple horizontal menu-bar and which will show all the social icons:and not affect the page.

**Comment by Princu7** [comment]
@Tikam02 Thanks for pointing out the issue. Yes. You can work on the above bug. Since this is a open-event-webapp repository, you will have to create the corresponding issue in the FOSSASIA site repository. You can work from there.

**Comment by Tikam02** [comment]
Thanks 👍 i will do.

**Comment by yashNadun** [comment]
@mariobehling can I take this?

**Comment by mariobehling** [comment]
@yashNadun Sure, please go ahead.

**Comment by mariobehling** [comment]
@yashNadun Please accept the invitation to the FOSSASIA team, so we are able to assign you.

**Comment by adarsh-ideal** [comment]
@mariobehling What else is needed to be done here?

**Comment by ParthS007** [comment]
working on it due to inactivity 👍

**Comment by ParthS007** [comment]
@mariobehling  Can we use material icons here?

**Comment by AdityaHirapara** [comment]
@ParthS007 Are you still working on this?
if not, then I would like to take this.

**Comment by ParthS007** [comment]
@AdityaHirapara  Please go ahead :+1:  You can work on this.

**Comment by mariobehling** [comment]
Closing this in favor of https://github.com/fossasia/open-event-webapp/issues/1775
