### ISSUE TITLE
Ensure columns on schedule page have same width as columns on rooms page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#838]
The schedule page has different column widths to the rooms page. Please change the width of the column pages and ensure it matches the design of the rooms page.

**Comment by Princu7** [comment]
@mariobehling 
I saw the source code of both the pages and they seemed to be using the same width of the columns. The date row was given 2 columns and the session titles were given 10 columns in both the pages. Can you please specify what specific changes in the width are we aiming for? Thanks.

**Comment by mariobehling** [comment]
Please compare sample page:
http://fossasia.github.io/open-event-webapp/schedule.html and http://fossasia.github.io/open-event-webapp/rooms.html

Width of left side and middle column are different.

**Comment by Princu7** [comment]
@mariobehling 
How is this?
![screenshot from 2016-10-05 23-33-35](https://cloud.githubusercontent.com/assets/8847265/19125309/3b964396-8b54-11e6-813a-dbdac219be82.png)
Comparing with rooms page
![screenshot from 2016-10-05 23-34-34](https://cloud.githubusercontent.com/assets/8847265/19125333/558d22ce-8b54-11e6-91ee-6eabd22c61b8.png)

**Comment by mariobehling** [comment]
Very good. Thank you.

**Comment by aayusharora** [comment]
closed via #854 :)
