### ISSUE TITLE
Implement upload progress area similar to gmail upload area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#840]
The upload area currently looks like that during upload:

![screenshot from 2016-10-05 19 36 45](https://cloud.githubusercontent.com/assets/1583873/19124343/1abf5ae8-8b33-11e6-85f9-5b91e0edef97.png)

Please implement a progress bar in the upload area similar to Gmail uploads as below.

![screenshot from 2016-10-05 19 34 07](https://cloud.githubusercontent.com/assets/1583873/19124419/6ee8861c-8b33-11e6-9eeb-e13d0732efe2.png)

**Comment by aayusharora** [comment]
@mariobehling The webapp generator page is without CSS. 
>Please implement a progress bar in the upload area similar to Gmail uploads as below.
This will require CSS. Should we write CSS in generator's page ?

**Comment by mariobehling** [comment]
Yes, I think it is the right time to add simple CSS.

**Comment by championswimmer** [comment]
@aayusharora It does use Bootstrap though doesn't it ?

**Comment by poush** [comment]
I am giving it a try.

**Comment by poush** [comment]
Something like this ?
<img width="444" alt="screen shot 2016-10-12 at 11 37 18 pm" src="https://cloud.githubusercontent.com/assets/1812082/19322008/e8bd345a-90d4-11e6-9ac3-9694cd0ce125.png">

**Comment by mariobehling** [comment]
Partly correct. The upload progress bar should show up exactly at the place where there is "choose file FOSSASIA16.zip". Also please add an "x"  at the end to give the user the choice to stop the process and return to the "choose file" bar.

**Comment by mariobehling** [comment]
<img width="436" alt="e8bd345a-90d4-11e6-9ac3-9694cd0ce125" src="https://cloud.githubusercontent.com/assets/1583873/19322726/7468eb18-90ba-11e6-8c3d-7debd01ce4e0.png">

**Comment by kartikhsr** [comment]
i want to work on this....can you help me how to do so sir

**Comment by poush** [comment]
Hi @kartikhsr Actually I am in mid of this. I had some work to complete that's why it is taking time.

**Comment by kartikhsr** [comment]
No issue sir...!!
I am a begineer so i am quite eager to work if guided by anyone...!!!
I can complete short and slight work easily , if you want so...i am ready to do..!! @poush

**Comment by kartikhsr** [comment]
@aayusharora i can add css easily...!!
I can help you if guided by you a little..!!

**Comment by Princu7** [comment]
Can I work on this? @mariobehling

**Comment by poush** [comment]
This is how it looks currently
![screenflow](https://cloud.githubusercontent.com/assets/1812082/19966125/69f78332-a1f0-11e6-92ec-f7758f75c177.gif)

Any suggestions ?

**Comment by Princu7** [comment]
@poush  Looks great :+1:

**Comment by mariobehling** [comment]
@poush Good job. Please make a PR.

**Comment by Tikam02** [comment]
i want to work on this issue.sir can i still contributeto it.

**Comment by aayusharora** [comment]
Solved via #934 Thanks @poush
