### ISSUE TITLE
Move link icon to row of social icons on tracks page

### ISSUE THREAD

**Issue by jainaman224** [fossasia/open-event-webapp#849]
@mariobehling I think this looks better 
![screenshot from 2016-10-14 23-02-29](https://cloud.githubusercontent.com/assets/13117482/19396764/4f8ed132-9262-11e6-93af-11f82722b3aa.png)
than
![screenshot from 2016-10-14 22-56-37](https://cloud.githubusercontent.com/assets/13117482/19396598/7ccc849c-9261-11e6-9472-7488f347922b.png)
Should I implement this...?

**Comment by aayusharora** [comment]
>I think this looks better ? 
 UX points 

@jainaman224 @mariobehling 
**"Link"**  does not refer to social link nor it is related to speaker , it is basically related to the whole container body representing the **content as card** which is shareable. I don't think we should attach it with social links.

**Comment by jainaman224** [comment]
@aayusharora I have suggested this to keep implementation similar to rooms page. Mario Sir has asked me to add link icon with social links #780 .
@aayusharora Ok, how about giving space between social links, as depicted above...?

**Comment by aayusharora** [comment]
@jainaman224  OK, I have read the issue #780, I don't think this to be a right approach to have link icon with speakers icons as I explained earlier and yeah space looks good to me.
@mariobehling  Can you check this once again?

**Comment by mariobehling** [comment]
Thank you for the input. There is never a perfect implementation for everyone and all use cases. Future implementations of the app will allow theme-ability to allow different implementations. For now please continue to follow a simple UI approach, where we do not clutter the starting UI too much and follow UI designs of existing apps, that are used by a lot of people, e.g. sched.org. 

@jainaman224 Therefore, please move the icon on all pages to the link area. Cheers.

**Comment by mariobehling** [comment]
Please move the link on tracks page as well. Cheers.

**Comment by aayusharora** [comment]
Its done :)
