### ISSUE TITLE
Schedule Page: Add link icon

### ISSUE THREAD

**Issue by jainaman224** [fossasia/open-event-webapp#857]
Like speakers, rooms and tracks page. It will be better to add link icon ![Link icon](https://cloud.githubusercontent.com/assets/1583873/18262985/b9cd6a88-7406-11e6-8f0f-369b2486b344.png) on schedule page.

**Comment by mariobehling** [comment]
Yes, please do. Thanks.

**Comment by aayusharora** [comment]
Solved by #857
