### ISSUE TITLE
Auto-deploy sample of Open Tech Summit to Heroku

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#861]
The sample of the OpenTechSummit has a lot of audio files, that are too big to deploy to Github without Large File Support. Therefore please auto-deploy the sample on pull request merges to Heroku.

The sample file is here: https://github.com/fossasia/open-event/tree/master/sample/OTS16

**Comment by shubham-padia** [comment]
@mariobehling  Looks like the `OTS16` sample is broken , i have implemented the solution using FOSSASIA16 sample right now. Please review #869

**Comment by mariobehling** [comment]
@shubham-padia Please open an issue here for the sample and describe what is the problem: https://github.com/fossasia/open-event

Would be great if you could help to solve it. Cheers.

**Comment by shubham-padia** [comment]
@mariobehling I'll start working on the issues asap. Meanwhile closing #869 .

**Comment by shubham-padia** [comment]
@mariobehling The max. slug size for heroku is 300MB which is exceeded by the current build if the OTS sample site is included.

```
-----> Compressing...
 !     Compiled slug size: 522.9M is too large (max is 300M).
 !     See: http://devcenter.heroku.com/articles/slug-size

 !     Push failed
       Done: 50.5M
-----> Launching...
```
Another solution is we can auto-deploy the OTS sample to website via FTP.
Your views?

**Comment by mariobehling** [comment]
> Another solution is we can auto-deploy the OTS sample to a website via FTP

@shubh1m Yes, good idea. How could we hide the ftp login data?

**Comment by shubham-padia** [comment]
Travis supports custom ftp deployments and the login data can be encrypted . For more refer https://docs.travis-ci.com/user/deployment/custom/#FTP

**Comment by shubham-padia** [comment]
@mariobehling If the solution seems feasible, i can try out the solution with my domain, should i go ahead ?

**Comment by aayusharora** [comment]
@shubham-padia Can you please outline, how you are going to implement this ?
