### ISSUE TITLE
Search on Tracks Page not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#863]
Please ensure that search is working again on tracks page, e.g. http://fossasia.github.io/open-event-webapp/tracks.html

**Comment by jainaman224** [comment]
@mariobehling Sir, I have already fixed it in #856

**Comment by mariobehling** [comment]
@jainaman224 Must have been lost somewhere. Please check on site with latest code: http://fossasia.github.io/open-event-webapp/tracks.html Not working here.

**Comment by jainaman224** [comment]
Please assign me.
