### ISSUE TITLE
UI Improvements on small screens and mobiles

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#864]
- [x] On small screens ensure the search bar is using the full width
  ![screenshot from 2016-10-18 23 52 22](https://cloud.githubusercontent.com/assets/1583873/19497729/f30635d4-958d-11e6-9539-96284c043f7c.png)
- [x] On small screens ensure the date buttons are placed next to each other
  ![screenshot from 2016-10-18 23 55 23](https://cloud.githubusercontent.com/assets/1583873/19497820/69746740-958e-11e6-9743-39030edb625a.png)
- [x] On top menu bar show make menu item to use gray background on scroll over and click
  ![screenshot from 2016-10-19 00 03 07](https://cloud.githubusercontent.com/assets/1583873/19498047/6de8a614-958f-11e6-8dbe-ab4eb8d1bc06.png)

**Comment by poush** [comment]
Search bar will be automatically fixed once #841 is merged. For other two things here is the screenshot of changes.

Grey Background on mobile screens
<img width="707" alt="screen shot 2016-10-29 at 11 47 23 pm" src="https://cloud.githubusercontent.com/assets/1812082/19831855/451d7f88-9e32-11e6-930a-7d3d2d0f8c9e.png">

and date buttons as
<img width="641" alt="screen shot 2016-10-29 at 11 47 08 pm" src="https://cloud.githubusercontent.com/assets/1812082/19831861/57e98954-9e32-11e6-9b43-58047d2dd591.png">
