### ISSUE TITLE
Additional speaker info not displayed In mobile view

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#865]
There should be speakers info on click on picture of speaker in mobile view. 

Please ensure that the additional info is shown, e.g. on sample site: http://fossasia.github.io/open-event-webapp/speakers.html

![screenshot from 2016-10-19 00 04 04](https://cloud.githubusercontent.com/assets/1583873/19498112/bf43de34-958f-11e6-88fc-5dcce2d81574.png)

**Comment by aayusharora** [comment]
@mariobehling , popover appears on hover fpr speaker image. Please reverify the issue :)

**Comment by aayusharora** [comment]
Kindly reopen if it needs something more :)
