### ISSUE TITLE
Modify design and position of the audio player

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-webapp#876]
@mariobehling @aayusharora @championswimmer Your views ?

**Comment by mariobehling** [comment]
Please propose what you think.

**Comment by shubham-padia** [comment]
- **For design :** Something like http://codepen.io/katzkode/pen/Kfgix can be used which looks elegant and simple, and about the position of the audio player.
- **For position:** instead of putting the audio player on the blue card ( with session heading and small description etc ), we can have a tag or a symbol on the card that indicates that audio is available for that specific card, but audio can only be accessed after expanding the card ( in a way similar to current implementation in schedules page ) .
Please give you suggestions on this implementation..

**Comment by mariobehling** [comment]
> For design

Ok, give me a few days to test it, please.

> For position

Yes, very good idea. Let's do it like that and then test it a while. Sounds like this is the way to go for me.
