### ISSUE TITLE
make this available via bower and npm

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#88]
would be cool to have it that way

**Comment by SaptakS** [comment]
Yeah. I agree. This will require signing up [https://www.npmjs.com/signup](here) I think. Would love to add this.

**Comment by sakshamsaxena** [comment]
On NPM, I'd suggest no. On Bower, maybe yes. On Docker, hell yes.

**Comment by oren** [comment]
I can help dockerizing the app if there is any interest in doing it.
