### ISSUE TITLE
Default avatar not displayed on tracks pages

### ISSUE THREAD

**Issue by shubham-padia** [fossasia/open-event-webapp#884]
![selection_009](https://cloud.githubusercontent.com/assets/13910561/19833732/972ab2fe-9e6a-11e6-94f0-6e38bac069d3.png)

**Comment by aayusharora** [comment]
Thanks ! I will look at it.

**Comment by shubham-padia** [comment]
Nevermind :smile: , I've fixed it in #885 .

**Comment by shubham-padia** [comment]
Closing this via #885 .
