### ISSUE TITLE
Local upload of the OTS 16 Sample doesn't generate the event folder

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#890]
@mariobehling  @aayusharora  When we try to upload the zip file of the OTS 16 sample, the event folder is not generated and the web app crashes. This is because of the large size of the OTS16 sample owing to which all the contents are not copied before they are read.
Here is an piece of the error 
`Error: ENOENT: no such file or directory, open '/home/princu/open-event-webapp/src/backend/../../dist/copy@gmail.com/tempproject/json/sessions'`

I am working on this issue.

**Comment by aayusharora** [comment]
Thanks @Princu7
