### ISSUE TITLE
Bug: App not creating, Generator hangs without logs

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#897]
![bug](https://cloud.githubusercontent.com/assets/12194719/20240137/00241792-a937-11e6-9e29-d27bcd56eac7.png)

The current generator is not working here with FOSSASIA Zip https://opev-webgen-dev.herokuapp.com/

**Comment by shubham-padia** [comment]
@aayusharora Works fine for me. Is your sample updated ?
![selection_017](https://cloud.githubusercontent.com/assets/13910561/20240162/b2cec4aa-a937-11e6-91f2-6a0c570bd059.png)
