### ISSUE TITLE
Increase Code Coverage

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#909]
- Add atleast one test to `servertest.js` file  inside `test` folder and  increase code coverage 
- Use mocha and chai for writing test

**Comment by Heredroky** [comment]
@aayusharora The tested file will be servertest.js?

**Comment by Princu7** [comment]
@Heredroky Yes.

**Comment by adarsh-ideal** [comment]
@aayusharora I'll try to do this.

**Comment by aayusharora** [comment]
@adarsh-ideal cool, we need to write many tests. Go ahead !!

**Comment by Princu7** [comment]
I will add some tests :)

**Comment by geekyd** [comment]
@Princu7 That would be awesome!

**Comment by niharika88** [comment]
hi,
Can I take this up?

**Comment by geekyd** [comment]
@niharika88 Sure go ahead!
