### ISSUE TITLE
Adding a Wiki for the Repository

### ISSUE THREAD

**Issue by pipix51** [fossasia/open-event-webapp#913]
The current readme on the repository is long and may turn off new contributors, hence by using a wiki the documentation would be simplified and allow those who need help to find it easily. I have implemented a wiki repository on my fork (https://github.com/pipix51/open-event-webapp/wiki). Please review the wiki and suggest any changes.

**Comment by Princu7** [comment]
@pipix51 Thanks. The wiki looks good.  @mariobehling @aayusharora @shubham-padia Please give your  reviews and suggestions regarding this.

**Comment by shubham-padia** [comment]
@pipix51 Thank you, this will certainly make things easier for new contributors.
@Princu7 Looks good to me :smile:

**Comment by mariobehling** [comment]
Thanks for this idea. Unfortunately this will change the flow that we have been pursuing across the open event projects for now. Changes would require a longer discussion about pros and cons. Many Open Source projects keep a much longer documentation within their repository. We could also add a table of contents on top of the Readme.md. There are a number of things to consider and this is currently out of scope during GCI. Best time to discuss those changes that should be implemented across projects is just before GSoC. Therefore I am closing this issue. Thanks for your input and let's come back to this at a later point. Cheers!
