### ISSUE TITLE
Problem Installing Webapp Generator Locally on Windows

### ISSUE THREAD

**Issue by pipix51** [fossasia/open-event-webapp#914]
When I type in `npm install` for local machines (documentation link is https://github.com/fossasia/open-event-webapp/blob/development/docs/INSTALLATION_LOCAL.md), the command prompt throws an error which states that `node-gyp rebuild` fails on your system.
![error thrown by npm install](https://cloud.githubusercontent.com/assets/19341222/20857507/120e290a-b96a-11e6-948a-8fa1e572f354.png)

Even if I skip the first step and proceed to run `npm run start` or `npm run server.generator`, the command prompt throws another error which states that the program failed at the open-event-webapp@2.0.0 start script `npm run server.generator`.
![error thrown by npm run start](https://cloud.githubusercontent.com/assets/19341222/20857506/1204ebd8-b96a-11e6-8b95-8fdc3cf1011a.png)

After researching on the `npm run start` problem (link to article is https://github.com/nodejs/node-gyp/issues/629) I found out that this is a problem that affects only Windows users as the OS does not come bundled with a C++ compiler and that those who wish to run NodeJS projects would have to install Visual Studio. 
I suggest adding this to the documentation to allow users who wish to download the Webapp Generator on their local machine to know the prerequisites.

**Comment by aayusharora** [comment]
Thanks @pipix51 Once you are able to solve your problem, generate the PR by adding in readme.md.

**Comment by pipix51** [comment]
The pull request is at https://github.com/fossasia/open-event-webapp/pull/915

**Comment by aayusharora** [comment]
Good work @pipix51 Thanks :)
