### ISSUE TITLE
Implement additional config options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#916]
Currently the config.json is indicating to use Sendgrid as a standard mailer and Amazon S3 for storage. Please implement additional options in the json:
* [ ] Add the option to use either Sendgrid or an SMTP mail delivery
* [ ] Add the option to use either Amazon S3 or local storage
* [ ] Also add documentation about the options into the file

**Comment by uttpal** [comment]
@mariobehling I would like to work on this issue, 
I will add option in config to set default mailing system(either sendgrid or smtp) in config, and use that transport to send mails.

**Comment by aayusharora** [comment]
@uttpal Thanks !! go ahead.

**Comment by uttpal** [comment]
@mariobehling @aayusharora  which version of node are you using, and are you comfotable with promises and generators for async.

**Comment by Princu7** [comment]
@uttpal I think we are using 5.0 and promises and generators should be fine. :+1:

**Comment by Princu7** [comment]
@uttpal The code looks great. Please update your PR description with the number of this issue which you are trying to solve. Also, it would be great if we could test it out somewhere. Please deploy the app on Heroku for the same.
@mariobehling @aayusharora What should be the default option for mail delivery? SMTP or Sendgrid? @uttpal Has set the default to SMTP.

**Comment by mariobehling** [comment]
@Princu7 I guess SMTP as it could be used immediately? But we need to make sure the automatic deployment still works.

**Comment by uttpal** [comment]
@mariobehling @Princu7 App is live at https://openevent-app.herokuapp.com/

**Comment by Princu7** [comment]
@uttpal Works great. Looking at your code, it seems that you have not set user and pass in SMTP configuration to environment variables. Please do it so that we can set them as config variables on the Heroku Platform for the official app. 

@mariobehling @aayusharora Is there any FOSSASIA official account from which we can send emails to the users instead of using the email address of the contributors?  It would appear more professional that way.

**Comment by uttpal** [comment]
@Princu7 Added smtp credentials.

**Comment by Princu7** [comment]
@uttpal Please don't add credentials on Github. No. In fact, revert it immediately. What I wanted to say was to do something like this:
user: process.env.smtpusername
pass: process.env.smtppassword

**Comment by Princu7** [comment]
We would then set them(user and pass) as config variables on Heroku which will behave as environment variables for the app. This way, no one will be able to see or use your credentials and it will give other users flexibility to change it while working locally or on cloud. Sorry for the misunderstanding.

**Comment by uttpal** [comment]
@Princu7 Sorry for such a misunderstanding, I am removing it right away and adding environment variables.

**Comment by uttpal** [comment]
@Princu7 Reverted changed and added environment variable, also updated the app at  https://openevent-app.herokuapp.com/.

**Comment by Princu7** [comment]
@uttpal Nice. Please email me your credentials so we can set them as config variables on Heroku. Thanks.

**Comment by uttpal** [comment]
@Princu7 credentials mailed!

**Comment by Princu7** [comment]
@uttpal They will be added shortly. Please squash your recent commits into one, please.

**Comment by uttpal** [comment]
@Princu7 Commits squashed.

**Comment by Princu7** [comment]
@uttpal I am extremely sorry for troubling you again. The number of environment variables are getting a bit high in my opinion. I think that we don't need to set anything as environment variable apart from the password. What do you suggest?

**Comment by uttpal** [comment]
@Princu7 That's perfectly fine as I have already implemented fallback, if the environment does not exist it will automatically search in the config, as of now config already contains host and port,  you just need to add username and password in the environment. does this work?

**Comment by Princu7** [comment]
@uttpal Yeah. Should be fine.
