### ISSUE TITLE
Updated gif about how to generate open-event-webapp

### ISSUE THREAD

**Issue by SrijanJha28** [fossasia/open-event-webapp#924]
There should be a video that how a person can generate the open event app

**Comment by Princu7** [comment]
@SrijanJha28 Thanks for the suggestion but we already have a GIF of the process of generating the open event webapp in the documentation. If you find something that can be improved in that, then do tell us.

**Comment by SrijanJha28** [comment]
It is a video by aayush arora in youtube which I would like to add in the readme file so that if anyone finds it difficult they may watch that video

**Comment by Princu7** [comment]
The video is really nice but a bit outdated. Most of the options are not present anymore. The current animation on the documentation page is a little more recent than that and the user doesn't have to leave the site and go to another domain. If you could make an updated GIF of the generation process, it would be really great. 
@mariobehling @aayusharora Please give your opinions on having an updated build process GIF in the documentation. Thank You.

**Comment by SrijanJha28** [comment]
Can you tell me from where would I get Upload your own JSON files or  API endpoint of event on OpenEvent

**Comment by aayusharora** [comment]
@Princu7 I agree, we should have an updated gif. @SrijanJha28  Thanks but the video is outdated according to the previous requirement of the project. Now it is changed and hence it will be better if you can provide the video link in readme featuring current webapp version.

**Comment by SrijanJha28** [comment]
Can you send me the link of the video

**Comment by aayusharora** [comment]
@SrijanJha28 There is no new updated video available. If you want to provide a video, you can create and the link in the readme.
Cheers :)

**Comment by SrijanJha28** [comment]
Can you please make a video and upload it on YouTube so that I could add it
