### ISSUE TITLE
Fixing the URL in the mail sent to the user.

### ISSUE THREAD

**Issue by mansikhemka** [fossasia/open-event-webapp#927]
The email sent to the user for the successful creation of the web app is incorrect. It lacks the %20 needed in place of spaces in the event name.

Therefore, the URL shows 404 on clicking.

(Based on the web app run on heroku.)

<img width="532" alt="screen shot 2016-12-26 at 12 17 50 am" src="https://cloud.githubusercontent.com/assets/13851011/21472450/c9ea60d2-cb00-11e6-986f-e84b028e3a7f.png">

Besides fixing this, I suggest that instead of having %20 in place of spaces in the event name in the URL, we can instead slugify it to make it less cumbersome.

**Comment by Princu7** [comment]
@mansikhemka Thanks for reporting the issue. Putting dash or underscore in place of the spaces would be good in my opinion. Any suggestions?
Also would you like to work on this issue?

**Comment by mansikhemka** [comment]
@Princu7 Definitely, I will place %20 instead of spaces.

**Comment by fatimarafiqui** [comment]
@Princu7 Should we not use encodeURI? That will be more appropriate solution.

**Comment by Princu7** [comment]
@fatimarafiqui Agree. That would be a better solution. Please open a pull request regarding it. Thanks

**Comment by aayusharora** [comment]
Nice work @mansikhemka  Thanks :)

**Comment by fatimarafiqui** [comment]
I will open the pull request shortly @Princu7 @aayusharora
