### ISSUE TITLE
Improve "Show starred" and "Search" field on mobile screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#939]
Show starred and search fields do not show up nicely on mobile screens. Please align and expand the buttons/field to match the other areas on mobile resolutions, e.g. compare here http://fossasia.github.io/open-event-webapp/tracks.html

![screenshot from 2017-01-03 19-22-52](https://cloud.githubusercontent.com/assets/1583873/21618274/63effeae-d1ea-11e6-9336-f77f6c8cc0b7.png)

**Comment by geekyd** [comment]
@mariobehling sir I have tried to fix the issue, added some css to the existing code please have a look.

![screen shot 2017-01-05 at 2 34 14 am](https://cloud.githubusercontent.com/assets/12807846/21659513/1e7f5218-d2f1-11e6-8872-9a9f2da4ef77.png)

**Comment by mariobehling** [comment]
Ok, very good.

1. Could you also make "Show Starred" the same width as the event days buttons, please?
2. Could you make the Search Area the same height as the event days buttons?

**Comment by geekyd** [comment]
@mariobehling sir I have made the changes you asked for, please have a look.
![screen shot 2017-01-05 at 9 26 53 am](https://cloud.githubusercontent.com/assets/12807846/21668591/4dd177c0-d329-11e6-921e-0932ec6e27a0.png)

**Comment by mariobehling** [comment]
I do not see a PR to our repo from you.
