### ISSUE TITLE
When installed to home screen (via Chrome on Android), it launches in landscape mode

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#94]
Should not be frozen to landscape mode, and rotate with the device.

**Comment by SilentFlame** [comment]
@championswimmer 
Anyone working on this issue?

would like to work.

**Comment by SilentFlame** [comment]
@championswimmer unable to reproduce on my android phone.
Either this is resolved or I/m unable to understand exactly what you are trying to say.

**Comment by championswimmer** [comment]
has been resolved
