### ISSUE TITLE
Session title not always full width on small resolutions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#940]
The colored session title is not always in full resolution in small resolutions. Please help to fix this.

![screenshot from 2017-01-03 19-27-50](https://cloud.githubusercontent.com/assets/1583873/21618359/d94aa136-d1ea-11e6-9174-deaa6d724f66.png)

**Comment by geekyd** [comment]
Hello sir I would like to work on this issue.
original code
`@media (max-width: 660px) {
  .event {
    max-width: 270px;
  }
}`
The above code fixes the size of the title which does not scale well on small resolutions as it is fixed.
![screen shot 2017-01-05 at 1 06 51 am](https://cloud.githubusercontent.com/assets/12807846/21656326/aec1e420-d2e3-11e6-8606-62875c9b80c5.png)

Please check the result.

**Comment by mariobehling** [comment]
Please make a pull request. So devs can review it. Thank you.

**Comment by geekyd** [comment]
Sir I have made the pull request , please check.
Thank you.
