### ISSUE TITLE
Bad Layout when showing starred sessions

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#945]
![layout](https://cloud.githubusercontent.com/assets/12194719/21675697/b94bfce4-d358-11e6-9e37-55f736a9d1aa.png)

**Comment by CosmicCoder96** [comment]
@aayusharora I would like to fix this, would it be okay to display the star of the starred session at the top-right corner of the box ?

**Comment by CosmicCoder96** [comment]
@aayusharora I made some changes which makes the stars align themselves towards the right.
<img width="889" alt="screen shot 2017-01-06 at 3 36 30 am" src="https://cloud.githubusercontent.com/assets/17252805/21701070/9bb5e854-d3c9-11e6-9895-b371acc4d813.png">
