### ISSUE TITLE
UX: Reset Loader when Zip is cancelled

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#946]
Whenever the user click on cancel Uploading zip , the loader should reset.
## Steps to Reproduce
- Upload Zip and click generate app
- Cancel Zip when app is generated and upload new zip 

![ui](https://cloud.githubusercontent.com/assets/12194719/21675838/4b81f1cc-d359-11e6-827b-81c5ea0b534f.png)

**Comment by Princu7** [comment]
@aayusharora I noticed this bug too. I will work on fixing it ASAP. Thanks.

**Comment by geekyd** [comment]
@aayusharora  I tried to solve the issue and I have got this result.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/12807846/21716515/e9f001d2-d430-11e6-9a6a-3d49a0842423.gif)

There is one more problem that I have noticed , while generating the app if we hit cancel it wont stop the generating process of the web app.

Check this out!

**Comment by Princu7** [comment]
@geekyd Looks great. I had also started working on the issue :smile:. In the future, before working on an issue, please ask the members who have volunteered to work on it before taking it up. This would lead to more efficient utilization of time and resources. Anyways, no problem. Please make a PR.

To cancel the generation process, placing a button next to the generation slider or a cancel button would be more apt. @aayusharora Please guide on this.

**Comment by geekyd** [comment]
@Princu7 Sorry about that, I will be more careful in the future! 
I'm generating a PR.

**Comment by geekyd** [comment]
@Princu7 Thank you :)

**Comment by Princu7** [comment]
@geekyd No problem at all. Good Work. It was a trivial issue so no harm done. Sometimes, it might happen that the other person might have invested a lot of time on the issue which would be nullified this way. Cheers :smiley:

**Comment by geekyd** [comment]
@Princu7 I'm sorry about the misunderstanding. I did not mean to nullify your work.

**Comment by Princu7** [comment]
@geekyd No problem at all. No misunderstandings. You didn't do anything but great work. I was speaking from a general perspective. All is Well :smiley:

**Comment by aayusharora** [comment]
@geekyd Nice work! You catch a crucial bug. You can create a seperate issue for that and can go ahead.
@Princu7 Do you want to work on this issue ?

**Comment by Princu7** [comment]
@aayusharora Geekyd wanted to work on it so he should go ahead. I will fix other bugs. Thanks.

**Comment by Princu7** [comment]
Issue has been fixed. Closing this.
