### ISSUE TITLE
Automatic deployment of generated event website to the user's Github Account

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#947]
I have been working on this feature for quite some time. This will give the users the ability to publish the event website on their Github account in the form of gh-pages.

**Workflow**
* Users will generate the event website with the help of the generator.
* If they want to deploy the generated website to their GitHub account, they will press on the **Deploy** button in the form.
* After clicking on the Deploy button, they will be taken to the **GitHub authentication** page where they will authorize the web app to make changes to their account.
* After they approve the requested permissions and enter their credentials, the process of uploading of files and making commits will start.
* After the whole website is completed, a **live link** to the gh-pages of the event website will appear on the page.

**Some Notes**
* I am still working on this feature. It would take some more time to get all the details right(interface, looks, error handling and display). But the core functionality has been somewhat implemented.
* Currently, the speed of uploading and committing of the file has been kept a bit low. On higher speeds, there were some conflicts since the Github database was not responding fast enough. I have emailed Github Support for an optimal no of requests per second.
* Authentication is managed through the library passport js.
* A repo named **eventSiteWebApp** is created in the user's account which contains the files of the event. User can delete that repository later if he wants.
* The app will ask for the user's permission to create and delete a repo from his/her account. 
* Since the process is a bit slow, please use the **EHealth Africa sample** for quick testing of the app.

Here is the link to the deployed app:
https://shrouded-ocean-89460.herokuapp.com
@mariobehling @aayusharora Please test and review. Thanks.

**Comment by mariobehling** [comment]
@Princu7 Awesome!

I could not try out the whole thing right now as the apps demands access to all repositories and I am not seeing a way to limit it to one repository. I would be ok to share with my personal repositories but sharing of organizations is a bit tricky. Is there a way to allow access to a specific repository or something along the lines?

![screenshot from 2017-01-05 12-41-07](https://cloud.githubusercontent.com/assets/1583873/21679461/868176f4-d344-11e6-910b-bb5b3fac100c.png)

Currently the "Deploy" button is already shown before the site is generated. Expected: It should show up together with the other buttons after site generation.

**Comment by Princu7** [comment]
@mariobehling I have removed the permissions which asked for access to the private repositories. Also, I have set the organizations permissions to read only. It should be sufficient, I guess. 

I am sorry that I didn't elaborate on the permissions required for the app to work. To give power to the app, we have to associate certain scopes to our OAuth token. Scopes let us specify exactly what type of access we need. Scopes limit access for OAuth tokens. They do not grant any additional permission beyond that which the user already has.

Currently, the app requests for OAuth token with three scopes-

**public_repo**( Used For Creating New Repository containing the contents of event Site)
_Grants read/write access to code, commit statuses, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories._

**delete**(Used In case the repository containing the event site is already there, then we need to remove it and make a create one)
_Grants access to delete adminable repositories._

**read:org**(Used for read-only access to organizations repositories)
_Read-only access to organization, teams, and membership._

I will fix the deploy button issue soon. I also made a video demonstrating the whole process. You can view it here
https://www.opentest.co/share/4378d8d0d37011e68531cf81a6426bba
Please review the deployed app. Thanks.

**Comment by SparshBansal** [comment]
@Princu7  Is there anything left in this issue to work on or is it closed.

**Comment by Princu7** [comment]
@SparshBansal It's finished. There is already a PR open for it :)
