### ISSUE TITLE
UX : Improving the menu for small screen size & the landing page

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#951]
I noticed that the menu in the current app on small resolution does not scale properly and can be improved. I have also noticed that the buttons on the main page of the app are not aligned properly.

![screen shot 2017-01-06 at 7 35 21 pm](https://cloud.githubusercontent.com/assets/12807846/21720167/bc5e21a6-d447-11e6-8225-299e786e61f3.png)

![screen shot 2017-01-06 at 7 37 10 pm](https://cloud.githubusercontent.com/assets/12807846/21720281/35379d3c-d448-11e6-8fd3-03cba48241a7.png)

I would like to improve the interface of the above pointed areas.

**Comment by aayusharora** [comment]
@geekyd Please propose the mockup of your UI .

**Comment by geekyd** [comment]
@aayusharora here is my proposed design for the ui.
check out for live demo :)
http://open-event-web-appp.herokuapp.com

![screen shot 2017-01-06 at 7 35 31 pm](https://cloud.githubusercontent.com/assets/12807846/21723406/4c4629b8-d456-11e6-8929-8e85b87dfe48.png)

**Comment by aayusharora** [comment]
@geekyd The UI is not correct and effective. Please consider https://fossasia.org/ navbar on small screen to come up with better UI.
