### ISSUE TITLE
Schedule information not shown

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#953]
## Steps to reproduce 

- Go to schedule page
- Click on any schedule
- Schedule div will not expand to provide schedule info.
Correct functionality on click:

![previous](https://cloud.githubusercontent.com/assets/12194719/21731632/480768d8-d47b-11e6-8b34-12d2dd7af314.png)

**Comment by CosmicCoder96** [comment]
@aayusharora I would like to work on this.

**Comment by Princu7** [comment]
@CosmicCoder96 Fixed. A javascript bug.

**Comment by aayusharora** [comment]
Thanks @Princu7  :)
