### ISSUE TITLE
Implement  a nav bar for sessions/tracks

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-webapp#954]
Currently there is no navbar on sessions/tracks pages and it becomes difficult to navigate through the sessions without a navbar. We could take inspiration from eventyay navbar from the link given below, on the webapp they are datewise so there would be an option to select the date and then the navbar would display the corresponding tracks according to the selected tab on navbar.

<img width="1104" alt="screen shot 2017-01-07 at 12 08 41 pm" src="https://cloud.githubusercontent.com/assets/17252805/21740088/00d898b6-d4d4-11e6-834c-ad981b547f22.png">

Eventyay sessions page : https://eventyay.com/e/18252ab6/sessions/

PS: If the issue seems valid, I would like to work on this.

**Comment by Princu7** [comment]
@CosmicCoder96 Great idea!!.

**Comment by aayusharora** [comment]
@CosmicCoder96 Good idea! How are you planning to do this on mobile. Where your proposed UI navbar will take 50% mobile screen when number of tracks increases.

**Comment by CosmicCoder96** [comment]
@aayusharora on smaller screens, it can be a fixed width scrollable (scrollable to right or down whichever works best ) Navbar so it doesn't cover the entire screen area. How does that sound? I'm on working on one and will give you a demo as soon as I can.

**Comment by aayusharora** [comment]
@CosmicCoder96 Sounds good. Suggestion is to post the proposed UI before coding it.

**Comment by CosmicCoder96** [comment]
@aayusharora I have made a PR #967 , there is a live link to preview as well, you can see the UI there.
