### ISSUE TITLE
App crashes when invalid zip is uploaded

### ISSUE THREAD

**Issue by uttpal** [fossasia/open-event-webapp#956]
Web app crashes if the uploaded zip file is invalid (not contains required folders and files).

Steps to reproduce:

1. Go to app homepage
2. Upload any zip that does not contains /sessions or  /speakers or /event or other folders.
3. Click generate webapp
4. You can see app crashing in server logs.

![error](https://cloud.githubusercontent.com/assets/8591801/21740422/d0e77878-d4df-11e6-8a83-549fc2fbc484.png)

I would like to work on this and submit a PR soon.
`

**Comment by Princu7** [comment]
Sure. Thanks.

**Comment by uttpal** [comment]
@Princu7 @mariobehling Issue fixed have a look https://openevent-app.herokuapp.com/
