### ISSUE TITLE
Slider does not progess linearly and the logs are not cleared on using another zip file

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#957]
If you generate the event site on uploading a zip file and then do the same process with another zip file, the logs of the previous attempt is not cleared. Also, the slider does not progress linearly. It goes from 95% to 90% at one instant.
![screenshot from 2017-01-07 14-28-15](https://cloud.githubusercontent.com/assets/8847265/21740644/acea3e6e-d4e5-11e6-82d3-a150ae388f07.png)
The red line denotes the end of log of first zip file and start of another.

I am working on these issue.

**Comment by Abhi2424shek** [comment]
Go on @princu7 👍
