### ISSUE TITLE
Image not visible

### ISSUE THREAD

**Issue by divyanshu-rawat** [fossasia/open-event-webapp#965]
In readme.md dependencies Image not visible .

![not visible](https://cloud.githubusercontent.com/assets/13464678/21761174/2ec06548-d677-11e6-8e82-9a65ea9da45f.png)

**Comment by Princu7** [comment]
@divyanshu-rawat Hi. Thanks for noticing the bug.  Would you like to work on it?

**Comment by divyanshu-rawat** [comment]
yes for sure please assign me !

**Comment by divyanshu-rawat** [comment]
@Princu7  It is working now !
