### ISSUE TITLE
Web app does not works properly when multiple clients generate event sites within a short window of time,

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#966]
Currently, the web app is not able to handle multiple requests around the same time. It behaves in a funny manner, delivering the wrong event site to the user. 

**Steps to reproduce**

* Open two tabs in the browser which will correspond to the two different users.
* Let User1 upload a sample zip. Don't press the Generate Button yet.
* Let User2 upload a sample zip. 
* Let User1 and User2  press the generate Button in any order.
* The event site generated for both the users will be exactly same even if they had uploaded a different zip file. To be more precise, the zip file which gets uploaded later will be converted into the event site.

It might be a bit difficult to try this so I made a video demonstrating this issue.  Here is the link
https://www.opentest.co/share/bc1a6f00d5d811e6a7cb6f2926412bab

@mariobehling @aayusharora This seems to be a major and interesting bug. I will work and try to solve this issue. Thanks.

**Comment by aayusharora** [comment]
Thanks @Princu7. This is something that needs attention. This may be because of single folder that is being replaced again and again. This can cause problem at same time click. 
Do you like to take it ?

**Comment by Princu7** [comment]
@aayusharora Yes. Thanks.

**Comment by poush** [comment]
The one simple solution could be appending last 6-8 digits of timestamp to the file name. This part should be done by the server and on upload complete server can return the name of the file which will be sent to the server again when creating the web app.

**Comment by aayusharora** [comment]
@Princu7 Will the client-{id} be different for the same user generating multiple apps at a single point of time.
Are they considered as seperate clients ?

**Comment by aayusharora** [comment]
@poush the idea of timestamps looks good to me.

**Comment by Princu7** [comment]
@aayusharora Yes. Whenever a connection to the server is made, an id is assigned to that socket. It is independent of the user and the time.
Here is the excerpt from app.js file
```
var id = 0;
io.on('connection', function(socket){
  id = id + 1;
  socket.userId = id; // we are using this as client-{id}
```

Since node has a single execution thread, we can guarantee that no two connections will ever be assigned the same id even if they make requests at the same time. There will be no race conditions.

**Comment by Princu7** [comment]
Yes. Whenever a connection to the server is made, an id is assigned to that socket. It is independent of the user and the time.
Here is the excerpt from app.js file

var id = 0;
io.on('connection', function(socket){
  id = id + 1;
  socket.userId = id; // we are using this as client-{id}
})
Since node has a single execution thread, we can guarantee that no two connections will ever be assigned the same id even if they make requests at the same time. There will be no race conditions.
Please correct me if I am wrong. Thanks

**Comment by Abhi2424shek** [comment]
The plan looks good to me @princu7 if the response will be served to the user of that section correctly.

**Comment by geekyd** [comment]
@Princu7 We can either go with the timestamp idea or we could simply use the user id appended after the zip to differentiate the uploaded file. It may need to change the codebase but it will make the app more robust.

Something like upload_userid.zip or upload_timestamp.zip.

**Comment by poush** [comment]
@geekyd I guess there is no user id kind of thing since we don't have user registration system.

Also to make timestamp idea, I would like to suggest one more thing which can be appended to file name to prevent files uploaded at the same moment and that thing can be username. This username can be simply fetched from email. 
So by this way, Our app will make sure no overwrites happens even when two events are created using the same email id and at the same moment.

**Comment by geekyd** [comment]
@poush Great idea! 
I was proposing user id from @Princu7 's example of using a variable id associated with each user. But you idea seems good as we wont have to deal with maintaining the id variable in our code base.

**Comment by Princu7** [comment]
@poush @geekyd Thanks so much for your suggestions :smiley: . I actually thought about using the user's email address and associate it with the zip but it was introducing several concerns like that before the user is able to upload the zip file, he should necessarily fill the email and it should be valid and so on.

That's why I adopted to go with this strategy of assigning an id or a number to every connection. I will try to explain it more clearly. **Id is associated with a connection, not a user**. If the same user open another tab, he will get a new id. If we open a new connection, we will just get a new id. This id is guaranteed to be unique, doesn't depend on time and user constraint and not require much computation to calculate.   Here is the short code snippet which assigns id to every new connection opened

```
var id = 0;
io.on('connection', function(socket){
  id = id + 1;
  socket.userId = id; // we are using this as client-{id}
})
```
The **client-{id} is nothing but the id of the connection itself**. Since this is unique for every connection opened, there is absolutely no chance of overwrites happening whatsoever. We are getting it just a cost of single variable id.
@aayusharora @poush @geekyd  
The timestamp solution is good but would require more work and I have already coded up this solution. Please provide feedback and suggestions on this approach. If this seems faulty, please correct me. Thanks.

**Comment by aayusharora** [comment]
Thanks @Princu7 Work accepted!!
