### ISSUE TITLE
Progress stuck on front end if error extracting zip on backend

### ISSUE THREAD

**Issue by uttpal** [fossasia/open-event-webapp#969]
If corrupted zip is uploaded or there is an error while extraction the frontend gets struck on progress without any error, while the error is thrown in backend logs.

- [ ] Send Error to user if corrupted zip
- [ ] Reset Progressbar to whenever there is an error

![struck](https://cloud.githubusercontent.com/assets/8591801/21847601/b3045416-d822-11e6-9cd2-78f0243111ba.png) 

![loge](https://cloud.githubusercontent.com/assets/8591801/21847677/2742ea68-d823-11e6-8742-c656313d06c9.png)

I am working to fix this issue.

**Comment by Princu7** [comment]
@uttpal Thanks. Sure, Go ahead. This might be because of this piece of code in the dist.js file which don't send the error to logger function.

```
unzipper.on('error', function (err) {
      console.log(err);
     });
```

**Comment by aayusharora** [comment]
@uttpal go ahead !! Thanks

**Comment by uttpal** [comment]
@aayusharora @Princu7 @mariobehling 
I have added one more task to this issue as both of them are related.
Is this fine?

**Comment by aayusharora** [comment]
@uttpal sounds reasonable. But, it will be better if the user knows the error too, currently we show event logs. Giving only useful information with bootstrap alert class can be one of the idea.

**Comment by uttpal** [comment]
@Princu7 @aayusharora Yep, taken care of that Please verify PR. Let me know if there are issues
