### ISSUE TITLE
Odd layout of Search bar placeholder on safari

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-webapp#973]
The search box on the tracks and rooms pages, has a place holder. It looks fine on chrome, but is displaced on safari.

<img width="1153" alt="screen shot 2017-01-12 at 11 10 15 pm" src="https://cloud.githubusercontent.com/assets/17252805/21901513/13a0edec-d91e-11e6-9826-325ae98b837e.png">
<img width="1137" alt="screen shot 2017-01-12 at 11 10 43 pm" src="https://cloud.githubusercontent.com/assets/17252805/21901514/13d0f3a2-d91e-11e6-87e9-5dc62eb4259d.png">

I would like to fix it.

**Comment by Princu7** [comment]
@CosmicCoder96 Please go ahead. Thanks.
