### ISSUE TITLE
Improving logs block on generating web app

### ISSUE THREAD

**Issue by poush** [fossasia/open-event-webapp#976]
I made a pull request for same. This pull request makes an auto scrolling "pre" tag based box with appropriate font size for logs shown on generating page.

See #975 

<img width="1440" alt="screen shot 2017-01-13 at 10 05 42 pm" src="https://cloud.githubusercontent.com/assets/1812082/21937501/b870b0a4-d9dd-11e6-8712-d2af7dabb84b.png">

**Comment by Princu7** [comment]
@poush Thanks!!
