### ISSUE TITLE
Add a minimalistic scroll to top sticky button on tracks page

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-webapp#977]
When the the number of tracks and sessions is on the higher side , for instance on the fossasia'16 site generated with webapp, it becomes cumbersome to reach the top. If a user is in the midst of the page vertically, the only option is to scroll all the way to bottom and click 'back to top' link or manually scroll to the  top of the page. It can be avoided by implementing a very minimalistic scroll to top button which appears on the bottom right of the screen as soon as the user starts scrolling.
I can show the proposed UI, if it seems a valid issue.

**Comment by Princu7** [comment]
@CosmicCoder96 I agree with you. I too sometimes feel the need of a button of some sorts which would take me to the top of the page rather than manually scrolling to the top of the page. Please propose the UI for it. Thanks!!

**Comment by aayusharora** [comment]
Valid enhancement in terms of UX. Go ahead @CosmicCoder96
