### ISSUE TITLE
Buggy speakers page dialogs on  small screen touch devices

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-webapp#978]
On a desktop, when the user hovers a person the extended dialog appears detailing the sessions and other details of that particular speaker. As soon as the user hovers away, the dialog closes and the user can view the details of any other speaker. 
However, while using a mobile browser, there is an erratic behaviour wherein opening a dialog of a speaker(by clicking on his/her picture) opens the dialog. 
This is where the issue comes in. There is no way of closing that dialog, unless some other speaker's picture is clicked.  
Furthermore due to a single speaker occupying the entire screen in horizontal as well as portrait mode the speaker immediately below the selected speaker gets blocked completely and can't be clicked on to view any details. All these quirks lead to a rather buggy experience.
All this can be fixed by implementing a simple fix.
**On clicking the selected speaker again the dialog should close** and the user may continue to browse the page.

To make the issue more clear here is an example on how to generate it:

![img_0704](https://cloud.githubusercontent.com/assets/17252805/21943010/62ca459e-d9f5-11e6-9abc-bc757a2c866c.PNG)

There are two speakers visible right now. If a user clicks on the first one(Abdul Rauf), the dialog opens revealing the details but completely blocking the next speaker (Abhishek Agrawal) as shown here : 
![img_0703](https://cloud.githubusercontent.com/assets/17252805/21943011/62cdf95a-d9f5-11e6-9323-0aac9c8eb56f.PNG)

The only way to close the first dialog is to click on the third or any other speaker , thereby leading to an overall buggy experience.

I would like to work on this.

**Comment by Princu7** [comment]
@CosmicCoder96  Great find. Please go Ahead. Thanks!!

**Comment by aayusharora** [comment]
Make sense @CosmicCoder96, Thanks :)
