### ISSUE TITLE
Docs for Windows

### ISSUE THREAD

**Issue by BrainBuzzer** [fossasia/open-event-webapp#979]
I've tried installing this app on my local machine which runs on windows and it actually fails to complete installation due to it's requirements. Sharp, a node module used itself requires Windows Build Tools and python. For setting up sharp, we need VIPS, which is yet another library. We need to create new docs separating windows installation and unix installation.

- [ ] Windows installation docs
- [ ] UNIX installation docs

**Comment by Princu7** [comment]
@BrainBuzzer Thanks for noticing. We have not fully tested our app on the platform. Would be great if you can work on this issue and help in improving the docs in regards to its installation on Windows platform.

**Comment by aayusharora** [comment]
@BrainBuzzer any updates ?

**Comment by BrainBuzzer** [comment]
I was not working on this issue. I will start my work now.
