### ISSUE TITLE
Reduce space between progress bar and status message

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#981]
During improvement in the presentation of the build logs, the space between the generation progress bar and the status message increased a bit. Also, the layout of the preview and the Download buttons was changed. Please help it to restore to the previous version.
Before
![screenshot from 2017-01-14 13-39-34](https://cloud.githubusercontent.com/assets/8847265/21953489/ec2c4d78-da5e-11e6-874f-c1bb6e51fd62.png)
After
![screenshot from 2017-01-14 13-33-47](https://cloud.githubusercontent.com/assets/8847265/21953495/f7a60e46-da5e-11e6-9fc4-676a99bed541.png)

**Comment by poush** [comment]
I will send a PR for this.
