### ISSUE TITLE
Disable generate button while processing

### ISSUE THREAD

**Issue by uttpal** [fossasia/open-event-webapp#982]
we should disable generate button while building any webapp.
I will send a PR soon.

**Comment by uttpal** [comment]
@mariobehling @Princu7 @aayusharora Please review PR

**Comment by geekyd** [comment]
@uttpal Great work!

**Comment by aayusharora** [comment]
@uttpal I am not able to understand the issue. The button is already disabled in the previous version before the webapp is generated.

**Comment by poush** [comment]
@aayusharora Actually it was disabled until some file was uploaded or API endpoint was provided. But during the generation process of app, I was able to click the Generate button again.

**Comment by uttpal** [comment]
@poush Thanks for explaining. @aayusharora Sorry for not discussing earlier, as I thought it is an obvious bug.

**Comment by aayusharora** [comment]
Cool !! @uttpal @poush Will check the PR.
