### ISSUE TITLE
Lots of linting issues

### ISSUE THREAD

**Issue by uttpal** [fossasia/open-event-webapp#984]
We have lots of lighting issues in the backend as well as frontend. we should fix them
![lint](https://cloud.githubusercontent.com/assets/8591801/21955315/db998fa4-da8e-11e6-99e9-b65e448abb12.png)

After auto fixing
![lintf](https://cloud.githubusercontent.com/assets/8591801/21955317/eafd6c2c-da8e-11e6-9d23-e51022510122.png)

As there are no extensive tests auto fix might break things.

What are your views @mariobehling @aayusharora @Princu7 ?

**Comment by aayusharora** [comment]
No @uttpal this way it will break things. We use Hound to check lint issues and codacy to maintain code quality. Closing this.
