### ISSUE TITLE
UI : Improved search bar on speakers page

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#986]
The search bar's design on the speakers page does is different from the search bar of other pages.
Currently the search bar looks like this:
![screen shot 2017-01-14 at 11 21 15 pm](https://cloud.githubusercontent.com/assets/12807846/21957140/44669262-dab6-11e6-8cb3-c4ff7b533ed4.png)

**Search bar on other pages:**
![screen shot 2017-01-14 at 11 21 21 pm](https://cloud.githubusercontent.com/assets/12807846/21957145/57971f3c-dab6-11e6-88f2-9bc3093beb05.png)

**Proposed design**
![screen shot 2017-01-14 at 11 26 47 pm](https://cloud.githubusercontent.com/assets/12807846/21957146/5797fc54-dab6-11e6-8ac1-7c5273e17df2.png)

**Comment by geekyd** [comment]
@aayusharora Im working on this issue, and will send a new PR for this.

**Comment by aayusharora** [comment]
go ahead @geekyd sounds reasonable.

**Comment by geekyd** [comment]
This issue was solved.
I'm closing the issue 
Cheers 😄
