### ISSUE TITLE
UX : Improving the links leading to speakers page

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#988]
When any link is clicked which leads to speakers page it does not auto scroll to the required speaker.
There is no automatic scroll to the required speaker like tracks page.

Please check the link
https://www.opentest.co/share/144e74e0dae911e68531cf81a6426bba

I will be working on this.

**Comment by aayusharora** [comment]
cool ! go for this :+1:

**Comment by geekyd** [comment]
@aayusharora Please review the app

Demo video:
https://www.useloom.com/share/c017fb40dd5311e6bb99ed2f6348f871

**Comment by aayusharora** [comment]
@geekyd Cant access this. Please generate the PR to check.

**Comment by geekyd** [comment]
@aayusharora sorry for the late response I was unwell , I have created a PR please review it.

**Comment by geekyd** [comment]
@Princu7 @aayusharora I have solved this , please close the issue.

**Comment by Princu7** [comment]
Thanks!!
