### ISSUE TITLE
App crashes in some cases

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#993]
Sometimes, when the user generates the zip file, the app will crash with the error "Error while copying file.  No (insert_any_file_name) found." It is most probably due to the asynchronous nature of node.js which might have been accidently ignored in the previous commits.

Here are the error logs:
```
[ { [Error: ENOENT: no such file or directory, open '/home/princu/open-event-webapp/dist/a@a.com/tempproject1/zip/images/speakers/ViralB.Shah_96.jpg.new']
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/princu/open-event-webapp/dist/a@a.com/tempproject1/zip/images/speakers/ViralB.Shah_96.jpg.new' },
  { [Error: ENOENT: no such file or directory, open '/home/princu/open-event-webapp/dist/a@a.com/tempproject1/zip/images/speakers/ZionNg_159.jpg.new']
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/princu/open-event-webapp/dist/a@a.com/tempproject1/zip/images/speakers/ZionNg_159.jpg.new' } ]

```
![screenshot from 2017-01-17 18-35-45](https://cloud.githubusercontent.com/assets/8847265/22021526/e2c04e38-dce3-11e6-98c6-9ee43f81a788.png)

@aayusharora @mariobehling I am working on this and will try to fix it as soon as possible.

**Comment by Abhi2424shek** [comment]
It's a file not found error basically if I am not wrong, can you give steps to reproduce the issue @princu7

**Comment by Princu7** [comment]
@Abhi2424shek 
You just have to generate the event file by uploading the zip file. The error will throw up. I have almost solved the issue. It was due to the asynchronous nature of node.js. A function was reading a file after it had been deleted by another function. hence the file not found error.
