### ISSUE TITLE
Add scroll to top button on all the pages

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#997]
Currently only tracks page has the button to scroll to top, it would be great if we have it on all the pages to provide a unified and a better user experience.

@aayusharora @Princu7 we should add the button to all the pages , what do you think?

**Comment by aayusharora** [comment]
Suggestion : Make it a template handlebar file like we have done header and footer and insert it in all pages in handlebars rather than coding it seperate for every file.

**Comment by geekyd** [comment]
@aayusharora Thats a great idea!
I'm on it :)
