### ISSUE TITLE
Implement the navbar on the rooms page

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-webapp#998]
The navbar like on tracks page can be implemented on the rooms page as well. we can add it now as rooms page has a lot of datewise content as well. 
I would like to work on this.

**Comment by Princu7** [comment]
@CosmicCoder96 Go for it. :+1:

**Comment by geekyd** [comment]
Awesome @CosmicCoder96 I was thinking the same!
Go for it!

**Comment by aayusharora** [comment]
@CosmicCoder96 Any updates on this ?

**Comment by CosmicCoder96** [comment]
@aayusharora sorry for the delay, was away on a tour. I will make the changes today itself.
